### ISSUE TITLE
use watcher instead of polling

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#1]
use [notify](https://crates.io/crates/notify) to watch git instead of permanent polling

**Comment by extrawurst** [comment]
unfortunately this introduces massive bloat of dependencies and reintroduces the outdated `mio 0.6` with its security problematic outdated `net2`: https://github.com/notify-rs/notify/issues/248

**Comment by 0xpr03** [comment]
Note: We're not depending on mio 0.6 [anymore](https://github.com/notify-rs/notify/pull/278)

**Comment by extrawurst** [comment]
@0xpr03 yeah but I am waiting for a stable release of `5.0`

**Comment by extrawurst** [comment]
or I am just using https://github.com/facebook/watchman
