### ISSUE TITLE
Get vim keys to work

### ISSUE THREAD

**Issue by mmynsted** [extrawurst/gitui#1012]
**Describe the bug**
I am not sure how to update the key bindings to make vim keys work for macOS.

**To Reproduce**
1. Read how to set VIM key bindings [here](https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md)
2. Run gitui one time so that default key bindings will be built.
3. Examine the directory wither key defaults should be defined, `$HOME/.config/gitui`
    When running `gitui` the first time, a new file named `key_config.ron` is created with a number of `struct` based, ron, key bindings. 
4. Add the contents of `vim_style_key_config.ron` to  the end of the `key_config.ron`. 
5. Run `gitui`. This results in a failure because of duplicate key bindings. 
6. Try again (start over) by removing the duplicates from the top of the file (the ones replaced by the items from `vim_style_key_config.ron` after appending the vim keys). This results in a failure message `KeyConfig loading error: 16:18: Expected struct`. The line and column numbers change but the result is the same no matter how I change the file.
7. Try again (start over) this time by adding saving the `vim_style_key_config.ron` to the `$HOME/.config/gitui` directory as a file named `key_bindings.ron`. This also fails to set key bindings.

**Expected behavior**

I would expect that vim keys could be set, at the very least from a read of vim key bindings, perhaps like from [here](https://github.com/extrawurst/gitui/blob/master/src/keys/key_config.rs#L20). 

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS 11.6.1 (20G224)`
 - GitUI Version: 0.18.0, installed from macports.   gitui @0.18.0_2 (active)
 - Rust version: `rustc 1.54.0 (a178d0322 2021-07-26)`

**Additional context**

I am not sure what else to try

**Comment by extrawurst** [comment]
This just recently changed and the documentation reflects the new behavior which will be released as 0.19

**Comment by extrawurst** [comment]
See https://github.com/extrawurst/gitui/issues/946

**Comment by extrawurst** [comment]
with release 0.19 now the docs in master reflect the behaviour of the release. please let us know if you still have issues
