### ISSUE TITLE
tag commit

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#103]
In the commit log, I want to be able to tag the selected commit.

* [ ] new command
* [ ] text input popup

**Comment by cruessler** [comment]
@extrawurst It looks like this issue is not taken yet. If that’s the case, I’d like to give it a try!

**Comment by extrawurst** [comment]
@cruessler absolutely! Looking forward. If u wanna chat about it or have any questions, feel free to join our discord too👍

**Comment by cruessler** [comment]
Cool, thanks for the hint!

**Comment by cruessler** [comment]
“In the commit log”, is that when you press <kbd>2</kbd> and then <kbd>Enter</kbd> on a commit?

**Comment by extrawurst** [comment]
no that's when you have the right-side commit-details open, right? I would expect this to be available even when being in plain reblog-view (only pressing [2])

**Comment by extrawurst** [comment]
@cruessler looks great!
![tagging](https://user-images.githubusercontent.com/776816/87599871-0071cf80-c6f4-11ea-9343-0709621e77ab.gif)

**Comment by cruessler** [comment]
@extrawurst Thanks for the feedback! Looking forward to my next contribution! :-)
