### ISSUE TITLE
Keep commit message when pre-commit hook fails

### ISSUE THREAD

**Issue by aouaki** [extrawurst/gitui#1035]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when my pre-commit fails, because the commit message I wrote in gitui gets lost. When I fix the issue and want to commit again, I have to write the commit message from scratch (I sometimes need a few attempts, that's very frustrating...)

**Describe the solution you'd like**
To me, the commit message I had written when the pre-commit failed should be pre-filled when trying to commit again.

**Additional context**
I'm using `pre-commit` for the hook, and gitui 0.18.0

Thanks!

**Comment by extrawurst** [comment]
Hey @aouaki thanks for reaching out. that makes sense. there is: https://github.com/extrawurst/gitui/discussions/937 which should solve this but no one took the time yet.

**Comment by extrawurst** [comment]
ok without the complexity of history and stuff just preserving the current msg if the commit fails was a rather low hanging fruit, so thats done
