### ISSUE TITLE
Renamed files show diff as new files, don't show changes from old file or path to old file

### ISSUE THREAD

**Issue by lilyball** [extrawurst/gitui#1038]
**Describe the bug**
If I have staged changes that include a file rename, gitui will show the staged change with the "R" status, but it won't tell me what path it was renamed from, and the diff for the file shows the whole thing as new instead of diffing against the old file.

**To Reproduce**
1. Rename a file
2. Make some edits to the renamed file, for good measure
3. Open gitui
4. Stage the new file
5. Check the diff
6. Stage the removed file
7. Check the diff

**Expected behavior**
After staging just the new file, the diff should show as all new. After staging the removed file, the diff should indicate what it was renamed from (ideally the status would too), and show the diff from the new file against the old file.

**Actual behavior**
The diff after just staging the new file is correct. After staging the old file, the status shows "R" but the diff continues to act as though it's a brand new file instead of renamed file.

**Context (please complete the following information):**
 - macOS 12.0.1 (21A559)
 - 0.19.0
 - 1.56.1

**Comment by extrawurst** [comment]
yeah this is an annoyance.

a) currently the status workdir against index does not detect renames, thats why we see the remove (old name) and add (new name) separately.
b) the diff shown is not smart enough currently, it will diff the old file as a entirely deleted one, new one as an entirely new one.

I agree, this needs to be fixed!

**Comment by extrawurst** [comment]
marked as `good first issue` since the PR #1040 is almost there and only needs a bit of cleanup to carry over the finish line. @Mifom seems to have left it

**Comment by Mifom** [comment]
@extrawurst I'll continue to work on this issue now.
