### ISSUE TITLE
gg/G in vim config

### ISSUE THREAD

**Issue by laktak** [extrawurst/gitui#1039]
The gg/G keys are missing in `vim_style_key_config.ron`

Since it's not possible to define `gg` (or is it?), I've simply added `g` as the only side effect is that it will go to `home` twice.

```
    home: Some(( code: Char('g'), modifiers: ( bits: 0,),)),
    end: Some(( code: Char('G'), modifiers: ( bits: 1,),)),
```

Modes would be nice though to group similar commands (like [ranger](https://github.com/ranger/ranger/)) and to make selection with `V` work.

If this is acceptable do you want me to do a PR?

**Comment by extrawurst** [comment]
> If this is acceptable do you want me to do a PR?

sure, I am not using the vim bindings, I rely on you guys to help me here 👍
