### ISSUE TITLE
Git fetch in status view

### ISSUE THREAD

**Issue by mystygage** [extrawurst/gitui#1045]
**Describe the bug**
After creating a new local branch `local-branch` I'm not able to execute a fetch [f] in "Status [1]". The following error is shown:
```
fetch failed:
git error:config value 'branch.local-branch.remote' was not found; class=Config (7); code=NotFound (-3)
```

**To Reproduce**
1. Open gitui
2. open branch overlay [b]
3. create new branch [c]
4. close overlay [ESC]
5. fetch [f]

**Expected behavior**
A `git fetch` is executed without an error.

**Context (please complete the following information):**
 - OS: `macOS 12.0.1`
 - GitUI Version `0.19`

**Additional context**
If I execute fetch [f] within the branches overlay, everything works fine.

**Comment by extrawurst** [comment]
What exactly do you expect to happen?
It seems the error is that the fetch command is enabled in the first place when this branch has no upstream!

**Comment by mystygage** [comment]
I think my assumption that [f] will trigger a fetch was wrong... The command hints in the status view shows clearly that a [f] triggers a git pull and therefore the error message is right. Sorry, I missed this.

I assumed, that pressing [f] on a branch without an upstream branch a simple `git fetch` is executed in the background.

**Comment by extrawurst** [comment]
@mystygage please check if we can close this one then, I created a followup for the issue: #1047

**Comment by mystygage** [comment]
thanks, sounds great. let's close this one
