### ISSUE TITLE
status: disable pull cmd on local-only branches

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#1047]
based on conversations in #1045

**Comment by quintik** [comment]
Somewhat related to this: disable all push/pull commands for repositories with no remotes? I tried `[p]` on a repository with no remotes and it exited gitui, with my terminal showing the output `Error: git: inconclusive remotes`. Here's the bugreport:

#### Software version

gitui 0.19.0 (cd639b2-modified)

#### Operating system

Linux 5.4.72-microsoft-standard-WSL2

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-linux-musl
- Family: unix
- OS: linux
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-linux-gnu

#### Environment variables

```bash
SHELL=/bin/bash
EDITOR=<not set>
GIT_EDITOR=<not set>
VISUAL=<not set>
```

#### Command-line

```bash
gitui --bugreport
```

**Comment by barkanido** [comment]
hey, @extrawurst I would like to try and tackle this. still a rust newbie. WDYT?

**Comment by extrawurst** [comment]
I think if you look up there is already a PR for it - feel free to check it out locally and review it - I did not have time to do so yet.

**Comment by extrawurst** [comment]
#1051 only handles the case where no remote is defined at all. we still need to fix the issue when a branch is not upstream but we have a remote defined

**Comment by extrawurst** [comment]
@barkanido ping. feel also free to join our discord to further discuss
