### ISSUE TITLE
Sample vim bindings config doesn't work.

### ISSUE THREAD

**Issue by zim0369** [extrawurst/gitui#1056]
I don't know what's wrong with the config but it simply doesn't work.

**Comment by zim0369** [comment]
Oh you changed the name of the file `key_config.ron` -> `key_bindings.ron`

**Comment by extrawurst** [comment]
@zim0369 yes, as noted in the changelog

**Comment by Tseyang** [comment]
Hi, sorry to reopen this but I'm running into the same issue even with the correctly named file. I have the sample vim config in `~/.config/gitui/key_bindings.ron` and am still seeing the default keybinds in place. I tried using `gitui -l` to see if anything popped up in the logs but I did not see anything of note regarding loading the config:

```
03:08:55 [TRACE] (1) gitui::app: [src/app.rs:320] event: Input(Key(KeyEvent { code: Char('j'), modifiers: NONE }))
03:08:55 [TRACE] (1) gitui::app: [src/app.rs:320] event: Input(Key(KeyEvent { code: Char('j'), modifiers: NONE }))
03:08:56 [TRACE] (1) gitui::app: [src/app.rs:320] event: Input(Key(KeyEvent { code: Down, modifiers: NONE }))
03:08:56 [TRACE] (1) gitui::app: [src/app.rs:320] event: Input(Key(KeyEvent { code: Down, modifiers: NONE }))
03:08:56 [TRACE] (1) asyncgit::diff: [asyncgit/src/diff.rs:98] request DiffParams { path: "src/foo.ts", diff_type: WorkDir, options: DiffOptions { ignore_whitespace: false, context: 3, interhunk_lines: 0 } }
03:08:56 [TRACE] (1) gitui::app: [src/app.rs:415] update_async: Git(Diff)
03:08:56 [TRACE] (1) asyncgit::diff: [asyncgit/src/diff.rs:98] request DiffParams { path: "src/foo.ts", diff_type: WorkDir, options: DiffOptions { ignore_whitespace: false, context: 3, interhunk_lines: 0 }
```

I believe the `DiffParams` traces are from the `Down` events, which correspond to the default keybinds, and the lack of traces from the `j` ones imply that the config was not loaded.

Is there a recommended way to debug this + further keybind customization?

Thank you so much for this tool, I'm a huge fan of it.
