### ISSUE TITLE
Unable to push (InvalidSpec error)

### ISSUE THREAD

**Issue by LudoPinelli** [extrawurst/gitui#1058]
**Describe the bug**
Unable to push. I have the following error:
`git error:unknown scheme for URL 'git+ssh://git@github.com/LudoPinelli/dotfiles'; class=Net  (12); code=InvalidSpec (-12)`.
I tried using `gitui -l` but no log is created.

**To Reproduce**
1. Stage files (or open gitui in the repo where files are stagged)
2. Press `p`

**Expected behavior**
A successful push.

**Context (please complete the following information):**
 - OS/Distro + Version: Ubuntu 21.04 on wsl2
 - GitUI Version 0.19.0
 - Rust version: 1.57.0

**Additional context**
Using `git push`on the command line (same terminal, same repo) or via LazyGit works fine.

**Comment by extrawurst** [comment]
maybe related to https://github.com/extrawurst/gitui/issues/916

**Comment by LudoPinelli** [comment]
I've seen that issue but in my case the format of the remote is `git+ssh://git@github.com/username/repo`.

**Comment by extrawurst** [comment]
yea I know but it could be just another non-standard shape of the urls git supports without being documented just like the brackets weirdness (see the upstream conversation in the libgit2 ticket, maybe you can add your to it too)

**Comment by LudoPinelli** [comment]
Ok, thanks for your answer (and for this really nice software^^). I close this issue then :)

**Comment by extrawurst** [comment]
@LudoPinelli make sure to post you use case to upstream too: https://github.com/libgit2/libgit2/issues/6163
