### ISSUE TITLE
Use netrc file when present

### ISSUE THREAD

**Issue by bastantoine** [extrawurst/gitui#1062]
Hello,

In my current git setup at work, I use a [`.netrc`](https://everything.curl.dev/usingcurl/netrc) file to perform authentication against a single Gitlab server for all of my repos.

When using the classic git binary there's no problem as it uses internally cURL which supports this file. The problem is that `gitui` doesn't support it, which mean that if I want to push to a remote, I get asked to enter my username and password, even thought they are already stored somewhere else.

It seems that neither [`git2-rs`](https://github.com/rust-lang/git2-rs/issues?q=netrc) nor [`libgit2`](https://github.com/libgit2/libgit2/issues?q=netrc) used by `git2-rs` has any support for it.

I could technically change all the push ref of my cloned repos, but I have to admit that with dozens of repos on my machine, I'd rather keep this as a last possible solution.

Would it be interesting to integrate it in `gitui`, or should I rather fill the request to `libgit2`?

**Comment by extrawurst** [comment]
> Would it be interesting to integrate it in gitui, or should I rather fill the request to libgit2?

if this is a behaviour the regular git applies it would be ideal to integrate upstream in libgit2 actually

**Comment by bastantoine** [comment]
> if this is a behaviour the regular git applies

Actually that's not something that git itself proposes, but rather a side consequence of it using cURL which supports the .netrc file, that's why I asked here, because that's not a behavior that's intended in the core of git.

**Comment by extrawurst** [comment]
@bastantoine I still would bring this conversation to libgit2 since it tries to mimic whatever behaviour git has

**Comment by extrawurst** [comment]
closing for now. please link an upstream ticket in libgit2 if you end up creating one
