### ISSUE TITLE
Crash at adding folder which is git repo by itself

### ISSUE THREAD

**Issue by kulik** [extrawurst/gitui#108]
**Describe the bug**
it's a crash when you stage folder which has .git folder inside, and still not a git-submodule
**To Reproduce**
Pre conditions. init repo, with git init, copy the other git repo inside.
1. open gitui
4. select coursor on folder which is repo
5. hit enter
crash

**Expected behavior**
At least nothing should happend
the best result it's to suggest to add it like git submodule. 

**Desktop (please complete the following information):**
 - OS: Linux ubuntu
 - gitui v0.5.0

**Additional context**

 gitui
Error: git error:invalid path: 'nginx/lua-lib/lua-resty-hmac/'; class=Index (10)

Caused by:
    invalid path: 'nginx/lua-lib/lua-resty-hmac/'; class=Index (10)

 where lua-resty-hmac/ - it's git repo by itself

**Comment by extrawurst** [comment]
Hey @kulik thanks for reporting this. Indeed this should not crash. but what is the expected behaviour? does the git cli support checking in this repo into the outer repo?

**Comment by kulik** [comment]
thereis a ugly way - just to comit it straight as it. i wouldn't expect that, probably it's normal for some cases with skiping .git folder. but the briliant way is 
https://git-scm.com/book/en/v2/Git-Tools-Submodules 
it's possible parse origins of internal git repo, and suggest user to add it as it or as submodule with current HEAD positio of it's parsed origin url, or suggest to enter other url but preserve HEAD

**Comment by extrawurst** [comment]
@kulik I cannot even figure out how to commit a `.git` subfolder using git-cli. it is simply ignored. so I am tending to simply swallow the error and ignore it in gitui aswell. submodules are a different can of worms

**Comment by extrawurst** [comment]
this is what should happen now:
<img width="730" alt="image" src="https://user-images.githubusercontent.com/776816/83693658-cbebfd80-a5f6-11ea-8fa3-f8c7245a4207.png">
