### ISSUE TITLE
Ctrl+U and Ctrl+D for page up/down

### ISSUE THREAD

**Issue by juancampa** [extrawurst/gitui#109]
**Is your feature request related to a problem? Please describe.**
Some keyboards (like mine) don't really have PgUp/PgDown. It would be great to have another keybinding to quickly scroll up and down the Diff pane.

**Describe the solution you'd like**

New keybindings:

 - `Ctrl+U` to scroll up
 - `Ctrl+D` to scroll down

These are the keybindings for `vi`/`vim` so a lot of folks should be familiarized with them.

**Comment by extrawurst** [comment]
Hi @juancampa thanks for your interest in `gitui`, I will never get used to those vi bindings, but I guess I am no benchmark here :D

**Comment by hasufell** [comment]
I think vi bindings have no place here. The other navigational keys are arrow keys. So the natural choice should be PageUp/PageDown.
