### ISSUE TITLE
Allow shift+enter to insert new line in commit message

### ISSUE THREAD

**Issue by andresovela** [extrawurst/gitui#1109]
**Is your feature request related to a problem? Please describe.**
It should be possible to create a multi-line commit message.

**Describe the solution you'd like**
Press shift+enter to enter a new line.

**Describe alternatives you've considered**
None.

**Comment by extrawurst** [comment]
did you know: you can open the external editor for this?

otherwise its probably a dup of https://github.com/extrawurst/gitui/issues/711

**Comment by andresovela** [comment]
External editor? No, how?

**Comment by extrawurst** [comment]
external editor support was added in `0.8.0`.
see this animation (notice the `Open editor` command in the action-bar on the bottom): 
https://github.com/extrawurst/gitui/blob/master/assets/vi_support.gif

**Comment by andresovela** [comment]
I see, cool thanks!

**Comment by crispinb** [comment]
Any chance of reconsidering this? External editor support is a nice additional feature, but seems like an unnecessary additional step for many commit messages of just a few lines. `Shift + Enter` is so common in this kind of context I tried it a few times before realising it really didn't enter a newline ;)

**Comment by extrawurst** [comment]
See #1171
