### ISSUE TITLE
URI-like navigation for branches

### ISSUE THREAD

**Issue by victormihalache** [extrawurst/gitui#1110]
**Is your feature request related to a problem? Please describe.**
I like for my branches to be descriptive and separate based on what they are for, so i have some branches that begin with `feat/`, some others with `bugfix/`, or `release/`. Furthermore, I also sometimes do stuff like `feat/feature-name/author1` and `feat/feature-name/author2`; this allows multiple devs to work on the same "little main branch" named `feat/feature-name`

**Describe the solution you'd like**
It would be nice for there to be a "file explorer"-like view when viewing branches (sort of like ranger) that allows you to better sort by category. See last section for screenshots of a mockup.

It basically treats branch names as if they were similar to URIs. Another thing could be to show, instead of just the latest, more commits, or even commits not present in your current branch.

**Describe alternatives you've considered**
Another thing that could do, is to have a way to specify a prefix and discard the rest for an easier view.

**Additional context**
Initial view:
![initial](https://user-images.githubusercontent.com/82441538/151404294-8a0f0693-db09-4697-a19a-599d450e7c7e.png)

Navigating through (see how other items appear):
![nav](https://user-images.githubusercontent.com/82441538/151404454-a058c1d5-783b-420a-aaa6-e5277d867b1a.png)

Arriving at a finish point (aka no more `/`):
![final-nav](https://user-images.githubusercontent.com/82441538/151404635-11e2ed78-e0e1-4900-98d9-d3e6fcaa2711.png)

**Comment by extrawurst** [comment]
I had something like that in mind with https://github.com/extrawurst/gitui/issues/633 and it could easily also parse `/` as a sub structure

**Comment by victormihalache** [comment]
So is there any chance this will be built any time soon?

**Comment by extrawurst** [comment]
If it get picked up by someone. Fancy contributing ?

**Comment by victormihalache** [comment]
Still in the process of learning rust, might look around to see if it's anywhere near something i can do.
