### ISSUE TITLE
Limiting commits shown in the commit log using a filter

### ISSUE THREAD

**Issue by jfrob** [extrawurst/gitui#1113]
**Is your feature request related to a problem? Please describe.**
Trying to find specific commits from the Log [2] view.

**Describe the solution you'd like**
Some kind of filter for the view, eg. by date, author and/or commit message (string search, regex match etc).

**Describe alternatives you've considered**
A simple text search to show only matching commits. 

**Additional context**
N/A

**Comment by jfrob** [comment]
I suppose this is somewhat related to https://github.com/extrawurst/gitui/issues/990 except this is for the commit log.

**Comment by extrawurst** [comment]
there is a pending MR for this: https://github.com/extrawurst/gitui/pull/672

**Comment by jfrob** [comment]
Aww, I completely missed that one. That should do it then.

**Comment by extrawurst** [comment]
I don’t know, the MR is outdated for a long time. I did not have the time to revive it
