### ISSUE TITLE
commitzen integration

### ISSUE THREAD

**Issue by AlbanMinassian** [extrawurst/gitui#1123]
how use gitui and commitzen <https://github.com/commitizen/cz-cli>
or how valide message after commit message inside gitui ?
Thanks

**Comment by AlbanMinassian** [comment]
solve with gitui 0.20.1 and commitlint

**Comment by januz** [comment]
@AlbanMinassian Do you have an example config/workflow for how you use `commitlint` with `gitui`? Thanks!
