### ISSUE TITLE
tui 0.17

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#1135]
Hello,

It would be great if you could upgrade tui dependency to 0.17.x which is available for some time as it complicates packaging of gitui in Fedora (as we have to have both 0.16 for gitui and 0.17 for other crates).

Thank you!

**Comment by extrawurst** [comment]
That’s a pickle, this update requires a minimum rust version too new for the stoneage version supported by stable Debian 😔

**Comment by extrawurst** [comment]
See https://github.com/fdehau/tui-rs/blob/master/CHANGELOG.md#breaking-changes

vs

https://packages.debian.org/search?keywords=rustc

**Comment by extrawurst** [comment]
should be fixed via 4a0e58a
