### ISSUE TITLE
View arbitrarily long multi-line annotations for git tags

### ISSUE THREAD

**Issue by skyfaller** [extrawurst/gitui#1138]
**Is your feature request related to a problem? Please describe.**
Happily, [we can view git tag annotations](https://github.com/extrawurst/gitui/issues/1076), including annotations with multiple lines. Sadly, if the annotation is long and goes on for many lines, we can't see the whole thing. In my current terminal emulator, gitui only displays the first 23 lines.

This issue will increase in importance if we [support creating multiple-line annotations for git tags](https://github.com/extrawurst/gitui/issues/1137).

**Describe the solution you'd like**
Adding a scrollbar seems like a good solution to me.

If adding scrollbars to a "popup window" is not desirable, perhaps refactoring the UI so that annotations can be viewed in a multi-panel interface, like the files list, might work better.

**Additional context**
![Screenshot of gitui with a long git tag annotation and no way to scroll to read the rest of it](https://user-images.githubusercontent.com/80093/154760486-7ba62e33-ddd2-47eb-8d3c-66859bd48a4a.png)

**Comment by skyfaller** [comment]
Are there obvious blockers to using `draw_scrollbar` as y'all once did for the revlog? https://github.com/extrawurst/gitui/issues/868

**Comment by extrawurst** [comment]
> Are there obvious blockers to using draw_scrollbar 

I don't think so

**Comment by extrawurst** [comment]
yeah i think this should be pretty simple to do using the machinery for scrollbars we use in a lot of places already

**Comment by MichaelAug** [comment]
Hi, I started working on this, i'm adding a new popup with a scrollbar for the tag annotation instead of using MsgPopup. should have a PR up soon :)

**Comment by extrawurst** [comment]
Why not the exiting one and add the scrollbar?

**Comment by MichaelAug** [comment]
Because currently the annotation is shown using:
```
	fn show_annotation(&self) {
		if let Some(tag) = self.selected_tag() {
			if let Some(annotation) = &tag.annotation {
				self.queue.push(InternalEvent::ShowInfoMsg(
					annotation.clone(),
				));
			}
		}
	}
```
Which calls 
```
			InternalEvent::ShowInfoMsg(msg) => {
				self.msg_popup.show_info(msg.as_str())?;
				flags
					.insert(NeedsUpdate::ALL | NeedsUpdate::COMMANDS);
			}
```

I didn't want to add a scrollbar to msg_popup as that is used in other places as well so decided to add a separate popup.

I'm happy to just add a scroll bar to the info popup if that's preferable

**Comment by extrawurst** [comment]
you raised a good point. i had to take a look again. my first hunch was: lets use the new multiline textinput but that one does not support readonly right now and is already a rather complex beast.

So in order to keep things simple you can just add vertical scrolling to `MsgPopup` (using `DetailsComponent` maybe for inspiration as it supports multiline scrollable text view already).

Ideally we put that functionality into a separate `ScrollableTextView` component and reuse it between (at least) `MsgPopup` and `DetailsComponent`. Both doing this in one step or in two would be fine to me. WDYT?

**Comment by extrawurst** [comment]
@MichaelAug for more instant exchange amongst contributors feel free to join our discord: https://discord.gg/d2p2NS7m

**Comment by MichaelAug** [comment]
> @MichaelAug for more instant exchange amongst contributors feel free to join our discord: https://discord.gg/d2p2NS7m

Thanks i'm already in the Discord :+1:

**Comment by MichaelAug** [comment]
I made a PR for the first part. After this is approved I'll make another PR to refactor `MsgPopup` and `DetailsComponent` to use a new `ScrollableTextView` component
