### ISSUE TITLE
Cannot push because of `Bad credentials`

### ISSUE THREAD

**Issue by bugemperor** [extrawurst/gitui#1150]
**Describe the bug**
Cannot push because of `Bad credentials`

**To Reproduce**
Press `p` to push

**Expected behavior**
Push correctly

**Screenshots**
![Screen Shot 2022-02-27 at 9 58 39 AM](https://user-images.githubusercontent.com/11213808/155865226-adb48d23-3052-49af-8167-813c14892fbc.png)

**Context (please complete the following information):**
 - OS/Distro + Version: [`macOS 10.15.5`]
 - GitUI Version: [`0.20.1`]

**Additional context**
It's OK to push with lazygit or git command

**Comment by montychen** [comment]
I have the same problem, how to solve it, please help me
