### ISSUE TITLE
Whether more editor options can be provided

### ISSUE THREAD

**Issue by alongnice** [extrawurst/gitui#1152]
When I try to edit a file, I use Vim by default. But the editor I'm more familiar with is Emacs, vim is very unfamiliar, but can't find the configuration parameters to switch. If you can ask the author to add this function, I wish Gitui can do better and better.

**Comment by kosayoda** [comment]
The relevant source code is
https://github.com/extrawurst/gitui/blob/006cdd63738db91e6c3074439bfd561eb0b5eb9c/src/components/externaleditor.rs#L72-L81

You have 4 options to set the editor used in gitui:
1. Set the `GIT_EDITOR` environment variable
2. Set the `VISUAL` environment variable
3. Set the `EDITOR` environment variable
4. Set the editor used by Git in your [Git Configuration](https://www.git-scm.com/book/en/v2/Customizing-Git-Git-Configuration)
