### ISSUE TITLE
Space as keybinding

### ISSUE THREAD

**Issue by DanielRivasMD** [extrawurst/gitui#1159]
Hi, has `Space` been considered as a field in the `KeySymbols` struct?

**Comment by extrawurst** [comment]
Depends for what event you wanna use it I suppose?

**Comment by DanielRivasMD** [comment]
Thanks for your reply. I would like to bind it to 'stage' file, similar to `lazygit`. But I cannot figure out how without modifying `KeySymbols` struct at the source code.

**Comment by extrawurst** [comment]
works for me if I re-bind:

```
(
  stage_unstage_item: Some(( code: Char(' '), modifiers: ( bits: 0,),)),
)
```

see [key_config](https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md) for more details
