### ISSUE TITLE
RFE: Commit graph (and annotations)

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#116]
**Is your feature request related to a problem? Please describe.**
It would be nice to see something like `git log --oneline --graph --all --decorate` in gitui, with the branch names / tags and a commit graph.

**Additional context**
![image](https://user-images.githubusercontent.com/2866862/84422355-33203800-ac1d-11ea-8c65-56f063e25bea.png)

**Comment by extrawurst** [comment]
definitely!

dup of #81
