### ISSUE TITLE
Provide some feedback after copying commit hash

### ISSUE THREAD

**Issue by MarcelBochtler** [extrawurst/gitui#1160]
**Is your feature request related to a problem? Please describe.**
I use the `Copy Hash [y]` feature in the log view quite often. Unfortunately, this feature offers no visual feedback when the key was hit.

**Describe the solution you'd like**
It would be great to get some visual feedback when the hash was copied.
E.g. show a small overlay / popup, that the hash was successfully copied.

**Comment by extrawurst** [comment]
Should be easy to implement as we have arbitrary message popup for this already
