### ISSUE TITLE
Orphan Branches and/or empty new branches (orphan + all files removed).

### ISSUE THREAD

**Issue by a-y-u-s-h** [extrawurst/gitui#1161]
**Is your feature request related to a problem? Please describe.**
It's a very common use case where you have a codebase but you want to create a branch with no files in it. So you first create an orphan branch like so:

```bash
git checkout --orphan <branchname>
```

This will create a new branch with no parents. Then, you can clear the working directory with:

```bash
git rm --cached -r .
```

And then you add the files, commit them and push them to github as a separate branch.

**Describe the solution you'd like**
An option in gitui that allows us to create an orphan branch.

**Describe alternatives you've considered**
The commands above.

**Comment by extrawurst** [comment]
How does this work in common git GUIs? Is that two steps there aswell?

**Comment by a-y-u-s-h** [comment]
> How does this work in common git GUIs? Is that two steps there aswell?

Not really sure. I haven't used any git GUIs other than Gitui.
