### ISSUE TITLE
Problem pushing / pulling with ssh url

### ISSUE THREAD

**Issue by jo541** [extrawurst/gitui#1162]
**Describe the bug**
When I try to push or pull request I have the message "git error:Couldn't find credentials". But I used ssh connection.

**To Reproduce**
1. Go to gitui
2. Commit new modification
3. Press p
4. Error message

**Expected behavior**
Have the possibility to use ssh url. 

**Context (please complete the following information):**
 - macOS 12.2.1
 - GitUI 0.20.1

**Comment by boutmos** [comment]
Same here :

#### Software version

gitui 0.20.1

#### Operating system

macOS 12.2.1 (Darwin 21.3.0)

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: unknown
- Host: aarch64-apple-darwin

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=<not set>
GIT_EDITOR=<not set>
VISUAL=<not set>
```

#### Command-line

```bash
gitui --bugreport
```

**Comment by chris-hulbert-phoenix** [comment]
Not sure if this helps (apologies if this is just comment-spam!) but here's my logs for the same issue:

#### Software version

gitui 0.20.1

#### Operating system

macOS 12.2.1 (Darwin 21.3.0)

#### Compile time information

- Profile: release
- Target triple: x86_64-apple-darwin
- Family: unix
- OS: macos
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2,sse3,ssse3
- Host: x86_64-apple-darwin

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=<not set>
GIT_EDITOR=<not set>
VISUAL=<not set>
```

#### Command-line

```bash
gitui --bugreport 
```

**Comment by extrawurst** [comment]
Can you guys share the offending ssh url?

**Comment by chrishulbert** [comment]
Thanks for responding :) Terribly sorry but I can't, it's a work one, which is a SAML-ed git repo with 'sso enabled'. Having said all that, as far as command-line git is concerned it's vanilla SSH, eg `git fetch` works fine.

One thing might be worth mentioning is: I'm using an 'id_ed25519' key as opposed to an RSA one. Perhaps that's related?

Here's my original post, i put it up on my wrong account:

Not sure if this helps (apologies if this is just comment-spam!) but here's my logs for the same issue:

Software version
gitui 0.20.1

Operating system
macOS 12.2.1 (Darwin 21.3.0)

Compile time information
Profile: release
Target triple: x86_64-apple-darwin
Family: unix
OS: macos
Architecture: x86_64
Pointer width: 64
Endian: little
CPU features: fxsr,sse,sse2,sse3,ssse3
Host: x86_64-apple-darwin
Environment variables
SHELL=/bin/zsh
EDITOR=<not set>
GIT_EDITOR=<not set>
VISUAL=<not set>
Command-line
gitui --bugreport

**Comment by boutmos** [comment]
> Can you guys share the offending ssh url?

No, it a private Gitlab

**Comment by detuur** [comment]
I get the same with my alias for gitlab:
```ssh-config
Host gl
  User git
  Hostname gitlab.com
  IdentityFile ~/.ssh/id_ed25519
```

This alias acts as shorthand for `git@gitlab.com`, so I can do things like
```sh
git clone gl:inkscape
```

This is stored then as the remote url for that repo:
```sh
$ git remote get-url origin
gl:inkscape
```

And then when trying to do manipulations in `gitui`, this gives:
```
┏Error━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┓
┃fetch failed:                                                        ┃
┃git error:failed to resolve address for gl: Try again; class=Net (12)┃
┃                                                                     ┃
┗━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┛
```

**Comment by detuur** [comment]
> Can you guys share the offending ssh url?

Public gitlab.com
