### ISSUE TITLE
Create multi-line commit messages

### ISSUE THREAD

**Issue by florealcab** [extrawurst/gitui#1171]
**Is your feature request related to a problem? Please describe.**
Commit with gitui allow only one commit line, without commit description (like is allowed with commit -m command)

**Describe the solution you'd like**
Allow to add a description to the commit: with a new description field, or simply with a multi-line commit

**Comment by kosayoda** [comment]
If you press the `Open editor` key (default is `^e`) while the commit window is open, you can edit the commit message using a text editor (similar to what `git commit` does).

**Comment by extrawurst** [comment]
See also #509

**Comment by florealcab** [comment]
> If you press the `Open editor` key (default is `^e`) while the commit window is open, you can edit the commit message using a text editor (similar to what `git commit` does).

Yes it did the trick thank you :)


> See also #509

Better to do that! Hope will be merged soon :D

**Comment by Zeioth** [comment]
I'm here for this same reason. A message in the commit window saying the user to press ctrl+e for multi-line commits, while we make something better, wouldn't hurt.

**Comment by extrawurst** [comment]
marking as good first issue, since its just about finishing the draft PR #509

**Comment by IgnisDa** [comment]
Any updates on this?

**Comment by crispinb** [comment]
I'll have a look to see if I can finish off https://github.com/extrawurst/gitui/pull/1309.

@extrawurst - are you open to assessing https://github.com/rhysd/tui-textarea/ for this purpose? I ask not yet knowing the gitui codebase (hence implications)  nor your attitude to deps. I've tried a couple of the examples and it seems nice on the face of it not to have to roll-your-own scrolling & cursor etc. It  might also have other uses within gitui perhaps?

If you're open to it I'll explore that route first briefly as a test of fit and report back. If not I'll disinter the above PR and see what I might do with it.

**Comment by crispinb** [comment]
Ah. I see now there's an [issue already suggesting use of tui-textarea](https://github.com/extrawurst/gitui/issues/1662), which should give us  multiline input for free. So never mind for now. I'll keep an eye on that issue in case help's needed at any stage. It would be a good one to get over the line.

**Comment by extrawurst** [comment]
closing favor of #2045
