### ISSUE TITLE
Support --git-dir flag for custom git dir locations.

### ISSUE THREAD

**Issue by mzeo** [extrawurst/gitui#1176]
I am using a custom git dir when I manage my dot files similar to this tutorial: https://www.atlassian.com/git/tutorials/dotfiles It requires the usage of the `--git-dir` flag for the git command. I would like to be able to use gitui for managing my dot files, but have not found a way to supply a custom git dir.

I would like for gitui to support the `--git-dir` flag from git.

I was unable to find a workaround.

**Comment by extrawurst** [comment]
Please run `gitui -h` it will show you the arg to do it
