### ISSUE TITLE
mintty(cygwin): using vim as editor messes up terminal

### ISSUE THREAD

**Issue by jjYBdx4IL** [extrawurst/gitui#1178]
when I start vim from gitui and then exit vim, the console gets garbled with terminal escape codes (color encodings). Terminal type is set to "xterm". gitui stops to display properly, though it continues to run (or so it seems). Output stays black/white from then on.

**Comment by extrawurst** [comment]
Weird. Can you share your logs please

**Comment by jjYBdx4IL** [comment]
how do I build this with visual studio? I'm now getting "invalid path".

**Comment by jjYBdx4IL** [comment]
or any way on Windows. "cargo install" yielded an error when building openssl....

**Comment by jjYBdx4IL** [comment]
btw there is CPackWiX, builds installer package directly from cmake.

**Comment by extrawurst** [comment]
See https://github.com/extrawurst/gitui/issues/806#issuecomment-884776501

**Comment by jjYBdx4IL** [comment]
sorry, no time for this
