### ISSUE TITLE
Fetch Failed: Trying to pull over SSH

### ISSUE THREAD

**Issue by cxloe** [extrawurst/gitui#1182]
**Describe the bug**
When i try to pull using a repo set up over SSH, i get the following:

fetch failed:
git error:ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.

**Context (please complete the following information):**
 - OS/Distro + Version:Neon 20.04 focal
 - GitUI Version: gitui 0.20.1
 - Rust version: rustc 1.61.0-nightly (285fa7ecd 2022-03-14)

**Comment by extrawurst** [comment]
well I guess the message gives it away, right? consider upgrading your old ssh key?

**Comment by cxloe** [comment]
Changed my SSH key to a fresher one. Is there any way to specify what key to use? I'm just getting "Bad credentials" now. Can confirm it's working fine with just "ssh git@github.com -v"

**Comment by tobealive** [comment]
Is it possible that the error message is inaccurately triggered? Unfortunately, I don't currently have the free time to investigate the gitui code base to give an answer to myself.

Despite having a freshly generated ed25519 key, I am still encountering the same error. There are no issues with other Git connections, such as via LazyGit. Initially, I thought the issue might be related to RSA keys that I use for other connections, so I wiped everything related to RSA. However, I still encounter the same RSA error when attempting to interact with Git via gitui.

`git error:ERROR: You're using an RSA key with SHA-1, which is no longer allowed. Please use a newer client or a different key type.`

**Comment by deadeyesky** [comment]
I am having this issue as well. Any fix or recommendations?
