### ISSUE TITLE
Can't push from gitui (Failed getting banner; class=Ssh (23), but working from cli

### ISSUE THREAD

**Issue by fulljackz** [extrawurst/gitui#1194]
**Describe the bug**
Error while trying to push with error 

```
git error:failed to start SSH session: Failed getting banner; class=Ssh (23)
```

**To Reproduce**

Don't really know how to reproduce.

**Expected behavior**
While testing gitui everything is ok, but push is not working.
When I quit application and write `git push ` in my terminal, everything is ok.

**Screenshots**
![image](https://user-images.githubusercontent.com/12140932/163337517-a70bf5ec-3c35-4204-815a-4b0ef88f5774.png)

**Context (please complete the following information):**
 - Ubuntu 22.04
 - GitUI Version 0.20.1
 - Rust version: rustc 1.60.0 (7737e0b5c 2022-04-04)

**Additional context**
Gitui was installed from cargo

**Comment by fulljackz** [comment]
Hum, after some investigations, I use custom ssh config to connect to servers through SSH (specifically for security purpose, I connect through a ssh proxy).

It seems that gitui is not sourcing `.ssh/config` file.

Is there a way to tell gitui sourcing it ?
Regards,

**Comment by extrawurst** [comment]
the upstream lib does not care for ssh/config see https://github.com/libgit2/libgit2/issues/4872

**Comment by Dandarprox** [comment]
Still unresolved

**Comment by greg-bell** [comment]
Duplicate of https://github.com/extrawurst/gitui/issues/495 ?
