### ISSUE TITLE
Pass through error messages from commit

### ISSUE THREAD

**Issue by CGMossa** [extrawurst/gitui#1195]
**Describe the bug**
I have a repository with hooks that warn of something or another.

I didn't ensure that the thing was done, so when I tried to commit some
changes, I got this:

![image](https://user-images.githubusercontent.com/1063624/163460929-3453fbe2-b9d0-475e-bc68-e281925fbec5.png)

Using `git commit -m` I got this:

```
PS C:\Users\angus\Documents\GitHub\DenmarkMap> git commit -m "another configuration commit"
README.md is out of date; please re-knit README.Rmd
use 'git commit --no-verify' to override this check
```

**Expected behavior**

I expected to get the message in `gitui`. 

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 10, 
 - GitUI Version: 0.20.1
 - Rust version: rustc 1.60.0 (7737e0b5c 2022-04-04)

**Comment by extrawurst** [comment]
It looks more like an issue running the hooks in the first place. Hard for me repro on a non windows machine though :(
