### ISSUE TITLE
`hjkl` keybindings on Mac don't work

### ISSUE THREAD

**Issue by xypnox** [extrawurst/gitui#1202]
**Describe the bug**
Vim Keybindings for Mac don't work -> Specifically the `hjkl` movement. 

**To Reproduce**
1. Set [config](https://github.com/extrawurst/gitui/blob/master/vim_style_key_config.ron) in `~/Users/(username)/.config/gitui`
2. Open `gitui` and try to use `hjkl`
3. No effect

**Expected behavior**
Move as it should.

**Context (please complete the following information):**
 - OS/Distro + Version: macOS 12.3.1 21E258 x86_64
 - GitUI Version gitui 0.20.1
 - Rust version: (`gitui` was installed via brew) rustc 1.57.0-nightly (003d8d3f5 2021-10-04)

**Additional context**

**Comment by extrawurst** [comment]
can't reproduce that problem. did you name the config correctly? the filename has to be `key_config.ron` see https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md

**Comment by xypnox** [comment]
Yep I did set it at the correct name:
```
 ~/.c/gitui ❯❯❯ pwd
/Users/xypnox/.config/gitui
~/.c/gitui ❯❯❯ ls
key_config.ron     key_config.ron.old theme.ron
```

I am running it in Alacritty. (alacritty 0.10.1 (2844606))

**Comment by extrawurst** [comment]
It has to be `key_bindings.ron`

**Comment by xypnox** [comment]
Thanks this works fine now!
