### ISSUE TITLE
Input is case sensitive

### ISSUE THREAD

**Issue by andresovela** [extrawurst/gitui#1211]
**Describe the bug**
Input should be case insensitive, but it isn't. I'd expect the `c` key to open the commit prompt, but it only opens when the caps lock key is not active.

**To Reproduce**
1. Open a repo with some staged changes
2. Press the caps lock key to write upper case
3. Press the `c` key

**Expected behavior**
The commit prompt should open. It doesn't.

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro + Version: Fedora 34
 - GitUI Version 0.20.1

**Additional context**
The same problem exists with other menus. For example `"b"` opens the branches prompt, while `"B"` opens the blame screen. The blame screen should only open on the `Shift+B` key combination.

**Comment by extrawurst** [comment]
> The same problem exists with other menus. For example "b" opens the branches prompt, while "B" opens the blame screen. The blame screen should only open on the Shift+B key combination.

I consider this the bug then. cause we explicitly use the casing in some 'cases'
