### ISSUE TITLE
Support pull --rebase

### ISSUE THREAD

**Issue by JavierL1** [extrawurst/gitui#1212]
**Is your feature request related to a problem? Please describe.**
As far as I know there is no support for the `git pull --rebase` command.

**Describe the solution you'd like**
It might be a good idea to bind the shortcut `⇧f` or `^f` to this action.

**Describe alternatives you've considered**
Currently I have to leave the app to execute the command manually.

**Comment by extrawurst** [comment]
if you configure your pull to be rebase by default, gitui will respect that too

**Comment by dljsjr** [comment]
> if you configure your pull to be rebase by default, gitui will respect that too

That is technically true but I want to +1 this issue if only because some workflows require you to be able to do both. I like to use `pull --rebase` to enforce linearity on certain branches but often use merge commits on long-lived non-main branches like release/support branches.
