### ISSUE TITLE
Missing documentation of default shortcut keys on Windows

### ISSUE THREAD

**Issue by SMUsamaShah** [extrawurst/gitui#1213]
**Describe the bug**
See this image. I don't understand the keys for Close, Local/Remote, Checkout, also some unreadable text with Compare, Delete and Rebase.
![image](https://user-images.githubusercontent.com/385283/165970225-d6c5e69a-7a53-4a71-834c-5e125e633144.png)

**To Reproduce**
1. Open gitui in cmd on Windows 10.
2. Press 'b' to show branches

Font in cmd is set to Consolas. Using Courier New is even worse.

**Expected behavior**
Keys should be readable. If not, please at least add in Readme.md the default key-bindings for Windows we can refer to.

**Context (please complete the following information):**
 - Windows 10
 - GitUI Version 0.20.1

**Comment by gepito** [comment]
Thanks @SMUsamaShah for the fix!
I'd prefer using enter or <Enter> instead of fancy characters as in the demo: https://extrawurst.itch.io/gitui
