### ISSUE TITLE
Config file for diff settings

### ISSUE THREAD

**Issue by ilkka** [extrawurst/gitui#1218]
I'm on Windows and mostly I'm checking out files with CRLF EOLs and letting git commit them with LFs. This is fine, but it causes gitui's diff view to show all lines as changed unless I ignore whitespace changes in the options popup.

Ideally I'd like gitui to act like the git CLI does, which is to ignore these EOL changes, since `core.autocrlf=true`. However it'd be enough for basic usage to just be able to always have ignore whitespace set to true via a config file.

**Comment by extrawurst** [comment]
ok let me look into our core lib if we can ignore line endings in diff (I would assume so).

the other point is worth an entire different ticket, as I would like to to start saving configs inside `.git`-folder in the future.

**Comment by kkysen** [comment]
Other `.git/config`/`.gitconfig` settings would be really useful, too, such as `diff.context`, as I often want more fine-grained diffs that don't group together unrelated but nearby changes.

**Comment by extrawurst** [comment]
done as of #849
