### ISSUE TITLE
Proxy config by git not working

### ISSUE THREAD

**Issue by dodowhat** [extrawurst/gitui#1220]
**Describe the bug**
Proxy config by `git config http.proxy ...` not working with GitUI ,
it works well from CLI.

**Context (please complete the following information):**
 - OS/Distro + Version: Debian Testing bookwarm
 - GitUI Version 0.20.1

**Comment by extrawurst** [comment]
looks like a dup of https://github.com/extrawurst/gitui/issues/1194

**Comment by cyejing** [comment]
I have the same problem.
my gitconfig `git config --global http.proxy 'socks5://127.0.0.1:1080`
fetch get error
```
fetch failed: 
git error:unknown http scheme 'socks5'; class=Http (34)
```

**Comment by hirschenberger** [comment]
This is still an issue
