### ISSUE TITLE
consider `GIT_DIR`/`GIT` when opening gitui

### ISSUE THREAD

**Issue by dreuter** [extrawurst/gitui#1223]
**Is your feature request related to a problem? Please describe.**
I am using [`vcsh`](https://github.com/RichiH/vcsh) to manage my dotfiles. It is a wrapper around git, which allows me to have more than one git repository "checked out" in the home directory. I would love to use gitui to stage/commit/log... in the vcsh repositories.
But currently it tells me:
```
$ gitui
invalid path
please run gitui inside of a non-bare git repository
```
Whereas the normal git commands like i.e. `git log` work as usual.

**Describe the solution you'd like**
gitui should respect the [`GIT_DIR`](https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables) variable, such that one can use gitui even if they are not in a subfolder of the git repo if this variable is set.

**Describe alternatives you've considered**
One could checkout the repos like normal, edit/copy and commit in the normal repo, push and pull via vcsh.

**Additional context**
https://github.com/RichiH/vcsh
https://git-scm.com/book/en/v2/Git-Internals-Environment-Variables

**Comment by mark2185** [comment]
In the meantime, have you tried using launching `gitui` with the `--directory` flag?

```
OPTIONS:
    -d, --directory <directory>    Set the git directory
```

**Comment by dreuter** [comment]
> In the meantime, have you tried using launching `gitui` with the `--directory` flag?
> 
> ```
> OPTIONS:
>     -d, --directory <directory>    Set the git directory
> ```

You are absolutely right, this is the correct workaround. `gitui -d=${GIT_DIR}` works like a charm :)
But I guess considering `GIT_DIR` would still be useful?

**Comment by mark2185** [comment]
> But I guess considering GIT_DIR would still be useful? And it should be relatively straight forward to implement then I guess.

I wholeheartedly agree, I just wanted to ease your trouble until it's implemented properly :)

**Comment by dreuter** [comment]
I just found 13afbf6bba61035011dbc47159dbdce8a7110fc8 I guess it is just not released. Sorry for the noise...

**Comment by glaeqen** [comment]
On that note, `vcsh run <repo> gitui` can be also used (it just forwards environmental variables to `gitui`). 

But in general this is not enough, because GIT_WORK_TREE for vcsh managed repos is in the home directory which causes `gitui` to explode when it tries to process all the untracked files. Is there some kind of workaround? If not, this could be solved by a flag to `gitui` that would make it ignore untracked files. Great project BTW, love it.

**Comment by extrawurst** [comment]
@glaeqen sounds like this is a whole different issue. can you open a new one and describe it so one can reproduce without prior knowledge?
