### ISSUE TITLE
gitui does not work inside a sparse checkout

### ISSUE THREAD

**Issue by W1M0R** [extrawurst/gitui#1226]
**Describe the bug**
Trying to launch gitui inside a sparse checkout produces the following message:

```bash
invalid path
please run gitui inside of a non-bare git repository
```

**To Reproduce**

```bash
$ git clone \
	--depth 1 \
	--filter=blob:none \
	--sparse \
	--branch master \
	https://github.com/extrawurst/gitui.git \
	~/gitui
$ cd ~/gitui
$ git sparse-checkout set --stdin <<EOF
.gitignore
EOF
$ gitui
invalid path
please run gitui inside of a non-bare git repository
$ lazygit
...just works...
```

**Expected behavior**
gitui should detect the repo and launch without error.

**Screenshots**
None

**Context (please complete the following information):**
 - Ubuntu 20.04
 - gitui 0.20.1
 - Rust version: Not installed

**Additional context**
Installed via nix.

**Comment by extrawurst** [comment]
see https://github.com/libgit2/libgit2/issues/2263

**Comment by extrawurst** [comment]
will close until upstream supports this

**Comment by melMass** [comment]
Seems like this is the upstream PR to follow: https://github.com/libgit2/libgit2/pull/6394
