### ISSUE TITLE
Add xclip or xsel as optional dependency on linux distrobutions

### ISSUE THREAD

**Issue by lil5** [extrawurst/gitui#1238]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I install gitui and can't copy anything because a dependency is not met

**Describe the solution you'd like**
To add xclip or xsel as (optional)? dependency to fedora's dnf and other Linux repositories, where needed.

**Describe alternatives you've considered**
An error message when copying does not succeed prompting the user to install the necessary dependency

**Comment by lil5** [comment]
https://github.com/extrawurst/gitui/issues/352

**Comment by lil5** [comment]
Bad bot

**Comment by extrawurst** [comment]
I do not maintain linux distro package so this is the wrong place for this request. support for xsel was added via: https://github.com/extrawurst/gitui/pull/390
