### ISSUE TITLE
Ranged copy hash

### ISSUE THREAD

**Issue by intrnl** [extrawurst/gitui#1244]
**Is your feature request related to a problem? Please describe.**
Cherry picking is a daily occurence for my work, and it would usually involve a lot of commits needing to be picked, often 1, but often 10-20 commits as well.

**Describe the solution you'd like**
It would be nice if we can do a commit selection and have the copy hash shortcut copy the range.

**Describe alternatives you've considered**
Yes, I could just do a copy and paste of every single commits I want picked, however that's not fast and convenient.

**Additional context**
None.

**Comment by extrawurst** [comment]
do you want all the commits listed in a comma-separated way or some `<commithash1>..<commithash2>` notation?

**Comment by intrnl** [comment]
The former is okay, the latter is a nice topping on top.

**Comment by extrawurst** [comment]
well the one is fundamentally different to the other :)
one can have gaps, the other not. so I lean towards the comma-separated list

**Comment by extrawurst** [comment]
@remique fine by me. are you up for making it a PR? ;)

**Comment by remique** [comment]
Sure, working on it 👍
