### ISSUE TITLE
Show tags and branch heads in the log view.

### ISSUE THREAD

**Issue by vext01** [extrawurst/gitui#1252]
**Is your feature request related to a problem? Please describe.**

I use `tig` to see where my branch is relative to another branch (typically main). I'd like to switch to `gitui` because it parses large git histories much faster, but I need to be able to see tags and branch heads in the log view.

**Describe the solution you'd like**

Display tags and branch heads in the log view.

**Additional context**

The same repo in `gitui` and `tig`.

`tig` shows the tags and branch heads in orange.

![image](https://user-images.githubusercontent.com/604955/177743040-a67d913c-b58a-4052-9d08-aab5b88bb902.png)

**Comment by extrawurst** [comment]
tags should be displayed already in the log view, can you double check?

**Comment by vext01** [comment]
Perhaps tags are shown, but as shown in my screenshots, branch heads are not.

I think both tags and branch heads need to be clearly discernible at a glance, like in tig.

Thanks
