### ISSUE TITLE
[panic] non deterministic panic on quit

### ISSUE THREAD

**Issue by nichelnich** [extrawurst/gitui#1263]
**Context (please complete the following information):**
 - OS/Distro + Version: [e.g. `ubuntu 18.04  kernel-V4.15.0-176`]
 - GitUI Version [v0.20.1]
 - Rust version: [1.62.1]
[gitui.log](https://github.com/extrawurst/gitui/files/9186093/gitui.log)

**Comment by extrawurst** [comment]
can you share some more details in how you got this? does it happen for you every time you quit the application?

**Comment by nichelnich** [comment]
> can you share some more details in how you got this? does it happen for you every time you quit the application?

not every time. some times panic just run and quit after status done. my repo is big, about 10G.
