### ISSUE TITLE
Remove hardcoded blue background color

### ISSUE THREAD

**Issue by jantari** [extrawurst/gitui#129]
**Is your feature request related to a problem? Please describe.**
It appears gitui uses a hardcoded blue color in some of its UI elements, such as the bottom shortcut row, the currently selected file on the top left and the diff header with the line information on the right. This blue color does not fit into most themes and may cause visibility and contrast problems with some.

**Describe the solution you'd like**
Use the terminals DarkBlue color palette instead of hardcoding colors.

**Describe alternatives you've considered**
None

**Additional context**
Screenshot of gitui with GruvBox Dark theme:
![image](https://user-images.githubusercontent.com/25607767/84691894-3bda7c00-af45-11ea-8669-9aff8f97b2d7.png)

**Comment by extrawurst** [comment]
Hi @jantari thanks for your interest in gitui. You can customise all colors following this guide: https://github.com/extrawurst/gitui/blob/master/THEMES.md 

let me know if there is anything you cannot customise to match your taste.

**Comment by jantari** [comment]
It is nice that the theme can be customized to take advantage of the 24bit True color terminals we have these days, but I think the default should be to use the terminals palette.

**Comment by extrawurst** [comment]
this is released in `0.8` now: https://github.com/extrawurst/gitui/releases/tag/v0.8.0
