### ISSUE TITLE
safe.directory '*' is not accepted

### ISSUE THREAD

**Issue by laktak** [extrawurst/gitui#1293]
**Describe the bug**

git works on mounted directories if you use
```
git config --global --add safe.directory '*'
```

But gitui will throw an error:
```
invalid path
please run gitui inside of a non-bare git repository
```

I can work around the issue by using 
```
git config --global --add safe.directory /mnt/...
```
but I have to do this for every directory.

**To Reproduce**
- run `git config --global --add safe.directory '*'`
- go to a mounted directory
- run `git clone https://github.com/extrawurst/gitui`
- cd into gitui and run `git status` # this will work
- run `gitui` # this will give an error

**Expected behavior**
gitui should use the same options as git (if this is a problem of a dependency please let me know so I can report it there)

**Context (please complete the following information):**
 - arch
 - gitui 0.20.1 (from arch repos)

**Comment by extrawurst** [comment]
that certainly needs to be reported in upstream: https://github.com/libgit2/libgit2

**Comment by laktak** [comment]
This has been fixed upstream.

**Comment by extrawurst** [comment]
waiting for git2-rs to cut a release for this: https://github.com/rust-lang/git2-rs/pull/935

**Comment by laktak** [comment]
Appears to be ready?

**Comment by Hpmason** [comment]
This appears to be fixed in the master branch, but the latest crates.io release still isn't fixed. For anyone still running into this issue try installing gitui from master:

```
cargo install --git https://github.com/extrawurst/gitui
```

**Comment by extrawurst** [comment]
Can someone validate if this works now since `0.25` should contain the upstream feature now

**Comment by laktak** [comment]
Yes, it works without problems, thank you!
