### ISSUE TITLE
[Help] Shortcut issues

### ISSUE THREAD

**Issue by hgezim** [extrawurst/gitui#1295]
How do I jump from one hunk to next without visiting each line? I'm SSH-ed into a Linux machine where `gitui` runs from a Mac.

**Comment by hgezim** [comment]
I'm having more shortcut troubles. Pressing <enter> doesn't add hunk but the whole file:

A video: https://share.cleanshot.com/EVN9Yy

**Comment by extrawurst** [comment]
for some reason it shows that you only have one hunk in the diff. that's why `enter` adds the whole file. need to figure out how to reproduce this

**Comment by extrawurst** [comment]
also related to #1523

**Comment by extrawurst** [comment]
duplicate of #1523
