### ISSUE TITLE
Push, Pull disabled on bare repo

### ISSUE THREAD

**Issue by nazdridoy** [extrawurst/gitui#1296]
**Describe the bug**
git cli push works with GIT_WORK_TREE="$HOME" GIT_DIR="$HOME/.dotfiles" prefix. 

`gitui -w $HOME -d $HOME/.dotfiles`
mostly works but "Push [p]" and "Pull [f]" options are disabled.

**Screenshots**
![2022-08-24_23-03](https://user-images.githubusercontent.com/45564804/186479682-2418329c-f1d4-4ea2-baf1-b02802b9a6cf.png)

**Context (please complete the following information):**
 - OS/Distro + Version: ArcoLinux
 - GitUI Version : gitui 0.21.0

**Comment by extrawurst** [comment]
can you provide a step by step repo how to clone something as bare so that I can reproduce this please?
