### ISSUE TITLE
untracked files in stash diff not shown

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#130]
unfortunately git stores the untracked files of a stash in the stash's [third parent](https://stackoverflow.com/a/51276389/2458533) so we need some super specific process to make sure the `inspect` works correctly here.

fun fact, the same applies to fork:
<img width="417" alt="Screenshot 2020-06-15 at 21 08 44" src="https://user-images.githubusercontent.com/776816/84696211-6976f380-af4c-11ea-98e1-338b384cf003.png">

**Comment by MCord** [comment]
I will take this one.

**Comment by extrawurst** [comment]
@MCord thanks again, this is released in `0.8` now: https://github.com/extrawurst/gitui/releases/tag/v0.8.0
