### ISSUE TITLE
Small bugs in the Help window

### ISSUE THREAD

**Issue by hansmuff** [extrawurst/gitui#131]
The 'Help: all commands' contains "Diff" twice [,](https://i.imgur.com/v5ziUOB.png) but when you try to highlight the first occurrence, it [https://i.imgur.com/XQ0TU6v.png](url) skips over it [https://i.imgur.com/DvEZu6J.png](url) and goes to "Add hunk" or "Inspect" depending which direction I scroll using the arrow keys up/down. Also I can't highlight the first entry "Log" [.](https://i.imgur.com/8XOZT7z.png)

This is on the Windows version running within Windows Terminal (the MS Store App version) on the latest Windows 10 Insider build.

**Comment by extrawurst** [comment]
Hey @hansmuff thanks for following up on this, as expected its a problem with the terminal color palette. 
Here is what it looks like for me:
<img width="683" alt="image" src="https://user-images.githubusercontent.com/776816/84707792-a1d3fd00-af5f-11ea-8467-2c086670c775.png">

The particular entry uses a inverted fg/bg, so it can happen if u are using a transparent background color. is that possible?

**Comment by extrawurst** [comment]
should be more clear to read now:

<img width="532" alt="image" src="https://user-images.githubusercontent.com/776816/85300760-42b64100-b4a7-11ea-865c-1b8601d9f053.png">

**Comment by extrawurst** [comment]
this released in `0.8` now: https://github.com/extrawurst/gitui/releases/tag/v0.8.0
