### ISSUE TITLE
Multi-Select in the "Stashes" View, to drop multiple stashes with one command

### ISSUE THREAD

**Issue by hansmuff** [extrawurst/gitui#132]
When in the "Stashes" view, I would like to select multiple stashes, and be able to use the Drop command on all the selected stashes. 

Suggested keyboard usage for this: SHIFT+Arrow selecting the highlighted plus the next/previous stash.
S key to Select or De-Select the highlighted stash. A to select or De-Select All stashes.

Commands "Apply" and "Drop" should work with multiple stashes, "Inspect" probably not.

**Comment by extrawurst** [comment]
This is supported now as of #854
