### ISSUE TITLE
Yubikey Authentication Support

### ISSUE THREAD

**Issue by maxrichie5** [extrawurst/gitui#1334]
**Is your feature request related to a problem? Please describe.**
My company uses yubikey authentication when interacting with the remote repo. 

From the command line this is what the looks like:
```
$ git pull
Confirm user presence for key ECDSA-SK SHA256:+OZM73LLxxxWYdacxxxxxJOCBM79F2OyoqAAVpxxxxx
```
Then I touch the yubikey, and it says
```
User presence confirmed
```
And does a normal pull.

When using GitUI this happens
<img width="1413" alt="Screen Shot 2022-09-14 at 3 57 48 PM" src="https://user-images.githubusercontent.com/46904505/190270322-073f692f-d2b2-4047-9d09-8cba4a5628af.png">

**Describe the solution you'd like**
I would like GitUI to support yubikey authentication. Just like the git CLI does.

**Comment by oliverpool** [comment]
(Looks like a duplicate of #969)
