### ISSUE TITLE
Freeze when `Blame` inside a `Blame`

### ISSUE THREAD

**Issue by AndyJado** [extrawurst/gitui#1336]
**Describe the bug**
---
My working repo is `rust` from `rust-lang`, I go `<Shift-B>` on a file from another commit and I see some spinning, then spinning goes off and freeze, I can `esc` to go back.

**To Reproduce**
---
1. Go to 'Files'
2. 'Blame'
3. Inspect that commit 'l'
4. Go to 'Files' with `<Shift + f>`, head in another commit now
5. `Blame` again on anyfile
6. freeze!

**Expected behavior**
---
Maybe forbid recursively blaming?

**Additional context**
---
If it's not a hurry, I'd like to fix it. I'm currently rather loaded

**Comment by extrawurst** [comment]
can't reproduce. can you give me exact files you blame to get this to happen?

**Comment by AndyJado** [comment]
>4. Go to 'Files' with <Shift + f>, head in another commit now
>5. Blame again on anyfile

sorry I wasn't clear, modified step 4.

I tested it on much smaller repo, it happens.

**Comment by extrawurst** [comment]
still no repro inside gitui repo. can you trigger it in the gitui repo?

**Comment by chenrui333** [comment]
Yeah, I am unable to reproduce either.

But I do see gitui runs blame pretty slow for me compared with gitlens (vscode) in the monorepo setup.

**Comment by extrawurst** [comment]
@chenrui333 yeah the blame slowness in some cases is in another issue already

**Comment by AndyJado** [comment]
Gone after upgrade, my bad.

package `gitui v0.20.1` with `gitui v0.21.0
