### ISSUE TITLE
aarch64 build?

### ISSUE THREAD

**Issue by fredngo** [extrawurst/gitui#1343]
**Is your feature request related to a problem? Please describe.**

Excitedly installed this on my ARM Linux box by following [these instructions](https://github.com/extrawurst/gitui/issues/1018#issuecomment-1102308583) and got:

```
$ gitui
bash: /usr/local/bin/gitui: cannot execute binary file: Exec format error
```

**Describe the solution you'd like**

Please build for `aarch64`

**Describe alternatives you've considered**

N/A

**Additional context**

My Ubuntu install:

```
$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.4 LTS
Release:        20.04
Codename:       focal

$ uname -a
Linux mylinuxbox 5.4.0-92-generic #103-Ubuntu SMP Fri Nov 26 16:15:10 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux

$ dpkg --print-architecture
arm64

$ arch
aarch64
```

**Comment by extrawurst** [comment]
yeah the linux build is x86 at the moment

**Comment by extrawurst** [comment]
open for PRs
