### ISSUE TITLE
Add vim key bindings

### ISSUE THREAD

**Issue by itsjoniur** [extrawurst/gitui#1344]
**Is your feature request related to a problem? Please describe.**
Can't use vim key bindings to move and navigate in buffers

**Describe the solution you'd like**
support vim key bindings

**Comment by tuanbass** [comment]
I have a look in the source code, and it likely already support vim binding, but not activated by default. 
```
cd ~/.config/gitui
curl -o key_bindings.ron  https://raw.githubusercontent.com/extrawurst/gitui/master/vim_style_key_config.ron
```

**Comment by extrawurst** [comment]
See https://github.com/extrawurst/gitui#bindings

**Comment by itsjoniur** [comment]
> I have a look in the source code, and it likely already support vim binding, but not activated by default.
> 
> ```
> cd ~/.config/gitui
> curl -o key_bindings.ron  https://raw.githubusercontent.com/extrawurst/gitui/master/vim_style_key_config.ron
> ```

Yes, I see
