### ISSUE TITLE
Show git hook status

### ISSUE THREAD

**Issue by Wyfy0107** [extrawurst/gitui#1351]
**Is your feature request related to a problem? Please describe.**
So a project I was working on was using husky and git hook to lint commit. And when I commit with gitui, it would take quite a long time before the lint is finished, and gitui just shows that's it's committing, which is confusing as it feels like something broken

**Describe the solution you'd like**
Could we somehow show git hook progress, if there is, to the user while committing?

**Describe alternatives you've considered**

**Additional context**

**Comment by valerio-pescatori** [comment]
I also think that would be a great feature. Actually I opened a discussion about it but nobody saw it: #2033  🥲

**Comment by extrawurst** [comment]
duplicate of #2039
