### ISSUE TITLE
Icons that are difficult to understand

### ISSUE THREAD

**Issue by qingfengfenga** [extrawurst/gitui#1357]
I downloaded and experienced gitui today. It's really great. It's exactly what I want.Thank you very much for your work

In addition, I also put forward some problems I encountered to make the tool better and better

Version
Windows 11 Pro 21H2 
gitui 0.21.0 msi

At present, there is only function description on the help page

Some icons are difficult to understand. You can add descriptions of shortcut key names in the help interface to help you understand the corresponding relationship between icons and keys

![pdeZ1sxkcr](https://user-images.githubusercontent.com/41416092/192202504-d6e1e8ed-f375-43a7-b321-2f8eb1deebe9.jpg)

![1FKx2g9MS5](https://user-images.githubusercontent.com/41416092/192202512-1f5c273c-efb5-457e-92d4-e3415d651453.jpg)

**Comment by extrawurst** [comment]
you can configure the symbols and overwrite the defaults: see https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md#key-symbols

**Comment by m-fonseca** [comment]
Are the docs still correct?  I tried those docs as an example and they didn't effect the symbols display for me.  Specifically
```
(
    enter: Some("enter"),
    shift: Some("shift-")
)
```
