### ISSUE TITLE
A blank removed line is not shown as changed when it is replaced by another line

### ISSUE THREAD

**Issue by marcbull** [extrawurst/gitui#1359]
A blank removed line is not shown as changed when it is replaced by another line.

**To Reproduce**

Execute the following block to setup the example:

```
export TEST_REPO=/tmp/test-repo
mkdir -p ${TEST_REPO}
pushd ${TEST_REPO}
git init
printf "###\n\naaa\n\n\n###\n" > example.txt
git add .
git commit -a -m "initial commit"
printf "###\n\naaa\nbbb\n\n###\n" > example.txt
git diff
```

The `git diff` shows how it should look like.

Now execute `gitui` to see the wrong diff view for example.txt.

The `gitui` doesn't show the removed line as changed before the new `bbb` line

**Expected behavior**

The diff of gitui and git diff should be identical.

**Thank you very much for this awesome tool.**

#### Software version

gitui 0.21.0

#### Operating system

macOS 12.6 (Darwin 21.6.0)

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
- Host: aarch64-apple-darwin

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=<not set>
GIT_EDITOR=<not set>
VISUAL=<not set>
```

#### Command-line

```bash
gitui --bugreport
```

**Comment by marcbull** [comment]
Ping

**Comment by conor-byrne** [comment]
Would just like to second this issue with another example:

git diff:
```diff
diff --git a/controller/DC10/Lib/Rabbit4000/RS232.LIB b/controller/DC10/Lib/Rabbit4000/RS232.LIB
index cab9f5d..bba9dc1 100644
--- a/controller/DC10/Lib/Rabbit4000/RS232.LIB
+++ b/controller/DC10/Lib/Rabbit4000/RS232.LIB
@@ -4891,12 +4891,11 @@ spx_isr::
                ld              hl, lxpc
                push    hl

-
+#if defined(SER_INSTRUMENT)
       ld hl, (ser_isrs)
       inc hl
       ld (ser_isrs), hl
-
-
+#endif

                ; IX = serXdata, IY = SxDR
 ioi    ld              a, (iy+SxSR_OFS)
```

gitui:
![image](https://github.com/extrawurst/gitui/assets/15220966/36f99f7e-24bc-4deb-84ed-c8decd4710ca)

#### Software version

gitui 0.22.1 (234e7cb)

#### Operating system

Windows 6.2.9200

#### Compile time information

- Profile: release
- Target triple: x86_64-pc-windows-msvc
- Family: windows
- OS: windows
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-pc-windows-msvc

#### Environment variables

```bash
SHELL=<not set>
EDITOR=<not set>
GIT_EDITOR=<not set>
VISUAL=<not set>
```

#### Command-line

```bash
"C:\Program Files\gitui\bin\gitui.exe" --bugreport newlines
```

Using powershell 7 in windows terminal

**Comment by extrawurst** [comment]
We could also fill in a minus-char to visualize the empty line being removed 👍

**Comment by extrawurst** [comment]
<img width="746" alt="Screenshot 2023-08-11 at 16 42 16" src="https://github.com/extrawurst/gitui/assets/776816/75eff83c-88e0-4d96-b978-adf7bde6036b">
