### ISSUE TITLE
optional theme overwrites

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#1367]
similar to the key bindings the theme config should use optional overwrites so that adding a new style does not break all the customised theme settings

**Comment by extrawurst** [comment]
see https://github.com/extrawurst/gitui/issues/946

**Comment by extrawurst** [comment]
motivated again by https://github.com/extrawurst/gitui/issues/1365

**Comment by cruessler** [comment]
I’m going to start working on this issue!

**Comment by extrawurst** [comment]
Thanks ❤️
You are on 🔥

**Comment by extrawurst** [comment]
thanks @cruessler 🥳
