### ISSUE TITLE
Hard reset for modified files

### ISSUE THREAD

**Issue by ClementNerma** [extrawurst/gitui#1372]
Hi there!

I've been using GitUI for a few days and I've been really enjoying it :)

I was wondering if it would be possible to add a "hard reset" shortcut to reset files to what they were at the last commit.

Basically, let's say I have a file, and edit it and commit the changes in commit A. Then I do some edits but want to revert them. This feature would revert the file to the state it was when I made commit A.

Thanks in advance for your answers!

**Comment by extrawurst** [comment]
You basically want to checkout a specific file to a specific commit ?

**Comment by ClementNerma** [comment]
> You basically want to checkout a specific file to a specific commit ?

No, to the last commit only. This would exactly equivalent to running `git checkout <path>` for tracked files.

Ideally it could work on directories too (git supports that as well). With a hard confirmation message defaulting to the 'No' option to ensure no data is accidentally lost, this could come very handy.
