### ISSUE TITLE
Arrow keys doesn't work in Wezterm

### ISSUE THREAD

**Issue by azzamsa** [extrawurst/gitui#1378]
**Describe the bug**
Arrow keys doesn't work in Wezterm

**To Reproduce**
1. Install wezterm
2. Install gitui
3. Use arrow key

**Expected behavior**
The arrow key should work

**Screenshots**

[Kooha-2022-10-05-18-17-10.webm](https://user-images.githubusercontent.com/17734314/194048453-6ef9d345-85c8-469c-9782-e6f25eb85518.webm)

**Context (please complete the following information):**
```
OS: Fedora Linux 36 (Workstation Edition) x86_64
Kernel: 5.19.12-200.fc36.x86_64
Shell: zsh 5.8.1
DE: GNOME 42.5
WM: Mutter
```

```
❯ gitui --version
gitui 0.21.0

~
❯ rustc --version
rustc 1.64.0 (a55dd71d5 2022-09-19)
```

**Additional context**

```
❯ wezterm --version
wezterm 20220909-090307-9bcc4e0b
```

```
GNOME Terminal: Version 3.44.1 for GNOME 42
```

**Comment by tomasol** [comment]
Try running `tput rmkx` before `gitui` . I found out `gitui` does not handle the arrow keys when in keyboard-interactive or normal mode (`tput smkx`) . Other applications (`mc`, helix editor) handle arrow keys fine in both application and normal modes.
[More context](https://github.com/fish-shell/fish-shell/issues/2139#issuecomment-388706768)

**Comment by azzamsa** [comment]
I  migrated to GNOME terminal after this incident. But today when I try to use the same version of wezterm and gitui, the arrow works. The only changes is now I am in Fedora 37 instead of 36. 

Thanks for the input. I will try it the the issue pops up again.
