### ISSUE TITLE
support gitmoji

### ISSUE THREAD

**Issue by Saafo** [extrawurst/gitui#1398]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Support display emoji in commit messages related to [gitmoji](https://github.com/carloscuesta/gitmoji)

**Describe alternatives you've considered**
Comparision products like VSCode, GitHub and GitLab all support gitmoji

**Additional context**
None.

**Comment by hemedani** [comment]
it's the same here :
https://github.com/extrawurst/gitui/issues/1192#issuecomment-1295834285

**Comment by extrawurst** [comment]
@hemedani 
#1192 is about autocomplete typing emojis (not even specifying whether unicode-emojis or gitmoji). this one is about graphical visualisation of gitmojis as unicode-emojis
