### ISSUE TITLE
fix commit hooks on windows (+tests)

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#14]
calling the hooks is currently only implemented of *nix systems.
how does this even work on windows? does git call *.bat files? help of someone on a windows machine would be required here.

**Comment by MCord** [comment]
I can take this if it's ok with you.

**Comment by extrawurst** [comment]
Absolutely! Are you running on windows? I have a hard time even testing this being on a Mac. Do you know how hooks work on windows? are they run expected as *.bat files?

**Comment by MCord** [comment]
yes I use a windows 10 as my main machine. for hooks on windows you have to specify an alternative interpreter. the default installation of git provides a bash interpreter but even PowerShell should work.

**Comment by extrawurst** [comment]
Ok I assume its regular bash scripts aswell, now that I look at it. 

@MCord could you add a unitest for the hooks, I realize they are missing

**Comment by extrawurst** [comment]
I tried to reach out to you twitter. would you be up for syncing on discord?

**Comment by MCord** [comment]
That would be great ! let me know when you are available to chat!

**Comment by MCord** [comment]
my handle is mcord on discord by the way.
