### ISSUE TITLE
add a way to remove from ignore file without opening .gitignore file in editor

### ISSUE THREAD

**Issue by yilmazdurmaz** [extrawurst/gitui#1402]
**Is your feature request related to a problem? Please describe.**
I am new to gitui and wanted to give it a try. it is pretty nice but "ignoring" a file by accident has become a pain and seems to be so until you add this feature.

while trying it in a fresh folder with a single file in it, accidentally pressed `i` and new `.gitignore` file is created with that file's name in it. none of the actions has anything to revert this incident and editing needs an editor (namely nano for default settings which is not installed).

**Describe the solution you'd like**
I can think of 2 possible solutions:
- add an "undo last operation" feature. this sound more plausible than the next one
- add a line editor, or something like that, to remove a line instead of using a full editor.

**Describe alternatives you've considered**
an alternative would be trying to play with settings which would take more learning/remembering

**Additional context**
...

**Comment by extrawurst** [comment]
maybe I am missing something with your use case, every time I add something to the gitignore by accident this appears as a diff in the status that I can easily revert before committing?

**Comment by extrawurst** [comment]
you can reset/revert individual hunks in a diff, no need to reset whole folders or files "accidentally" and forever, just the ignore that you want to revert.

see the steps in this recording:
![Screenflick Movie 7](https://user-images.githubusercontent.com/776816/220369983-49323a0a-621d-4b74-993d-efba8a434866.gif)

**Comment by yilmazdurmaz** [comment]
Hi @extrawurst , you closed the request but my intention for the request still holds open: "add a way to remove from ignore file"

Resetting hunk is valid only when you want to discard all changes from last commit. But it does not offer a solution for "accidental" addition to the ignore file.

Let me extend with another example situation: you do not have a wildcard option to ignore files, so you are selecting them by hand. there are many file you are trying to ignore and you want to remove few among other. the ones you want to remove might just slipped by, or you decided not to ignore, or even some old ones you want to un-ignore.

Resetting the changes/hunks is not suitable for this purpose, and opening an editor means leaving the gitui interface and is annoying.

meanwhile, I see a "reset lines [d]" and "stage lines [s]" commands that seemingly not doing anything while unstaged, and "unstages line [s]" for staged file that is close to what I describe, but moving between staged and unstaged is confusing.

as this is a feature request post, its implementation may even take 1-2 years. or you may mark it with some "not implementing" message. I hope you reconsider your decision to close.

PS: what are these "reset lines [d]" and "stage lines [s]" commands and why I could not make them work? bug maybe?

**Comment by extrawurst** [comment]
> meanwhile, I see a "reset lines [d]" and "stage lines [s]" commands that seemingly not doing anything while unstaged, and "unstages line [s]" for staged file that is close to what I describe, but moving between staged and unstaged is confusing.

you are right, the granular lines based ops do not support reverting lines upstages. see #582 - this makes this issue a duplicate

**Comment by extrawurst** [comment]
conceptually gitui is not intended to be a substitute for your editor, that's why couples edits to the commit message send you to an editor. for any complex ignore file changes I apply the same. but yea #582 will solve your particular use case

**Comment by yilmazdurmaz** [comment]
Alright, for the moment I will try this partial staging. 

from your linked issue, I followed jumped to an older one. https://github.com/extrawurst/gitui/issues/59#issuecomment-793188504

that comment of yours shows them working, and later you merged a commit, but "reset/stage lines" do not work for me on v0.22.1 for windows. shall I open a new bug report,

**Comment by extrawurst** [comment]
> that comment of yours shows them working, and later you merged a commit, but "reset/stage lines" do not work for me on v0.22.1 for windows. shall I open a new bug report,

for sure, with a repro, that would be ideal

**Comment by yilmazdurmaz** [comment]
I was thinkering about how to make a video to show you the reset/stage lines, and have found an interesting solution to the main problem of this discussion. 
- stage gitignore file (move under staged changes)
- browse to the file under staged changes
- switch to file, move to line and press "s" to unstage it
- browse to the file under unstaged changes
- switch to file, move to line and press "d" to remove it from file

PS: "d" key works this way but "s" is still doing nothing while file is under unstaged changes.

[video-convert-1677001847037.webm](https://user-images.githubusercontent.com/1812105/220422016-80990292-6e73-4354-842b-fda6e4e3716a.webm)

**Comment by yilmazdurmaz** [comment]
> PS: "d" key works this way but "s" is still doing nothing while file is under unstaged changes.

scratch that. this "stage lines [s]" also work under the conditions that:
- file is in "staged changes" area
- and at least 1 line is unstaged with "unstage lines [s]"
- then file is viewed under "unstaged changes" area

are the one in my post above and this sequence here something you had in mind when you imlemented these functions?
