### ISSUE TITLE
Open commit editor doesn't show changes.

### ISSUE THREAD

**Issue by vunhatchuong123** [extrawurst/gitui#1420]
**Describe the bug**

When you write `git commit` it opens an editor with the list of changes to be commit, but GitUI doesn't show it.

**To Reproduce**
1. Go to 'Staged Changes'
2. Click on 'Commit'
3. Click on 'Open Editor'

**Expected behavior**

Show list of changes to commit.

![image](https://user-images.githubusercontent.com/20581504/200155176-6b3746c8-6558-4c5c-8a25-0b35e7186393.png)

**Actual behavior**

Doesn't show list of changes.

![image](https://user-images.githubusercontent.com/20581504/200155239-96551f89-7574-465c-8d61-3d45fe177035.png)

**Context (please complete the following information):**
 - Pop!_OS + Version: [e.g. `macOS 10.15.5`]
 - GitUI Version 0.21

**Comment by extrawurst** [comment]
fixed via 9b46bb6
