### ISSUE TITLE
Can't push changes git   (error:error authenticating: no auth sock variable; class=Ssh (23))

### ISSUE THREAD

**Issue by dgel** [extrawurst/gitui#1421]
I'm using ssh to push to a gitlabs instance, which works fine with the git cli, but produces an error in gitui

**To Reproduce**

 - open gitui
 - create a commit
 - press 'p' to commit
 - observe message:
 
    push failed:
    git error:error authenticating: no auth sock variable; class=Ssh (23)

**Expected behavior**

commit gets pushed to remote, just as works with git push

**Context:**
 - CentOS Linux 7 (Core)
 - gitui 0.21.0
 - Rust 1.64.0

**Additional context**

I don't have a ~/.ssh/config file, using default key ~/.ssh/id_rsa, 

I've read other tickets talking about similar issues, recommending ssh-agent, but 1. running ssh-agent doesn't seem to work and I don't have permissions to install more packages and 2. ideally if the config automatically works in git, it ought to automatically work in gitui too

**Comment by extrawurst** [comment]
unfortunately upstream libgit2 does not honour `~/.ssh/config` see https://github.com/libgit2/libgit2/issues/5640
