### ISSUE TITLE
Interactive rebase made easy

### ISSUE THREAD

**Issue by BinaryDennis** [extrawurst/gitui#1425]
## Problem
Im always frustrated when I have to quit `gitui` and fall back to command line git to do interactive rebase, ie `git rebase -i <hash>`

## Solution
It would be very nice to have a section/option/window in `gitui` to do interactive rebasing in an easy way. 

Example:
1. Move a commit up/down in the list by arrow keys + some modifier
2. Keyboard shortcuts for altering a commit in the list, eg pick/drop/squash/reword 

## Inspiration
See how `lazygit` is doing it, perhaps something similar would be possible to make in `gitui` but keeping the UI/UX clean and simple? (IMHO `lazygit` is too messy and I the list of keyboard shortcuts is hard to read/use/remember)

Attaching a few screenshots from `lazygit`'s interactive rebasing:

<img width="238" alt="Screenshot 2022-11-08 at 10 04 33" src="https://user-images.githubusercontent.com/814063/200523191-39fed1af-ab2d-42ef-9157-4c6e118a4e7d.png">
<img width="479" alt="Screenshot 2022-11-08 at 10 04 21" src="https://user-images.githubusercontent.com/814063/200523199-58ae2d68-1bc6-4d3d-9d93-e9915e09e6ff.png">

**Comment by extrawurst** [comment]
duplicate of #32 ?

**Comment by BinaryDennis** [comment]
> duplicate of #32 ?

yup it seems so, sorry I didn't see that before posting my FR.

Go ahead and close this one if you want to.
