### ISSUE TITLE
No message commit

### ISSUE THREAD

**Issue by Folded-Code** [extrawurst/gitui#1426]
**Is your feature request related to a problem? Please describe.**
I want to commit with no message (I know its not best practice. This is for personal projects)

**Describe the solution you'd like**
When on the commit message input allow the user to commit even if the input is empty.

**Describe alternatives you've considered**
Could require ctrl/cmd enter to commit with no message.

**Additional context**
It would also be good to show "No commit message" like github in the logs as a no message commit is currently blank.

**Comment by extrawurst** [comment]
this is really not best practice and not something I would want to pollute the command bar with by providing an extra command. if you wanna do this commit with `"no commit message"` once and use the new `commit-message-history` feature in the next release (currently only on master) that allows you to reuse previous commit messages

**Comment by Folded-Code** [comment]
Ok thank you. I still think it would be good to show the text "No commit message" maybe with a highlight like GitHub in the logs.
<img width="371" alt="image" src="https://user-images.githubusercontent.com/34174315/201172575-c19f8394-b642-4d6a-bffe-64460ae4394e.png">

For other people who don't want to have a commit message, I've noticed if you commit one space it shows no message on GitHub.
