### ISSUE TITLE
Too many open files in system (os error 23)

### ISSUE THREAD

**Issue by yurivict** [extrawurst/gitui#1439]
**Describe the bug**
Application crashes while browsing "files to stash" and the log end like this:
```
18:21:31 [TRACE] (1) asyncgit::tags: [asyncgit/src/tags.rs:67] request
18:21:31 [TRACE] (1) gitui::app: [src/app.rs:380] event: Input(Key(KeyEvent { code: Tab, modifiers: NONE, kind: Press, state: NONE }))
18:21:32 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:32 [TRACE] (1) gitui::app: [src/app.rs:380] event: Input(Key(KeyEvent { code: Tab, modifiers: NONE, kind: Press, state: NONE }))
18:21:32 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:102] request: [hash: 411913559819473704] (type: Both)
18:21:32 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:32 [TRACE] (1) gitui::app: [src/app.rs:380] event: Input(Key(KeyEvent { code: Up, modifiers: NONE, kind: Press, state: NONE }))
18:21:32 [TRACE] (1) gitui::app: [src/app.rs:380] event: Input(Key(KeyEvent { code: Down, modifiers: NONE, kind: Press, state: NONE }))
18:21:33 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:34 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:35 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:36 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:37 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:160] status fetched: 411913559819473704 (type: Both)
18:21:37 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Status)
18:21:37 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:38 [TRACE] (1) gitui::app: [src/app.rs:380] event: Input(Key(KeyEvent { code: Down, modifiers: NONE, kind: Press, state: NONE }))
18:21:38 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:39 [TRACE] (1) gitui::app: [src/app.rs:494] update_async: Git(Log)
18:21:40 [ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(Watch error: Error { kind: Generic("Too many open files in system (os error 23) about [\"/disk-samsung/freebsd-ports/games/puckman/pkg-descr\"]"), paths: [] }), location: Location { file: "src/watcher.rs", line: 105, col: 14 }, can_unwind: true }
trace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: thread_start
             at /disk-samsung/freebsd-src/lib/libthr/thread/thr_create.c:292:16

18:21:40 [ERROR] notify receive error: receiving on a closed channel
```

**Context (please complete the following information):**
 - OS/Distro + Version: FreeBSD 13.1 STABLE
 - GitUI Version v0.22.0-9-gbc15b5d
 - Rust version: 1.64.0

**Comment by extrawurst** [comment]
1) please check out if the crash happens no matter what tab you go just after a few seconds
2) Can you please try current master (`make debug`) and run with `-polling` to not use filesystem watcher

provide a full log please

**Comment by yurivict** [comment]
> please check out if the crash happens no matter what tab you go just after a few seconds

Yes it does.

[gitui.log](https://github.com/extrawurst/gitui/files/10060187/gitui.log)

**Comment by yurivict** [comment]
With ```--polling``` it doesn't fail.

You should handle the ```Too many open files in system (os error 23)``` error internally and correct for it somehow.

**Comment by 0xpr03** [comment]
Is this with the kqueue or the fsevent backend ?

**Comment by extrawurst** [comment]
@yurivict thanks for the log. it shows that your system is trying to use the `Kqueue` watcher. (@0xpr03 thanks for taking this to the source over at notify)

**Comment by yurivict** [comment]
Is there a workaround?
This bug makes gitui pretty unusable on FreeBSD.

**Comment by 0xpr03** [comment]
I'm not involved in gitui, but in file watching:

Either you use --polling, or you increase your OS limits.

According this [this](https://unix.stackexchange.com/questions/66863/freebsd-too-many-open-files-but-should-be-able-to-open-another-160-000-files) you can increase your file handle limits.

Basically gitui watches for file changes to update its UI, but to do that, it'll have to watch each file in your directory by opening up a file handle. Because that is how file watching works in BSD (and linux): You want to watch a file for changes, you use a file handle. And if you have too many or your limit is too low, you'll hit this error.

**Comment by yurivict** [comment]
Why do you need to have so many files open?
Do you open every file in the repository?

**Comment by 0xpr03** [comment]
Technically they're not open. But on BSD every file you watch for changes is using a file handle, in the same sense opening a file would.

Probably watching for changes in the code, to update the UI (stash,changes,..)

**Comment by yurivict** [comment]
> Probably watching for changes in the code, to update the UI (stash,changes,..)

But the UI can't see that many files at the same time.

**Comment by 0xpr03** [comment]
If I want to display which files are changed, and I want to know when they are changed, I've to subscribe to any changes in the directory of your repository. And that means all files. That means amount of files of file handles.

**Comment by yurivict** [comment]
What is done in Linux differently for this?

**Comment by 0xpr03** [comment]
Nothing. It's different in windows. Windows won't count one file handle per watched file if you watch a whole folder.

**Comment by extrawurst** [comment]
all good I just hope this can be addressed upstream: https://github.com/notify-rs/notify/issues/455

**Comment by 0xpr03** [comment]
If you mean issuing an error of MaxFilesWatch, then yes. But as far as I can see we will have to consume file handles, like with inotify on linux. So we can't prevent the issue itself.
