### ISSUE TITLE
Make scrolling great again

### ISSUE THREAD

**Issue by x80486** [extrawurst/gitui#144]
## Describe the Bug

Scrolling on `Unstaged Changes` (or `Staged`) sections is a little bit weird. For instance, with a long list of files, when you reach the bottom and try to go back the highlighted line doesn't go to the top to start scrolling again, but it goes with the list.

> Notice the `Diff` section behaves as one would expect.

## To Reproduce
1. Have a Git repo with a good amount of unstaged or staged files that will allow you to scroll
2. Press the <kbd>Down</kbd> arrow until the bottom is reached
2. Press the <kbd>Up</kbd> (several times)

Notice how the list moves with the press of every <kbd>Up</kbd> arrow along with the highlighted line, instead of just the highlighted line.

## Expected Behavior

The list should stay in place until the top is reached, then it should move accordingly.

> I filed this _as a bug_ because the `Diff` section behaves correctly (for what I expect). This could have been an enhancement, or probably that's the intended behavior — in that case I would expect you to reconsider and possibly make it work like the `Diff` section!

## Desktop
 - OS: Arch Linux `Linux uplink 5.4.46-1-lts #1 SMP Wed, 10 Jun 2020 20:36:34 +0000 x86_64 GNU/Linux`
 - Browser: N/A (why this matters anyway?)
 - Version: `gitui 0.7.0`

**Comment by extrawurst** [comment]
@x80486 you are absolutely right, this can be improved!

followup to #52

**Comment by extrawurst** [comment]
@tisorlawan thanks again, this is released in `0.8` now: https://github.com/extrawurst/gitui/releases/tag/v0.8.0
