### ISSUE TITLE
When the editor is closed the screen doesn't return to the same state: the menu at the bottom isn't shown

### ISSUE THREAD

**Issue by yurivict** [extrawurst/gitui#1443]
The menu only appears when Down/Up is pressed.

**Comment by extrawurst** [comment]
Cannot reproduce

**Comment by yurivict** [comment]
https://user-images.githubusercontent.com/271906/203154599-9a447d58-7070-4ad4-9328-8ae715008c2a.mp4

**Comment by extrawurst** [comment]
Can you please provide the output for `gitui —bugreport` and more infos about what terminal you try this in?

**Comment by yurivict** [comment]
```
$ gitui --bugreport report.txt
#### Software version

gitui 0.22.0 (11-eol-40728-g087257190722-modified)

#### Operating system

freebsd 13.1-STABLE

#### Compile time information

- Profile: release
- Target triple: x86_64-unknown-freebsd
- Family: unix
- OS: freebsd
- Architecture: x86_64
- Pointer width: 64
- Endian: little
- CPU features: fxsr,sse,sse2
- Host: x86_64-unknown-freebsd

#### Environment variables

```bash
SHELL=/usr/local/bin/bash
EDITOR=vim
GIT_EDITOR=<not set>
VISUAL=<not set>
```

```



XFCE4 terminal
FreeBSD 13.1

**Comment by extrawurst** [comment]
not sure how to tackle this as I cannot reproduce this problem

**Comment by yurivict** [comment]
This is maybe an XFCE4 terminal problem. Did you try on XFCE4?

**Comment by hermitmaster** [comment]
Seeing the same issue here. Using Alacritty terminal and tmux.

#### Software version

gitui 0.22.1

#### Operating system

macOS 12.6.1 (Darwin 21.6.0)

#### Compile time information

- Profile: release
- Target triple: aarch64-apple-darwin
- Family: unix
- OS: macos
- Architecture: aarch64
- Pointer width: 64
- Endian: little
- CPU features: aes,crc,dit,dotprod,dpb,dpb2,fcma,fhm,flagm,fp16,frintts,jsconv,lor,lse,neon,paca,pacg,pan,pmuv3,ras,rcpc,rcpc2,rdm,sb,sha2,sha3,ssbs,vh
- Host: aarch64-apple-darwin

#### Environment variables

```bash
SHELL=/bin/zsh
EDITOR=nvim
GIT_EDITOR=<not set>
VISUAL=<not set>
```
