### ISSUE TITLE
remove polling watcher

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#1444]
notify based PollWatcher does a ton of caching and can be expensive in giant repos. the new `--polling` arg should sidestep using notify entirely and go back to a regular status polling

**Comment by cruessler** [comment]
@extrawurst Can you provide a bit more context on the changes needed? Is this related to the lines of code below? I’m not sure I completely understand this issue yet.

https://github.com/extrawurst/gitui/blob/3e0ec29d0da842ddd0b9cff15355f01206b7b814/src/watcher.rs#L84-L97

**Comment by extrawurst** [comment]
More and more people struggle with this new `notify` based solution. it seems brittle and not well working on some platforms. I am currently leaning towards reverting back to the old approach (poll every few seconds) and provide a new program arg `--watcher` that will use the current default which is using the `notify` crate.

using the PollWatcher as the alternative is less performant because it does cache file hashes which in giant repos can still be unscalable. before I added `notify` (#1) we basically just triggered a Status refresh after a certain sleep - I think it was 2 seconds. to make sure we pick up when new diffs or so arrived.

hope that makes the idea here more clear
