### ISSUE TITLE
Navigation improvement

### ISSUE THREAD

**Issue by pomozoff** [extrawurst/gitui#1447]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when trying to navigate through a plenty of remote branches by up and down arrows.

**Describe the solution you'd like**
1. Add PgUp and PgDown shortcuts.
2. Add a filter text field. I believe it would be useful not only in the "branch" window.

**Describe alternatives you've considered**
Nothing more.

**Additional context**
Nothing to add.

**Comment by extrawurst** [comment]
1. totally agreed. 
2. is a dup of #1350

lets make this issue about adding pageup/down support in the branch list view

**Comment by ObiWanRohan** [comment]
Looks like 1 is already present. The `PgUp` and `PgDn` keys are working in the branch list view.

**Comment by pomozoff** [comment]
Good news!
How do they work on a MacBook?

**Comment by ObiWanRohan** [comment]
I am on Linux with a full keyboard so I directly have the keys.
Can you try with `fn + Up Arrow` and `fn + Down Arrow`?

Here's where the scroll is implemented.
https://github.com/extrawurst/gitui/blob/b59526c86c3faaac29716fe472f322c134a52305/src/components/branchlist.rs#L231-L246

**Comment by pomozoff** [comment]
Yes, that works.

**Comment by extrawurst** [comment]
so this can be closed then?
