### ISSUE TITLE
Additional help line for amend commit is missing

### ISSUE THREAD

**Issue by strandloper** [extrawurst/gitui#1448]
**Describe the bug**
Issue #778 indicated that an additional line should be present for ammend commit in the help. However this does not appear in v0.22.1.

**To Reproduce**
1. Press h to open help
2. Scroll down to the Commit section
4. No indication is given that ^a for Amend must be used in the commit popup.

**Expected behavior**
Expect to see
![image](https://user-images.githubusercontent.com/668433/203552206-43455dd1-32f7-47e9-8c10-c97ab686f52b.png)

**Screenshots**
Actually see
![image](https://user-images.githubusercontent.com/668433/203552315-c4adecd2-9463-4ace-a211-8d0832773f7a.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 11 22H2
 - GitUI Version 0.22.1
 - Rust version: N/A running from gitui.exe

**Comment by extrawurst** [comment]
thanks for pointing this out. made the help more clear via #1449 
<img width="750" alt="Screenshot 2022-11-23 at 14 57 32" src="https://user-images.githubusercontent.com/776816/203565666-1768c14e-348c-4517-9b96-8b8ebc60bba2.png">
