### ISSUE TITLE
error[E0723]: heap allocations are not allowed in const fn

### ISSUE THREAD

**Issue by RupankarGhosh** [extrawurst/gitui#145]
I was trying to build `gitui` as documented: using  ```cargo install gitui ```
But this error occurs. I'm using android termux with current _rustc_ .

**Comment by extrawurst** [comment]
Sounds like: https://github.com/extrawurst/gitui/pull/117#issuecomment-643683845

**Comment by extrawurst** [comment]
We should add the min version like this: https://github.com/rust-lang/rfcs/pull/2495

**Comment by extrawurst** [comment]
ok damn, the `min supported rust version` is not there yet: https://github.com/rust-lang/rust/issues/65262

anyhow, the error you see is when you are not building with rust 1.44 or higher. let me know if the problem still persists
