### ISSUE TITLE
focus_right key binding doesn't work to inspect stash (right arrow still used)

### ISSUE THREAD

**Issue by dblume** [extrawurst/gitui#1454]
**Describe the bug**

If using the vim key bindings mentioned at [KEY_CONFIG.md](https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md), the "l" key will focus right and move right as expected in most tabs but "Stashes". Tip at the bottom will say, "Inspect \[l\]" but you have to press the right arrow to inspect.

**To Reproduce**
1. Use the vim key bindings mentioned at [KEY_CONFIG.md](https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md). (Only focus_right matters for this bug.)
2. Stash a change. (So you have something to see at step 4.)
3. Run gitui, notice hjkl navigation works as expected.
4. Go to Stashes Tab. Try to inspect the stash with the "l" key as described in the tip at the bottom of the screen. It doesn't work. But pressing the right-arrow key works, as if you hadn't installed any key bindings.

**Expected behavior**
Pressing the "l" key when focus is on a stash "inspects" the stash. (As the tip at the bottom suggests.)

**Context (please complete the following information):**
 - Windows WSL2 Ubuntu 20.04.1 LTS (and Ubuntu 20.04.5 LTS (not WSL))
 - GitUI Version 0.22.1

**Comment by extrawurst** [comment]
inspecting is actually a separate item in the bindings, please see `stash_open` at https://github.com/extrawurst/gitui/blob/master/vim_style_key_config.ron#L46

the bug here is that the label shown on the bottom does not use the right key binding 🤦‍♂️
