### ISSUE TITLE
key bindings should be additive, not exclusive

### ISSUE THREAD

**Issue by dblume** [extrawurst/gitui#1455]
**Is your feature request related to a problem? Please describe.**

Adding the vim key bindings shouldn't unmap the arrow keys. Many popular apps (vim, GMail, Google Drive, VisiData) allow for both. (If this feature is implemented, then vim key bindings could be baked in, too, delighting two distinct sets of users.)

GitUI already does this (on some tabs) for 'q' and 'ctrl+c' for clean exit, even though the tip at the bottom only shows "Quit \[^c\]". So this new feature is consistent with GitUI's UX.

**Describe the solution you'd like**

After adding key bindings, the new key bindings work, and any other pre-existing key bindings that could still work do. If users want to unmap a key, it could be an explicit unmap command.

**Comment by extrawurst** [comment]
this opens another can of worms. what do we do with duplicate assigned keys?

**Comment by dblume** [comment]
Do you mean different keys, same assignment? GitUI already supports 'q' and '^c' for exit. I've mentioned that vim, GMail, Google Drive, VisiData all support both hjkl and the arrow keys for navigation. So either mode of navigation would continue to work.

Or do you mean same key different assignments, like how 'l' (or right arrow) can mean focus_right, move_right, and stash_open? But you've already solved that one.

**Comment by dblume** [comment]
Maybe related to your "duplicate assigned keys" question, I notice the vim key bindings include

`status_reset_item: Some(( code: Char('U'), modifiers: ( bits: 1,),)),`

Which I'm really happy about, because it hides "Undo Commit \[⇧U\]" in the Status tab when navigating changes. Because I usually would want to reset a file than undo a commit. So this instance is actually a desired improvement. (If I wanted to retain "undo_commit" I could remap it, but I don't. I'm happy with the vim mapping provided here with the duplicate.)
![vim_mapping](https://user-images.githubusercontent.com/885061/204408223-2a1600fa-3f71-48da-a559-c0b51e33731f.png)

**Comment by olivertzeng** [comment]
@dblume How about `hjkl` keys? It must be great if @extrawurst adds these keybindings inside too!

**Comment by extrawurst** [comment]
this is not actionable right now. if we want to support this we need a proposal
