### ISSUE TITLE
GitUI build error, invalid path 'target/debug/GitUI -l'

### ISSUE THREAD

**Issue by saber716rus** [extrawurst/gitui#1456]
**Describe the bug**
I am doing an offline build in a closed build system, but the problem is in the source code itself.

**To Reproduce**
1. Executing the make command
2. I see error: "Error: invalid path
please run gitui inside of a non-bare git repository
make: *** [Makefile:9: profile] Error 1"

**Expected behavior**
The package was built successfully.

**Screenshots**
![Screenshot_2022-11-28-02-02-03-576_com.termux.jpg](https://user-images.githubusercontent.com/22714555/204164621-997938df-e2b2-4837-9d1c-f0595be6e29d.jpg)![Uploading v{aa2d98f} (0c0f6098-ee42-44e6-acee-919529563251 id=0x7f0a0193 tag=CreateIssueFragment) …]()

**Context (please complete the following information):**
 - ROSA Fresh rootfs 12.3
 - GitUI Version 0.22.1
 - Rust Version rust-1.63.0-1.aarch64

**Additional context**
Finished dev [unoptimized + debuginfo] target(s) in 8m 58s
     Running `target/debug/gitui -l`
Error: invalid path
please run gitui inside of a non-bare git repository
make: *** [Makefile:9: profile] Error 1

I enter the make command without any options.

**Comment by saber716rus** [comment]
![Screenshot_2022-11-28-02-02-10-551_com.termux.jpg](https://user-images.githubusercontent.com/22714555/204164984-e08877ac-4baa-49e1-8df4-d73f21c17aaa.jpg)

**Comment by saber716rus** [comment]
Your makefile incorrectly creates the gitui package. I created a package for Rosa Linux, so I became the maintainer of your package.

https://abf.io/saber716rus/gitui

**Comment by extrawurst** [comment]
if you want to fix anything please open a PR

**Comment by saber716rus** [comment]
> if you want to fix anything please open a PR

If I find the reason, I will open a PR.
