### ISSUE TITLE
Cannot open external/internal editor

### ISSUE THREAD

**Issue by PatWie** [extrawurst/gitui#1461]
**Describe the bug**
Cannot launch any editor to edit a previous commit message (even the last one).

**To Reproduce**
```
cd /tmp
mkdir test && cd  test
git init && touch "a"
git add a &&  git commit -m "override me"
```

Open gitui and click `e` when the commit message is highlighted.

**Expected behavior**
Opening the same editor as when editing a file from the `Files` tab or clicking `ctrl+e` when creating the commit message in the first place.

**Screenshots**
![image](https://user-images.githubusercontent.com/6756603/205611849-897a7088-b8c3-4064-87ac-104343cf3330.png)

**Context (please complete the following information):**
 - OS/Distro + Version:  18.04.1-Ubuntu
 - GitUI Version: `gitui 0.22.1` from cargo install
 - Rust version: `rustc 1.62.0 (a8314ef7d 2022-06-27)`

**Additional context**
The menu item on the bottom of the screenshot mit be missleading. Does this function even exists? If not, then the `edit` menu item should be removed. The logs indicate a keypress has been detected
```
10:14:13 [TRACE] (1) gitui::app: [~/.cargo/registry/src/github.com-1ecc6299db9ec823/gitui-0.22.1/src/app.rs:382] event: Input(Key(KeyEvent { code: Char('e'), modifiers: NONE, kind: Press, state: NONE }
))
```

**Comment by extrawurst** [comment]
ha good point, this UX sucks. the edit is actually about the file selected in the tree below. let me fix that. editing a previous commit messages is a feature not supported yet
