### ISSUE TITLE
can't show tab

### ISSUE THREAD

**Issue by lyj0309** [extrawurst/gitui#1465]
**Describe the bug**

**To Reproduce**
termius solarized dark

**Expected behavior**
show tab like 1, 2, 3
**Screenshots**
![image](https://user-images.githubusercontent.com/50474995/206382321-995eaaf2-7f5e-45c4-b843-a864ffca3449.png)

**Context (please complete the following information):**
 - OS/Distro + Version: ubuntu22
 - GitUI Version 0.22.1

**Comment by non-descriptive** [comment]
I had similar bug with solarized theme in Alacritty and it turns out that my color setup used `base03` (`#002b36`) as one of gray colors. Check out your terminal color setup. Probably `dark_gray` should be set to `base0` (`#839496`) instead.
