### ISSUE TITLE
Issues encrypting files with git-crypt.

### ISSUE THREAD

**Issue by soundstep** [extrawurst/gitui#1468]
**Describe the bug**

It seems that committing and pushing with gitui interferes with [git-crypt](https://github.com/AGWA/git-crypt).

Git staging, committing and pushing using only with git command line works.

Not sure what's happening, something to investigate?

**To Reproduce**
1. Create a repo
2. Initialize git-crypt
3. Add a secret
4. Commit and Push using gitui

**Expected behavior**

Secrets should be encrypted, as they are while using the git command line, but they end up being pushed to the remote in clear.

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS 12.1 (21C52)`
 - GitUI Version: `gitui 0.22.1`
 - Rust version: installed with brew

**Comment by extrawurst** [comment]
seems like another thing upstream libgit2 is not supporting. git-crypt is based on filters just like #1089
