### ISSUE TITLE
Fetch command in status tab for just the current branches remote

### ISSUE THREAD

**Issue by alensiljak** [extrawurst/gitui#1471]
**Is your feature request related to a problem? Please describe.**
I am looking for a quick and convenient way to see the incoming / outgoing commits in a repo. Related to #1413. Since F is mapped to Pull, I am wondering if there is a Fetch command. Perhaps it would be quicker to fetch changes and avoid potential merge issues. 

**Describe the solution you'd like**
A fetch command in addition to pull. 

**Describe alternatives you've considered**
Hm?

**Comment by alensiljak** [comment]
One of the reasons I missed this functionality is that the Branches don't work on the phone and Fetch seems to be available in the Branches pop-up. Looking forward to that fix!

**Comment by alensiljak** [comment]
> just to clarify: you would want the same `fetch` that currently is available in the branches window?

At the moment I can't answer that completely as I did not previously (due to the Branches bug on the phone) realize that functionality was there. I just had a brief look on desktop and the fetch of a branch seems to show the incoming commits on remote.

My general idea is to be able to manually refresh the changes count (up/down) from the Status page. Preferably this would be automatic but an explicit manual trigger (i.e. via `F` key) would also be fine. 

I often get conflicts or unnecessary merges in my notes repository and seeing incoming commits would help. Thanks!

**Comment by extrawurst** [comment]
> (due to the Branches bug on the phone)
that was #1470 ? feel free to test with a build from master

**Comment by alensiljak** [comment]
> > (due to the Branches bug on the phone)
> 
> that was #1470 ? feel free to test with a build from master

Correct. Alright, let me try `cargo install` directly from the repo...

**Comment by alensiljak** [comment]
Unfortunately, I don't know how to overcome the last hurdle. Linking with cc fails on the last package (gitui) due to an undefined symbol `__aarch64_ldadd4_acq_rel`. I'll try some more but might ultimately need to wait for the binary release for aarch64-linux-android (or a Termux package).

I'm a bit confused about how the current fetch works. I don't see an indication of the number of changes in the branches window but only when back to the Status screen. Which is kinda ok, I guess.

To add to my previous comment, I think that fetching the currently linked remote branch would be ok if done directly from the Status screen.

**Comment by alensiljak** [comment]
Just tried on desktop - the workflow seems to be:
- open Branches pop-up
- switch to remote tab
- fetch changes
- close the pop-up
- observe the number of changes 
 
The pop-up covers the change indicator below and needs to be closed in order to see the result of the fetch operation.
![image](https://user-images.githubusercontent.com/462445/208863839-10618cbd-dde3-4732-87e8-93befcd3a237.png)

Also, it is not clear what the fetch will do - does it fetch all branches or just the current one.

Therefore, I would suggest that there is a fetch operation added to the Status (main) window, which fetches the currently-linked branch, if available. I think all the logic is already in place so it is a matter of adding the command to the UI.

**Comment by extrawurst** [comment]
`fetch` in the branch popup fetches everything. a dedicated `fetch` in the status view to just fetch the current remote branch makes sense 👍
