### ISSUE TITLE
"Edit [e]" appears twice in the status line

### ISSUE THREAD

**Issue by exoton** [extrawurst/gitui#1489]
**Describe the bug**
**Edit [e]** appears twice in the status line

**Expected behavior**
Once is enough.

**Screenshot**
![Screenshot from 2022-12-28 02-48-04](https://user-images.githubusercontent.com/62148/209779213-8d4ef809-d469-4a7b-9c0c-5a888d68e2b2.png)

**Context:**
 - archlinux
 - gitui 0.22.1
 - rustc 1.66.0 (69f9c33d7 2022-12-12) (Arch Linux rust 1:1.66.0-1)

**Comment by extrawurst** [comment]
closed via e5c62d0
