### ISSUE TITLE
Change editor

### ISSUE THREAD

**Issue by Talleyrand-34** [extrawurst/gitui#1493]
I want to cheange the text editor.

A option to change the editor, on one hand it could be a conf in .config/gitui/config.toml or add a (hidden) settings tab to modify what it is neccesary for the user.

What is your opinion about this? Do i  miss something?

**Comment by extrawurst** [comment]
you can set these env: `GIT_EDITOR``, `VISUAL`, `EDITOR`
let me know if that works for you

**Comment by justrico** [comment]
> 

Great! Set `export EDITOR=nvim` works for me.

**Comment by creeloper27** [comment]
> you can set these env: `GIT_EDITOR`, `VISUAL`, `EDITOR` let me know if that works for you

For new linux users and especially the not-too-tecnical-ones I suggest adding an improved version of this comment of yours to the README of the project,
maybe even with a few examples like:
#### (this is just a draft and can surely be improved upon)
```bash
# to change the default editor gitui will use in the current shell you can set the envirment variable EDITOR, here are some examples:
export EDITOR=nano  # change the default editor to nano
export EDITOR=vi  # change the default editor to vi
export EDITOR=vim  # change the default editor to vim
export EDITOR=nvim  # change the default editor to nvim

# to make the change permanent you can add the line to your "~/.bashrc", "~/.zshrc" or other configuration file depending on the shell that you are using, you can see what shell you are currently using by running:
echo $SHELL
```

**Comment by overtube** [comment]
failed to launch editor:                                  ┃                                             │
│                                             ┃"vi": No such file or directory (os error 2)




mine .bashrc is



#
# ~/.bashrc
#

export EDITOR=nano

### Add rbenv

export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

### Add depot_toolsforchromiumdev

export PATH="$PATH:/path/to/depot_tools"

### Add NVM

[ -z "$NVM_DIR" ] && export NVM_DIR="$HOME/.nvm"
source /usr/share/nvm/nvm.sh
source /usr/share/nvm/bash_completion
source /usr/share/nvm/install-nvm-exec

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# alias ls='ls --color=auto'
# PS1='[\u@\h \W]\$ '
source /usr/share/nvm/init-nvm.sh
export LD_LIBRARY_PATH=/usr/local/lib

# Created by `pipx` on 2023-05-04 14:36:15
export PATH="$PATH:/home/ui/.local/bin"

export PATH=$PATH:~/.roswell/bin

**Comment by overtube** [comment]
so, what I can do for change default editor to NANO?

**Comment by overtube** [comment]
also ur tool is great, and work fast and perfect

**Comment by overtube** [comment]
Glad Thanks! now all is work, awesome, great!

**Comment by extrawurst** [comment]
seems *fixed*
