### ISSUE TITLE
sort and search in branch list

### ISSUE THREAD

**Issue by srayuws** [extrawurst/gitui#1494]
**Is your feature request related to a problem? Please describe.**
In our code repo, we have a lot of branches. I only care about some branches: the `main`, branches with my name, and recent updated branches.

In the current branch window, it is sorted by the branch name. This makes me very hard to find the `main`, I need to a few page down (and maybe a few page up) to find it. 

**Describe the solution you'd like**
1. Sort the branch list not only by branch name. We can add another button to sort it with the most recent commit time.
2. in the branches windows, add a `/` function to filter the branch name. It could be simple text match or a regular expression.

**Describe alternatives you've considered**

For finding the recent branches, the graph view can help a lot.  I noticed that there is already an issue for it: https://github.com/extrawurst/gitui/issues/81

And for finding a branch, in our practice, we use a folder-like branch name convention: `a/b/c`. If the branch window can show it as a tree view, it will also help. 

**Additional context**
n/a

**Comment by carlmnssn** [comment]
yes! 👍🏼 a fuzzy finder in the remote branch view would be very helpful!

**Comment by extrawurst** [comment]
#1350 implements the fuzzy finder, this should solve this
