### ISSUE TITLE
Display non-UTF8 commit messages at least partially

### ISSUE THREAD

**Issue by Boddlnagg** [extrawurst/gitui#150]
**Describe the bug**
Currently when a commit message contains invalid UTF8, the whole message is replaced by the string `<unknown>`.

**To Reproduce**
Create a Git commit with a message that contains invalid UTF8.

**Expected behavior**
I think it would be more useful to use replacement characters (i.e. lossy decoding), so at least most of the commit message is displayed correctly if it only contains a single non-UTF8 character somewhere.

**Comment by extrawurst** [comment]
@Boddlnagg thanks for reporting this, good point! It should be fixed now, but you have no idea how hard it was to force invalid utf8 down rusts safe throat. even the git shell fixed up broken utf8 commit message files. If you could build and test `gitui` on master to make sure your repro cases are fixed would be awesome!

**Comment by Boddlnagg** [comment]
Yes, it works now! Thanks for the quick fix 👍

**Comment by extrawurst** [comment]
Great! @Boddlnagg thanks for checking!

**Comment by extrawurst** [comment]
released in `0.8` now: https://github.com/extrawurst/gitui/releases/tag/v0.8.0
