### ISSUE TITLE
show remote branches In log

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#1501]
only if remote and local are on a different commit

**Comment by cruessler** [comment]
@extrawurst I’d like to work on this issue, hoping to get a PR ready by the weekend!

**Comment by extrawurst** [comment]
@cruessler absolutely! note that the showing of local branches was already added in #1371 and that we now only need to extend this to remote branches

**Comment by cruessler** [comment]
@extrawurst This was more complicated than I expected. Currently, branch names are stored as `String`s in `CommitList` and don’t contain information about corresponding upstream branches. We could change that and use `BranchInfo`, but we would need to change `LocalBranch` which currently has `has_upstream: bool`, but no information on which upstream it is tracking.

I see two options:

1. Implement a simple solution that does show remote branches even for commits where there’s a corresponding local branch. This would be easy and still could later be extended.
2. Change the way information about branches is stored, in particular, add something like `upstream: String` to `LocalBranch` and use that information in `CommitList`. This would require more work, but it would satisfy the requirement to only show remote branches when they are on a different commit than their corresponding local branch.

**Comment by extrawurst** [comment]
Hey @cruessler thanks for looking into this. To be honest I see a lot of value in doing "right" now (option 2) because having that info of what upstreams a local branch has will also be relevant for #1306 (pushing to all remotes of a branch) - wdyt?

**Comment by cruessler** [comment]
I also think it makes sense to go for the more precise option. Locally, I already started looking into extending `LocalBranch`, but I wasn’t sure whether it would be better to separate the UI feature from changing the data structures because I don’t yet know which parts of the application will be affected by the latter. I’ll try doing both changes in this PR, and then we can decide how to proceed.

**Comment by janbaer** [comment]
I used TIG before, and I was also missing the helpful information about how much ahead my current branch is of current or remote head. @extrawurst take a look on, how it's looking in TIG. Thanks in advance!

**Comment by extrawurst** [comment]
this issue is just about showing the `labels` like we already do with local branches tips
