### ISSUE TITLE
Allow for better composing of commit (messages)

### ISSUE THREAD

**Issue by abergmeier** [extrawurst/gitui#1502]
gitui currently does a very good job of displaying status.
Staging files already is quite good. Writing the commit message feels lacking, though.

**Is your feature request related to a problem? Please describe.**
When you have a highly technical problem (think Linux kernel) you might need to write details about what a certain PR does.
Then it is helpful to compose the commit message while also being able to look up details in the staged files.
The modal commit dialog prevents that.

**Describe the solution you'd like**
Something similar to git-gui where you have the commit message as a component of the status.
Not sure whether a complex dialog like in git-gui makes sense though.
I think I would prefer a staged/commit tab more.
Probably would be best to simply replace unstaged component with the commit message editor in that screen then.

**Describe alternatives you've considered**
The current way is that you need to jump into your editor and then from there figure out which files/lines you want to look at.
It is slow and sometimes cumbersome.

**Additional context**
Hitting `c` in status screen could then jump straight to the tab.
Having an own screen would also provide space for extended handling like amending, signing, precommit states, etc. to be shown.

**Comment by extrawurst** [comment]
I like the idea of moving the commit popup into the stage view once going into `commit-mode`.

**Comment by theduke460** [comment]
When committing, there are not provisions for entering a first subject line by allowing a blank line to be entered before the commit body.  The result is that a 'git log --oneline' doesn't produce the one-line summaries that one would expect.  Allowing  SHIFT-ENTER to enter a blank line would be a nice solution.

**Comment by extrawurst** [comment]
In the mean time you can use ctrl+e to edit the message in your external editor

**Comment by extrawurst** [comment]
for a while already a work-in-progress commit message will not be wiped anymore when closing the commit popup for looking something up:

https://github.com/extrawurst/gitui/assets/776816/570f0050-80b6-41d5-89b6-18d6d8137e72
