### ISSUE TITLE
Delay when opening external editor

### ISSUE THREAD

**Issue by raphCode** [extrawurst/gitui#1506]
The delay before the external editor opens is bothering me, it's annoying at best and disruptive at worst.
It makes my normally snappy vim startup feel like emacs or some bloated, laggy electron-based IDE.

I read https://github.com/extrawurst/gitui/issues/157.
I don't know what can be done, maybe starting the editor in parallel with stopping input polling? 

In my opinion, adding loading spinners to operations that should take no time is really disappointing and not the kind of software I want to see or use in this day and age.

**Comment by MartinVincent** [comment]
FYI: You can eliminate the wait if you immediately press Enter after launching the edit command. 

ie:
place the cursor on a given file  <<<<  press 'e' to edit, then without waiting press 'Enter' and voilà, your file is editable in vim.

**Comment by MartinVincent** [comment]
@raphCode 
FYI: You can eliminate the wait if you immediately press Enter after launching the edit command. 

ie:
place the cursor on a given file  <<<<  press 'e' to edit, then without waiting press 'Enter' and voilà, your file is openned in vim.
