### ISSUE TITLE
Crash when resetting hunk of non standard size

### ISSUE THREAD

**Issue by Zykino** [extrawurst/gitui#1512]
```sh
❯ gitui
Error: `hunk not found`
```
Command status is 1.

Steps to reproduce:
1) Make some changes in close proximity in a file
2) Open `gitui`, configure the "Context lines" (in the Options menu) to less than the default so it makes new, smallers hunks
3) `Reset Hunk [Shift + D]`
4) Back to the shell?

**Comment by extrawurst** [comment]
will be fixed in #1746
