### ISSUE TITLE
Stash inspect

### ISSUE THREAD

**Issue by davxy** [extrawurst/gitui#1525]
Looks like the stash inspect doesn't work 

To reproduce:
1. go to "Stashes" pane (5)
2. press inspect key ('l')
3. Nothing happens

Expected behavior: stash changes are shown

**Comment by extrawurst** [comment]
Hm weird. it works for me with the regular key binding. can you check if rebinding that key works?

**Comment by davxy** [comment]
I'm using the following `key_bindings.ron` 

```
// Vim Navigation
// * https://github.com/extrawurst/gitui/issues/1189
// * https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md


(
    focus_right: Some(( code: Char('l'), modifiers: ( bits: 0,),)),
    focus_left: Some(( code: Char('h'), modifiers: ( bits: 0,),)),
    focus_above: Some(( code: Char('k'), modifiers: ( bits: 0,),)),
    focus_below: Some(( code: Char('j'), modifiers: ( bits: 0,),)),

    move_left: Some(( code: Char('h'), modifiers: ( bits: 0,),)),
    move_right: Some(( code: Char('l'), modifiers: ( bits: 0,),)),
    move_up: Some(( code: Char('k'), modifiers: ( bits: 0,),)),
    move_down: Some(( code: Char('j'), modifiers: ( bits: 0,),)),

    open_help: Some(( code: Char('H'), modifiers: ( bits: 0,),)),
)
```

And in the stash page neither `H` nor `l` works

**Comment by davxy** [comment]
Update: in the stashes pane (5) with the keybindings I shared above
1. I can look inside a stash using "right arrow" (thus the mapping is ignored in this particular page)
2. to return back I have to use the `h` key (the "left arrow is ignored as expected)

So in short in this particular pane:
- `move_right` is mapped to "right arrow"  <--- wrong
- `move_left` is mapped to "h" <-- correct

**Comment by extrawurst** [comment]
Please use the provided `vim_style_key_config.ron` because it will also set the special key to define `stash_open`: https://github.com/extrawurst/gitui/blob/master/vim_style_key_config.ron#L46

it does not use the `move_right` key. let me know if that works for you

**Comment by extrawurst** [comment]
48eed05 add this key also in the documentation inside `KEY_CONFIG.md`

**Comment by davxy** [comment]
Works for me! thank you
