### ISSUE TITLE
Cursor not appear when typing CJK characters in commit message

### ISSUE THREAD

**Issue by Saafo** [extrawurst/gitui#1538]
**Describe the bug**
Cursor not appear when typing CJK characters in commit message

**To Reproduce**
1. Go to 'commit message'
2. type Chinese characters e.g. 中文
3. move cursor forward or backward
4. See the cursor disappear when under Chinese characters

**Expected behavior**

**Screenshots**
<img width="212" alt="image" src="https://user-images.githubusercontent.com/46736350/217749021-c0b23a33-7221-46e4-82f1-5f2e09216351.png">

(Cursor disappeared)

**Context (please complete the following information):**
 - OS/Distro + Version: [e.g. `macOS 13.0`]
 - GitUI Version [e.g. `0.22.1`]
 - Rust version: [e.g `1.44`]

**Additional context**

**Comment by extrawurst** [comment]
I would assume its a font thing, because on my terminal it works with these characters you send:

![Screenflick Movie 5](https://user-images.githubusercontent.com/776816/218251616-f8ec848e-646b-46e8-a582-8577bbb4d41d.gif)

**Comment by Saafo** [comment]
@extrawurst Thanks for the try, but I found maybe it's relative to my Terminal `warp`, I use the same font in iTerm2, but it's ok there. I'll open an issue in warp's repo.
