### ISSUE TITLE
Bindings for directional movement between panes

### ISSUE THREAD

**Issue by strogonoff** [extrawurst/gitui#1543]
**Is your feature request related to a problem? Please describe.**

Switching between panes is counter-intuitive. Related: #1539, #227.

**Describe the solution you'd like**

I rather suspect it’d be worthwhile to have a set of bindable controls to switch between panes in the layout directionally (up/down/left/right), as opposed to having to remember context-specific switches (like `w` to switch to/from staging area while in Status mode).

**Describe alternatives you've considered**
—

**Additional context**
—

**Comment by extrawurst** [comment]
`w` is exactly the only example that comes to mind. Help me out otherwise. Don’t see a systematic lack of such binding that at this point are 99% duplication
