### ISSUE TITLE
respect solarized color scheme

### ISSUE THREAD

**Issue by soloturn** [extrawurst/gitui#1554]
the color contrast with a solarized color scheme is not that great, especially with file contents. below a screenshot from gnome terminal, switched over to its default solarized scheme. would be great if it would autoatically choose different colors, or allow to easy configure it.

![image](https://user-images.githubusercontent.com/825568/219944796-319ea69c-a59b-4e58-9498-86e1ca69015c.png)

**Comment by extrawurst** [comment]
you can change every color. there is no way for the terminal and therefore gitui to know what theme you use.

**Comment by extrawurst** [comment]
see here how to customise: https://github.com/extrawurst/gitui/blob/master/THEMES.md
