### ISSUE TITLE
can you add a way to edit configuration without leaving gitui, that we normally do with `git config`

### ISSUE THREAD

**Issue by yilmazdurmaz** [extrawurst/gitui#1556]
**Is your feature request related to a problem? Please describe.**

I prefer not to set global user/email and configure these separately locally for each repo folder. And for this reason, when I try to commit inside gitui, an error welcomes me if I try to commit saying these are not set. an easy thing to forgot.

The thing is it is annoying to leave gitui everytime I need to change some configuration, local or global.

So, it would be nice if we could configure repository settings without leaving gitui.

**Describe the solution you'd like**

I can't think of a solution for now.

**Describe alternatives you've considered**

Alternative!? Just exit gitui, or open another terminal, then use `git config`

**Additional context**

**Comment by extrawurst** [comment]
can you let me know what configs your change that frequently that this becomes such a bottleneck? or do you have to work constantly with new fresh clones you have to rollout configs to? just trying to understand the use case better

**Comment by yilmazdurmaz** [comment]
It is not a bottleneck as we already have a way to do this; `git config`. Nor it is something that needs to be implemented in a near future, if at all. It is just about working without leaving gitui which would be a nice addition if possible ;)

As for the use case, small daily throw-away projects that would still need version tracking not to forget what has been done would benefit much from this configuration extra. it is better to keep them isolated from system/global configuration until we decide what to do with them. but again, configuring from a single place.

Long-term projects would also benefit, in my opinion, from being able to be configured in a single place, namely inside gitui.
