### ISSUE TITLE
esc to exit program

### ISSUE THREAD

**Issue by yagarea** [extrawurst/gitui#1558]
**Is your feature request related to a problem? Please describe.**
`esc` does not end program

**Describe the solution you'd like**
make `esc` exit program

**Describe alternatives you've considered**
keybind esc to sending kill command

**Additional context**
I would like to exit gitui with press of `esc`

**Comment by extrawurst** [comment]
Have you tried customizing it to your liking? https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md

**Comment by extrawurst** [comment]
Specifically: https://github.com/extrawurst/gitui/blob/master/src/keys/key_list.rs#L48
