### ISSUE TITLE
communicate delay when opening external editor

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#157]
right now only the `spinner` indicates that something is happening when opening the external editor which can take up to 2 seconds because the input polling needs to stop first.

see #46

**Comment by extrawurst** [comment]
done in de7f48f88ef099e03e0a823675252427fec79cab
![vi_support](https://user-images.githubusercontent.com/776816/86518953-13ec8300-be36-11ea-9e9e-46d83967e28f.gif)

**Comment by MartinVincent** [comment]
FYI: You can eliminate the wait if you immediately press Enter after launching the edit command. 

ie:
place the cursor on a given file  <<<<  press 'e' to edit, then without waiting press 'Enter' and voilà, your file is editable in vim.

**Comment by extrawurst** [comment]
Yeah there must have been some fuckup when switching from the polling mechanism to the file-watcher. see #1506
