### ISSUE TITLE
See the current remote « sync state » (behind / ahead)

### ISSUE THREAD

**Issue by phaazon** [extrawurst/gitui#1583]
**Is your feature request related to a problem? Please describe.**
In most git clients, there is a way to know whether the current branch is behind and/or ahead its remote counterpart. This is very useful to know whether we must `push` or `fetch & rebase` / `pull`. I haven’t found anything so far in `gitui` and I think it’s one of its most important lacking feature.

**Describe the solution you'd like**
In the `Status [1]` tab, we should have an extra line or something describing the behind / ahead state, if a remote is set, like `↓510` if we need to fetch 510 commits. Same thing for ahead commits.

Also, I think that could be visible in the branch popup as well.

**Describe alternatives you've considered**

**Additional context**

**Comment by extrawurst** [comment]
this is implemented since https://github.com/extrawurst/gitui/issues/362

**Comment by phaazon** [comment]
Then forget this issue. Thanks!
