### ISSUE TITLE
Better named release asserts

### ISSUE THREAD

**Issue by dclong** [extrawurst/gitui#1593]
**Is your feature request related to a problem? Please describe.**
The naming of release asserts is confusing. For example, it's not obvious whether `gitui-linux-musl.tar.gz`, `gitui-mac.tar.gz` and `gitui-win.tar.gz` are for x86_64 or arm64.

**Describe the solution you'd like**
Follow a strict naming convention, e.g., `gitui-os-arch.tar.gz`. For Linux OS, `musl`, `gnu` or `unknown` can be included.

**Additional context**
Apps might want to download gitui automatically depending on OS and Arch. A strict naming make this much easier to do.

**Comment by extrawurst** [comment]
Good point, feel free to create a PR

**Comment by extrawurst** [comment]
superceded by #2148
