### ISSUE TITLE
only use right to move to diff from staged changes

### ISSUE THREAD

**Issue by pzzxqj** [extrawurst/gitui#1597]
**Describe the bug**
I use the  [vim style key config](https://github.com/extrawurst/gitui/blob/master/vim_style_key_config.ron),
 but can't move to diff area from unstaged or staged by pressing `l`. I have to use right arrow following the tip of bottom.
**To Reproduce**
1.  Go to unstaged or staged of status
2. press `l`, don't work

**Expected behavior**
press 'l' moving to right diff area

**Screenshots**

**Context (please complete the following information):**
 - opensuse tumbleweed
 - GitUI Version 0.22.1

**Comment by extrawurst** [comment]
cannot reproduce on `master`. please double check by building from source. to validate that it will be fixed in the next release

**Comment by pzzxqj** [comment]
i clone the repository and use `make install`, it works well.
