### ISSUE TITLE
Commit message missing when starting on Log tab

### ISSUE THREAD

**Issue by pdanpdan** [extrawurst/gitui#1608]
**Describe the bug**
When GitUI was closed on `Log` tab and it is started again the text of the commit messages is not displayed.
After changing to another tab and back the text is displayed.

**To Reproduce**
1. Start GitUI in a repo
2. Switch to `Log` tab [2]
3. Close GitUI
4. Start GitUI again
5. It should start on `Log` tab and the commit messages should be missing

**Expected behavior**
The messages should show on start :)

**Screenshots**
On start
![Screenshot from 2023-03-18 09-35-59](https://user-images.githubusercontent.com/118764/226092216-e93207a3-3676-4ee0-a098-0f9e25d45840.png)

After tab change
![Screenshot from 2023-03-18 09-36-13](https://user-images.githubusercontent.com/118764/226092239-a4bd0d7a-759b-4aeb-831b-a6b9f1f02893.png)

**Context (please complete the following information):**
 - Pop!_OS 22.04 LTS on Wayland (intel)
 - wezterm terminal
 - gitui 0.22.1 (downloaded from releases on github)

**Comment by extrawurst** [comment]
dup of #1473
