### ISSUE TITLE
switch to less heavy alternative to clap

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#161]
something like https://github.com/RazrFalcon/pico-args or https://github.com/google/argh

just by removing clap the **release** binary size shrank by 500k

**Comment by studoot** [comment]
[gumdrop](https://docs.rs/gumdrop/0.8.0/gumdrop/) is another possible option - [this blog post](https://blog.kodewerx.org/2020/06/the-rust-compiler-isnt-slow-we-are.html) suggests a 500kB size reduction as well.

**Comment by extrawurst** [comment]
let's keep this help output as similar as possible:
```
gitui 0.8.1
Stephan Dilly <dilly.stephan@gmail.com>
blazing fast terminal-ui for git

USAGE:
    gitui [FLAGS] [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -l, --logging    Stores logging output into a cache directory
    -V, --version    Prints version information

OPTIONS:
    -d, --directory <directory>    Set the working directory
```

**Comment by extrawurst** [comment]
ok I tried `pico-argh` and it reduces the raw binary size by 400kb (200kb after stripping), but does not reduce the dependencies at all (other than `textwrap`, which we soon need anyway due to #181). also the compile time only gets reduced by 7s. on the other hand convenience gets reduced significantly so I for now decide that the gain is not worth the pain
