### ISSUE TITLE
Please make a conda recipe

### ISSUE THREAD

**Issue by abalter** [extrawurst/gitui#1626]
It would be great to be able to install this with `conda install -c conda-forge gitui`.

**Comment by TheBlackSheep3** [comment]
in progress https://github.com/conda-forge/staged-recipes/pull/23509

**Comment by TheBlackSheep3** [comment]
This issue can be closed. `gitui` is available through conda via the conda-forge channel.
```
conda install gitui --channel conda-forge
```
I'll maintain the [feedstock](https://github.com/conda-forge/gitui-feedstock) and publish upcoming releases to conda.

**Comment by extrawurst** [comment]
@TheBlackSheep3 thanks for this. can you add it to the readme?
