### ISSUE TITLE
minor request about linux release

### ISSUE THREAD

**Issue by pm100** [extrawurst/gitui#1636]
(returning here after long absence. I always sing the praises of this project))

Wanted to install linux version on x86_64. I had no idea what 'musl' was. Took me a long time to work out that this means x86_64 version
At first I guessed aarch64 ("AMD 64 bit architecture" perhaps? nope)

Some hint in the readme as to which file to install would be useful given that this is almost certainly the most common choice

**Comment by extrawurst** [comment]
Wanna make a PR?

**Comment by pm100** [comment]
Done. I considered putting links to the downloads in the readme. But that would mean it has to be edited every time. So didnt

________________________________
