### ISSUE TITLE
Windows msi installer

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#164]
Inspired by usage of *wix* in nushell: https://github.com/fdncred/nushell/commit/c58a456dbc74a86f0e89519ca4d3e928ea6b3224#diff-56c30d9224897b08c28075052d4595c5

**Comment by non-descriptive** [comment]
maybe add [chocolatey](https://chocolatey.org/) packages as well?

**Comment by kdebowski** [comment]
I would love to see gitui in [Scoop](https://scoop.sh/) repository

**Comment by extrawurst** [comment]
I am not using windows, so I am very much depending on some contribution here.

**Comment by rashil2000** [comment]
gitui is there in the main bucket of Scoop. 
@extrawurst Just add a section like this to the Readme in this repo. 

### Scoop (Windows)

```
scoop install gitui
```

**Comment by extrawurst** [comment]
@rashil2000 thanks for pointing it out, its added!

**Comment by pm100** [comment]
I have created an installer for gitui using that toolkit. Works great

I have no idea how to integrate it into the github CI process. I will look see how nushell does it

**Comment by extrawurst** [comment]
@pm100 thanks for tackling this. `cd.yml` only runs when we tag a new release. `ci.yml` runs on each commit you should be able to open a draft PR and the CI should run

**Comment by extrawurst** [comment]
@pm100:
> you sure about that? ci.yml does not build any of the install assets, cd is the one that does it. You only really need to build the msi when you bless a release. For sure I can use ci to test it out

Maybe I should have been more clear: yes ultimately we need to adjust the CD but for the purpose of testing we use CI until we see it works correctly

**Comment by extrawurst** [comment]
Closed in https://github.com/extrawurst/gitui/pull/360
