### ISSUE TITLE
Key bindings mapping

### ISSUE THREAD

**Issue by alex-popov-tech** [extrawurst/gitui#165]
Thanks for such a great tool!

That would be really great to have mapping mechanism similar to tig

So for example i can map arrow keys to hjkl, stage one file to `a`, stage all to `A`, `tab` to jump between stage/unstage, etc.

**Comment by alex-popov-tech** [comment]
because navigating using keyboard is really awesome, but 'enter'/'esc'/'arrow keys' not the easiest keys to type :)

**Comment by extrawurst** [comment]
@alex-popov-tech thanks for your interest in `gitui`, this topic is definitely on my radar (see #57)

**Comment by alex-popov-tech** [comment]
get it, subscribed on pr, thanks! @extrawurst
