### ISSUE TITLE
External editor does not start with EDITOR set

### ISSUE THREAD

**Issue by darthmall** [extrawurst/gitui#1654]
**Describe the bug**
I have set `EDITOR=nvim` in my shell, but when I hit ctrl-e, nothing happens.

**To Reproduce**
1. Stage changes
2. Press 'w' to switch to staged changes
3. Press 'ctrl+e'
4. Nothing happens

**Expected behavior**
NeoVim should start up with the commit message template.

**Context (please complete the following information):**
 - OS/Distro + Version: Pop!_OS 22.04 LTS x86_64
 - GitUI Version: 0.22.1
 - Rust version: 1.67.1

**Additional context**
I’m using fish version 3.6.1 for my shell, and I have NeoVim version 0.8.2. I have tried running `EDITOR=vi gitui` and ctrl-e still does nothing.

**Comment by pm100** [comment]
^e is only available in the commit popup. 'h' shows help

![image](https://user-images.githubusercontent.com/489231/232552319-0647f191-9eed-4f8d-ae15-8be62583b427.png)

in the staged change box, press 'c' to start a commit. You will get

![image](https://user-images.githubusercontent.com/489231/232552479-1667d5d6-a77b-4c1d-ba49-6b7002a22917.png)

now hit ^e

![image](https://user-images.githubusercontent.com/489231/232552903-a55cfd57-595f-4915-9823-6e9cbe72bd16.png)

**Comment by darthmall** [comment]
Thanks, I misunderstood the help menu in the app. But now I’m getting an error:

```
Failed to launch editor:
"$EDITOR": no such file or directory (os error 2)
```

I’ve tried the following:

1. `EDITOR=nvim gitui`
2. `EDITOR=vi gitui`
3. `EDITOR=/home/evan/.local/bin/nvim gitui`

I have no trouble launching either `vi` or `nvim` from the same shell in which I then launch `gitui`.

**Comment by darthmall** [comment]
> BTW the precedence is GIT_EDITOR, core.editor, VISUAL, EDITOR

Ok, that’s what it was. I had a bad value for `core.editor` in `~/.gitconfig`.

But for what it’s worth, I was not passing `gitui` as an argument to `nvim`. The commands I executed are:

1. `EDITOR=nvim gitui`
2. `EDITOR=vi gitui`
3. `EDITOR=/home/evan/.local/bin/nvim gitui`

Beginning the command with `EDITOR=nvim` sets the environment variable `EDITOR` for just that command, so that you don’t have to keep running `export` or `set` in your shell when you’re testing multiple values.

**Comment by pm100** [comment]
Yup, my bad with the last question. So you good now? Can you close this please
