### ISSUE TITLE
replace textinput with tui-textarea

### ISSUE THREAD

**Issue by pm100** [extrawurst/gitui#1662]
The popup used for text input is fine in most cases but generates many requests for features in the multiline case, particularly the commit message.

There are several open requests on this. Rather than a piecemeal approach of adding bits and pieces I think it would be better to use a plugin component that offers 
- line split and join
- undo
- full multiline edit
- cut / paste
- .....

tui-textarea https://github.com/rhysd/tui-textarea is just such a component

I have done an experiment to see how easy it would be to drop in. Its pretty straightforward. Took a couple of hours

unless you think this is a completely stupid idea I will give it a less hacky go. You could then clone if from my repo and see what you think. The UI looks the same, its just that the multiline textinput supports full edit.

I also have a couple of points to discuss about it in terms of what keys should do what. But I want to see if you think this is at least a possibility before engaging is further debate.

PS - are you aware of the whole ratatui thing. https://github.com/tui-rs-revival/ratatui

**Comment by extrawurst** [comment]
> unless you think this is a completely stupid idea I will give it a less hacky go

if it can be used in gitui without changing a ton of keys I am in 💪

> are you aware of the whole ratatui thing

yeah I just updated today to ratatui: 904885e

**Comment by pm100** [comment]
The main question re keys. In the commit edit window the behavior of the 'enter' key.

The 'natural' thing for an edit window is for this to break a line / add a new line. However gituis natural workflow for commit is
- 'c'
- 'switch to ratatui'
- 'ENTER'

which closes the dialog and does the commit. I can make that work, then left with what should the break line be?
- ctrl-Enter
- ctrl-M (its tui-textarea default)

They are not obvious though. I will add a 'help' option I think.

Second question

Why is there all that warning stuff about commit message length. What rules are you enforcing and where do they come from, since I need to do the same thing- I think

**Comment by crispinb** [comment]
Hey @pm100 - re the commit message length warning, see https://github.com/extrawurst/gitui/issues/478

**Comment by crispinb** [comment]
> which closes the dialog and does the commit. I can make that work, then left with what should the break line be?
> 
>     * ctrl-Enter
>     * ctrl-M (its tui-textarea default)

FWIW as a relative gitui newcomer, I would think, as you suggest, unmodified `Enter` should behave exactly as now. No point in befuddling current users.

I don't like either of your proposed newline-entering shortcuts. `ctrl-Enter` is used in many other apps to submit (eg. here in github issues!). `ctrl-M` seems a bit obscure to me.

I would suggest `SHIFT+Enter`. It's fairly commonly used for this purpose IIRC. It's actually the first one I tried in gitui when I realised (counter to my expectations) that `Enter` submitted the dialogue.

**Comment by rakibulhaq** [comment]
I am with the `SHIFT + Enter` 👍

**Comment by extrawurst** [comment]
@pm100 do you want to work in this?

**Comment by pm100** [comment]
My problem is that I am waiting for the owner of tui textarea to accept a PR. I have prodded a couple of times but got no response. I have the changes to Gitui basically working, but off my own fork of textarea.

________________________________

**Comment by AmmarAbouZor** [comment]
We'll need the author of `tui-textarea` to update the version on `crates.io` too. The last version there still have dependencies to the deprecated `tui-ts` crate. I've opened an issue there a while ago and haven't got any response since then.
Without this update it's impossible to publish the new version on `crates.io` because they don't accept dependencies from outside crates.io packages

**Comment by pm100** [comment]
There are quite a few things I would like to change about that package. I was thinking about created a tui widgets repo. Add textarea, with fixes, plus tui menu, which is another semi abandoned tui project

________________________________

**Comment by AmmarAbouZor** [comment]
A new version of text-area has finally arrived. I think this can be implemented now

**Comment by pm100** [comment]
resuming work on this now, watch this space

**Comment by pm100** [comment]
@extrawurst Almost done. Disappered down a big rabbit hole getting them to add a couple of features that gitui needs (useful to all tho), now done. I am stuck on something weird tho.

I syncd the latest gitui, added my changes all works fine.

But now the test for loading vim key config fails. My issue is that I dont see how it can work. The .ron file has lines like this ` open_help: Some(( code: F(1), modifiers: ( bits: 0,),)),` but that requires that the struct being loaded has Option<> type. It did at one point in key_list_file.rs but that got removed. So I dont see how the current code works, it does work, but I cant see how it works, so I cant work out what I have broken and how to fix it. Any clues would be great

**Comment by pm100** [comment]
@AmmarAbouZor   @extrawurst see pr #1937

**Comment by pm100** [comment]
Work completed , now only changes one file, but it is stuck on the ratatui version issue see

**Comment by pm100** [comment]
not that this will also fix #1699 as tui-textarea has full support for all language types

**Comment by extrawurst** [comment]
Closed via #2051
