### ISSUE TITLE
`Diff [->]` is stuck with right arrow instead of configured `move_right` key

### ISSUE THREAD

**Issue by luckslovez** [extrawurst/gitui#1670]
**Describe the bug**
When configuring custom `move_right` and `move_left` keys, one may expect to be able to go back and forth to the `Diff` pane using those. Instead, the default arrow keys need to be used.

**To Reproduce**
1. Configure vim key binding style https://github.com/extrawurst/gitui/blob/master/vim_style_key_config.ron in ` ~/.config/gitui/key_bindings.ron` (which contain custom `move_right` and `move_left` keys)
```
    move_left: Some(( code: Char('h'), modifiers: ( bits: 0,),)),
    move_right: Some(( code: Char('l'), modifiers: ( bits: 0,),)),
```
2. Open gitgui
3. Notice the symbol for the `Diff` option at the bottom is still arrow right
4. Press `l` (key for `move_right`) and notice nothing happens, you need to press arrow right to get to the diff

**Expected behavior**
To go back and forth to the Diff pane is possible with the keys configured for `move_right` and `move_left`.

**Screenshots**
![image](https://user-images.githubusercontent.com/22451525/234864608-0c5c5f0b-5189-4f61-b085-0995c32550fe.png)

**Context (please complete the following information):**
 - OS/Distro + Version: [`macOS 13.3.1`]
 - GitUI Version [`0.22.1`]

**Comment by pm100** [comment]
after investigation I find this is fixed (accidentally) by https://github.com/extrawurst/gitui/pull/1540. Build from master source of wait for next release
