### ISSUE TITLE
!verify on commit skips too much

### ISSUE THREAD

**Issue by pm100** [extrawurst/gitui#1689]
Working on adding prepare_commit_msg hook I see that currently too many actions are skipped when verify is off. 
 - The post commit hook is skipped, this does not verify and should be run (git runs it when -n supplied)
 - the gitui 'prettify-message' call is skipped. I think this should still be run

This is however a functional change so I wont just roll it into the change I am working on unless you say to do it

**Comment by extrawurst** [comment]
I Must have overlooked that when reviewing the pr that added the !verify option. PR to fix this is welcome
