### ISSUE TITLE
Move right keybinding inconsistent

### ISSUE THREAD

**Issue by chrstnwhlrt** [extrawurst/gitui#1708]
The move_right keybinding isn't used in every view inside gitui, which forces the user to switch between arrow keys and hjkl depending on the current state.

**Example 1**: Using the provided vim keybindings, try to open commit details, focus on the diff view on the right. 

Steps:

1. Open gitui 
2. Press 2 to switch to the commit log
3. Select a commit using j or k and show the details using <enter>
4. To switch to the commit inspection the user has now to use the right arrow key
5. Select a file within the commit  j or k
6. To focus the file content (and allow scrolling) the user is again forced to use the right arrow key

**Example 2**: Show the git history of a specified file

Steps:

1. Open gitui
2. Press 3 to switch to the files tab
3. Select a file using j or k and show the revisions using H
4. Navigate the logs on the left using j or k
5. To focus the file content (and allow scrolling) the user is forced to use the right arrow key

**Comment by pm100** [comment]
i think this is already reported and fixed here https://github.com/extrawurst/gitui/issues/1670
