### ISSUE TITLE
BUG: File is listed on "Unstaged Changes" even when on gitignore

### ISSUE THREAD

**Issue by Zeioth** [extrawurst/gitui#1714]
**Describe the bug**
The content of my gitignore is

    /lua/base/git-ignored
    init.lua

* The first entry is ignored correctly, and it is not displayed in "Unstaged changed" (even after making changes to the files in the directory)
* The second entry is not ignored correctly and it is still listed on "Unstaged changes" (when changed) even though it is on the gitignore file.

**To Reproduce**
1. git clone https://github.com/Zeioth/NormalNvim.git
2. add some change to init.lua
3. run gitui and you will see it appears listed even though it is on the git ignore.

**Expected behavior**
Files in gitignore are not displayed on "Unstaged Changes" (so we don't commit them by accident).

**Screenshots**
![screenshot_2023-06-06_20-32-58_396025030](https://github.com/extrawurst/gitui/assets/3357792/6cafe3b6-24f6-4937-982e-730bd0a585ce)

**Context (please complete the following information):**
 - OS/Distro + Version: Arch linux
 - GitUI Version: 0.22.1
 - Rust version: 1.26.0-3

**Comment by utherpally** [comment]
I don't believe this is an issue because Git will continue to track any files that are already being tracked. You can verify this by running `git status`, which will show the same result.

**Comment by Zeioth** [comment]
It seems you are right. It is not possible to have a local file in a different state than on remote, even if the file is on gitignore.

    git rm --cached <file-path>

Don't seem to help either. 

Anyway if this is not a gitui bug I'm closing it. Thank you so much for looking into it.
