### ISSUE TITLE
Popping stash disallowed with staged changes

### ISSUE THREAD

**Issue by eclairevoyant** [extrawurst/gitui#1724]
**Describe the bug**

Popping a stash with anything staged throws an error:

```
git error:1 uncommitted changes exist in the index; class=Stash (19); code=Uncommitted (-22)
```

**To Reproduce**
1. Add any files to stash
2. Stage any changes
3. Attempt to pop stash 

**Expected behavior**

No error should occur, and staged changes should stay staged after popping, because `git stash pop` works this way.

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro + Version: Linux (stable version from nixpkgs, git version built from source)
 - GitUI Version `0.22.1`, I also tested with latest git commit
 - Rust version: unknown for nixpkgs version, 1.70.0 for the latest git commit version

**Additional context**

n/a

**Comment by extrawurst** [comment]
we currently do not allow unstashing with conflicts. I wonder if we should just drop that limitation and create files in conflict or first confirm whether that is the desired behaviour because in case of `pop` the clean stash is gone afterwards

**Comment by eclairevoyant** [comment]
from my testing, it seems even if there are no conflicts, as long as any file is staged it will throw this error. e.g. if I edit file A, stash changes, then edit file B, stage it, popping is no longer allowed by gitui (even though conflicts are impossible)

**Comment by eclairevoyant** [comment]
Looks like this is something libgit2 added for some reason in libgit2/libgit2#3259:

> Stash application should stage new files, even when we're not updating the index.

> Oh, right, it turns out that we should also block stash application if there are any staged changes.

Closing.
