### ISSUE TITLE
cannot load commit.template

### ISSUE THREAD

**Issue by malleroid** [extrawurst/gitui#1745]
Thanks for the great product!
I just started using it, but I'm reporting something I didn't quite understand.

I have commit.template set up and it is loaded when I run the `git commit` command from the shell.
However, when I try to edit the commit message by `^e` when committing from gitui, it is not loaded.

I am aware that commit.template is supported, but is there something wrong with my configuration? (https://github.com/extrawurst/gitui/issues/546)

The first one is when you run `git commit`, and the second one is when you open the editor from gitui.

<img width="527" alt="image" src="https://github.com/extrawurst/gitui/assets/38337195/8542a4f1-25a2-41fb-b0c9-10f84084143f">
<img width="396" alt="image" src="https://github.com/extrawurst/gitui/assets/38337195/af7ba1c0-ff4c-42df-b75a-be8013838b03">

The following is a description of the settings for git commit.template.

<img width="307" alt="image" src="https://github.com/extrawurst/gitui/assets/38337195/958942a0-4097-4901-823a-de90dc0f0b74">
<img width="294" alt="image" src="https://github.com/extrawurst/gitui/assets/38337195/d4f09e42-6cde-4722-ab5a-f979cb9bee8d">

- OS: macOS Ventura 13.3
- GitUI version: 0.23.0

**Comment by extrawurst** [comment]
have you tried if a complete path works? (not using `~`)

**Comment by extrawurst** [comment]
if you can please build from source with 5246aab (on branch `fix-1745-commit-template-problem`) which will add more error logging around commit-template loading, to help diagnose this

**Comment by malleroid** [comment]
Thanks for the reply!
Sorry for the delay in noticing your response.

I will try the information you provided!

**Comment by malleroid** [comment]
@extrawurst 
I was able to load and display it when I set it to an complete path! Thank you!!!! 😆 
However I do have a request. 
I'm using dotfiles to reuse information like .gitconfig across multiple machines, so it would be great if it could be loaded with relative paths as well.

I've tried using it after checking out the relevant branch locally and running `cargo build`.  
And stop using Homebrew installed version.

However, I'm not very familiar with Rust, and I apologize, but I couldn't locate the log. 
It looks like the `setup_logging` initializes the configuration using crates like `log` or `simplelog`, and I assumed that the output would be in a file called `gitui.log`. 
Even when using the `find` command, I couldn't locate it. 

Could you possibly advise where the output might be found?

Additionally, I want to express my appreciation for your support!

**Comment by extrawurst** [comment]
see https://github.com/extrawurst/gitui/blob/master/README.md#diagnostics

**Comment by malleroid** [comment]
@extrawurst 

Totally missed that. Thanks!
Here's the error part from the generated log.

```
06:48:18 [TRACE] (1) gitui::app: [src/app.rs:509] update_async: Git(Status)
06:48:18 [TRACE] (1) gitui::app: [src/app.rs:392] event: Input(Key(KeyEvent { code: Char('c'), modifiers: NONE, kind: Press, state: NONE }))
06:48:18 [ERROR] read commit.template failed: No such file or directory (os error 2)
06:48:21 [TRACE] (1) gitui::app: [src/app.rs:392] event: Input(Key(KeyEvent { code: Char('e'), modifiers: CONTROL, kind: Press, state: NONE }))
06:48:22 [INFO] input polling suspended
06:48:22 [TRACE] (1) gitui::app: [src/app.rs:392] event: State(Paused)
06:48:25 [INFO] input polling resumed
```

The result showed an error indicating that it couldn't detect the presence of the file.

Is there any other information you need from me?

**Comment by extrawurst** [comment]
> if it could be loaded with relative paths as well.

it will work with relative paths. what it does not support right now is `~`

**Comment by malleroid** [comment]
@extrawurst 
Thank you for your prompt response!! 😃 

I built it locally and confirmed that I was able to load the commit_template just as you've modified! Great! 🥇
