### ISSUE TITLE
key_bindings.ron should follow symlink

### ISSUE THREAD

**Issue by okuramasafumi** [extrawurst/gitui#1751]
**Describe the bug**

When I use symlink to configure key bindings like below, it didn't work.

```sh
ln -s ~/dotfiles/git/gitui/keyconfig.ron ~/.config/gitui/keyconfig.ron
```

When I use `cp` instead of `ln -s` it worked.

**To Reproduce**
1. Create `key_bindings.ron` somewhere (say, `~/key_bindings.ron`)
2. `ln -s ~/keyconfig.ron ~/.config/gitui/keyconfig.ron`
3. Confirm that it is not applied

**Expected behavior**

Symlink should work.

**Context (please complete the following information):**
 - OS/Distro + Version: macOS 13.4.1
 - GitUI Version 0.23.0
 - Rust version: None (installed via Homebrew)

**Additional context**

I tried to use symlink since I wanted to put my config in my dotfiles. This could be pretty common.

**Comment by Muttsuri** [comment]
It's a hacky solution for now, but couldn't you use hard-links ?
I'm not familiar with macOS but given it's UNIX based it should work similarly, no ?
Short and clear soft-link vs hard-link difference, post [here](https://www.linkedin.com/pulse/hard-link-soft-link-ana-maria-roman-valencia). And according to [this](https://discussions.apple.com/thread/251599508) macOS thread, you could create your hard-link with:
```console
ln ~/dotfiles/git/gitui/keyconfig.ron ~/.config/gitui/keyconfig.ron
```
(yes it's just killing the -s soft-link flag)

I agree that it should be able to follow symlinks just but it might help you for now I hope 🙂

**Comment by TheBlackSheep3** [comment]
Hey! Is this issue already assigned to someone? If not, I would like to work on it.

**Comment by extrawurst** [comment]
We don’t assign. You make a PR and that’s it :)

**Comment by TheBlackSheep3** [comment]
Thanks
