### ISSUE TITLE
Add `signoff`to commits

### ISSUE THREAD

**Issue by domtac** [extrawurst/gitui#1757]
Projects I am working on are requiring to have signed-off commits to trace the origin of changes.
Here is the documentation to this [git feature](https://git-scm.com/docs/git-commit#Documentation/git-commit.txt--s)
 
I would propose, having this as an option to apply this to all following commits or use capital c when committing to sign the commit off

**Comment by extrawurst** [comment]
https://docs.pi-hole.net/guides/github/how-to-signoff/

Sounds like a command that should just add text to the commit message, or am I missing something?
