### ISSUE TITLE
invalidstring is missing license file on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#177]
Same as it happened in past with asyncgit, would be much appreciated if you could make a new release.

**Comment by extrawurst** [comment]
@ignatenkobrain damn, why is crates.io not protecting against it if that is a problem :( fixed In 5c33e97

**Comment by extrawurst** [comment]
@ignatenkobrain I assume you refer to a `gitui` release and not only an `invalidstring` release, right?

**Comment by ignatenkobrain** [comment]
`invalidstring` release is enough.

**Comment by extrawurst** [comment]
@ignatenkobrain cool then we are good: https://crates.io/crates/invalidstring/0.1.2
