### ISSUE TITLE
Segmentation Fault on Arch Linux

### ISSUE THREAD

**Issue by piotryordanov** [extrawurst/gitui#1773]
I just updated my packages to latest on Arch Linux using `pacman -S gitui`

I can't run the program without having a segmentation fault error:

```fish
fish: Job 1, 'gitui' terminated by signal SIGSEGV (Address boundary error)
```

And in bash:
```sh
[alpha@stronghold coredump]$ gitui
Segmentation fault
```

The AUR `gitui-git` version works fine. It seems to be a week behind.

**Comment by overtube** [comment]
gitui-git version work fine but if make update with package manager get this: `error: failed to prepare transaction (could not satisfy dependencies)
:: installing libgit2 (1:1.7.0-3) breaks dependency 'libgit2.so=1.6-64' required by gitui-git
`
and system cannot update

**Comment by sgued** [comment]
Recompiling the arch package works. I suspect the bug comes from the arch build. I opened a bug there: https://bugs.archlinux.org/task/79209.

**Comment by sgued** [comment]
Looks like a rebuild has been pushed and fixes the issue.
You might need to wait for  it to propagate to you mirror.

I think this issue can be closed.
