### ISSUE TITLE
Is amend broken on last release?

### ISSUE THREAD

**Issue by oroulet** [extrawurst/gitui#1778]
**Describe the bug**
stage some changes
"c" to get into commit box
Ctrl-e, Ctrl-n work fine but Ctrl-a does nothing at all

**Expected behavior**
I am expecting the commit window to disapear and the changed amended to last commit

**Screenshots**
![image](https://github.com/extrawurst/gitui/assets/2564046/14649124-26a5-4a4b-895e-0ecf9d0dc138)

**Context (please complete the following information):**
 ubuntu. installed with ? cargo install gitui`  one hour ago

**Comment by extrawurst** [comment]
works for me. can you provide the log?

**Comment by oroulet** [comment]
arrrg, ctr-a was swallowed by tmux. sorry for reporting that...
