### ISSUE TITLE
cargo update

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#1781]
updating a few major dependencies is blocked right now by the ecosystem taking its time to follow the new major versions of `syn` and `bitflags`. and minor versions of `regex-syntax`, `redox_syscall`.

## `syn`
as it seems we have to wait for a few remaining crates to release new versions:
* `struct-patch-derive` (using old `syn`): https://github.com/yanganto/struct-patch/issues/19
  * it uses `proc-macro-error` which has no support for `syn2` merged&released yet: https://gitlab.com/CreepySkeleton/proc-macro-error/-/merge_requests/36
* `bugreport` which in turn requires `git-version` (using old `syn`): https://github.com/fusion-engineering/rust-git-version/pull/20 
  * or alternatively: https://github.com/sharkdp/bugreport/issues/13
* `chrono` -> `iana-time-zone` -> `iana-time-zone-haiku` (`v0.1.1`) which still depends transitively on syn1 via `cxx-build`: https://github.com/strawlab/iana-time-zone/pull/110

## `regex-syntax` ✅
* `syntect` (using old `regex-syntax`): https://github.com/trishume/syntect/issues/486

## `redox_syscall`
* `shellexpand` in turn using `redox_users` used by (using old `redox_syscall`): https://gitlab.redox-os.org/redox-os/users/-/merge_requests/36
* `notify` using `filetime` (`redox_syscall`): https://github.com/alexcrichton/filetime/issues/98
  * bump in `notify`: https://github.com/notify-rs/notify/pull/521
  * new `notify` release: https://github.com/notify-rs/notify/issues/513

## `bitflags`
* `ron` (`bitflags`): https://github.com/ron-rs/ron/issues/469
* `notify` (`bitflags`): https://github.com/notify-rs/notify/issues/513
* `crossterm` (`bitflags`): https://github.com/crossterm-rs/crossterm/issues/807
* `git2` (`bitflags`): https://github.com/rust-lang/git2-rs/issues/976
* `syntect`: https://github.com/trishume/syntect/pull/490

help needed: 
* `redox_syscall` itself does not support working with `bitflags` 2.x: [redox_syscall](https://gitlab.redox-os.org/redox-os/syscall/-/issues/34) (MR needed)

plus our very own:
* usage of `dirs-next`: https://github.com/extrawurst/gitui/pull/1783

**Comment by yanganto** [comment]
`struct-patch-derive` already use syn2 after 0.3.0 release

**Comment by extrawurst** [comment]
ok i will merge this now and add the two remaining exceptions to unblock a lot of other work. the two exceptions are `bitflags` and `itertools`
