### ISSUE TITLE
Linux builds, please?

### ISSUE THREAD

**Issue by dufferzafar** [extrawurst/gitui#18]
I currently use `lazygit`, but have a few gripes with it. 

I understand that this project is in very early stages, but I'd still want to try it.

Having linux builds like other rust tools would be great, thanks!

**Comment by extrawurst** [comment]
Hi @dufferzafar thanks for your interest in the project. I currently setting up continuous deployment for macos builds since this is my home platform. I want to look into linux/windows builds after that, but maybe you can shed a light what the right approach to deal with Linux is, simply providing a ubuntu build binary or is there a package manager that I should focus on?
any interest in helping out with this?

**Comment by dufferzafar** [comment]
So, I feel like you should just try to mimic how other "popular" rust tools do this. Like ripgrep, fd, exa etc. I think having a .deb file, a .rpm file and a .tar.gz file containing a static binary should be enough for just about everyone.

I've never used the rust tool chain myself. But I've been meaning to for some time now, so sure I'd try to see how it all works. 

And yeah, we'd have them automated by GitHub actions so that whenever a tag is released. The corresponding binaries go up.

**Comment by extrawurst** [comment]
So I added GitHub Actions to automate deployment of Mac builds, I will look at linux next and mimic `procs` (https://github.com/dalance/procs) is doing and start with an `rpm` package. is that a format that you could test then?

**Comment by dufferzafar** [comment]
No, sorry, I use ArchLinux and won't be able to test rpm easily. Or debs for that matter. For me, the best format would be a statically linked executable. Packaged in a tarball. 

Like this one for ripgrep: https://github.com/BurntSushi/ripgrep/releases/download/12.0.1/ripgrep-12.0.1-x86_64-unknown-linux-musl.tar.gz

or this for procs: https://github.com/dalance/procs/releases/download/v0.9.20/procs-v0.9.20-x86_64-lnx.zip

**Comment by extrawurst** [comment]
Ok then tarball'd binary for musl it is! :)

**Comment by extrawurst** [comment]
@dufferzafar would non-musl `x86_64-unknown-linux-gnu` also work? I cannot seem to make it work with musl :(

**Comment by dufferzafar** [comment]
Yeah. Non Musl will work for me as well.

**Comment by extrawurst** [comment]
@dufferzafar can you please checkout the first try releasing a linux build: https://github.com/extrawurst/gitui/releases/tag/v0.1.8

**Comment by dufferzafar** [comment]
```
gitui: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory
```

**Comment by dufferzafar** [comment]
Doing the same with `lazygit`:

```
╰─❯ ldd `which lazygit`
        not a dynamic executable
```

**Comment by dufferzafar** [comment]
So I think we want statically linked binaries for linux.

**Comment by extrawurst** [comment]
ok next try, can you look at the artifact here: https://github.com/extrawurst/gitui/actions/runs/79754750

**Comment by dufferzafar** [comment]
Yeap, that worked!

**Comment by extrawurst** [comment]
ok great 👍

**Comment by extrawurst** [comment]
should be integrated in next version then

**Comment by extrawurst** [comment]
as of `v0.1.9` linux builds are part of the deployment pipeline: https://github.com/extrawurst/gitui/releases/tag/v0.1.9

**Comment by yermulnik** [comment]
Apologies for resurrecting this issue but I've got an issue with latest `gitui` (`v0.10.0`):
```
> /tmp/yz/gitui
bash: /tmp/yz/gitui: No such file or directory

> strace /tmp/yz/gitui
execve("/tmp/yz/gitui", ["/tmp/yz/gitui"], [/* 108 vars */]) = -1 ENOENT (No such file or directory)
write(2, "strace: exec: No such file or di"..., 40strace: exec: No such file or directory
) = 40
exit_group(1)                           = ?
+++ exited with 1 +++
```
`v0.9.1` works just fine.

Also `.deb` would be super useful and I think I can volunteer to test it if any.

**Comment by jugglerchris** [comment]
@yermulnik Does /tmp/yz/gitui actually exist?

Are you able to show the output of `ls -l /tmp/yz/gitui`, `ldd /tmp/yz/gitui` and `file /tmp/yz/gitui` please?

**Comment by jugglerchris** [comment]
This sounds like #259 too.

**Comment by jugglerchris** [comment]
I can reproduce this - I'll put the answers to the above on #259.

**Comment by yermulnik** [comment]
@jugglerchris 
```
> ls -l /tmp/yz/gitui
-rwxr-xr-x 1 yz docker 2277240 Aug 29 20:35 /tmp/yz/gitui

> ldd /tmp/yz/gitui
        linux-vdso.so.1 =>  (0x00007ffc7094d000)
        libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007f1166c1a000)
        libXau.so.6 => /usr/lib/x86_64-linux-gnu/libXau.so.6 (0x00007f1166a16000)
        libXdmcp.so.6 => /usr/lib/x86_64-linux-gnu/libXdmcp.so.6 (0x00007f1166810000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f1166446000)
        /lib/ld64.so.1 => /lib64/ld-linux-x86-64.so.2 (0x00007f1166e3c000)

> file /tmp/yz/gitui
/tmp/yz/gitui: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib/ld64.so.1, BuildID[sha1]=0ead58df2438331cfba31c46d33722915f567768, stripped
```

> I can reproduce this - I'll put the answers to the above on #259.

Thank you. I'll take a look.
