### ISSUE TITLE
Impossible to ctrl-click hyperlinks in commit message in some terminals

### ISSUE THREAD

**Issue by werman** [extrawurst/gitui#182]
**Describe the bug**

It's impossible to ctrl-click hyperlinks in commit message - it looks like the content of terminal is always updating, there is a brief moment the link is highlighted, however the ctrl-click never works.

I'm able to ctrl-click in `guake` and not able in vscode's built-in and in `kitty`. Didn't test other ones.

For me the issue's severity is low.

**To Reproduce**

Have a commit with a hyperlink and a vscode's built-in or `kitty` terminal.

**Expected behavior**

User should be able to ctrl-click the link.

**Screenshots**

![gitui-unclickable-link](https://user-images.githubusercontent.com/3993671/86814789-8b1a5500-c08a-11ea-869e-a70220f59757.gif)

**Context (please complete the following information):**
 - OS/Distro + Version: Arch Linux
 - GitUI Version 0.8.1
 - Rust version: 1.44.1

**Comment by extrawurst** [comment]
weird I cannot reproduce this on macOs using iTerm2:
![Screenflick Movie 46](https://user-images.githubusercontent.com/776816/86818847-2dd0d480-c087-11ea-8543-aae1d3e1641b.gif)

I might need support on this one by someone with a linux machine 🤔
