### ISSUE TITLE
Interactive reverts

### ISSUE THREAD

**Issue by non-descriptive** [extrawurst/gitui#1824]
**Is your feature request related to a problem? Please describe.**
Sometimes it's useful to revert just some line that was already commited and persist in the tree. I wish there was a mechanism to revert certain lines/hunks in a similar way we do with staging - in code view mode in current commit select some line and revert just those lines. 

**Describe the solution you'd like**
I didn't find any similar git functional, so it's gonna be a bit tricky to implement. We can simulate such behaviour doing
`git revert HASH --no-commit/-n` to make staged revert, then unstage everything and stage only lines we wanted to revert and discard everything else. 
The other tricky issue when revert triggers conflict, but in general we can just force it to take whole reverted version or specify it somehow like `--mainline/-m` or `--strategy/-X` option of `git-revert` does. 

**Describe alternatives you've considered**
Alternatively we can try and pop some interactive revert mechanism which also will show result of `git revert -n` with all the conflicts for the __*current file*__ and allow quickly stage all necessary stage.

I haven't seen anyone implemented mechanisms like this, so no references for this feature are existent.

**Comment by extrawurst** [comment]
You can revert a commit and then selectively manage what you actually want to stage and commit right?

**Comment by non-descriptive** [comment]
Over two tabs if no conflicts occured, yes, if we speaking about `gitui` only. `Shift` + `D` on specidied commit, unstage everything and stage lines we want. 
If conflict occured we need to pop out and solve the it and after that we can stage lines we want.

Also noticed that if we trigger revert and discard all changes pending revert will be still in progress. Were there an issue about it, or should I make one?

**Comment by extrawurst** [comment]
> Were there an issue about it, or should I make one?

technically a git repo can still be in dirty state even though all changes were reverted. the `abort revert` command is available in that case.
