### ISSUE TITLE
Use `popup_up` and `popup_down` keys in the Log search popup

### ISSUE THREAD

**Issue by auvred** [extrawurst/gitui#1831]
**Describe the bug**
The `LogSearchPopupComponent` was introduced in the https://github.com/extrawurst/gitui/pull/1800. But for some reason in this popup `move_up` and `move_down` keys are used for navigation instead of `popup_up` and `popup_down`. This may conflict with vim-like key bindings, e.g I want to type `j` but this just moves selection down

**To Reproduce**
1. Go to 'Log'
2. Press `f`

**Expected behavior**
It would be great to be able to type search query even if `move_up` and `move_down` are remapped to `j` and `k`

**Screenshots**
![image](https://github.com/extrawurst/gitui/assets/61150013/713a001e-615f-4ed5-b621-1f0874917a27)
**Additional context**

https://github.com/extrawurst/gitui/blob/7558d25e257fac9572582dce7e2aec39b69be2b0/src/components/log_search_popup.rs#L373-L380

The `FuzzyFindPopup` uses `popup_up` and `popup_down` for such movements:
https://github.com/extrawurst/gitui/blob/7558d25e257fac9572582dce7e2aec39b69be2b0/src/components/fuzzy_find_popup.rs#L362-L372

Also I guess the `navigate_tree` should be changed to `scroll_popup`, because only vertical scrolling is supported there
https://github.com/extrawurst/gitui/blob/7558d25e257fac9572582dce7e2aec39b69be2b0/src/components/log_search_popup.rs#L331

I will be glad to submit a PR if this is not intentional behavior :)

**Comment by extrawurst** [comment]
very good catch, thank you!
