### ISSUE TITLE
open editor running inside vscode is broken

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#184]
it simply shows an empty file:
![Screenflick Movie 47](https://user-images.githubusercontent.com/776816/86819665-442b6000-c088-11ea-93ea-8b60de5b320b.gif)

opening same file through running `gitui` in terminal works.
the editor functionality to edit commit messages is not affected.

related to #173

**Comment by jonstodle** [comment]
The path at the bottom of Vim looks correct. But it does say _New DIRECTORY_, which might be a clue. (I think Vim shows _New DIRECTORY_ if you "open" a non-existant location.

Could it be that VS Code somehow sets a different work directory for vim, than the repository root? And that way vim tries to open a different location?

**Comment by extrawurst** [comment]
Ok it actually turns out not to be limited to vscode, simply run `gitui` in a subfolder of your repo and it will stop working
