### ISSUE TITLE
Unable to switch to branches with names containing a '/' character

### ISSUE THREAD

**Issue by strandloper** [extrawurst/gitui#1851]
**Describe the bug**
Since updating to version 0.24.0 this morning I am unable to use the switch branch feature in gitui.

**To Reproduce**
1. Press '1' to go to the Status tab then 'b' to view Branches.
2. Scroll up or down to select a different local branch whose name contains a '/' character then press Enter to switch to that branch.
3. A switch branch error stating "git error:cannot locate local branch '23.05.1'; class=Reference (4); code=NotFound (-3)" is displayed
4. Note that while the name of the branch is "release/23.05.1" the error message has dropped the "release/" portion.
5. Attempting the same for a branch name that does not contain a '/' character, e.g. "Test" does not display an error and the branch is switched.

**Expected behavior**
I should be able to switch between branches whether they contain a '/' character or not.

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 11 Version 22H2 (OS Build 22521.2134)
 - GitUI Version: 0.24.0
 - Rust version: N/A (installed from gitui.msi)

**Comment by extrawurst** [comment]
its introduced by 514e8f0175245c06a7f1634e343abf0bc248f393 for #1809 by @lightsnowball

**Comment by extrawurst** [comment]
its fixed on master. hope to cut a patch release the coming days. want to get the CI pipeline improvements in before though (see #1852)

**Comment by extrawurst** [comment]
@paul-uz feel free to revert back to 0.23 for the time being, it does not have this problem

**Comment by paul-uz** [comment]
@extrawurst I tried, but I'm using `brew` and `brew install gitui@0.23.0` doesn't work

**Comment by extrawurst** [comment]
Here are the binaries: https://github.com/extrawurst/gitui/releases/tag/v0.23.0

**Comment by extrawurst** [comment]
fixed in https://github.com/extrawurst/gitui/releases/tag/v0.24.1

**Comment by paul-uz** [comment]
@extrawurst sorry to be a pain, it's not coming through on Brew

**Comment by extrawurst** [comment]
see https://github.com/Homebrew/homebrew-core/pull/140883

**Comment by paul-uz** [comment]
I'm looking at the link, but I don't understand what you mean, I am unable to upgrade gitui via brew

**Comment by extrawurst** [comment]
its merged, its not in my hands how long the angels of caching take for it to reach users :)
