### ISSUE TITLE
Cannot switch to a branch with a `/` in the name

### ISSUE THREAD

**Issue by jamesrampton** [extrawurst/gitui#1858]
**Describe the bug**
Cannot switch to a branch with a `/` in the name.

**To Reproduce**
1. Have a branch with a `/` in its name
2. Use `b` to pull up the branch menu
3. Hit `enter` on said branch

**Expected behavior**
Should be able to switch to this branch

**Screenshots**
<img width="2019" alt="Screenshot 2023-08-29 at 16 19 37" src="https://github.com/extrawurst/gitui/assets/1833713/34f5f8e4-6d0f-4eb4-9148-594e3d922976">

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS 13.5`
 - GitUI Version: `0.24.0`
 - Rust version: `1.72`

**Additional context**
Switching to this branch with `git checkout` does not fail.

**Comment by extrawurst** [comment]
Duplicate of #1851

**Comment by jamesrampton** [comment]
Oops. Sorry for the noise.

**Comment by extrawurst** [comment]
fixed in https://github.com/extrawurst/gitui/releases/tag/v0.24.1
