### ISSUE TITLE
Cannot checkout branch with a sub folder prefix

### ISSUE THREAD

**Issue by paul-uz** [extrawurst/gitui#1861]
We use gitflow, so we have branches prefixed with `feature/`, `bugfix/` etc

GitUI cannot checkout these out, locally or remotely, see image below.

<img width="1041" alt="Screenshot 2023-08-30 at 13 14 13" src="https://github.com/extrawurst/gitui/assets/73826774/0dd488bb-650f-4e71-8dba-26edced6138b">

**Comment by paul-uz** [comment]
Nvm, dupe of https://github.com/extrawurst/gitui/issues/1851

**Comment by extrawurst** [comment]
fixed in https://github.com/extrawurst/gitui/releases/tag/v0.24.1
