### ISSUE TITLE
The log tab doesn't update the commit history when branches are checked out.

### ISSUE THREAD

**Issue by LuarRaNa** [extrawurst/gitui#1862]
**Describe the bug**
Tab: The log does not update when branches are checked out, it seems that it only appends the commit history and does not update the view.

**To Reproduce**
1. Go to Log tab.
2. Checkout a branch.
3. Repeat step 2 a few times.

**Expected behavior**
Log updates and shows the correct commit history.

**Screenshots**
https://github.com/extrawurst/gitui/assets/67846413/2d436a10-0934-4068-9b16-5d1b6f46186f

**Context (please complete the following information):**
 - `macOS 13.5.1`
 - `0.24.1`
 - `wezterm 20230712-072601-f4abf8fd`

**Additional context**

**Comment by extrawurst** [comment]
please check `v0.24.2` release
