### ISSUE TITLE
file history does not refresh

### ISSUE THREAD

**Issue by nbigaouette** [extrawurst/gitui#1883]
**Describe the bug**

When the history changes outside of `gitui`, the `Log [2]` tab does not get refreshed. This seems to be a regression in 0.24.0.

**To Reproduce**
1. Open a repo in `gitui`
2. Change git history, f.e. by rebasing and changing commits.
3. Visit the `Log [2]` tab
4. History is the same as before step 2.

**Expected behavior**
The git history should be refreshed, i.e. it should show the latest repo state.

**Context (please complete the following information):**
 - macOS 13.5
 - GitUI Version 0.24.0

**Additional context**

Might be a generalization of #1879.

**Comment by extrawurst** [comment]
Can you try 0.24.2 please

**Comment by extrawurst** [comment]
Potentially a dup of #1866

**Comment by nbigaouette** [comment]
Tried 0.24.2 and issue is absent. Thanks! 👍
