### ISSUE TITLE
make diff line-break visualisation "¶" optional

### ISSUE THREAD

**Issue by laktak** [extrawurst/gitui#1894]
The commit ["visualize empty line in diff better"](https://github.com/extrawurst/gitui/commit/6ec647710d48a2e80ab4ec2b1a2a6c878e7876d9) (also #1359) added a feature that shows

> ¶

for blank lines.

Unfortunately this distracts me when reading code and while I understand why you added it, I really would like to turn it off.

AFAIK there is no configuration for this at the moment - would it be possible to add this as a theme option?

https://xkcd.com/1172/ ;)

**Comment by gorentbarak** [comment]
There are already pull requests for this. Maybe you could close this issue?

**Comment by extrawurst** [comment]
i wont close an issue as long as the fix is not merged
