### ISSUE TITLE
git error:failed to set hostkey preference

### ISSUE THREAD

**Issue by imwubing** [extrawurst/gitui#1897]
git error:failed to set hostkey preference: The requested method(s) are not currently supported; class=Ssh (23)

gitui 0.24.2

![image](https://github.com/extrawurst/gitui/assets/24838751/0aeeece4-ced3-404e-b82e-693361cba719)

**Comment by extrawurst** [comment]
looks like an upstream issue: https://github.com/libgit2/libgit2/issues/6612

**Comment by ogios** [comment]
same issue
![image](https://github.com/extrawurst/gitui/assets/96933655/d2351cce-828c-40a3-aa34-a3a665c538d5)

**Comment by extrawurst** [comment]
See above, ist a known issue
