### ISSUE TITLE
New ignored file didn't append to a new line

### ISSUE THREAD

**Issue by leesiongchan** [extrawurst/gitui#191]
**Describe the bug**
New ignored file didn't append to a new line

**To Reproduce**
1. Click 'i' on file
4. See .gitignore

**Expected behavior**
Should append to a new line

**Screenshots**
![image](https://user-images.githubusercontent.com/324418/87107477-685a8d00-c292-11ea-90d8-b721eb370e71.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Manjaro
 - GitUI Version 0.8.1
 - Rust version: 1.44

**Additional context**

**Comment by extrawurst** [comment]
hi @leesiongchan thanks for reporting this! unfortunately I cannot reproduce it so far. the potential failure surface is rather small: a problem in writing to the `.gitignore` file. anyway what you describe is not even 'crashing' the app which means the ignore method does not even literally fail.

I guess I need more help to reproduce it: what folder of your repo did u run gitui in? what file did you try to ignore. 
And can you please run `gitui` with logging enabled and provide it: (see https://github.com/extrawurst/gitui#diagnostics)

**Comment by leesiongchan** [comment]
Do you have empty line at last in .gitignore? Try removing it, I am able to reproduce it if my .gitignore isn't end with an empty line

**Comment by extrawurst** [comment]
@leesiongchan now I realise what you mean! thanks! 🙏
