### ISSUE TITLE
Compact Treeview

### ISSUE THREAD

**Issue by thezealousfool** [extrawurst/gitui#192]
Thanks for building this tool.

When files changed are down in the tree hierarchy, having branching of every folder in the way of the file is unnecessary and a little annoying.

For example (android project),
![Screen Shot 2020-07-10 at 7 50 40 PM](https://user-images.githubusercontent.com/20724374/87211335-09733300-c2e7-11ea-9ed1-16f047bd559a.png)
in the example above, `app/src/main` can be combined together in one line instead of having `app`, `src` and `main` in 3 different lines.

**Comment by extrawurst** [comment]
Hi @thezealousfool thanks for your interest in *gitui* - I like the proposal

**Comment by WizardOhio24** [comment]
I've been working on this and managed to produce what I think you're after.  Here's a screenshot.
![Working_Screenshot](https://user-images.githubusercontent.com/52405405/94132586-664aa800-fe57-11ea-9f97-b48b48f48392.png)

I'll put in a pull request soon, when I have time.

**Comment by extrawurst** [comment]
that looks pretty cool! ❤️
