### ISSUE TITLE
Not able to commit with predefined (template) commit message

### ISSUE THREAD

**Issue by magical-heyrovsky** [extrawurst/gitui#1921]
**Describe the bug**

The recording below demonstrates the problem.

I have a commit message template in a gitconfig like this:

```
[commit]                                                                           
    template = ~/.config/git/custom-template
```
and gitui can also read it. So far everything as expected. When I try to commit something (`c`) it opens up the text area with my predefined commit message. But I am not able to immediately commit (`⏎`) because the option is greyed out. I need to remove or add a character in order to be able to commit.

**To Reproduce**
1. Try to commit a change (`c`).
2. See the predefined commit message in the text area.
3. Try to commit (`⏎`).
4.  It doesn't work because the option is greyed out.

**Expected behavior**
1. Try to commit a change (`c`).
2. See the predefined commit message in the text area.
3. Try to commit (`⏎`).
4. Changes are commited.

**Screenshots**

[Screencast.webm](https://github.com/extrawurst/gitui/assets/101060148/db07d678-ea39-482b-92b3-fc5134910be8)

**Context (please complete the following information):**
 - OS/Distro + Version: Ubuntu 23.04
 - GitUI Version 0.24.3
 - Rust version: not installed

**Comment by remique** [comment]
I believe this might have been an intended behavior, with intention that git templates serve as templates. 
```rust
// impl CommitComponent
fn can_commit(&self) -> bool {
	!self.is_empty() && self.is_changed()
}

fn is_changed(&self) -> bool {
	Some(self.input.get_text().trim())
		!= self.commit_template.as_ref().map(|s| s.trim())
}
```
Not sure whether it should stay this way or allow no changes if `commit_template` is not `None`. If latter, should be a pretty easy fix.

**Comment by extrawurst** [comment]
i guess its fair to commit the template unchanged. shell will allow the same i assume

**Comment by Krismix1** [comment]
> ... shell will allow the same i assume

I wanted to tackle this issue, so I tested the behavior of the git CLI. It does not allow the commit with the template message, outputting "Aborting commit; you did not edit the message." ([source](https://github.com/git/git/blob/3e0d3cd5c7def4808247caf168e17f2bbf47892b/builtin/commit.c#L1810))

Nevertheless, I went ahead and created a PR. If the intent is still to match the behavior of the git CLI, it can be rejected

**Comment by extrawurst** [comment]
no lets stay consistent with the shell then. @magical-heyrovsky if the CLI allows empty commit messages then feel free to open an issue to fix gitui be compatible
