### ISSUE TITLE
Cannot modify line-break

### ISSUE THREAD

**Issue by cgahr** [extrawurst/gitui#1935]
**Describe the bug**
I want to modify/remove the line break, however it remains as its default character.

**To Reproduce**
1. move the following config to the config dir.
1. run `gitui`

I changed to color of `selection_bg` to test that the config is being used, its a bright cyan color:
```ron
(
  selection_bg: Rgb(0,255,255),
  line_break: Some(""),
)
```

**Expected behavior**
The line-break symbol should not be there (compare screenshot).

**Screenshots**
![grafik](https://github.com/extrawurst/gitui/assets/26804763/a3542825-975b-4f0c-a5d5-f7560edfc37e)

**Context (please complete the following information):**
 - OS/Distro + Version: `Ubuntu 22.04.3 LTS`
 - GitUI Version: `gitui 0.24.3`
 - Rust version: - (installed via nixpkgs-unstable)

**Comment by extrawurst** [comment]
this was done recently: https://github.com/extrawurst/gitui/issues/1894 - its marked to release as `0.25`

**Comment by cgahr** [comment]
Ahh, didn't realize it's not released yet!
