### ISSUE TITLE
add export variable for themes to used

### ISSUE THREAD

**Issue by DinkyTrady** [extrawurst/gitui#1994]
**Is your feature request related to a problem? Please describe.**
i want to use custom theme without `-t theme_name` or aliases on my `config.fish`

**Describe the solution you'd like**
it will be great if gitui had export variable name like bat
``` bash
export BAT_THEME="tokyonight" # bash/zsh

# gitui for example
export GITUI_THEME="tokyonight"
```
```fish
set -gx BAT_THEME tokyonight # fish

# gitui for example
set -gx GITUI_THEME tokyonight
```

**Describe alternatives you've considered**
or adding new variable on `theme_custom.ron` like
set_default = true

**Additional context**
since i'm using LazyVim with custom keybindings it that will open gitui but i cant to use subcommands

**Comment by extrawurst** [comment]
You don’t need to use the -t arg if you overwrite the default theme like described here: https://github.com/extrawurst/gitui/blob/master/THEMES.md

**Comment by DinkyTrady** [comment]
oh! i'm not reading seriously 😅
close the issue
