### ISSUE TITLE
Brew formula errors when installing `gitui` on Linux(brew) 

### ISSUE THREAD

**Issue by studoot** [extrawurst/gitui#200]
**To Reproduce**
1. Type the command `brew install gitui` on a Linux box (Ubuntu 18.04 here) with [Linuxbrew](https://docs.brew.sh/Homebrew-on-Linux) installed.
2. See the following error output:
    ```
    libiconv: is not needed on Linux, where iconv.h is provided by glibc
    Error: gitui: An unsatisfied requirement failed this build.
    ```

**Expected behavior**
`gitui` should be built from source & installed into Linuxbrew.

**Context (please complete the following information):**
 - Ubuntu 18.04 (running on Windows Subsystem for Linux) & Ubuntu 20.04 VM.
 - GitUI 0.8.1

**Comment by studoot** [comment]
Argh - I guess I should have reported this to Homebrew-Core, not here. Sorry!

**Comment by peaceiris** [comment]
Fixed in https://github.com/Homebrew/linuxbrew-core/issues/22329
