### ISSUE TITLE
Syntax highlighting: Typescript files not highlighted

### ISSUE THREAD

**Issue by pmiossec** [extrawurst/gitui#2005]
**Describe the bug**

Files with `.ts` and `.tsx` files are supported.

**To Reproduce**
1. Go to 'Files' tab
2. Select a typescript file with `.ts` extension
3. See that there is no syntax highlighting (but working with other type of files)

**Expected behavior**

a typescript file with `.ts` extension  is  highlighted.

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 11
 - GitUI Version: 0.24.3

**Additional context**

Sorry, I know that it is maybe a https://github.com/trishume/syntect/ issue but as not being a rust developer, I won't be able to manage it rightfully.

**Comment by pmiossec** [comment]
Another tool that use the same version is working well ( https://github.com/dandavison/delta/blob/main/Cargo.toml#L41 ). So I don't know...

**Comment by extrawurst** [comment]
seems to be a syntect limitation: https://github.com/trishume/syntect/issues/447

**Comment by Aleksanaa** [comment]
> seems to be a syntect limitation: [trishume/syntect#447](https://github.com/trishume/syntect/issues/447)

But syntect isn't going to adding even more language support, and others can be added by introducing [two-face](https://crates.io/crates/two-face) (https://github.com/trishume/syntect/issues/523#issuecomment-2002063879)

**Comment by extrawurst** [comment]
Good find!
