### ISSUE TITLE
Show the whole diff for a change.

### ISSUE THREAD

**Issue by vext01** [extrawurst/gitui#203]
Long-time tig user here. Tried gitui for the first time.

**Is your feature request related to a problem? Please describe.**

I'd like to see the whole diff for a commit. Currently only sub-diffs are shown when you select a path in the change inspector.

**Describe the solution you'd like**

One way to do this might be to display diffs for directory entries, then the top-most directory would display the whole change's diff.

Thanks.

**Comment by extrawurst** [comment]
Hi @vext01, thanks for giving young `gitui` a shot. I know traditional tools support this usually but I always found it harder to read, this is gonna require a substantial refactoring, I am not gonna lie
