### ISSUE TITLE
Custom git pager / diff view

### ISSUE THREAD

**Issue by colbs255** [extrawurst/gitui#2032]
**Is your feature request related to a problem? Please describe.**
Git pagers like delta make diffs easier to view - it would be nice if gitui allowed you to provide the pager you want.

**Describe the solution you'd like**
Allow users to specify the git pager they want to use via the config file. Example: [delta](https://github.com/dandavison/delta)

**Describe alternatives you've considered**
Lazygit :P 

**Additional context**
Lazygit is doing it [here](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md)
(only thing keeping me from moving from lazygit)

**Comment by extrawurst** [comment]
dupe of #358
