### ISSUE TITLE
Impossible to configure color of title of current active block

### ISSUE THREAD

**Issue by cgahr** [extrawurst/gitui#2052]
**Describe the bug**
It is not possible to configure the color of the title of the currently active block directly. That's the orange part on the following screenshot:
![image](https://github.com/extrawurst/gitui/assets/26804763/4853becf-f50c-4887-9717-f3e6350aec96)

As far as I can tell, `gitui` use `color4` of the terminal instead.

**Expected behavior**
There should the option to configure this style element directly using the config.

**Context (please complete the following information):**
 - OS/Distro + Version: Ubuntu 22.05 LTS
 - GitUI Version 0.24.3
 - Rust version: no installed

**Additional context**

**Comment by extrawurst** [comment]
This is not a feature yet, not a bug

**Comment by cgahr** [comment]
Any pointer, which part of the code I have to touch if I want to implement this myself?

**Comment by extrawurst** [comment]
@cgahr by looking into how it would be done I saw its just this simple change, so I did it. please feel free to review it and pick up another good-first-issue

**Comment by cgahr** [comment]
Thank you so much, I'm happy it was a very small change.

I think, however, that you might have introduced a bug while implementing this, see #2056.
