### ISSUE TITLE
theme.ron is not parsed correctly

### ISSUE THREAD

**Issue by cgahr** [extrawurst/gitui#2056]
**Describe the bug**
On the current master, the `theme.ron` file is not parsed correctly and it has no effect. The log throws the following message:
```
17:21:20 [ERROR] KeysList parse error: 1:1: Expected opening `(` for struct `KeysListPatch`
```
The config was working at version `0.24.3`. It is

```ron
(
  selected_tab:Rgb(247,241,255),
  command_fg: Rgb(247,241,255),
  selection_bg: Rgb(82,80,83),
  selection_fg: Rgb(247,241,255),
  cmdbar_bg: Rgb(82,80,83),
  cmdbar_extra_lines_bg: Rgb(82,80,83),
  disabled_fg: Rgb(139,136,143),

  diff_line_add: Rgb(123,216,143),
  diff_line_delete:Rgb(252,97,141),
  diff_file_added: Rgb(123,216,143),
  diff_file_removed: Rgb(252,97,141),
  diff_file_moved: Rgb(148,138,227),
  diff_file_modified: Rgb(252,229,102),
  commit_hash: Rgb(148,138,227),
  commit_time: Rgb(253,147,83),
  commit_author: Rgb(123,216,143),
  danger_fg: Rgb(252,97,141),
  push_gauge_bg: Rgb(34,34,34),
  push_gauge_fg: Rgb(34,198,222),
  tag_fg: Rgb(148,138,227),
  branch_fg: Rgb(252,229,102),

  line_break: Some("enter"),
)
```

**To Reproduce**
1. build `gitui` from the current master 
2. set above theme 
3. start gitui

**Expected behavior**:
The `theme.ron` file should be parsed correctly and take effect.

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro + Version: Ubuntu 22.05
 - GitUI Version f1da79b4b24531bcf1caefe45de87d1824ba5876
 - Rust version: 1.75.0

**Comment by extrawurst** [comment]
@cgahr are you sure its the theme ron that break? the error message suggests that the key config is broken.

**Comment by extrawurst** [comment]
@cgahr please update to be10d90 which makes sure theme loading errors are printed into the logfile

**Comment by extrawurst** [comment]
@cgahr 

> 1. at https://github.com/extrawurst/gitui/commit/f1da79b4b24531bcf1caefe45de87d1824ba5876, gitui did not throw and error in the log file if there is an empty key_bindings.ron file

but it prints the error in the CLI, right?

> 2. it seems to me that --theme <path> does not have an effect

i have to investigate but it seems related to #2007 ?

> 3. in theme.ron, colors have to be inside Some(...) to properly take effect. Is this new?

since 2022 :) see #1367 - also checkout `THEMES.md` it should document the way to define a theme

**Comment by cgahr** [comment]
1. It only prints the error to the log file, not to CLI
2. it does seem to be similar to #2007, but at least for me, changing my theme in the default dir, properly takes effect. 
3. Good to know! In my case, it was trying to "translate" my config, but with it being write-protected it obviously failed.
