### ISSUE TITLE
Tags not showing in log

### ISSUE THREAD

**Issue by albertogg** [extrawurst/gitui#206]
Hi, this is a very cool TUI, thank you. I was testing it out and found myself needing to look at which commits are tagged within the Log. It seems that this is not happening despite seeing that the feature was implemented in #47. I haven't look at the code.

**Expected behavior**
Seeing the tag next to the commit message.

**Screenshots**
 
Here are a couple of screenshots. One is with GitUp showing the tag in the commit, and the second one is the Log on GitUI.
![Screen Shot 2020-07-19 at 12 16 05 PM](https://user-images.githubusercontent.com/451539/87879574-bfaadc80-c9b9-11ea-850c-5f489e42bf0f.png)
![Screen Shot 2020-07-19 at 12 16 24 PM](https://user-images.githubusercontent.com/451539/87879575-c20d3680-c9b9-11ea-9dee-a790c6f4c7ec.png)

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS 10.14.6`
 - GitUI Version: `0.8.1`
 - Rust version: `1.42`

**Comment by extrawurst** [comment]
@albertogg thanks for reporting this. I cannot reproduce the problem for tags pointing to commits in the current branch. Is the repo you experience the issue open source to reproduce?

**Comment by albertogg** [comment]
Thanks, for the quick response... yes, it is. It's this one https://github.com/qmk/qmk_firmware.

**Comment by extrawurst** [comment]
So turns out to be an issue in the library I am using to interact with the git repo: https://libgit2.org - I am working on a small repro for them to look into.

**Comment by albertogg** [comment]
ha, Interesting. I see that you already put the work rust-lang/git2-rs#594. Thanks! let's see how this goes.

**Comment by extrawurst** [comment]
got it. aside from the linked ticket my code still had a shortcoming in dealing with tags that are directly pointing to the commit and tags that tage a detour, weird stuff happening in git sometimes... anyway looks better huh:

<img width="1392" alt="image" src="https://user-images.githubusercontent.com/776816/87989057-a9983b80-cae1-11ea-94fd-e36ddeec9f9c.png">

**Comment by albertogg** [comment]
Nice, I can imagine. very fast turn around. thanks!

**Comment by extrawurst** [comment]
@albertogg btw. this is what confused me in the base c++ lib: https://github.com/libgit2/libgit2/issues/5586

**Comment by albertogg** [comment]
I see, If you don't annotate the tag they will be "lightweight", that behavior seems odd, I would have never thought of that. But I don't completely understand... is the rust library using the c++ library underneath?

**Comment by extrawurst** [comment]
@albertogg exactly, libgit2 is the base library powering gitlab and gitkraken and git2-rs is the rust safety wrapper that I am using
