### ISSUE TITLE
Squash commits

### ISSUE THREAD

**Issue by mbhall88** [extrawurst/gitui#209]
I regularly squash my last *n* commits.

**Describe the solution you'd like**
It would be really cool if you could select commits in the Log screen and squash the selected commits.

**Describe alternatives you've considered**
Using the git CLI (which is fine)

**Comment by extrawurst** [comment]
@mbhall88 thanks for your interest in *gitui*. this and interactive rebase in general is on my list: https://github.com/extrawurst/gitui/issues/32
