### ISSUE TITLE
push failed: git error:invalid or unknown remote ssh hostkey; class=Ssh (23); code=Certificate (-17)

### ISSUE THREAD

**Issue by towry** [extrawurst/gitui#2095]
**Describe the bug**

Can not do basic push operation.

**To Reproduce**
1. press `p` to push.

**Expected behavior**
Push should be working as running command `git push origin master`.

**Screenshots**

<img width="1005" alt="截屏2024-02-23 09 52 25" src="https://github.com/extrawurst/gitui/assets/8279858/e12c4031-91ad-4a11-b2d8-264800dd171d">

**Context (please complete the following information):**
 - OS/Distro + Version: 13.3 (22E252)
 - GitUI Version 0.25
 - Rust version: rustc 1.71.0

**Additional context**

`~/.ssh/config`:

```
Host github.com
  Hostname ssh.github.com
  Port 443
```

`~/.ssh/known_hosts`:
<img width="335" alt="截屏2024-02-23 09 55 35" src="https://github.com/extrawurst/gitui/assets/8279858/0692611f-b572-4b69-9d67-079583114306">

**Comment by extrawurst** [comment]
ssh/config is currently not considered by upstream, there is already an issue for this: #2096

**Comment by jerviscui** [comment]
I resolved the issue by following these steps.

1. Remove the configuration from the `.ssh/config` file:

    ```
    Host github.com
        ...
    ```

2. Back up and delete `.ssh/known_hosts`,
3. Test the connection; `known_hosts` will be regenerated,

    ```
    ssh -T git@github.com
    ```

4. Start the SSH agent; run PowerShell as an administrator:

    ```
    Get-Service ssh-agent | Set-Service -StartupType Automatic; Start-Service ssh-agent
    ```

5. Add the private key:

    ```
    ssh-add $env:USERPROFILE\.ssh\id_ed25519
    ```

6. Add the contents of `id_ed25519.pub` to your GitHub SSH keys.
