### ISSUE TITLE
Going to Files from Details -> Inspect or Diff is not working

### ISSUE THREAD

**Issue by VasilisManol** [extrawurst/gitui#2114]
**Describe the bug**
Going to Files Tab from Details or Diff view in Log is failing

**To Reproduce**
1. Go to 'Log' Tab.
2. Select a commit from history and press 'Enter' to go to Details and then 'Right' Inspect.
3. The option to go to Files with F is presented.
4. Pressing 'F' has no effect.
5. Selecting a file and pressing 'Right' again to diff will have the same issue. Files option is presented but nothing happens.

**Expected behavior**
I expected to go to Files Tab showing the selected file and the commit revision inspecting.

**Context (please complete the following information):**
 - Ubuntu 23.10 
 - GitUI 0.25.1

**Additional context**
Otherwise Files tab works as expected. Tested on Alacritty and Foot.

**Comment by extrawurst** [comment]
I suspect that this is just commands showing up in the cmd bar that are unavailable in these circumstances

**Comment by VasilisManol** [comment]
I haven't checked. It would be a cool feature though to have them available. Like you are checking a specific commit in the log tab and then you jump to files to inspect a changed file at that commit.

**Comment by martihomssoler** [comment]
Hey, as per discussed in the discord server. I found the commit that removed the functionality ( [7dcf93e ](https://github.com/extrawurst/gitui/commit/7dcf93e0b279a7f09a98b44fee88430afa09e149) ). I will fix it and get back to you with a proper PR.
