### ISSUE TITLE
Commit messages that begin with a hash (#) are ignored

### ISSUE THREAD

**Issue by cleavera** [extrawurst/gitui#2136]
**Describe the bug**
When using gitui to create a commit, commit messages that start with a # are ignored. This is the default behaviour of git however setting the config value `core.commentChar` makes the commit message work when using git on the command line, however commiting through gitui the commit message is still stripped out

**To Reproduce**
1. Go to a project and make some changes
2. Open git UI
3. Commit the changes
4. In the commit message dialog, use the message "#5123 test"
5. Go to the log and the message for that commit is blank
6. Make more changes
7. Run `git config --global core.commentChar ";"``
8. Repeat the above steps
9. Same outcome

**Expected behavior**
The behaviour should match commiting with the command line, where changing the core.commentChar is respected

**Screenshots**
![image](https://github.com/extrawurst/gitui/assets/10167467/5313bce9-ffc1-4351-9a65-a82b791a839f)
![image](https://github.com/extrawurst/gitui/assets/10167467/60d2fb99-67a5-47ac-85ce-534177a6ac1f)
![image](https://github.com/extrawurst/gitui/assets/10167467/45456c3d-7147-4f00-a3c1-1b05b8699019)

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 11, 23h2, 22631.3296
 - GitUI Version: 0.24.3
 - Rust version: 1.75.0

**Comment by extrawurst** [comment]
should be fairly simple to implement: see https://github.com/extrawurst/gitui/commit/1a1c948020be636d2df5dde145a2189b9e6d50ae

add `commit_message_prettify` into `asyncgit` and handle the config loading and forwarding of the configured comment-char

**Comment by cleavera** [comment]
Thanks very much @extrawurst and @Concelare
