### ISSUE TITLE
Move to (un)staged when the current selection is empty

### ISSUE THREAD

**Issue by jonstodle** [extrawurst/gitui#215]
**Is your feature request related to a problem? Please describe.**
When using the _Stage all_ command (or just when all items have been (un)staged. The focus should switch to the other view. There's isn't really a reason for the focus to remain in _Unstaged changes_, when all the files have been moved to _Staged changes_ (and vice versa).

**Describe the solution you'd like**
When using _Stage all_ or when all files have been moved from or to the "stage", the focus should change to the relevant area where there are files present.

**Describe alternatives you've considered**
None

**Additional context**
...

**Comment by extrawurst** [comment]
Hey @jonstodle that's a good idea! Are you up for it? :)

**Comment by jonstodle** [comment]
Yes
