### ISSUE TITLE
Allow reset to branch in branches view

### ISSUE THREAD

**Issue by OmegaJak** [extrawurst/gitui#2170]
**Is your feature request related to a problem? Please describe.**
As part of my workflow (squashing commits locally before merging), I need to leave gitui to run a command like `git reset --soft master`. While possible to do in the commits/log view, it is not always easy to find the desired branch as the target for resetting. 

**Describe the solution you'd like**
I would suggest that it be possible to reset directly from the branches view. Not sure what hotkey is best since `Shift+R` is already taken in that view (and so is 'r'), but that would make it consistent with the log view. Hitting the hotkey to reset should bring up the same menu as was added for #1500 and function the same way, just targeting the select branch instead of a specific commit.

**Describe alternatives you've considered**
Maybe this could be mitigated by making it easier to find branches in the log view (I couldn't find a way to in the `find` dialogue). But that seems less direct than adding a way in the branch view itself.

**Additional context**
Thanks for the awesome tool!

**Comment by extrawurst** [comment]
this is fairly easy to integrate

**Comment by OmegaJak** [comment]
Excellent, thank you!
