### ISSUE TITLE
List Remotes Popup

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#2172]
Currently we can not list the available remotes, add, rename or remove them.

From the `BranchListPopup` we should allow opening a popup that provides that functionality.

Mockup of this popup:
```
┌Remotes─────┐
│origin      │
│foo         │
│..          │   
│Details─────│
│name: origin│
│url: git:...│
└────────────┘
Scroll [↑↓] Fetch [⇧F] Edit [e] Add [a] Remove [r]
```

Other popups are good ways for inspiration on how to do this e.g `SubmodulesListPopup`

**Comment by ADTmux** [comment]
Hey, could I work on this?

**Comment by extrawurst** [comment]
Absolutely

**Comment by extrawurst** [comment]
Please join our discord for easier communication: https://discord.gg/d3nETBB4

**Comment by remique** [comment]
Hey @ADTmux, just wondering if you are still working on this?

**Comment by asier-paz** [comment]
Same question here. Is anybody working on this as of now?

**Comment by extrawurst** [comment]
Nope. Feel free to claim it. Also join our discord for coordination if you like

**Comment by robin-thoene** [comment]
Hey, just to be transparent: I started working on it now as discussed via Discord.
