### ISSUE TITLE
Allow opening files from gitui from within the parent process rather than spawning a new one with vim

### ISSUE THREAD

**Issue by piersolenski** [extrawurst/gitui#2179]
A common work flow is to use gitui from within vim, using via a floating terminal window, or dedicated plugin, such as https://github.com/is0n/fm-nvim.

When opening files from within gitui, it would be great if it could use the parent instance of vim could be used, rather than spawning a new instance of vim within the window.

This is something [lazygit](https://github.com/jesseduffield/lazygit) supports via the `nvim-remote` setting, so it would be awesome to have feature parity.

https://github.com/kdheepak/lazygit.nvim/issues/22

**Comment by extrawurst** [comment]
so its basically about adding a configuration of what program is spawned when triggering an `edit`?

**Comment by piersolenski** [comment]
Yes, then it would work in the same manner that Lazygit does it 👌

**Comment by piersolenski** [comment]
In the end I achieved this with https://github.com/willothy/flatten.nvim

**Comment by gogongxt** [comment]
Hello. How do you do that with flatten.nvim plugin. I install the plugin and gitui can open file in neovim normally but the gitui terminal will be blocked and i must ctrl-c to close it and open gitui again. Thanks if you can reply this issue.  @piersolenski

**Comment by piersolenski** [comment]
These are the relevant parts from my config for how I do it using https://github.com/willothy/flatten.nvim in combination with https://github.com/akinsho/toggleterm.nvim

```lua
return {
	"willothy/flatten.nvim",
	opts = function()
		return {
			window = {
				open = "alternate",
			},
		}
	end,
}
```

```lua
-- Terminal management
return {
	"akinsho/toggleterm.nvim",
	config = function() -- Default terminal
		local keymap = vim.keymap.set

		require("toggleterm").setup({
			-- size can be a number or function which is passed the current terminal
			size = function(term)
				if term.direction == "horizontal" then
					return vim.o.lines * 0.5
				elseif term.direction == "vertical" then
					return vim.o.columns * 0.5
				end
			end,
			direction = "horizontal",
			float_opts = {
				width = function()
					return math.floor(vim.o.columns * 0.62)
				end,
				height = function()
					return math.floor(vim.o.lines * 0.62)
				end,
			},
			open_mapping = [[<c-t>]],
			highlights = { FloatBorder = { link = "FloatBorder" } },
			start_in_insert = true,
			insert_mappings = true,
			shade_terminals = false,
		})

		-- Floating terminal
		local Terminal = require("toggleterm.terminal").Terminal

		-- GitUI
		local gitui = Terminal:new({
			cmd = "gitui",
			hidden = true,
			direction = "float",
			float_opts = {
				width = function()
					return math.floor(vim.o.columns * 0.92)
				end,
				height = function()
					return math.floor(vim.o.lines * 0.92)
				end,
			},
		})

		local function toggle_gitui()
			gitui:toggle()
		end

		keymap("n", "<leader>gg", toggle_gitui, { silent = true, desc = "GitUI" })
	end,
}
```
