### ISSUE TITLE
gitui pulls a yanked dependency when installing with cargo

### ISSUE THREAD

**Issue by 3f6a** [extrawurst/gitui#2181]
**To Reproduce**

```
$ cargo install gitui --locked
...
warning: package `backtrace v0.3.70` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
...
```

**Expected behavior**

Yanked dependencies are not good. Could the lock file be updated to remove this yanked version?

**Context (please complete the following information):**

```
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 9.11 (stretch)
Release:	9.11
Codename:	stretch

$ rustc --version
rustc 1.77.2 (25ef9e3d8 2024-04-09)
$ cargo --version
cargo 1.77.2 (e52e36006 2024-03-26)
```

**Comment by extrawurst** [comment]
Ugh, Yanking should be forbidden. Is that with master or the release tag?

**Comment by extrawurst** [comment]
the yanked `backtrace` did not contain any security problem but raised the MSRV on windows (no idea why this needed to be yanked). so you can safely go with that build for now. i will release a new version soon from master where this is already updated
