### ISSUE TITLE
Vim-like navigation

### ISSUE THREAD

**Issue by jabra98** [extrawurst/gitui#220]
Would be cool if it was possible to navigate with the h,j,k,l keys. I changed the bindings inside the src/keys.rs file and it seems to work just fine (rebound 'h' for help to '?').

**Comment by jonstodle** [comment]
This relates to #57

**Comment by extrawurst** [comment]
yeah this is in the pipeline 👍

**Comment by Splode** [comment]
Would love to see vim-style navigation supported by default, as well.

**Comment by extrawurst** [comment]
> Would love to see vim-style navigation supported by default, as well.

Supported via https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md

**Comment by Splode** [comment]
> 
> 
> > Would love to see vim-style navigation supported by default, as well.
> 
> Supported via https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md

Brilliant, thanks!
