### ISSUE TITLE
Add --version cli argument handling

### ISSUE THREAD

**Issue by MuAlphaOmegaEpsilon** [extrawurst/gitui#221]
Since `gitui` development is really fast right now, it is especially useful to be able to quickly track down the current version I have installed.
I was expecting to simply launch `gitui --version` and receive immediately back on the prompt the version number (and maybe the commit SHA?) related to the gitui version running.

Please, would you consider adding the `--version` handling?

**Comment by extrawurst** [comment]
@MuAlphaOmegaEpsilon did you try it at all? It is implemented already since https://github.com/extrawurst/gitui/releases/tag/v0.5.0

```
gitui --version
gitui 0.9.0
```

also see:
```
gitui --help
gitui 0.9.0
Stephan Dilly <dilly.stephan@gmail.com>
blazing fast terminal-ui for git

USAGE:
    gitui [FLAGS] [OPTIONS]

FLAGS:
    -h, --help       Prints help information
    -l, --logging    Stores logging output into a cache directory
    -V, --version    Prints version information

OPTIONS:
    -d, --directory <directory>    Set the working directory
```

**Comment by MuAlphaOmegaEpsilon** [comment]
@extrawurst yes I did, I suppose I had a version prior to 5.0 then. Great that it's already in!
