### ISSUE TITLE
"Bad credentials" error when pulling in gitui, works fine using `git pull`

### ISSUE THREAD

**Issue by braden-godley** [extrawurst/gitui#2216]
**Describe the bug**
When I try to push/pull using gitui, I get a "Bad credentials" error. However, I am able to perform `git push` and `git pull` without issues.

**To Reproduce**
1. Open my git repository
2. Run `gitui`
3. Press `f` to pull.
4. See error.

**Expected behavior**
I expect for it to communicate with my SSH agent to use my credentials and successfully perform the git pull/push.

**Screenshots**
Pulling in terminal:
![image](https://github.com/extrawurst/gitui/assets/70014062/608b4f61-2816-466d-afe6-661c3803bd9e)
Pulling in gitui:
![image](https://github.com/extrawurst/gitui/assets/70014062/95f05772-4e7f-49c3-92fa-88a4d6eb8631)

**Context (please complete the following information):**
 - Operating system: NixOS + 23.11.3920.25e3d4c0d359
 - Gitui Version: 0.26.1
 - Rust version: 1.77.2

**Additional context**
I am using 1Password as an SSH agent. However, I don't think that it should matter which specific SSH agent I am using. So I'm not entirely sure why this is occurring.

Additionally, I am definitely using SSH for my remote origin:
![image](https://github.com/extrawurst/gitui/assets/70014062/807386cc-3f8a-4606-ad7d-6433ccdf08a6)

Thanks for the help!

**Comment by remique** [comment]
This is possibly a duplicate of #495?

**Comment by braden-godley** [comment]
Yeah, this seems to be a problem with libssh2 as someone in that issue pointed out.
> This is largely a libssh2 issue (it doesn't parse ~/.ssh/config and is an incomplete ssh client implementation due to this). Until this is fixed (either upstream in libssh2, or by gitui dropping the offending dep), the ostensibly 'correct' workaround is:

Closing as a duplicate
