### ISSUE TITLE
allow interactive amend commit

### ISSUE THREAD

**Issue by tjhei** [extrawurst/gitui#222]
Commit learned to amend the last commit using ^a, which is awesome. Problem: it only works if you have staged changes to add (otherwise [c] commit is disabled). 
It would be great if amend works similar to git-cola, where checking "amend" puts the changes from the last commit back into "staged" so it allows staging additional hunks, unstaging parts, and then editing the message.

**Describe the solution you'd like**
Add an "amend" toggle in the status view (maybe when "staged changes" are selected).

I can provide more info how it works in git-cola if needed.

**Comment by extrawurst** [comment]
Maybe you can give more details how git-cola does this? does it effectively rollback the last commit when u amend and then you basically do a fresh commit?

**Comment by tjhei** [comment]
> Maybe you can give more details how git-cola does this? does it effectively rollback the last commit when u amend and then you basically do a fresh commit?

Certainly.

1. You enable "amend last commit":
![image](https://user-images.githubusercontent.com/1531285/89741032-d776fd00-da5b-11ea-8b6a-2950c4ee7596.png)
2. Now the last commit message, description, staged files, etc. are visible (note: this does not change anything in the working copy, git-cola just pulls up the last commit up as if it was not commited yet). You get back into the original unmodified state if you disable "amend last commit" at this point:
![image](https://user-images.githubusercontent.com/1531285/89741048-f9707f80-da5b-11ea-8ef8-b34ba8f23681.png)
3. Now you can stage/unstage files, change the commit message, inspect the last commit, etc... When you hit commit:
![image](https://user-images.githubusercontent.com/1531285/89741079-3fc5de80-da5c-11ea-9193-423a4c9eca2c.png)

Let me know if you have other questions!

**Comment by WizardOhio24** [comment]
With this, I'm wondering if a full roll-back feature might be good?  I'm thinking that then you could roll-back to any commit, not just the first one as with amend(much like how the reword PR #312 works on the first commit and every other and so can replace amend -m which only works on the first).  So this would need to checkout a certain commit, the user could make their changes, then once committed rebase the branch previously checked out on top of it.  And of course, when rebasing, warn that history is about to be rewritten.  It's definitely possible.
