### ISSUE TITLE
Selection cursor not moving after deleting a stash at the end of the list

### ISSUE THREAD

**Issue by hansmuff** [extrawurst/gitui#223]
**Describe the bug**
[MINOR INCONSISTENCY] When on the Stashes[4] screen and multiple stashes are present and you delete the last one, the cursor doesn't move. 

**To Reproduce**
Go to Stashes[4] and have multiple stashes
Jump to the last one, I use SHIFT+CursorDown
Hit "D" and then ENTER
Now there's no cursor bar. If I hit "D" again, nothing happens because nothing is selected.

**Expected behavior**
When you're on any but the last stash, deleting the stash you are on leaves the cursor "in place" and the stash below the one you delete gets selected. I expect that when I select the last one, the selection realizes there's no next one, and instead goes one back.

**Screenshots**
Not required for this, I think :)

**Context (please complete the following information):**
 - Windows 10 on Windows Terminal (from the App Store)
 - GitUI Version 0.8.0
 - Rust version: N/A

**Additional context**
Fairly straightforward. It's not really a problem, it's a small inconsistency.

**Comment by extrawurst** [comment]
Thanks for reporting this @hansmuff
