### ISSUE TITLE
The lock file for v0.26.2 is out of sync

### ISSUE THREAD

**Issue by alerque** [extrawurst/gitui#2234]
Trying to build Arch Linux distro packages for `gitui`, the current release cannot be built with `--locked` because the lock file is apparently out of sync with the Cargo manifest. This is important for distro packages, especially for distros that monitor builds for reproducibility.

**Comment by extrawurst** [comment]
can you try again now that 6ad80ea is pushed?

**Comment by alerque** [comment]
Cherry picking that patch builds fine.

For the sake of other distros, packagers, and even users that default to locked installed a small patch release to fix that issue would probably be appreciated.

**Comment by extrawurst** [comment]
will release as `0.26.3`
