### ISSUE TITLE
Loading theme, seems broken 

### ISSUE THREAD

**Issue by Alt-iOS** [extrawurst/gitui#2235]
**Describe the bug**
Gitui cant read ```theme.ron``` file on macos

**To Reproduce**
1 Place the following on your theme.ron
```ron
(
    selected_tab: Some(Reset),
    command_fg: Some(Rgb(205, 214, 244)),
    selection_bg: Some(Rgb(88, 91, 112)),
    selection_fg: Some(Rgb(205, 214, 244)),
    cmdbar_bg: Some(Rgb(24, 24, 37)),
    cmdbar_extra_lines_bg: Some(Rgb(24, 24, 37)),
    disabled_fg: Some(Rgb(127, 132, 156)),
    diff_line_add: Some(Rgb(166, 227, 161)),
    diff_line_delete: Some(Rgb(243, 139, 168)),
    diff_file_added: Some(Rgb(249, 226, 175)),
    diff_file_removed: Some(Rgb(235, 160, 172)),
    diff_file_moved: Some(Rgb(203, 166, 247)),
    diff_file_modified: Some(Rgb(250, 179, 135)),
    commit_hash: Some(Rgb(180, 190, 254)),
    commit_time: Some(Rgb(186, 194, 222)),
    commit_author: Some(Rgb(116, 199, 236)),
    danger_fg: Some(Rgb(243, 139, 168)),
    push_gauge_bg: Some(Rgb(137, 180, 250)),
    push_gauge_fg: Some(Rgb(30, 30, 46)),
    tag_fg: Some(Rgb(245, 224, 220)),
    branch_fg: Some(Rgb(148, 226, 213))
)
```

**Expected behavior**
The theme looks like the catpuccin mocha

**Context (please complete the following information):**
 - `macos 14.4.1`
 - `gitui nightly 2024-05-18`
 - `rustc 1.78.0 (9b00956e5 2024-04-29)`

**Additional context**
The log file says the following 
`.config/gitui/theme.ron"]: 2:24: Expected string`

**Comment by Alt-iOS** [comment]
Thats the version brew installs, but even when moving to stable and installing with `cargo install`, it will give the same error

**Comment by Alt-iOS** [comment]
Going back to gitui 0.26.1 fixes the issue

**Comment by Alt-iOS** [comment]
Also it seems that inside nvim it simply ignores the theme.ron file and uses whatever nvim theme is currently applied, Idk if this is a misconfig on my side tho, but as far as I understand, calling gitui inside nvim or directly in terminal shouldnt change the theme (no alias or nothing with -t option configured)

**Comment by kaidev0711** [comment]
tôi cũng gặp vấn đề tương tự nên đã quay về với lazygit :)

**Comment by kaidev0711** [comment]
I had the same problem so I went back to lazygit :)

**Comment by extrawurst** [comment]
some upstream crate changed the way Colors are serialized. thanks for reporting

**Comment by Alt-iOS** [comment]
No worries! And thanks a lot for such great utility

**Comment by extrawurst** [comment]
Unfortunately the `Rgb` notation for colors seems to have vanished from `ratatui` parsing colors, the way to achieve the same result now requires specifying colors in hex format `#00ff00`, sorry for the inconvenience. The upcoming PR #2243 will clarify this and `0.26.3` will mark this as a breaking change with a few examples

**Comment by shagohead** [comment]
Can you figure out how to set indexed colors now?

**Comment by shagohead** [comment]
No, i mean indexed, which can be referenced by numbers from ANSI color table. It used to be like that: Indexed(18) (https://docs.rs/tui/0.12.0/tui/style/enum.Color.html)

**Comment by Alt-iOS** [comment]
AH, no, sorry, try just putting "" around it, if it doesn't work, just use google to convert to rgb HEX, that's what worked for me

**Comment by shagohead** [comment]
> AH, no, sorry, try just putting "" around it, if it doesn't work, just use google to convert to rgb HEX, that's what worked for me

Surrounding with quotes works. Thank you. It was silly not to try
