### ISSUE TITLE
UI colors change dramatically between 0.26.1 and 0.26.2

### ISSUE THREAD

**Issue by cinerea0** [extrawurst/gitui#2239]
**Describe the bug**
Upgrading from v0.26.1 to v0.26.2 results in a large change in the UI colors.

**To Reproduce**
1. Build gitui from https://github.com/extrawurst/gitui/archive/refs/tags/v0.26.2.tar.gz using `cargo build --release --locked --no-default-features --features ghemoji,regex-onig`
2. Download theme file from https://github.com/catppuccin/gitui/blob/main/theme/mocha.ron and place it in `~/.config/gitui`
3. Run `gitui -t mocha.ron`

**Expected behavior**
I expected the UI colors to remain more or less the same. If this was an expected consequence of the update then I can file a bug with the theme creators.

**Screenshots**
On version 0.26.1:
![gitui-0 26 1](https://github.com/extrawurst/gitui/assets/49368915/7cffb7eb-d3c1-466c-84f2-310ee0806e15)

On version 0.26.2:
![gitui-0 26 2](https://github.com/extrawurst/gitui/assets/49368915/c20422de-83fb-42fc-a4eb-7412a30cda7c)

**Context (please complete the following information):**
 - OS/Distro + Version: Void Linux (rolling)
 - GitUI Version: 0.26.2
 - Rust version: 1.77.1

**Additional context**
The following log file line appears in 0.26.2 but not in 0.26.1:

`16:36:03 [ERROR] theme error ["~/.config/gitui/mocha.ron"]: 2:24: Expected string`

The corresponding line in the theme file: `selected_tab: Some(Reset),`

**Comment by extrawurst** [comment]
i believe this is a duplicate of #2235

**Comment by cinerea0** [comment]
> i believe this is a duplicate

I will close this issue in favor of that one since they were first.
