### ISSUE TITLE
How to toggle options in log search popup?

### ISSUE THREAD

**Issue by dam5h** [extrawurst/gitui#2250]
It's unclear how to toggle these options:

![image](https://github.com/extrawurst/gitui/assets/6738286/43f8def7-3303-43cc-98f4-32255b7434c5)

Specifically I am in the log view trying to search for commit hash, but its not working as Summary is only thing checked, I also don't see option for commit sha, so maybe that is something to add?

Can someone enlighten me?  

EDIT: I just found `Search Hash [^j]` in menu at bottom but I still would love to understand how to toggle these options / checkboxes throughout gitui....

Cheers!

**Comment by extrawurst** [comment]
you just go up and down, choose which to toggle and then toggle:

![Screenflick Movie 42](https://github.com/extrawurst/gitui/assets/776816/a62d983d-1135-4c64-99bf-8618b382b5a6)

**Comment by extrawurst** [comment]
closing this but feel free to let me know if there is still an issue for you

**Comment by dam5h** [comment]
Howdy @extrawurst !  Thanks for pointing that out, but I have an issue still...

For some reason my arrow keys don't work (although the `Scroll[..]` menu with arrows does show in my helper menu on bottom bar.  I do have them mapped to `h-l-k-j` via `key_bindings.ron`, could that be my issue?

```
(
    move_left: Some(( code: Char('h'), modifiers: "")),
    move_right: Some(( code: Char('l'), modifiers: "")),
    move_up: Some(( code: Char('k'), modifiers: "")),
    move_down: Some(( code: Char('j'), modifiers: "")),
    shift_up: Some(( code: Char('K'), modifiers: "SHIFT")),
    shift_down: Some(( code: Char('J'), modifiers: "SHIFT")),

    stash_open: Some(( code: Char('l'), modifiers: "")),
    open_help: Some(( code: Char('Z'), modifiers: "SHIFT")),

    status_reset_item: Some(( code: Char('D'), modifiers: "SHIFT")),
)
```

**Comment by dam5h** [comment]
Also, once I get toggles working will this allow searching of git SHA as well?
