### ISSUE TITLE
bad CPU type in executable: gitui

### ISSUE THREAD

**Issue by NoahCardoza** [extrawurst/gitui#2252]
**Describe the bug**
When trying to execute the macOS binary of release [v0.26.2](https://github.com/extrawurst/gitui/releases/tag/v0.26.2), I get: `zsh: bad CPU type in executable: gitui`

**To Reproduce**
1. Download the [v0.26.2](https://github.com/extrawurst/gitui/releases/tag/v0.26.2) release for Mac.
2. Attempt to execute it

**Expected behavior**
It executes and runs the program.

**Context (please complete the following information):**
 - OS/Distro + Version: macOS 14.5
 - GitUI Version: v0.26.2
 - Rust version: N/A

**Additional context**
I tried downloading/unzipping a couple times to make sure it wasn't some sort of fluke. I'm using an Intel machine. I haven't attempted to build from source. The previous release works just fine, which is what I'm using currently.

**Comment by extrawurst** [comment]
Please give the new explicit x86 mac nightly version a try: https://github.com/extrawurst/gitui/blob/master/NIGHTLIES.md

**Comment by extrawurst** [comment]
closed via │671c841 and will release in `0.26.3`
