### ISSUE TITLE
Vim-like navigation using hjkl.

### ISSUE THREAD

**Issue by fanliver** [extrawurst/gitui#227]
Using `h` `j` `k` `l` for navigation is quite common for those who use the terminal a lot. Is there any way to remap the key like that?

`h` `j` `k` `l`: Move in same pane
`Ctrl` + `h` `j` `k` `l`: Switch between panes (staged, unstaged, diff)

**Comment by extrawurst** [comment]
thanks for your interest in `gitui`. this is already tracked as: https://github.com/extrawurst/gitui/issues/57

**Comment by tony** [comment]
For vim-style keybindings, see https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md or https://github.com/extrawurst/gitui/discussions/1114
