### ISSUE TITLE
Ability to autocomplete commit messages with ChatGPT

### ISSUE THREAD

**Issue by vladimir-salvador** [extrawurst/gitui#2270]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**

It would be great to have a command for automatically generating the commit message using an LLM like chatGPT.

On the message box that appears to commit, it would be great to have a cmd to autogenerate the commit 
message based on the staged files.

the LLM api key would be provided by a config file. 

**Additional context**

example of said features includes the jetbrains products that autocomplete commits messages and editors like Zed that allows you to query llms based on a provided api key.

**Comment by extrawurst** [comment]
see https://github.com/extrawurst/gitui/pull/1979

**Comment by vladimir-salvador** [comment]
> see #1979

Oh lord. Why my gpt search didn’t showed me that issue?
Thank you. Closing this now.
