### ISSUE TITLE
git error:get_string called on a live config object when trying to commit

### ISSUE THREAD

**Issue by c02y** [extrawurst/gitui#228]
**Describe the bug**

**To Reproduce**
1. open gitui inside a git repo
2. stage a modified file
3. write a commit message
4. try to commit
5. commit failed, "git error:get_string called on a live config object"

I tried gitui multiple times, failed to commit, but this commit is done successfully using tig.

**Expected behavior**
commit the commit message successfully

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro + Version: [5.7.14-1-MANJARO]
 - GitUI Version [0.9.1]
 - Rust version: [1.45.2]

**Additional context**

**Comment by extrawurst** [comment]
seems related to https://github.com/extrawurst/gitui/issues/79
can you do me a favour and share the config for this repo for the `user.name` and `user.email` ?

**Comment by c02y** [comment]
`user.name`  == empty
`user.email` == "myemail@email.com"

**Comment by extrawurst** [comment]
it is exactly the opposite of #79
<img width="554" alt="image" src="https://user-images.githubusercontent.com/776816/89728762-fb244e00-da2f-11ea-91a3-1aa45c467cac.png">

so it fails if u have a name but no email defined.
```
[user]
         name = Stephan Dilly
```

**Comment by c02y** [comment]
Yes, I get it now, but I used tig to commit it successfully, which is weird, since `user.name` can be undefined in the commit step.

I think we can treat this issue an bug of gitui

**Comment by cruessler** [comment]
If this is not taken yet, I’d have a look.

**Comment by extrawurst** [comment]
@cruessler sure! 👍

**Comment by extrawurst** [comment]
@cruessler any progress on this? I am thinking about cutting a release to get the `vim` key bindings out the door

**Comment by cruessler** [comment]
@extrawurst Sorry for the delay. I’ll now start working on it.

**Comment by cruessler** [comment]
@c02y Running `git commit` with `user.email` not set fails on my machine both using `git` and `tig` with the exact same error message: `*** Please tell me who you are.` If I am not overlooking anything, `gitui` could improve on its error message, but does not do anything unusual.

```
❯ git --version
git version 2.25.1

testrepo on master [+]
❯ tig -v
tig version 2.4.1
ncursesw version 6.2.20200212
readline version 8.0
```

**Comment by dgrine** [comment]
+1

**Comment by extrawurst** [comment]
#269 actually fixes this, but having reliable tests for this is a pickle, but hey lets just bite that bullet
