### ISSUE TITLE
[BUG]: Does not support custom git config path via GIT_CONFIG_GLOBAL

### ISSUE THREAD

**Issue by utilyre** [extrawurst/gitui#2298]
**Describe the bug**
I tried to commit some changes and got the following error

```
commit error:
git error:config value 'user.name' was not found; class=Config (7); code=NotFound (-3)
```

It turns out it cannot find `user.name` or any other config because I have my git configuration in a different path from `~/.gitconfig`, which I achieved by setting `GIT_CONFIG_GLOBAL` to `~/.config/git/config.ini`.

**To Reproduce**
1. `export GIT_CONFIG_GLOBAL=~/.config/git/config.ini` (or any other location)
2. Go to a git repository and make some changes
3. Commit through `gitui`

**Expected behavior**
It should check for this environment variable and use it if set.
Also there is another environment variable that is related: `GIT_CONFIG_SYSTEM`.

**Workaround**
```bash
ln -s $GIT_CONFIG_GLOBAL ~/.gitconfig
```

**Context (please complete the following information):**
 - OS/Distro + Version: `Fedora Linux 40`
 - GitUI Version: `gitui 0.26.3 2024-06-02 ()`
 - Rust version: NA (installed through `dnf`)

**Comment by extrawurst** [comment]
That is interesting. upstream supports this since last year: https://github.com/libgit2/libgit2/pull/6544

**Comment by extrawurst** [comment]
@utilyre if you have any chance to build from #2299 it would be great to test if this fixes your problem

**Comment by koffydrop** [comment]
@extrawurst i was having the same problem and the build from #2299 did fix it

**Comment by extrawurst** [comment]
#2299 is merged now and a new nightly build triggered
