### ISSUE TITLE
Use default shell for git-hooks instead of bash

### ISSUE THREAD

**Issue by mtsgrd** [extrawurst/gitui#2317]
Would it be possible to run the hooks with the shell specified by `$SHELL` instead of defaulting to bash here? If I understand correctly, it matters when running from a non-login (e.g. gui application) shell since bash won't inherit desired environment variables.

https://github.com/extrawurst/gitui/blob/4ef633a75a3581936d0da9aade7af8ed7aad98ab/git2-hooks/src/hookspath.rs#L116-L117

**Comment by yerke** [comment]
zsh is the default shell on macOS these days.

**Comment by yerke** [comment]
My attempt to fix this issue: https://github.com/extrawurst/gitui/pull/2343

**Comment by yerke** [comment]
@extrawurst is it possible to make a new release just for git2-hooks? Thanks.

**Comment by Joshix-1** [comment]
On *nix it should be possible to execute the git-hooks directly. That's how git does it I think. 

> it matters when running from a non-login (e.g. gui application) shell
Wouldn't it be better to make sure to run gitui from a login-shell?

> Would it be possible to run the hooks with the shell specified by $SHELL instead of defaulting to bash here?
Nothing guarantees that the login shell behaves like sh so it shouldn't be assumed that it does.

#2483 tries to improve the git-hooks behaviour, but it would be bad if it broke existing workflows.
So what are you doing that you think it should read `SHELL`? If you are using git2-hooks, there could maybe be an option added to specify how to execute the git-hooks. But for gitui reading `SHELL` and trying to execute hooks with that is for sure the wrong way.
