### ISSUE TITLE
Gitui shows files excluded via sparse checkout as deleted.

### ISSUE THREAD

**Issue by Icantjuddle** [extrawurst/gitui#232]
**Describe the bug**
I use git's sparse checkout feature along with worktrees to have multiple branches checked out simultaneously but not have to checkout the whole tree (would be too large for my disk). Gitui shows all the files I've excluded via sparse checkout as deleted which is incorrect.

**To Reproduce**
1. Clone a this repo.
1. `git sparse-checkout init --cone` (will by default exclude everything that isn't right below the root)
1. `gitui` 

**Expected behavior**
Files excluded from the sparse-checkout not marked as deleted.

**Screenshots**

![image](https://user-images.githubusercontent.com/14916819/89933539-0a3c0500-dbc4-11ea-974a-bf25904572ec.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Ubuntu 16.04
 - GitUI Version 0.8.0
 - Rust version: 1.44.1

**Comment by extrawurst** [comment]
unfortunately this is down to lack of support for sparse working dirs in `libgit2` which we use under the hood: https://github.com/libgit2/libgit2/issues/2263

**Comment by Icantjuddle** [comment]
Ah makes sense, kinda a bummer, but thank you very much for looking into it :slightly_smiling_face:.

**Comment by extrawurst** [comment]
Well it seems there might be a workaround: The config of the repo contains the definitions of the sparse checkout (ignored paths) so in theory when diffing/staging/commiting we could explicitly ignore deleted files in those paths.. it feels wrong to do this at application level though but hey if someone is willing to make a PR for this I am not going to be picky :)
