### ISSUE TITLE
Wrong binary size comparison in README.md

### ISSUE THREAD

**Issue by Ardelean-Calin** [extrawurst/gitui#2330]
**Describe the bug**
The [Benchmarks](https://github.com/extrawurst/gitui?tab=readme-ov-file#3--benchmarks-top-) section of the README specifies the `gitui` binary size to be `1.4MB` crushing competition. However, the latest `gitui` release, `v0.26.3` has a binary size of `12MB`, much closer to lazygit's current(v.0.43.1) `18MB`:

```bash
ls -lh gitui
-rwxr-xr-x 1 calin users 12M iun  2 16:05 gitui
```
```bash
ls -lg lazygit
-rwxr-xr-x 1 calin users 18M iul 13 13:27 lazygit
```

**To Reproduce**
1. Download the latest binary releases of `gitui` and `lazygit` from their respective `Releases` tab.
2. Extract the archives.
3. Run `ls -lh <binary>` for both of them

**Expected behavior**
The comparison should be updated as it is no longer up-to-date.

**Screenshots**
![image](https://github.com/user-attachments/assets/d0bc50aa-3a5f-4ded-ac1f-e6391a88e70c)

![image](https://github.com/user-attachments/assets/7ef82924-1ff8-4230-9288-7196f26b8bdd)

**Context (please complete the following information):**
 - OS/Distro + Version: NixOS 24.05
 - GitUI Version 0.26.3
 - Rust version: No Rust

**Comment by extrawurst** [comment]
on my mac the situation is actually:
`25M lazygit`

and 

`10M gitui`

but good catch, let me update that
