### ISSUE TITLE
git error:config value 'user.name' was not found; class=Config (7); code=NotFound (-3)

### ISSUE THREAD

**Issue by Zamy846692** [extrawurst/gitui#2397]
Just installed this from [MSYS2](https://packages.msys2.org/packages/mingw-w64-x86_64-gitui) on Windows 10. The error `commit error: git error:config value 'user.name' was not found; class=Config (7); code=NotFound (-3)` happens when I Do Commit for the first time.
I suppose that I am supposed to set `user.name`, but am unsure where or how that happens.

1. Move file to _Staged Changes_ by pressing **enter**.
2. Press **C** to commit.
3. Type commit message.
4. See error.

I assume that there is supposed to be a notification that the Commit worked? as you can guess - that didn't happen.

**Context:**
Windows 10 Home, Version: 22H2.
gitui nightly 2024-06-03 (95e1d4d)
Installed by MSYS2 Pacman.

I am completely new to this program and do not have the default Git installed on my PC.

**Comment by extrawurst** [comment]
see https://docs.github.com/en/get-started/getting-started-with-git/setting-your-username-in-git

**Comment by Zamy846692** [comment]
Ok, after installing Git with MSYS2 Pacman I was able to follow the instructions and set both my username and email, it worked after that. But now when I try to push it, an error comes up saying:
```
push failed:
git error:the SSL certificate is invalid; class=Ssl (16); code=Certificate (-17)
```
The previous problem seems fixed, but any idea about this?

**Comment by jerviscui** [comment]
> ```
> push failed:
> git error:the SSL certificate is invalid; class=Ssl (16); code=Certificate (-17)
> ```
> 
> The previous problem seems to be fixed, but any idea about this one? 

@Zamy846692, has this issue been resolved?

**Comment by Zamy846692** [comment]
No, I just used the Msys2 `git` with its GUI.
