### ISSUE TITLE
Able to view diffs between two branches or among some commits in tree view

### ISSUE THREAD

**Issue by maple-leaf** [extrawurst/gitui#242]
**Is your feature request related to a problem? Please describe.**
Sometimes we want to view all changes between branches and commits, we can use 'git diff' to achieve this. But **this lacks tree view**.

**Describe the solution you'd like**
Able to view diffs in a tree view, and able to select each file to view details.

**Comment by extrawurst** [comment]
currently `gitui` does not support handling multiple branches. diffing two random commits should actually be doable with a few changes to the `InspectCommitComponent` just wondering how to design the UX for that, I think we are going to need a `mark commit` sort of selection mechanism for that

**Comment by maple-leaf** [comment]
Refresh this ticket.
