### ISSUE TITLE
whitespace at end of line in commit msg eats cursor

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#247]
<img width="291" alt="image" src="https://user-images.githubusercontent.com/776816/91494938-fc6fca80-e8b9-11ea-9bdf-b417b353f1a0.png">

move cursor one left:
<img width="299" alt="image" src="https://user-images.githubusercontent.com/776816/91494969-098cb980-e8ba-11ea-8bf7-5bc70a3cd98f.png">

**Comment by ciaranmooney** [comment]
I think I understand where this might be coming from. I believe the building of the output of a TextInput component mixes the styling and content to a point where the above issue can occur.

As part of #197 I am partway through refactoring how xxx builds up the Text return value. Where the String containing the characters and the styling are built up in stages. See this [branch](https://github.com/ciaranmooney/gitui/commits/feature/refactoring_textinput).

My changes are currently broken with regards to an existing test and UTF-8 (the carriage return symbol). Once that is sorted I'll write another test for the above scenario to see if the issue has been solved as part of my changes.

**Comment by edfloreshz** [comment]
I'm not very familiar with the project but I'd like to try to fix the issue.

**Comment by extrawurst** [comment]
@edfloreshz I think @ciaranmooney is working on this already, please make sure to checkout his branch first, so we don't have two people fixing the same issue :)

**Comment by ciaranmooney** [comment]
@edfloreshz Indeed, I believe my refactor of the TextComponent will remove this issue (see [https://github.com/ciaranmooney/gitui/tree/feature/refactoring_textinput](my branch) Although I haven't tested it yet. I've got my head around how the area is working so I feel well placed to solve this issue.

**Comment by edfloreshz** [comment]
Okay, thanks for letting me know @ciaranmooney @extrawurst! 🙂

**Comment by extrawurst** [comment]
@ciaranmooney is this still coming in at some point? maybe other might want to look into this particular issue until then so we can clear it for `0.11`

**Comment by ciaranmooney** [comment]
I am afraid I will have to concede defeat to this issue and allow others to take a crack at it.

**Comment by pm100** [comment]
can you explain what the bug is, I dont see it

**Comment by extrawurst** [comment]
On the screenshots you can see that the underscore indicating the cursor position disappears when under a space at the end of a line

**Comment by pm100** [comment]
how did you get that new line in there?

And I have no cursor when typing only when backtracking (left / right arrow), is that right?

**Comment by extrawurst** [comment]
You can use the external editor to get linebreaks in there. If you do not see the underscore I see the bug :)

**Comment by pm100** [comment]
got it, let me tackle this - i suspect its a tui issue

**Comment by pm100** [comment]
as i suspected this is a tui bug, I have filed a bug with them and a solution

https://github.com/fdehau/tui-rs/issues/404

when they fix it the trailing " " character needs to be a trailing NBSP character 

`const NBSP: &str = "\u{00a0}";`

there is a simple work round for gitui, which is to use a '_' character instead of a space at the end of the line while editing. This looks slightly odd because the underline character is slightly different to the underline of a space. But its barely noticeable. You want a PR for that? It means there is an always visible cursor which is nice.

The alternative is to turn of text wrap but I dont think thats a good idea.

**Comment by extrawurst** [comment]
![Screenflick Movie 87](https://user-images.githubusercontent.com/776816/102698827-992aef00-4240-11eb-869d-a7f0af59292f.gif)
