### ISSUE TITLE
0.9.1 and 0.10.0-* are missing on crates.io

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#255]
I wanted to package latest rc version that was just released but noticed that latest version on crates.io is actually 0.9.0..

Can you fix it please?

**Comment by extrawurst** [comment]
I did not think it make sense to push RCs to crates to be honest. after all its release candidates. the missing `0.9.1` was a mistake indeed.

**Comment by ignatenkobrain** [comment]
@extrawurst well, I'd like to have RCs in Fedora's development version so whoever (including me) want to use those - could do so. Since cargo knows that it is pre-release, it will not install it when `cargo install gitui` is run. Users would need to specify exact prerelease version they want.. But I think this is much better than just not pushing it at all.

**Comment by ignatenkobrain** [comment]
For example, see https://crates.io/crates/actix-web. When you open it, it offers you a `2.0.0`, but there are bunch of pre-release `3.0.0` versions that are available for users that want them. In Fedora, for example, we ship only pre-release versions of actix-* stack because only that contains fixes we want our users to have.

**Comment by extrawurst** [comment]
`actin-web` is a library and pre-releases are actually interesting to users. the pre-releases I just did were just because I have not other way to test the CD pipeline and they are of no value to any. If I every do actual pre-releases that are supposed to be used I will push them. In this particular case I will remove the pre-release tags again in just a few minutes

I just pushed `0.9.1` to crates.

**Comment by ignatenkobrain** [comment]
> If I every do actual pre-releases that are supposed to be used I will push them

Oh, I thought that they could be used by users that want pre-release :) If it was just for CI, then sure :)

> I just pushed 0.9.1 to crates.

Thanks, I'm updating it in Fedora right now.

**Comment by extrawurst** [comment]
`0.10.0` is also being pushed right now.

**Comment by ignatenkobrain** [comment]
\o/

**Comment by extrawurst** [comment]
@ignatenkobrain crates.io is updated now and the full release tag `0.10.0` is pushed, should be through CD soon
