### ISSUE TITLE
only use static linked ssl on linux

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#268]
is it possible to only use the `vendored-openssl` of `git2-rs` on linux?

**Comment by cruessler** [comment]
@extrawurst I could take a look at this issue. What are the findings so far?

**Comment by extrawurst** [comment]
oops forgot to close this one. did that already: https://github.com/extrawurst/gitui/commit/7d1e3643b10b9d75f4b60646ec9af7e1150121f4
