### ISSUE TITLE
Adhere to the XDG base directory specicifation

### ISSUE THREAD

**Issue by piegamesde** [extrawurst/gitui#27]
**Is your feature request related to a problem? Please describe.**

Since gitui has no configuration (yet?), this may be a bit early, but you're already on the wrong path:

> to enable logging to `~/.gitui/gitui.log`:

So please don't do that and use the XDG environment variables do determine where to put config, log and other files.

**Additional context**

https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

**Comment by extrawurst** [comment]
That is a very good point. I was wondering what is the "standard" here! Thanks for pointing me in the right direction.

**Comment by extrawurst** [comment]
@piegamesde does that adhere to convention on linux?

this will log to:
 * `$HOME/Library/Caches/gitui/gitui.log` (mac)
 * `$XDG_CACHE_HOME/gitui/gitui.log` (linux using `XDG`) 
 * `$HOME/.cache/gitui/gitui.log` (linux otherwise)

**Comment by piegamesde** [comment]
LGTM, even if I can't speak for MAC users (in theory the XDG specification is not limited to Linux, but ¯\_(ツ)_/¯ ). You could partly follow the specification on MAC by using `$XDG_CACHE_HOME` if set, but defaulting to `$HOME/Library/Caches` instead of `$HOME/.cache` if not.

**Comment by extrawurst** [comment]
merged

**Comment by piegamesde** [comment]
Thx
