### ISSUE TITLE
support force push

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#274]
see https://github.com/libgit2/libgit2/issues/4286 for how to do `force` with libgit2

we should try to push first and if it fails we ask if we should force push, this way we only need one `push` command

**Comment by WizardOhio24** [comment]
For this, would it not be better to create a separate command/key for it?  Usually when you want to force push, you know, it's not like you usually push, fail and decide to force push, this would probably result in overwritten commits and annoy everyone else who was contributing who would then have to `reset --hard` or `force push` to sort out the branch.  It would be more common to push, fail, rebase and push again.
Usually you would only force push if you had rewritten history and should only do it on a branch where you are the sole commiter.  And if you had rewritten history, you'd know you have to force push.

So I think this should be on a separate key, perhaps Shift-P?

**Comment by alocquet** [comment]
Hello.
My usage of force push is the one described by @WizardOhio24 : I force push when I rewrite my history.
I think we should use --force-with-lease option to avoid erasing the commits of another user.

**Comment by extrawurst** [comment]
@WizardOhio24 ok lets do `Shift+P`

**Comment by GitMurf** [comment]
> WizardOhio24 ok lets do `Shift+P` but with confirmation popup

I know this is an old issue but this message seems like the intent is to have a confirmation popup for when  you are force pushing. I would like that so I do not accidentally force push. did the confirmation get removed? is there a way I can change some configuration to require a confirmation before force pushing? Thanks!

**Comment by GitMurf** [comment]
Nevermind! it appears the confirmation works as expected! The problem was I tried re-mapping shift+p to ctrl+p for force push with the following:

`force_push: Some(( code: Char('P'), modifiers: "CONTROL")),`

But I didn't realize that when you use control modifier, you have to make sure the character `P` is lowercase. So the correct re-mapping is this which works as expected with a confirmation. Thanks!

`force_push: Some(( code: Char('p'), modifiers: "CONTROL")),`

**Comment by cloudlena** [comment]
Does it actually do a push with `--force` or one with `--force-with-lease` now? If the latter, should we indicate that somewhere? When I was using the feature, I wasn't sure. That's why I came here 😅

**Comment by extrawurst** [comment]
@cloudlena its good ol --force
