### ISSUE TITLE
Copy commit hash in log tab and commit info component

### ISSUE THREAD

**Issue by yanganto** [extrawurst/gitui#281]
It is nice to provide a commit hash copy feature when focus on log tab or commit info component.

**Comment by extrawurst** [comment]
what keeps your from marking it and simply using the terminal copy-function?

**Comment by yanganto** [comment]
I often rebase my git commit by rebase a previous commit or cherry-pick some commit from different branch. Gitui provides a better git log viewer.  If it can provide a simple way to copy the commit hash, it will be an awesome feature for me.  If this feature is good for this project, I am willing to put my afford on this issue.  Thanks.

**Comment by extrawurst** [comment]
what I mean is this:
![Screenflick Movie 69](https://user-images.githubusercontent.com/776816/92740655-3511a880-f37e-11ea-8d3b-5a9787abefb0.gif)

**Comment by yanganto** [comment]
This can be done with a mouse,  and I use a [terminal](https://github.com/alacritty/alacritty) with keyboard selection mode for this currently.  I use a laptop for doing coding most of the time, the keyboard is the most usable and reliable input device for me.  Not all the trackpad is as good as MacBook makes, and the mouse is not always with a laptop.  Such that I wish this feature can be accepted.  :)

**Comment by extrawurst** [comment]
ok but then lets first tackle https://github.com/extrawurst/gitui/issues/262

**Comment by yanganto** [comment]
PR is waiting, the bot is not smart.
