### ISSUE TITLE
Reset item and revert hunk not working with key bindings

### ISSUE THREAD

**Issue by mbhall88** [extrawurst/gitui#286]
**Describe the bug**
Both Reset item ['D'] (stash_drop) and revert hunk ['U'] (status_reset_item) are not working with the vim key bindings. By not working, I mean when I press <kbd>D</kbd> on an entry, nothing happens.

**To Reproduce**
Steps to reproduce the behaviour:
1. Using [this](https://github.com/mbhall88/.dotfiles/blob/master/gitui.vim_style_key_config.ron) config
2. Make a change to a file in a git repo
3. Open gitui
4. Try and Reset item with <kbd>D</kbd> or go to the diff window and try to revert a hunk with <kbd>U</kbd>

**Expected behavior**
The actions work...

**Context (please complete the following information):**
 - OS/Distro + Version: [e.g. `ubuntu 18.04`]
 - GitUI Version [e.g. `0.10.1`]
 - Rust version: [e.g `1.46.0`]

**Comment by extrawurst** [comment]
@yanganto can you look into this?

**Comment by nerdrew** [comment]
It looks like `stash_drop`'s key code is displayed as the shortcut when looking at the `Status [1]` tab. I set both

```
    status_reset_item: ( code: Char('!'), modifiers: ( bits: 0,),),
    stash_drop: ( code: Char('!'), modifiers: ( bits: 0,),),
```

and then I could reset from both the `Status [1]` tab and from the diff view. Setting `bits: 1` made it not work, so maybe it doesn't like if the `Char('U')` is uppercase and the "shift" modifier is used?

**Comment by mbhall88** [comment]
I'm a bit unclear whether that was a question/suggestion/comment?

**Comment by yanganto** [comment]
@mbhall88 It can be work with the following setting if this still not works please kindly pin me.  I will try to solve your problem.  Thanks. 
`stash_drop: ( code: Char('D'), modifiers: ( bits: 1,),),`

**Comment by yanganto** [comment]
I will fix the example later, sorry about this.

**Comment by mbhall88** [comment]
The revert hunk with <kbd>U,/kbd> now works, but `stash_drop` with <kbd>D</kbd> doesn't. (I am using the exact config file you added in #316)
