### ISSUE TITLE
you can use "upx" to compress file, reduce the file size of 'gitui'

### ISSUE THREAD

**Issue by GavinGuan24** [extrawurst/gitui#287]
UPX is an advanced executable file compressor. UPX will typically
reduce the file size of programs and DLLs by around 50%-70%.

```sh
cool@macBook-Pro ~ $ du -sh /usr/local/bin/gitui
872K	/usr/local/bin/gitui
```

**Comment by extrawurst** [comment]
upx compresses at the cost of startup time, right? could you compare the two?

**Comment by GavinGuan24** [comment]
it's a immature advice. 🤔
If you don’t like it, please ignore it.😁
I really like gitui. Good job !!!

em..., In fact, I did not accurately compare their startup speed.
However, when used, there is really no obvious difference.
Because the file size of binary file that you gave is already small.
I just think that the file size can be more extreme.
