### ISSUE TITLE
Make panel jumping more intuitive

### ISSUE THREAD

**Issue by piegamesde** [extrawurst/gitui#29]
**Is your feature request related to a problem? Please describe.**

The UI doesn't really tell that you can use 1-4 to switch between panels. There is a number behind the panel's title (`Unstaged Changes [1]`), but that could also be the number of unstaged files.

**Describe the solution you'd like**

Lazygit does a pretty good job at it: The bottom panel says: `1-5: jump to panel, […]`.

**Comment by extrawurst** [comment]
Hey @piegamesde thanks for your valuable feedback! Did you look into the help screen? 
<img width="533" alt="image" src="https://user-images.githubusercontent.com/776816/79962420-4e29c380-8488-11ea-8751-d35680f955b3.png">

**Comment by piegamesde** [comment]
Yes I did. But I didn't know how to unstage things for the first five minutes due to this :)

**Comment by extrawurst** [comment]
I understand that it can be confusing in the beginning - let me give it some thought. The problem is the actionbar on the bottom is already pretty full, therefore entries in there need to be brief and still expressive otherwise the bar gets cut off on smaller terminals

**Comment by extrawurst** [comment]
as you suggested there is a command shown in the quickbar at the bottom now indicating how to switch focus to `Focus Stage [2]` or `Focus Unstaged [1]`:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/776816/80700363-dd188a80-8add-11ea-9acf-fb3840fc333d.png">
