### ISSUE TITLE
left key in tree broken

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#291]
before https://github.com/extrawurst/gitui/pull/288 the `left` key *jumped* up to the current parent dir, now it simply moves one up:
![Screenflick Movie 71](https://user-images.githubusercontent.com/776816/94371424-c0b56400-00f6-11eb-8fe2-a6e21ec2aad6.gif)

**Comment by extrawurst** [comment]
previously:
![Screenflick Movie 73](https://user-images.githubusercontent.com/776816/94371493-3cafac00-00f7-11eb-9b02-d69d6f5fa190.gif)

@WizardOhio24 can you look into this?

**Comment by WizardOhio24** [comment]
Sure, apologies for breaking it.

**Comment by extrawurst** [comment]
No worries! Thanks for tackli g this!!❤️
