### ISSUE TITLE
new folder-folding breaks scrolling

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#295]
another followup to #288

moving selection and scrolling behaves weird when some folders are collapsed:
![Screenflick Movie 74](https://user-images.githubusercontent.com/776816/94437690-65d74780-019e-11eb-8a13-608bfff4fdbf.gif)

@WizardOhio24 do you mind also looking into this?

**Comment by WizardOhio24** [comment]
Of course, apologies again :persevere:.
