### ISSUE TITLE
stashing support

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#3]
some question need to be solved for this:
* does the stashing happen in the status tab? or..
* we will need a new tab for the stash list anyway, is that the place to also save stuff to the stash? this would allow setting the options like `include untracked files`?
* if we stash in the status-tab, do we use a popup to ask for the options like that?

**Comment by extrawurst** [comment]
WIP at https://github.com/extrawurst/gitui/pull/70

**Comment by extrawurst** [comment]
<img width="758" alt="image" src="https://user-images.githubusercontent.com/776816/82326970-f1192300-99dd-11ea-8ce5-8a435b0ec5cc.png">

I think I am going for a two tab approach now

**Comment by extrawurst** [comment]
WIP 
<img width="631" alt="image" src="https://user-images.githubusercontent.com/776816/82351547-03568980-99fd-11ea-9c2e-326613469cf5.png">

**Comment by jugglerchris** [comment]
This looks useful!  One thing that would be useful that I don't see above is being able to stash individual lines or hunks rather than full files, like `git stash push --patch` (but with a better UI).  I can raise this as a new feature request for later down the road (if you think it's a worthwhile enhancement, that is).

**Comment by extrawurst** [comment]
Yeah that's actually two feature requests. Stashing individual files was on my list (which we need the upstream lib to add support for first: https://github.com/libgit2/libgit2/issues/4725), but stashing hunks actually never crossed my mind 🙈

**Comment by jugglerchris** [comment]
Thanks, I've raised a new feature request for stashing hunks.

**Comment by extrawurst** [comment]
finished: https://github.com/extrawurst/gitui/commit/63d3bf5661c78f38b238780ad8709b0176bd1541

will go out in next release

**Comment by extrawurst** [comment]
![stashing](https://user-images.githubusercontent.com/776816/82823086-34283a00-9ea7-11ea-9755-e0fb863a79e3.gif)

**Comment by extrawurst** [comment]
released: https://github.com/extrawurst/gitui/releases/tag/v0.4.0
