### ISSUE TITLE
Support rebase (git rebase <branch>)

### ISSUE THREAD

**Issue by WizardOhio24** [extrawurst/gitui#302]
**Is your feature request related to a problem? Please describe.**
When pushing to a remote repo, it may be required to rebase if someone else has contributed while you were working and it would be useful to be able to perform a rebase in GitUI.

**Describe the solution you'd like**
When you press the 'r' key in the status tab, a popup should appear asking you which branch you want to rebase onto.  After selecting the branch and pressing enter, git will rebase the current branch onto the selected branch.  If there are no conflicts, a popup will appear saying the rebase was successful.  (For the initial implementation, this should only rebase, not fetch as well as it would in `pull --rebase`).
If there are conflicts, the rebase will take over the whole screen, the title will become "{current_branch rebasing onto other_branch}" with a filetree on the left and a diff box on the right (telling the user where the conflicts are).  All the tabs along the top will disappear (I don't see a need for them to be there, this would clearly illustrate that the user must either abort or continue with the reabse and should make no other changes).  On this rebase screen the user can press esc to cancel(abort) and 'c' to continue.  After the rebase has successfully finished, a popup will be displayed saying the rebase has been completed successfully. 

**Describe alternatives you've considered**
There is currently no way to rebase in GitUI

**Comment by extrawurst** [comment]
This is a dup of #32, right? And I think the branch list view can be reused once we have more branching functionality (#91)

**Comment by WizardOhio24** [comment]
I don't think so, but it is linked to #32 and the functionality implemented in this would be used in #32 .  #32 wants to be able to do an interactive rebase in the log tab (so squash/fixup/reword/drop commits, i.e `git rebase -i <commit>`), whereas here I propose doing a rebase onto another branch (as you might do a merge) in the status tab (i.e `git rebase <branch>`).

#32 wants: https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History (after 'Changing Multiple Commit Messages')
This Issue wants: https://git-scm.com/book/en/v2/Git-Branching-Rebasing

I agree the branch list could be reused, so #91 should be completed before attempting this.

**Comment by extrawurst** [comment]
@WizardOhio24 thanks for clarifying - sounds right! let's tackle #91 and then focus on this
