### ISSUE TITLE
Push fails with username not found.

### ISSUE THREAD

**Issue by edfloreshz** [extrawurst/gitui#304]
**Pushing to a repository fails**
I made a small modification to a file to test gitui, after I made a commit and tried to push I got a backtrace error.

**To Reproduce**
1. Modify a file
2. Commit (or don't, happens either way)
3. Push
4. See the error

**Expected behavior**

**Screenshots**
![Screenshot_20201004_032915](https://user-images.githubusercontent.com/22224438/95012974-da244780-05f1-11eb-8c30-0b778055c6a3.png)

**Context (please complete the following information):**
 - Arch Linux 
 - GitUI Version [0.10.1]
 - Rust version: [1.46]

**Additional context**
I don't know if this is an in-progress feature, if it is, feel free to close the issue.

**Comment by extrawurst** [comment]
Yeah *pushing* is indeed in-progress but either way an easy way to keep it from crashing is to use the methods we already use to show errors in other places (example: https://github.com/extrawurst/gitui/issues/108)

but the question is: do you actually have not username defined ?

**Comment by edfloreshz** [comment]
If by having a username defined you mean having it on git config, then yes. In case there's an internal git credentials keychain in `gitui`, then no. 

Do you mind if I try to handle the UB in this issue? Might be a good way to start contributing to your project for the first time 🧑🏻‍💻.

**Comment by extrawurst** [comment]
Sure take it :)
Yeah I mean the gitconfig, gitui does not handle user credentials directly.

BTW. this is no *undefined behaviour* - its a very well defined *panic* :P

**Comment by edfloreshz** [comment]
Oh okay, sorry, handle the crash then :+1:  
Thank you!

**Comment by edfloreshz** [comment]
@extrawurst Unrelated to this issue, I have a question.
Is the `push` option supposed to be available even when no commit has been made?

**Comment by extrawurst** [comment]
> Is the `push` option supposed to be available even when no commit has been made?

actually no, it could be shown in a `disabled` state. but let's create another issue for that

**Comment by extrawurst** [comment]
fixed in #305

**Comment by extrawurst** [comment]
@edfloreshz do you mind looking into #353 to see if this allows you to push to the repo in question?

**Comment by edfloreshz** [comment]
Sure! 👍🏻
