### ISSUE TITLE
git pull (fetch+simple merge)

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#319]
git pull is short for `git-fetch` + `git-merge`/`git-rebase`.
I added `asyncgit::fetch_origin` already so now all that's left is to merge/rebase afterwards.

this is to be more specific than #90

**Comment by remique** [comment]
I might be wrong, but wouldn't it be better to first implement an interface for merging and solving conflicts? And then reuse that interface when fast-forward pull is not possible?

**Comment by extrawurst** [comment]
yeah I am at that point, I am reducing the scope of this to conflict free merging and otherwise will discard the merge with an error message. the whole merging/conflict story is post-0.11

**Comment by extrawurst** [comment]
so good news. the fast forward merge support works. I'd like to cleanup somethings first and then tackle three-way merging in a separate ticket. for now we have a *secret* key `f` that performs a fetch and tries to ff-merge. its a start.

todo:
- [ ] show progress of ongoing fetch
- [ ] prominent place to show repo state if not in `clean` state (in prep for merging)
- [ ] understandable error if ff-merge does not work
