### ISSUE TITLE
progress bar for push seems broken

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#328]
since we switched to a new `tui-rs` version the progress bar behaves weird - not actually filling the background

**Comment by alocquet** [comment]
Hi !
I think there is a problem in last version of tui-rs lib, after a refactoring in there style cascading.
Anyway, there are some updates in gauge usage that I will push in a MR :)

**Comment by alocquet** [comment]
I have updated gauge label to display 'progess' value and I see that gauge component is OK. The problem is that progression value interchange between 0 and 100 values. I'll try to see why...

**Comment by extrawurst** [comment]
In your Screenshot it looks like it should. Did you change anything? In my local version the background does not turn white on 100% progress.

The fact that no steps in between are shown is a different issue entirely

**Comment by alocquet** [comment]
Nice :)
I'll push the fix. There is a refactoring in style cascading and a method name has changed.

**Comment by alocquet** [comment]
It was a breaking change in this release : https://github.com/fdehau/tui-rs/releases/tag/v0.10.0
