### ISSUE TITLE
linux fallback for copy-to-clipboard suing xsel

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#352]
thanks to @cruessler we now can use copy-to-clipboard on linux. 

but if your linux does not have `xclip` installed we do not try any fallback like `xsel`. we should do that and then have an error msg listing which ones we try.

**Comment by denismaxim0v** [comment]
I'd like to have a try on this if it's still for takes

**Comment by extrawurst** [comment]
@denismaxim0v absolutely - go for it :)
