### ISSUE TITLE
Allow selection/unselection of hunks per file

### ISSUE THREAD

**Issue by carun** [extrawurst/gitui#355]
I'm always frustrated with the lack of ability to select/unselect hunks to staging. [git-crecord ](https://github.com/andrewshadura/git-crecord) is the best example for this.

I would like to be able to select/unselect hunks to commit/stage.

I switch to [git-crecord](https://github.com/andrewshadura/git-crecord) if I have to select or deselect hunks. This prevents me from using gitui as I usually have many hunks.

In the screenshot below, hunk 1 is unselected and hunks 2 and 3 are selected for commit.

![image](https://user-images.githubusercontent.com/471374/96653113-2e674100-12ed-11eb-8185-63725905ac4d.png)

**Comment by extrawurst** [comment]
That’s already possible. Hit enter when being focused on a hunk in the diff

**Comment by carun** [comment]
That's good to know, let me try this.

**Comment by extrawurst** [comment]
I assume this is superseded by #356
