### ISSUE TITLE
Shortcut hints for Enter and few other keys missing from status line

### ISSUE THREAD

**Issue by carun** [extrawurst/gitui#356]
**Describe the bug**

On Windows, PuTTY SSH client, arrow of the `enter` key is not visible.

This screenshot is of the status line and was taken from the staging window .

![image](https://user-images.githubusercontent.com/471374/96656905-a9345a00-12f5-11eb-8ecb-dd8883b2bce7.png)

As seen, the shortcut keys are missing for `Unstage item` and `Next`.

**To Reproduce**

1. Use Windows + PuTTY SSH client, optionally set remote character set translation to UTF-8
![image](https://user-images.githubusercontent.com/471374/96657092-2233b180-12f6-11eb-901f-64c714f1009f.png)

2. Invoke gitui and switch to stage Window

**Expected behavior**

We need to see the arrow keys to hint the user with the shortcuts

**Screenshots**

Attached above.

**Context (please complete the following information):**

 - OS/Distro + Version: [`run gitui on Ubuntu 20.04 64 bit, connected from Windows via PuTTY`]
 - GitUI Version [`0.10.1`]
 - Rust version: [`1.47.0-nightly`]

Ultimately, I'm thinking this could be related to the font encoding, not sure.

**Comment by pm100** [comment]
making sure I understand. You are on a windows machine and use ssh to connect to a Ubuntu machine and run gitui on that remote ssh shell

**Comment by carun** [comment]
That's correct.

**Comment by pm100** [comment]
Update: I can almost repro. In my case I dont get blanks I get the windows classic "I cant render that character" glyph 

![image](https://user-images.githubusercontent.com/489231/96803890-5f657580-13c2-11eb-8056-41827aa79e29.png)

And I can repro with a one line c program too

![image](https://user-images.githubusercontent.com/489231/96803943-80c66180-13c2-11eb-8b46-e17bef690463.png)

that sequence is what gitui uses to display the 'enter' key (u23ce). I get this on a 'normal ' terminal 

![image](https://user-images.githubusercontent.com/489231/96804003-a9e6f200-13c2-11eb-94f4-435c83a9f54a.png)

but this on putty

![image](https://user-images.githubusercontent.com/489231/96804032-bcf9c200-13c2-11eb-8992-bd32d8ea8cf4.png)

So this really looks like a putty issue. It is to do with glyph substitution. The more modern win apps use fancy glyph substitution logic when the specified font doesnt have a particular character. For example the Windows Terminal that I am using when it works, is using Cascadia Code as its font. Cascadia Code does not have that character, so somehow it is substituting a glyph from a different font. WT uses very new text drawing APIs (DirectWrite). Putty tries to draw the same char (and I have it configured to use the same font) but we just get the 'dunno' glyph. Putty uses the 'classic' win32 GDI APIs.

I am still investigating to find out what DirectWrite is doing but I suspect we will have run into a brick wall.

**Comment by pm100** [comment]
OK I can give you a putty fix for this. Its actually a windows font tweak (I learned something new today )

Assume you are using Courier New font for putty. Open regedit (usual, dont mess it up warnings apply)

Go to HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink

add a new multi_string value called 'Courier New' and set it like this

![image](https://user-images.githubusercontent.com/489231/96807552-b3c12300-13cb-11eb-8dee-ffb2cbb23674.png)

log off, log on and you should be OK. If you are using a different font then use that name..
What this is doing is telling the  font manager for GDI to fall back to a different font if it cant find the character in the base font. See here 

https://docs.microsoft.com/en-us/globalization/input/font-technology

**Comment by extrawurst** [comment]
Wow @pm100 thanks for investigating this! @carun does this work for you?

**Comment by pm100** [comment]
> Wow @pm100 thanks for investigating this! @carun does this work for you?

not a lot of rust work tho :-(

**Comment by carun** [comment]
@pm100 thanks, this works mostly! I cannot figure out what "Next" does.

From PuTTY
![image](https://user-images.githubusercontent.com/471374/96944697-60fd6f00-1490-11eb-98a8-f579e5789d2c.png)

From Windows Terminal
![image](https://user-images.githubusercontent.com/471374/96944792-b33e9000-1490-11eb-92ce-0492f6d3d1ff.png)

**Comment by pm100** [comment]
I do not know what it does either, but the character required is the left arrow key I think. I will see if I can track down why that one glyph isnt working

**Comment by carun** [comment]
Great, thanks for the solutions. Learnt something about Windows in this thread. Appreciate it! I will mark this issue as resolved.
