### ISSUE TITLE
add windows binaries in release page

### ISSUE THREAD

**Issue by prabirshrestha** [extrawurst/gitui#36]
currently it only include linux and mac.

**Comment by extrawurst** [comment]
Hi @prabirshrestha thanks for your interest in the project!
Windows binaries are in preperation. I could use some testing help on windows, you can checkout the current build here: https://github.com/extrawurst/gitui/actions/runs/89425008

**Comment by prabirshrestha** [comment]
I used cargo install and it works in windows.

Would be good to have binaries so folks that have rust tools can easily use it. It was more for others as I already use rust.

**Comment by extrawurst** [comment]
win binaries should be in the next release; https://github.com/extrawurst/gitui/commit/d22571c919aea221d4c8a5b07efb708abfc37619

**Comment by extrawurst** [comment]
first release containing win binaries: https://github.com/extrawurst/gitui/releases/tag/v0.1.12

**Comment by prabirshrestha** [comment]
Thanks. For the quick action.
