### ISSUE TITLE
Better explanation how to configure external editor

### ISSUE THREAD

**Issue by ser-drephs** [extrawurst/gitui#382]
I wish there was some kind of multi-line commit message support. 

Inside the commit dialog it should be possible to create a line break using <kbd>CTRL+ENTER</kbd>.

It is possible to use any other external editor, but configuring it is also not documented in any way 😊

**Comment by extrawurst** [comment]
@Ser-Drephs thats what the external editor support is for. What platform are you on? `vi` is usually available and used? Also if you try to open in external editor what error do you get? Cause it should tell you how it works

**Comment by Ser-Drephs** [comment]
Thanks for the fast reply @extrawurst 

I am using Windows. With Windows there is no `vi`. I installed `vim` using chocolatey. Also using the external editor I had to dig through the code to find out that I need to set the environment variable `GIT_EDITOR`.

**Comment by extrawurst** [comment]
Again, what error message did you get before?

**Comment by Ser-Drephs** [comment]
Sorry forgot that 😁

```
Error
failed to launch editor:
"vi": Das System kann die angegebene Datei nicht finden. (os error 2)
```

**Comment by Ser-Drephs** [comment]
After installing `vim` ([Link](https://chocolatey.org/packages/vim)) and adding User Environment Variable `GIT_EDITOR` with path `C:\Tools\vim\vim82\vim.exe` the external editor launches.

**Comment by extrawurst** [comment]
Ok then the issue is that this error should be more helpful. It should tell you what to do.

**Comment by akshay1992kalbhor** [comment]
I would like to help with this one!
Aside from the error message is there anything else that needs to be changed?

**Comment by extrawurst** [comment]
@akshay1992kalbhor no I think the error msg is the important part here

**Comment by akshay1992kalbhor** [comment]
Ok I have a few questions which might or might not be stupid.
1. I am assuming the error message should mention just the 'GIT_EDITOR' environment variable and not the other ones. Or should it?
2. How much info should the message have? Should it include the commands to add environment variables on all the platforms? ( I am be overthinking this one)

**Comment by Ser-Drephs** [comment]
From a user perspective:

1. It should have both. The error message and informing the user about the environment variable `GIT_EDITOR`.
1. Using a tool like this I would assume that the user knows how to add an environment variable 😉

**Comment by akshay1992kalbhor** [comment]
I am thinking of something simple, something like this: "Could not open the external editor. Make sure you have set the environment variable GIT_EDITOR." A simple google search can let the user know what it is and how to set it. Any suggestions will be appreciated.

**Comment by akshay1992kalbhor** [comment]
Can someone checkout the pull request?

**Comment by holly-hacker** [comment]
The error message here still isn't great, it won't mention the `GIT_EDITOR` environment variable and I only figured this out by googling and arriving at this issue.
