### ISSUE TITLE
outgoing commits on untracked branch

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#385]
right now when I only create the branch locally and do not push it upstream it is **not** shown that there is stuff to be pushed:

<img width="321" alt="image" src="https://user-images.githubusercontent.com/776816/97504558-6585c400-1977-11eb-894f-5cfde7659685.png">

if we detect that the branch has no upstream we should show the number of commits that would potentially go up once we push upstream

**Comment by cruessler** [comment]
@extrawurst I’ll have a look!
