### ISSUE TITLE
msi installer fails on clean windows install

### ISSUE THREAD

**Issue by pm100** [extrawurst/gitui#394]
The msi installer binary does not install vcruntime140.dll so app wont start

Download of the vc redist and install fixes it but really the msi should do this

**Comment by extrawurst** [comment]
could you look into this? can we do this using `cargo wix`?

**Comment by pm100** [comment]
Yes, I am working on it - I posted a feature / bug request to the cargo-wix team. Its really a generic issue. I filed a bug here just so it didnt get lost.

I set up a clean new windows system to see what would happen in various scenarios, hence this one and the hooks one. I was kind of intended to use the hooks one to do a deep fix of windows hooks, but fixing the panic is a good idea of course. Once I have a clearer idea of the best solution I will raise another issue.

**Comment by pm100** [comment]
for the wix issue right now you can simply have a release note that syas you must install 

https://aka.ms/vs/16/release/vc_redist.x64.exe

or 

https://aka.ms/vs/16/release/vc_redist.x86.exe

**Comment by extrawurst** [comment]
@pm100 cool. can you link the issue we are depending on?

**Comment by pm100** [comment]
https://github.com/volks73/cargo-wix/issues/114

**Comment by extrawurst** [comment]
@pm100 where are we on this?

**Comment by pm100** [comment]
@extrawurst cargo-wix wont make any change so we have 3 choices
 - leave it as a release note
 - change the build for the MSI binary to be static linked (so take out the no-build flag)
 - change the wix setup in gitui build to include vcruntime

I have tested the second option and it works fine. The package size increases from 2mb to 7mb, but then that would also happen in we did the third choice

I started on the third choice when I reported the bug originally. I havent got it to work to my satisfaction yet. And stopped once option 2 came up

**Comment by extrawurst** [comment]
I think option 3 is the least intrusive, lets add the wix config file to the repo and bundle up the runtime with the installer. maybe you can find another project to find inspiration how they do it. we can't be the only one doing this.

**Comment by pm100** [comment]
OK, I already looked around a lot, msft recently changed how they package the runtime so a lot of suggestions no longer work. And the team that did cargo-wix didnt even realize this was an issue :-)

I will make it go but it will take a while.

**Comment by extrawurst** [comment]
@pm100 was this fixed by https://github.com/extrawurst/gitui/pull/431 ?

**Comment by pm100** [comment]
yes

**Comment by extrawurst** [comment]
fixed in #431
