### ISSUE TITLE
support wayland copy to clipboard

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#397]
according to @1wilkens in #390 our current copy to clipboard binaries may not cover wayland (correct me if I am wrong).

maybe we can use this opportunity to cleanup the support for multiple fallback programs for running copy to clipboard:
* use `which` on all platforms
* have a list of platforms specific programs 
* try them all before erroring out

**Comment by 1wilkens** [comment]
While we can certainly do that, we could also use a rust library to handle the clipboard. There are several choices, but [copypasta](https://crates.io/crates/copypasta) seems to be the most up-to-date one. I can understand if you don't want to add a (potentially) heavy dependency, however we already included `which` just for clipboard support, so I would actually use the abstraction from a proper clipboard library.

**Comment by extrawurst** [comment]
@1wilkens good thinking, but we have been there and tried that and reverted it because of dynamic dependencies that these libraries introduce: https://github.com/extrawurst/gitui/pull/261

`which` only needs `libc` and can still compile to a static binary

**Comment by 1wilkens** [comment]
My bad, I should have looked maybe ;) In this case, the proposed solution seems good. I'll try to address the wayland part in a PR soon :)

**Comment by cas7breeder** [comment]
Just bumping this to not let the bot kill this; Using `wl-copy` on Wayland here. Great tool!

**Comment by extrawurst** [comment]
@cas7breeder feel free to reopen it if you are about to submit a PR :)
