### ISSUE TITLE
push gauge background is not default but explicit black

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#401]
this should be fixed to not break with customised terminal color schemes

**Comment by extrawurst** [comment]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/776816/97987803-31c5f680-1ddc-11eb-8797-ba1e99075661.png">

**Comment by WizardOhio24** [comment]
Not sure this is an easy first issue, was looking at it a bit and it looks like you need to get the background color of the terminal theme, which in TUI is given by Reset, but Reset also makes the text invisible.  I'm not sure how you're supposed to get the background color of the terminal without accessing the terminal's config.  Am I missing something obvious?
