### ISSUE TITLE
core.editor is ignored

### ISSUE THREAD

**Issue by pm100** [extrawurst/gitui#414]
git goes through the following sequence to find the external editor
 - GIT_EDITOR
 - core.editor
 - VISUAL
 - EDITOR
 - "vi"

Currently gitui does not look at core.editor. vscode sets this value when you install the git extension for it so this is a very common situation. I expect other cases set it too.

During investigating this I found 2 other issues
 - gitui calls config.get_str - this always fails, see https://github.com/rust-lang/git2-rs/issues/474
 - gitui when passed a complex editor string doesn't work

vscode set my core.editor to

`core.editor="C:\Users\paulm\AppData\Local\Programs\Microsoft VS Code\Code.exe" --wait`

This doesnt work once I fixed the config lookup.

![image](https://user-images.githubusercontent.com/489231/98504408-c5982800-220b-11eb-8bc2-634f7cf3a34c.png)

The code hints that this would not work.

I think the other calls to config.get_str need to be changed too. I certainly confirmed that get_str on code.editor was silently failing with the error indicated in the git2 bug. I expect that others will silently fail too.

**Comment by extrawurst** [comment]
@pm100 how much of this is fixed via #419 ?

**Comment by pm100** [comment]
all of it. Except the referenced call to get user.name and user.email (fix for bug to do withuser.name not set )  i didnt want to roll to much into on PR. There is another PR that really isnt needed either, was created by back and forht over this one but it is resvolved here https://github.com/extrawurst/gitui/pull/426

**Comment by extrawurst** [comment]
Cool thanks for that, will work my way through the PRs over the next days. I finally want to release push - call defeat on pull for now. it is just too complex right now and the unreleased version grows out of proportion
