### ISSUE TITLE
Search commits for message or author

### ISSUE THREAD

**Issue by WizardOhio24** [extrawurst/gitui#429]
**Is your feature request related to a problem? Please describe.**
It would be good to be able to search the commit list for words in the commit message, or in the author name(i.e filter by author).  For example, if you wanted to go back several hundred commits to find what a commit did, or a previous implementation, and you knew what the commit message contains, it would be good to just search for it, rather than scrolling through hundreds of commit messages to find that one commit.

**Describe the solution you'd like**
Press a button, perhaps `f` or `s`, and be able to search the commit list for words.  This should search both author and commit message. 

**Describe alternatives you've considered**
Scrolling through hundreds of commits

**Comment by willir** [comment]
This feature is actually pretty important to me. And as far as I can tell the pull request is in progress, so just posting to keep the issue open.

**Comment by extrawurst** [comment]
@willir thanks for your interest, unfortunately the PR seems abandoned. feel free to pick it up :)

**Comment by willir** [comment]
@extrawurst, Oh, I see. Thanks for the quick response! I'll try to find time to finish that PR.

**Comment by WizardOhio24** [comment]
Yeah, author of the PR here, I haven't found the time to finish it (not abandoned, but halted), currently the feature is implemented, it works (instructions are in the PR(https://github.com/extrawurst/gitui/pull/506)) but the code needs refined, some of the functions are quite big. I'm going to be pretty busy for the next month but after that I would be able to finish it.  But feel free to take it on, the code just needs to be made better, and feel free to ask any questions about it.

**Comment by willir** [comment]
Hi @WizardOhio24 @extrawurst, I've created a new pull requests #672 with some comments fixed. I'll try to find time to fix other comments a bit later.
