### ISSUE TITLE
Is it possible to resize the panes (e.g. the file tree when looking at a specific commit)?

### ISSUE THREAD

**Issue by nerdrew** [extrawurst/gitui#436]
**Is your feature request related to a problem? Please describe.**
(note: I use a large monitor.) When looking at a single commit there is a lot of space used for the commit message, which is usually no more than a couple (to a handful of lines) and then the potentially large file list is crammed into the bottom 40% of the split.

**Describe the solution you'd like**
Can we either a) make the split percentages configurable or b) make it dynamically re-sizable or c) both?

**Describe alternatives you've considered**
None.

**Additional context**
Commit view:
![Screen Shot 2020-12-03 at 16 35 42](https://user-images.githubusercontent.com/10101/101106783-be073d00-3585-11eb-8f37-346b4fe606df.png)

Log view:
![Screen Shot 2020-12-03 at 16 35 48](https://user-images.githubusercontent.com/10101/101106802-c5c6e180-3585-11eb-86de-60d91f6284f2.png)

**Comment by extrawurst** [comment]
Hi @nerdrew thanks for your interest in gitui. I see your point. allowing to configure or even dynamically resize panes is a bigger hassle but I think I have an idea for this. the message pane should have a max height while it is not focused which you can do in the commit-view (upper screenshot). let me give this a try.

**Comment by extrawurst** [comment]
slightly better but we need a longterm solution for this: 

<img width="1900" alt="image" src="https://user-images.githubusercontent.com/776816/101423858-3f4e2f00-38fa-11eb-806b-3db25c13d225.png">

<img width="1896" alt="image" src="https://user-images.githubusercontent.com/776816/101423893-4f660e80-38fa-11eb-944b-ce8a1ce7d9a7.png">

**Comment by extrawurst** [comment]
I hope the better defaults improve things. but making all panes dynamically sizeable is a huge undertaking especially because `tui-rs` is not made for this currently. so I will close this for now
