### ISSUE TITLE
Add support for MSYS2 / Git for Windows environment

### ISSUE THREAD

**Issue by andgeno** [extrawurst/gitui#440]
**Is your feature request related to a problem? Please describe.**
I tried to run the Windows executable in a Git for Windows MINGW64 terminal session. The program starts up but seems to just freeze instantly. Only way out is Ctrl-C, no other input is registered or works. I then ran the same executable in a Windows cmd terminal session and that worked fine but feels very inconvenient to me since most of my time I am working in a UNIX shell.

**Describe the solution you'd like**
Add support for MSYS2 / MINGW64 environments like the popular Git for Windows distribution.

**Describe alternatives you've considered**
A possible workaround would be to use an alias that will launch a Windows Cmd process with gitui inside the correct working directory.
Right now this is just too inconvenient for me to use so I hope for added support in the future.

**Comment by pm100** [comment]
i will look at this one

**Comment by pm100** [comment]
this is a crossterm bug, their simple test app doesnt work under msys. I will report it.

**Comment by ffes** [comment]
When I run Git Bash from Windows Terminal and start the Windows executable of gitui 0.11.0 I only see the raw escape sequences:

![afbeelding](https://user-images.githubusercontent.com/3225656/105168174-0a004800-5b1a-11eb-93a5-f97157d76331.png)

**Comment by levirs565** [comment]
This allso occured when using Powershell in Conhost when `$env:TERM` is not empty.

When `$env:TERM` is empty.

![syU9nFUUye](https://user-images.githubusercontent.com/42236775/107841186-465a5780-6deb-11eb-8123-24f76ebbe89c.gif)

Then I set `$env:TERM` to `xterm-256color`. This bug occur.

![HkyQVphRHl](https://user-images.githubusercontent.com/42236775/107841205-7275d880-6deb-11eb-9ec2-7380cb6cdf71.gif)

Then I set `$env:TERM` empty. Gitui work as excepted.

![qOYJ71Dmbr](https://user-images.githubusercontent.com/42236775/107841276-2ecf9e80-6dec-11eb-9f7f-1daede34330a.gif)

This bug also occurred when I use Alacritty as terminal emulator.

![qaZagTTWQD](https://user-images.githubusercontent.com/42236775/107841348-a8678c80-6dec-11eb-8654-3fad256c2021.png)

**Comment by ffes** [comment]
Bad bot... 😞

Still doesn't work

**Comment by extrawurst** [comment]
@ffes feel free to take a go at this

**Comment by ffes** [comment]
@extrawurst If it was written in a language I know I might have given it a go, but Rust is not a language I know.
