### ISSUE TITLE
Feature: GitUI splash screen

### ISSUE THREAD

**Issue by WizardOhio24** [extrawurst/gitui#443]
**Is your feature request related to a problem? Please describe.**
It would be cool if GitUI opened up with a splash screen (that just displays for a few seconds before going into the actual GitUI application).

**Describe the solution you'd like**
Essentially GitUI should appear in ASCII blocks in the center of the terminal for 1-4 seconds(whatever works best), then should transition to the application.  This could be annoying for users who open and close GitUI often so there should also be a way to turn this off.
Below is an example of what this could look like
```
        ████████████████████████████████████████████████████████████████████
  
        ████████████  ███████████  ███████████  █████     █████  ███████████
        ████████████  ███████████  ███████████  █████     █████  ███████████
        ████             █████        █████     █████     █████     █████
        ████    ████     █████        █████     █████     █████     █████
        ████     ███     █████        █████     █████     █████     █████   
        ████████████  ███████████     █████     ███████████████  ███████████
        ████████████  ███████████     █████     ███████████████  ███████████
        
        ████████████████████████████████████████████████████████████████████
```
It would be good for the version to be shown here as well(somehow).
This will also need to determine if the terminal size is big enough to support this width/height of characters and if not perhaps not show it (or show something different?).

**Comment by extrawurst** [comment]
yeah I am also not a fan of these splash screens. also the version of the tool can be found via cmd line arg `--version` or in the help popup

**Comment by cdecompilador** [comment]
Maybe here would be a good place to put the `gitui (version)` or something similar like showing the names of the contributors.

![image](https://user-images.githubusercontent.com/36774000/103935008-3da89e80-5126-11eb-8378-a0a042d0b025.png)

**Comment by extrawurst** [comment]
@cdecompilador i am grateful for your interest in this topic but I am unclear 1) how you want to fit the contributors in the marked area and 2) why it matters from a user perspective?

A comparison: I don’t see any way to print out all contributors of git using any command on the git cli either - iff a user is interested in knowing the people behind the project the git repository is containing that information and GitHub even makes it very nice in a Visual way to see avatars and all.
I put effort in connecting every contribution in the changelog in direct Connection to the GitHub User contributing and think it is a devaluation of People putting a lot of work in by adding a simple list of contributors inside the application.

if you worry about the version please see above, I find two ways to figure it out sufficient (one of which is very standard `gitui —version`)

let’s not forget that this tool is supposed to be efficient and serving the user. Let’s focus on adding features 🚀
