### ISSUE TITLE
Support the various "ignore whitespace" git diff flags

### ISSUE THREAD

**Issue by nerdrew** [extrawurst/gitui#444]
**Is your feature request related to a problem? Please describe.**
Small changes that alter the indentation look like huge changes without `--ignore-all-space` or `--ignore-space-changes` in `git diff`.

**Describe the solution you'd like**
I'd like a key that toggles diff views between the various ignore space options (don't ignore, ignore all space, and ignore space changes). Ideally it would be toggle-able when looking at a particular diff / commit, but if it can only be applied at the "tab" level, that would be ok too.

**Comment by extrawurst** [comment]
I think that could be done. would you expect a diff to switch back to not ignoring whitespaces again once you change a file or keep this option until you explicitly change it again?

also how would we indicate in what mode the current diff view is?

**Comment by nerdrew** [comment]
I'm not sure for either question. Probably keep the setting until I change it again? Note: ignoring whitespace can have weird effects on staging / unstaging changes. Some kind of indicator in the bottom bar or at the top in the `Diff: <filename>` area... FWIW I almost always have "ignore whitespace" set when I'm reviewing PRs (the setting is easier to use in bitbucket than in github).

**Comment by extrawurst** [comment]
will be possible if we have a general way to change options (related to #809)

**Comment by extrawurst** [comment]
`ignore-all-space` supporting coming with #849

**Comment by nerdrew** [comment]
Thanks!

**Comment by nerdrew** [comment]
Actually, I have a followup question: are there plans to use these diff options when looking at the commit log diffs?

**Comment by extrawurst** [comment]
if they don't lets open a new ticket, that would be a bug
