### ISSUE TITLE
Seeing inaccurate adds/deletes in status 

### ISSUE THREAD

**Issue by focusaurus** [extrawurst/gitui#447]
**Describe the bug**

I have one particular large/old git repo that consistently shows many files as deleted/added in the status pane when they are not modified and no other git tool shows any changes.

The files are on disk and in the git repo. The gitui diff panel shows them as 0 bytes but they are not zero bytes on disk. They are normal files with code in them.

**To Reproduce**
1. Start gitui in this one particular repo
2. Sorry, the repo is proprietary so I can't share it and I'm also not able to reproduce this bug in other repos. I know this isn't that helpful but I wanted to file in case others might be seeing this issue.

**Expected behavior**

Every other git tool shows no pending changes for status.

**Screenshots**

![screenshot-gitui-status-2020-12-15](https://user-images.githubusercontent.com/482377/102275574-d14dcd00-3ee2-11eb-9d38-5b4ea879cecd.png)

![gitui-diff-2020-12-15 at 14-39-21](https://user-images.githubusercontent.com/482377/102275956-651f9900-3ee3-11eb-89d6-14782323295b.png)

**Context (please complete the following information):**
 - OS/Distro + Version: macOS 10.15.7
 - GitUI Version 0.10.1
 - Rust version: 1.44.0

**Comment by extrawurst** [comment]
Wow that’s a curious case. Can you make sure to compare that with what gitkraken shows you? They use libgit2 aswell and that makes sure it’s really on us to sort that out.

if it’s just us we have a Good chance to find the problem.

**Comment by focusaurus** [comment]
OK so I installed gitkraken and it whines about not supporting private repos in the free version, but behind the warning I can see in the status that it too seems to think there are modified files. So maybe its something with libgit2?

![gitkraken-status-2020-12-15 at 16-19-10](https://user-images.githubusercontent.com/482377/102284645-c0588800-3ef1-11eb-822d-8719411390fe.png)

**Comment by extrawurst** [comment]
Sorry I am not using gitkraken myself, I just thought its the most prominent user of the same library. Yeah it could mean that it is a problem in `libgit2` itself. I think there are other actual free tools using the lib. but I need to dig deeper for that

**Comment by extrawurst** [comment]
@focusaurus apparently GitUP (seehttps://github.com/libgit2/libgit2/issues/4679) uses libgit2 aswell, maybe u can try that one to compare

**Comment by focusaurus** [comment]
OK GitUP is now the 3rd GUI to show the same set of spurious changes in the work tree. I guess it's a bug there but probably useless to file until I have some way a maintainer could reproduce.

**Comment by focusaurus** [comment]
I got a tip to check for whitespace differences from one of the libgit2 maintainers but so far I don't see evidence of that.
