### ISSUE TITLE
Search commits by sha

### ISSUE THREAD

**Issue by khoan** [extrawurst/gitui#449]
**Is your feature request related to a problem? Please describe.**
Unable to view a commit by its sha.

**Describe the solution you'd like**
Hit s, then enter sha

**Describe alternatives you've considered**
Using Up/Down, PageUp/PageDown is cumbersome.

**Additional context**
Nice work! Thanks.

**Comment by extrawurst** [comment]
@khoan thanks for your interest in gitui. this feature is on my list of long term goals aswell!
