### ISSUE TITLE
segfault on Gentoo

### ISSUE THREAD

**Issue by dm9pZCAq** [extrawurst/gitui#459]
**Describe the bug**
_segfault_ when trying to launch

**To Reproduce**
just run `gitui`

**Screenshot**
![img](https://0x0.st/iCMr.png)

**Context**
 - installed with `cargo install gitui`
 - OS: Gentoo x86_64
 - GitUI Version: 0.11.0
 - Rust version: 1.47.0

**Additional context**
when trying to run with `--logging` log file is empty
but `--help` show help info without segfault

 - [strace log](https://0x0.st/iCMz.strace)

**Comment by extrawurst** [comment]
hi @dm9pZCAq I personally do not run gentoo. can you build a debug build and check if it is a little more telling? also what I find weird is that the trace looks like you are linking against `libgit2` dynamically, that should actually not be the case

**Comment by extrawurst** [comment]
@dm9pZCAq the repo you try to run in is not public, I assume?

**Comment by dm9pZCAq** [comment]
repo is public

but it fails even if gitgui is outside of repo

**Comment by extrawurst** [comment]
smells like a gentoo specific issue then :(

**Comment by extrawurst** [comment]
did you check if the last release had the same problems?

**Comment by dm9pZCAq** [comment]
in `void linux` it is also dynamic linked with libgit (and running without segfault)
![libgit](https://0x0.st/iCMB.png)

only difference in rust version (void: `1.48`)

also when i tried to compile with `rust 1.46` there are error in unstable  feature
![unstable](https://0x0.st/iCMM.png)

**Comment by extrawurst** [comment]
> also when i tried to compile with rust 1.46 there are error in unstable feature

yeah you need a the latest stable rust

> in void linux it is also dynamic linked with libgit (and running without segfault)

dynamically linked libgit is not tested or maintained.

**Comment by dm9pZCAq** [comment]
I took a closer look at the strace and realized that the problem is in the ssl, namely in libressl

and when i removed vendored-openssl feature [there](https://github.com/extrawurst/gitui/blob/master/asyncgit/Cargo.toml#L16) it is worked without segfault

but what's strange in the void is also libressl and everything works with vendored-openssl feature

**Comment by dm9pZCAq** [comment]
may be not the best, but [there is](https://notabug.org/dm9pZCAq/dm9pZCAq-overlay/commit/09610097a7952373ac719f803a6607c24f46af88#diff-38ccb4d4845bfee7d191b6c1797a2b982a79cd6R164) my solution

**Comment by extrawurst** [comment]
@dm9pZCAq its a stretch but maybe what you observed is due to: https://github.com/rust-lang/git2-rs/issues/645#issuecomment-748627220 - can you check if with the new git2-rs release you still have those issues?

**Comment by dm9pZCAq** [comment]
no

after:
```sh
git checkout v0.11.0
cargo update
#    Updating ahash v0.6.1 -> v0.6.2
#    Updating anyhow v1.0.35 -> v1.0.36
#    Updating base64 v0.12.3 -> v0.13.0
#    Updating const_fn v0.4.3 -> v0.4.4
#    Updating git2 v0.13.12 -> v0.13.14
#    Updating indexmap v1.6.0 -> v1.6.1
#    Updating libgit2-sys v0.12.14+1.1.0 -> v0.12.16+1.1.0
#    Updating openssl-src v111.12.0+1.1.1h -> v111.13.0+1.1.1i
#    Updating openssl-sys v0.9.58 -> v0.9.60
#    Updating parking_lot_core v0.8.1 -> v0.8.2
#    Updating quote v1.0.7 -> v1.0.8
#    Updating ron v0.6.3 -> v0.6.4
#    Updating socket2 v0.3.17 -> v0.3.19
#    Updating syn v1.0.54 -> v1.0.55
#    Updating vcpkg v0.2.10 -> v0.2.11
cargo run
```
i got the same segfault
