### ISSUE TITLE
CD pipeline for chocolatey

### ISSUE THREAD

**Issue by jakoss** [extrawurst/gitui#463]
I noticed that gitui 0.11.0 wasn't uploaded to chocolatey automatically. Is there such a step in CD pipline? If not - it might be worth to do that. Chocolatey is package manager of choice for a lot of us :)

**Comment by extrawurst** [comment]
I actually do not maintain the choice builds. I think @nils-a brought it there. maybe he can give some input on that

**Comment by nils-a** [comment]
It was uploaded automatically, but it's still in moderation.

https://chocolatey.org/packages/gitui/0.11.0

Unmoderated packages can be installed using the `-prerelease` switch, if I'm not mistaken.

**Comment by jakoss** [comment]
Ok, thanks for the info!

**Comment by nils-a** [comment]
@jakoss 
For completeness:
* The source for the package is at https://github.com/nils-a/au-packages/tree/main/gitui
* The "pipeline" is at https://github.com/nils-a/au-packages/actions?query=workflow%3A%22Update+Packages%22 and runs daily at 7:35 am UTC (That means, if two releases are made in one day I'll only publish the newest release availabe at 7:35 - like it happende with the `0.11.0-rc1` & `0.11.0-rc2` - they were created the same day and the following morning only the `0.11.0-rc2` was published.)
* Status of the last run is always visible at https://gist.github.com/nils-a/be944da6cbb50300f2e3114bf35724a0#gitui
