### ISSUE TITLE
Enter label

### ISSUE THREAD

**Issue by savchenko** [extrawurst/gitui#464]
**Describe the bug**
Depending on the font used, Enter label ("left arrow") can be hard to comprehend.

**To Reproduce**
1. Open  `gitui`
2. What does this arrow mean?
![image](https://user-images.githubusercontent.com/300146/103120777-1afb9c00-46c9-11eb-81dc-ccb70ed67e89.png)
Is this backspace? Left arrow on the keyboard?
3. No, it's Enter.

**Expected behavior**
Perhaps using "[Enter]" would make UI less prone to user error.

**Context (please complete the following information):**
 - OS/Distro + Version: Debian Bullseye (current testing)
 - GitUI Version: v0.11.0

**Comment by extrawurst** [comment]
I get your point, but I like the reduced verbosity of those symbols. of course it requires them to be universally clear in the various fonts. how does the following work for you?

Can you build from `better-enter-symbol` branch and let me know if this renders the same for you?

<img width="85" alt="image" src="https://user-images.githubusercontent.com/776816/103134140-50938b80-46af-11eb-9e25-d8974d701c96.png">

**Comment by savchenko** [comment]
Not quite:

![image](https://user-images.githubusercontent.com/300146/103145378-6e352380-4789-11eb-808f-10dbcba79053.png)

The font is "Consolas".

**Comment by extrawurst** [comment]
> Also, left/right arrows look suspicious here:

It is not supposed to be left/right its `top`/`bottom`:
<img width="268" alt="image" src="https://user-images.githubusercontent.com/776816/103149174-78462a80-4767-11eb-925c-1604f2babf71.png">

**Comment by extrawurst** [comment]
The problem with _consolas_ is that I can't seem to get the original on my Mac, the remakes I can find don't even contain the characters you see, so I am kinda lost here :(

So longterm we could consider customisability of those texts/symbols (they are hardcoded now), short-term I would suggest to try a different terminal font (my fave is [JetBrains Mono](https://www.jetbrains.com/lp/mono/))

**Comment by extrawurst** [comment]
@savchenko let me know if you agree we can close this in favour of #465 ?

**Comment by savchenko** [comment]
Absolutely, sounds like the best decision possible.
