### ISSUE TITLE
allow customising key symbols

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#465]
#464 showed that we should allow overwriting/customizing the symbols we use to show key codes. this can be added similarly to our general key configuration in `keys.rs` see `get_key_symbol`

**Comment by josmith42** [comment]
I think I'd like to take a stab at this.

Question: in addition to implementing the feature, would you like the PR to also update the key config documentation so users know how to customize the symbols?

**Comment by extrawurst** [comment]
docs for this: https://github.com/extrawurst/gitui/blob/master/KEY_CONFIG.md#key-symbols
