### ISSUE TITLE
Commit message character count and warning

### ISSUE THREAD

**Issue by austinbutler** [extrawurst/gitui#466]
**Is your feature request related to a problem? Please describe.**

It's hard to tell how long my commit message is.

**Describe the solution you'd like**

Basically mimic VS Code, where you can set a warning after a certain number of characters.

![image](https://user-images.githubusercontent.com/354741/103165077-40230400-47c8-11eb-9f1b-3b2369596e32.png)

**Describe alternatives you've considered**

Alternatively even just a simple character count would be helpful.

**Comment by extrawurst** [comment]
![Screenflick Movie 88](https://user-images.githubusercontent.com/776816/103171565-91c1a200-484d-11eb-820f-73bafa272bce.gif)

**Comment by extrawurst** [comment]
@austinbutler regarding the warning, I am wondering if there is a general rule of what is too long and what is not?

**Comment by austinbutler** [comment]
@extrawurst thanks for the blazing fast turnaround!

The most common AFAIK is the [50/72 guideline](https://stackoverflow.com/questions/2290016/git-commit-messages-50-72-formatting). 50 or less character summary, blank line, then 72 characters or less description.
