### ISSUE TITLE
Warn when commit message is suspiciously long

### ISSUE THREAD

**Issue by savchenko** [extrawurst/gitui#478]
**Is your feature request related to a problem? Please describe.**
Users might write extra-long commit messages which frustrate variety of workflows.
Consider someone pushing the following:
![image](https://user-images.githubusercontent.com/300146/103740901-06fc5680-5048-11eb-8ebe-9095d9810061.png)

**Describe the solution you'd like**
- Limit 1st line to 50 symbols
- Keep 2nd line empty
- Wrap the rest at 72 characters

**Describe alternatives you've considered**
Format each commit manually.

**Additional context**
N/A

**Comment by extrawurst** [comment]
problem with this is that it is not well defined what limits are correct and I am shying away of requiring the user to fiddle in more config files.

the most common way to assure stuff like this is having (pre)commit-hooks

**Comment by extrawurst** [comment]
to reiterate my feedback from the #508:

I am not a fan of this requiring new configuration, abusing the style config I not an option.

my suggestion for an MVP is:
* we hardcode the first-line-limit to 50
* we show a red message (`first line exceeds x chars`) on the bottom (of the dialog, left of the count) if the limit is exceeded

**Comment by extrawurst** [comment]
looks like this now:
![Screenflick Movie 5](https://user-images.githubusercontent.com/776816/116701217-f0e41e80-a9c7-11eb-899b-741a212148af.gif)

**Comment by savchenko** [comment]
I wonder how the 2nd line has appeared. Have you merged/implemented shift+enter somewhere in-between? :)

**Comment by extrawurst** [comment]
> I wonder how the 2nd line has appeared. Have you merged/implemented shift+enter somewhere in-between? :)

that's what the external editor support is currently used for:
<img width="136" alt="image" src="https://user-images.githubusercontent.com/776816/116701824-a616d680-a9c8-11eb-8e54-414faa5553c3.png">

**Comment by savchenko** [comment]
> edit: that is until #509 is merged

Subscribed. Thank you!
