### ISSUE TITLE
Document tab key to change tab

### ISSUE THREAD

**Issue by Thra11** [extrawurst/gitui#48]
**Describe the bug**
It took me a while to work out how to change to the "Log" tab, as the key to press, tab, isn't mentioned in the help.

**To Reproduce**
1. Open gitui
2. press 'h' to view the help

**Expected behavior**
The help should show the key to press to change tab, (Something like "Change tab [tab]") probably in the General section.

**Desktop (please complete the following information):**
 - OS: NixOS Linux
 - Version 0.2.1

**Comment by extrawurst** [comment]
ha very good point! Thanks @Thra11 for the hint. just wanted to release tags in the log (#47) but let me first fix that too
