### ISSUE TITLE
more tag support

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#483]
right, now I can only create a tag.

lets add a popup or tab (not sure yet) that allows:

* list all tags (mark the ones not pushed to remote)
* delete a tag
* fetch tags

**Comment by ffes** [comment]
You know about these settings?

```
fetch.prunetags=true
push.followtags=true
```

**Comment by WizardOhio24** [comment]
Thinking a tab would be best for this, then could view associated commit details on the right (and perhaps press <enter> to go into the commit, like in the log tab).  So it is like the log tab, but for tags, rather than commits.

**Comment by cruessler** [comment]
@extrawurst I’d like to start working on this. I also think that introducing another tab seems like a good idea.

**Comment by extrawurst** [comment]
@cruessler take a go at it :)
I find a popup more fitting to be honest. similar to the branch list (list, rename, delete, ..) - in particular because I'd like quickly jump to the tag's commit in the log then. decoupling the tags-list and the log makes not much sense in my opinion.
what do you think?

**Comment by WizardOhio24** [comment]
Was going to mention, filtering by tag (so making a "tag-log") with `:t` is part of the search/filter functionality in #672 (continued from #506).  So a popup might be better, but I'd question if it would even be necessary (after the search functionality is added, considering you can filter commits by/for tags).  Perhaps just to jump to a commit with a specific tag?  (or should that be implemented by holding down a key and pressing down/up to jump down/up tags?)

**Comment by extrawurst** [comment]
> @extrawurst I’d like to start working on this. I also think that introducing another tab seems like a good idea.

Any update from your side?

**Comment by extrawurst** [comment]
> Was going to mention, filtering by tag (so making a "tag-log") with `:t` is part of the search/filter functionality in #672 (continued from #506). So a popup might be better, but I'd question if it would even be necessary (after the search functionality is added, considering you can filter commits by/for tags). Perhaps just to jump to a commit with a specific tag? (or should that be implemented by holding down a key and pressing down/up to jump down/up tags?)

Searching/Filtering is a different use case to having a dedicated UI to list tags and targeted tag-specific functionality.

**Comment by cruessler** [comment]
@extrawurst Yes, I'm planning on presenting a first version in the next few days! I would go with a popup and make it similar to the one for branches so that they feel consistent.
