### ISSUE TITLE
git2 compile error when cargo installing

### ISSUE THREAD

**Issue by hoijui** [extrawurst/gitui#503]
when executing `cargo install gitui`, I get:

```
   Compiling git2 v0.13.17
error[E0658]: use of unstable library feature 'str_strip': newly added
   --> /home/hoijui/.cargo/registry/src/github.com-1ecc6299db9ec823/git2-0.13.17/src/cred.rs:283:39
    |
283 |                 self.path = Some(path.strip_prefix('/').unwrap_or(path).to_string());
    |                                       ^^^^^^^^^^^^
    |
    = note: see issue #67302 <https://github.com/rust-lang/rust/issues/67302> for more information

error: aborting due to previous error

For more information about this error, try `rustc --explain E0658`.
error: failed to compile `gitui v0.11.0`, intermediate artifacts can be found at `/tmp/cargo-installWOyxWf`

Caused by:
  could not compile `git2`.

To learn more, run the command again with --verbose.
```

**Comment by extrawurst** [comment]
hi @hoijui thanks for your interest in gitui. any reason to ignore all the info the bug report template asks you to fill in making it easier to help you with your issue? 

without any further information my best guess is you try to build with some older rust version. as the readme states: we build using most recent rust

**Comment by extrawurst** [comment]
hi @hoijui thanks for your interest in gitui. any reason to ignore all the info the bug report template asks you to fill in making it easier to help you with your issue?

without any further information my best guess is you try to build with some older rust version. as the readme states: we build using most recent rust

**Comment by hoijui** [comment]
Then I would recommend updating [the `edition` field](https://github.com/extrawurst/gitui/blob/325d74204ad17b809a6032dfe8effe9d8e7310b0/Cargo.toml#L6)
and using ['rust = 1.696` in Cargo.toml](https://github.com/rust-lang/rfcs/pull/2495).

my rust version is `rustc 1.44.0 (49cae5576 2020-06-01)`.

**Comment by extrawurst** [comment]
@hoijui the `edition` is correct and the `rust` field did not make it into current cargo yet: https://doc.rust-lang.org/cargo/reference/manifest.html

current supported rust version is: `rustc 1.49.0 (e1884a8e3 2020-12-29)`
