### ISSUE TITLE
error authenticating failed connecting agent class=ssh (23)

### ISSUE THREAD

**Issue by mwkcoding** [extrawurst/gitui#505]
**Describe the bug**
When using Powershell v7.1.0 and pushing to self-hosted private git servers, it returns the error `error authenticating failed connecting agent class=ssh (23)` (see screenshot)

**To Reproduce**
1. Go to a private repository hosted on a private git server and open gitui
2. Attempt to push (doesn't need changes/commits ready to push)
3. See error

**Expected behavior**
A successful push without errors.

**Screenshots**
![image](https://user-images.githubusercontent.com/16936030/105962638-60bcd300-6080-11eb-967d-38e1718609bf.png)

**Context (please complete the following information):**
 - OS/Distro + Version: `Windows 10 Pro Version 20H2 (build 19042.746)`
 - GitUI Version: `0.11.0`
 - Rust version: `???`

**Comment by extrawurst** [comment]
Hi @mwkcoding thanks for your interest in gitui, we use `libgit2` as the underlying git tool and I think it still has some limitations when it comes to ssh, `cargo` uses the same lib and I found this comment: https://github.com/rust-lang/cargo/issues/1851#issuecomment-244166027

can you check if that helps working around those limits? 

I myself do not have a windows machine to test/debug this.

**Comment by mwkcoding** [comment]
I don't find that issue very helpful. None of the fixes they're suggesting works for me.

**Comment by extrawurst** [comment]
probably related to #495
