### ISSUE TITLE
square boxes in bottom menu shortcut and file listing 

### ISSUE THREAD

**Issue by shivakumargn** [extrawurst/gitui#515]
Some of the bottom menu options show the shortcut key as a square box (screenshot is attached).
<img width="589" alt="gitui_bottom_menu" src="https://user-images.githubusercontent.com/171191/107724022-d96e9100-6d08-11eb-8215-96e37bc8d865.png">

The "Files" section of the git commit view as well as square box prepended to folders (screenshot is attached).
<img width="259" alt="gitui_files" src="https://user-images.githubusercontent.com/171191/107724046-e7bcad00-6d08-11eb-9f59-5c03744b92a3.png">

This was on a putty window when connecting from windows system to a linux system.
- Terminal: Putty (connecting from windows to linux). The display character set was set to UTF-8.
- Linux Distro: CentOS 7.x
- GitUI Version: 0.11.0

(Thanks for the tool. It is awesome.)

**Comment by extrawurst** [comment]
that looks a lot like something goes wrong in the transmission via putty. there is not much I can do about it

**Comment by shivakumargn** [comment]
You are right. Checked on a linux system where the character was displayed correctly. Closing the ticket.
