### ISSUE TITLE
Properly set `ft=gitcommit` when opening editor

### ISSUE THREAD

**Issue by savchenko** [extrawurst/gitui#518]
**Is your feature request related to a problem? Please describe.**
When user opens an editor to redact the commit message, it does not pass the `filetype`.

**Describe the solution you'd like**
Pass `set ft=gitcommit` to vim when editing commit message.

**Describe alternatives you've considered**
Set filetype manually on each edit.

**Additional context**
This can be done via `-c` flag, e.g.:
```sh
nvim -c ":set ft=gitcommit" -- /path/to/commit
```

**Comment by savchenko** [comment]
This might be partially related to https://github.com/extrawurst/gitui/issues/517.

**Comment by extrawurst** [comment]
> This might be partially related to #517.

I don't see what it has to do with #517 - one is about *which* file to open and this one is about *how* to open it in nvim - what am I missing?

**Comment by savchenko** [comment]
@extrawurst , 
*hunch* 
they both refer to the "open editor" so might be handled within the same logical module.

**Comment by extrawurst** [comment]
@savchenko can you tell me more about this, I am not a vim user. is that something git does when opening the editor for a commit msg? can you point me to some documentation?

**Comment by savchenko** [comment]
Editor for `git` can be set separately:

```
export EDITOR="nvim"
export GIT_EDITOR="nvim -u $HOME/.config/nvim/init.vim"
```

> also how would this behave if the user configures its EDITOR to be something else?

I would imagine that `gitui` simply uses whatever is defined in user's EDITOR and GIT_EDITOR environment variables preferring the latter one, same as git does. If none are present &mdash; fallback to vi/nano/ed.

> is that something git does when opening the editor for a commit msg?

When editing git commit message. git detects `.git/COMMIT_EDITMSG` and sets `filetype=gitcommit` which results in a nice highlighting, proper wrap and so on:

![image](https://user-images.githubusercontent.com/300146/109077132-9cb08a00-774b-11eb-8487-d077263f8807.png)

**Comment by MagicDuck** [comment]
@extrawurst I think the problem might just be the file name. When committing through gitui, it sets the file name to `gitui/COMMITMSG_EDITOR`. Using the name that @savchenko mentions above `.git/COMMIT_EDITMSG` should allow it to work correctly in theory. Actually, even `gitui/COMMIT_EDITMSG` should work according to this: https://github.com/neovim/neovim/blob/0a653f7ab98dfc05bf0532b9f81bc19377031900/runtime/filetype.vim#L646.

**Comment by extrawurst** [comment]
> @extrawurst I think the problem might just be the file name. When committing through gitui, it sets the file name to `gitui/COMMITMSG_EDITOR`. Using the name that @savchenko mentions above `.git/COMMIT_EDITMSG` should allow it to work correctly in theory. Actually, even `gitui/COMMIT_EDITMSG` should work according to this: https://github.com/neovim/neovim/blob/0a653f7ab98dfc05bf0532b9f81bc19377031900/runtime/filetype.vim#L646.

thanks for the hint, I think #733 fixes this now
