### ISSUE TITLE
Support for Page Up and Page Down keys in Branchlist

### ISSUE THREAD

**Issue by nheilbuth** [extrawurst/gitui#519]
Would be nice to be able to scroll long lists (ie. branches list) using page up/down instead of just arrow keys

**Comment by extrawurst** [comment]
good point, it is missing on the branchlist. let me know where you miss it aswell

**Comment by nheilbuth** [comment]
Just noticed that pgUp/Down support is also missing in the files list when inspecting a commit 
(go to log, select a commit, press right arrow to inspect).
