### ISSUE TITLE
Panic, "Could not find file to open: No such file or directory"

### ISSUE THREAD

**Issue by savchenko** [extrawurst/gitui#526]
**Describe the bug**
Gitui crashes when git errors with "No such file or directory"

**To Reproduce**
1. Open repository that exhibits the issue
2. Navigate to the file that can't be accessed
3. `gitui` crashes immediately

**Expected behavior**
Error message is shown to a user, UI does not crash.

**Screenshots**
```
panic: PanicInfo { payload: Any, message: Some(error getting diff: Git(Error { code: -3, klass: 2, message: "could not find \'/home/user/code/xxxx/xxxx/xxxxxxxx/xxxxx.xxx\' to open: No such file or directory" })), location: Location { file: "asyncgit/src/diff.rs", line: 122, col: 14 } }
trace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: start_thread
  13: clone

panic: Any
trace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: start_thread
   7: clone
```

**Context (please complete the following information):**
 - OS/Distro + Version: Debian Bullseye
 - GitUI Version: 0.11.0
 - Rust version: 1.48.0

**Additional context**
N/A

**Comment by extrawurst** [comment]
Any idea what is different about this repo ? Is it an open source repo I can reproduce that with?

**Comment by savchenko** [comment]
Unfortunately repository is not available on the Internet. There was a file-system corruption which prevented git from accessing some folders within the working tree (but not the `.git` one).

**Comment by extrawurst** [comment]
diffs are created against working dir files, so this would explain the crash. does the problem persist?

**Comment by savchenko** [comment]
The repository was restored from a backup and the problem hasn't manifested since then. Please feel free to close the issue if you'd like.

If this reoccurs, I will try to preserve the affected repository and reply here.
