### ISSUE TITLE
Commit input box hides branch name

### ISSUE THREAD

**Issue by focusaurus** [extrawurst/gitui#529]
**Is your feature request related to a problem? Please describe.**

My company requires commit messages have a certain format and a link to a ticket number which I usually encode into the branch name for reference. My issue is I start a commit and then need info from the branch name, which is obscured by the commit text input box, so I have to ESC out of the commit to see what I need, load it into short term memory, then start the commit message again.

**Describe the solution you'd like**

If the commit input box could be just like 2 lines lower on the screen, that would solve this.

**Describe alternatives you've considered**
Or branch name could go somewhere else. Most Git UIs put the branch name in a fairly prominent location toward the top left of the UI somewhere.

**Additional context**

Just a nice to have that seems maybe not super difficult (unless the terminal UI widget library makes it hard which would be sad).

**Comment by extrawurst** [comment]
that's a fair point I actually encountered that myself too!

**Comment by extrawurst** [comment]
this is what I came with now:

<img width="909" alt="image" src="https://user-images.githubusercontent.com/776816/108868152-35cd8c80-75f6-11eb-9878-71fc6d514cbe.png">
