### ISSUE TITLE
more error handling

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#53]
I started `asyncgit` crate ignoring errors `unwrap` is all over the place but the goal would be to handle them correctly like with `sync::get_commits_info`

**Comment by MCord** [comment]
Hi, I would love to help but I don't have much experience in Rust. Can I take this issue ?

**Comment by extrawurst** [comment]
Hy @MCord thanks for your interest in helping❤️! Absolutely you can grab this one - let me know when you need any input!

**Comment by MCord** [comment]
So here is my first question: do we want to define a custom error for `asyncgit` lib or use the `git2::Error` ? in many cases the underlying error is `git2::Error` but for example in `hook::hooks_commit_msg()` it might be an `std::io::Error` or if for whatever reason we can not get a temp file name we have to return some kind of error, which type would that be ?

**Comment by MCord** [comment]
Ok, let's try that. I will send a PR so we can discuss the implementation.

**Comment by extrawurst** [comment]
Really cool! Thank you❤️!

**Comment by MCord** [comment]
I have created a pull request #58 but the build is failing, I am trying to figure out what went wrong.
