### ISSUE TITLE
Don't discard commit message entered without confirmation

### ISSUE THREAD

**Issue by focusaurus** [extrawurst/gitui#530]
**Is your feature request related to a problem? Please describe.**

So for vim users where typing ESC to exit insert mode is deep deep muscle memory, I find myself hitting `c` to commit, typing a message then by reflex typing ESC and having gitui discard the message I just crafted.

Anyone else shooting themselves with this footgun too?

**Describe the solution you'd like**

If the commit message is still empty, OK to close with a single ESC. But maybe if there's content entered, prompt to confirm before discarding?

**Describe alternatives you've considered**

Well something other than ESC would solve it too but that might make the overall keybinding style inconsistent.

**Comment by extrawurst** [comment]
fair point, actually this was the behaviour at some point. I agree we should go back to that 👍

**Comment by focusaurus** [comment]
Yay! Thank you!
