### ISSUE TITLE
more reliable and readable unittest for force push

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#537]
based off of #534 (and #535):

# Currently

@WizardOhio24 it looks like the internals of `repo_init` were unclear: it creates independent temporary test repositories (including an empty commit).

the current unittests both test essentially the same thing:

```
create **new** repo (a), add empty commit to (a)
create **new** repo (b), add empty commit to (b)
create bare repo (c)

now we commit some temp file to (a)
now we push from (a) to (c)

now we commit some temp file to (b)
test that we cannot push (b) to (c)

now force push (b) to (c) doing a history rewrite
```

only difference is that the second unittest `test_force_push_rewrites_history` does some additional checks that the right commit IDs are in `(c)` at the end.

# Desired

1) `test_force_push` can be simplified to just test that we can overwrite (c) with (b) - no additional file need to be committed

2) a real life use case would be nice where we *actually* create a repo (a), **clone** (a) to (b) and then have two commits that collide and test that force does what it should

**Comment by amalik18** [comment]
I can try this

**Comment by amalik18** [comment]
How do I assign it to myself?

**Comment by extrawurst** [comment]
> How do I assign it to myself?

Just open a PR when you are ready and mention this issue in it 👍
