### ISSUE TITLE
Incorrect documentation. key_config.ron is loaded from $HOME/Library/Application Support/gitui on Mac

### ISSUE THREAD

**Issue by JoyceBabu** [extrawurst/gitui#540]
**Describe the bug**

As per the documentation

> On first start gitui will create key_config.ron file automatically based on the defaults. This file allows changing every key binding.
> 
> The config file format based on the Ron file format. The location of the file depends on your OS:
> 
> - $HOME/.config/gitui/key_config.ron (mac)

But on macOS, the key_config.ron is created under `$HOME/Library/Application Support/gitui`

**To Reproduce**
1. Install gitui with `brew install gitui`
2. Run `gitui`

**Expected behavior**
`key_config.ron` to be created under `$HOME/.config/gitui`

**Context (please complete the following information):**
 - OS/Distro + Version: [`macOS 11.2.1`]
 - GitUI Version [`0.11`]

**Additional context**

**Comment by extrawurst** [comment]
Did you install via brew or cargo? Or did you build from master? This was changed since the last release

**Comment by JoyceBabu** [comment]
I installed with `brew install`.

**Comment by extrawurst** [comment]
For future reference - this changed in #317
