### ISSUE TITLE
when select log[2]   panic

### ISSUE THREAD

**Issue by jellybobbin** [extrawurst/gitui#542]
### env
```
macos     10.14.6
gitui     0.8.1
iterm2    3.3.4
```
### git log (It's a test, usually not very long)
```
commit 060deab38708174af142e79dee5f1abddee2bcd5 (HEAD -> master, origin/master)
Author: jelly <jellybobbin@gmail.com>
Date:   Thu Feb 25 09:18:16 2021 +0800

    兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼
容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報
基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功
能兼容力報基础功能
```
![屏幕快照 2021-02-25 09 26 59](https://user-images.githubusercontent.com/28227644/109089593-7a6b3c00-774c-11eb-97a2-399e4cb03d7f.png)

### gitui
```
panic: PanicInfo { payload: Any, message: Some(byte index 100 is not a char boundary; it is inside '容' (bytes 99..102) of `兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基础功能兼容力報基`[...]), location: Location { file: "/private/tmp/rust-20200705-74315-rfuccz/rustc-1.44.1-src/src/libcore/str/mod.rs", line: 1920, col: 47 } }
trace:
   0: backtrace::capture::Backtrace::new
   1: gitui::set_panic_handlers::{{closure}}
   2: std::panicking::rust_panic_with_hook
   3: _rust_begin_unwind
   4: core::panicking::panic_fmt
   5: core::str::slice_error_fail
   6: core::str::traits::<impl core::slice::SliceIndex<str> for core::ops::range::Range<usize>>::index::{{closure}}
   7: core::str::traits::<impl core::ops::index::Index<I> for str>::index
   8: asyncgit::sync::commits_info::get_message
   9: asyncgit::sync::commits_info::get_commits_info
  10: gitui::tabs::revlog::Revlog::update
  11: gitui::main
  12: std::rt::lang_start::{{closure}}
  13: _main
```

![屏幕快照 2021-02-25 09 32 14](https://user-images.githubusercontent.com/28227644/109089535-64f61200-774c-11eb-8ce0-51cf5767bb9f.png)

## But when the item window is properly sized, it is normal:
![屏幕快照 2021-02-25 09 43 50](https://user-images.githubusercontent.com/28227644/109090502-00d44d80-774e-11eb-826e-31eecd905389.png)

**Comment by extrawurst** [comment]
To allow me to reproduce this I would need to have the full commit message that contains this Unicode character. 

the Issue template asks for more information like the gitui version you used, please provide them

**Comment by extrawurst** [comment]
see #188 as reference

**Comment by jellybobbin** [comment]
ok,thanks...

**Comment by extrawurst** [comment]
> but it happened in my work, not at home (version 0.11.0), I need to confirm the version information tomorrow...

please also provide me with as much data as possible to reproduce this, the problem must be some unicode rendering that breaks but In order for this to be reproducible I need the message/author name that makes it break

**Comment by jellybobbin** [comment]
> > but it happened in my work, not at home (version 0.11.0), I need to confirm the version information tomorrow...
> 
> please also provide me with as much data as possible to reproduce this, the problem must be some unicode rendering that breaks but In order for this to be reproducible I need the message/author name that makes it break

No problem. In fact, it happened in two existing warehouses

**Comment by extrawurst** [comment]
> No problem. In fact, it happened in two existing warehouses

I assume a warehouse is a git repository? :)
if so its no wonder, its utf8 related and you probably use a lot multibyte characters in your names and commit messages

**Comment by jellybobbin** [comment]
> > No problem. In fact, it happened in two existing warehouses
> 
> I assume a warehouse is a git repository? :)
> if so its no wonder, its utf8 related and you probably use a lot multibyte characters in your names and commit messages

Yes, it's a git repository, so is it normal?

**Comment by jellybobbin** [comment]
@extrawurst 

I used itrem2. I found it is related to the size of itrem2 window. When itrem2 window is very small, it is normal. When itrem2 window is large (such as full screen), it will have problems.

**Comment by extrawurst** [comment]
@jellybobbin I just realize you created the same issue already in the past: #420
Now that you provided the information that this happens in `gitui 0.8.1` the answer is going to be the exact same: 

version `0.8.1` is **super old** and this bug is already fixed. please update or provide a reproduction that still crashes the most recent version.

**Comment by jellybobbin** [comment]
maybe it's too long and I forgot it.,thx..
