### ISSUE TITLE
on-demand branchname validity (while typing)

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#559]
libgit2 exposes a helper function to check a branch name validity: https://libgit2.org/libgit2/#HEAD/group/branch/git_branch_name_is_valid

lets run this against the input **before** it gets confirmed.
this way we can give live feedback to the user whether the name is valid.

**Comment by extrawurst** [comment]
same for tag names: https://libgit2.org/libgit2/#HEAD/group/tag/git_tag_name_is_valid

**Comment by franciscod** [comment]
hello there! rust newcomer here. will take a shot at this :)

**Comment by extrawurst** [comment]
> hello there! rust newcomer here. will take a shot at this :)

Very cool, welcome! Let me know when you need any help

**Comment by extrawurst** [comment]
requires upstream change first: https://github.com/rust-lang/git2-rs/issues/714

**Comment by franciscod** [comment]
wip: https://github.com/rust-lang/git2-rs/pull/715

**Comment by franciscod** [comment]
also wip: https://github.com/extrawurst/gitui/compare/master...franciscod:wip_check_branch_name

(won't create PR until the one in git2-rs lands)

**Comment by extrawurst** [comment]
@franciscod congrats for the merge in `git2-rs` but it did not contain the same function for tags which we also wanted to cover in here :(

**Comment by franciscod** [comment]
Thanks! `git_branch_name_is_valid` is the only one that I implemented. Internally it also checks that it's a valid name for a reference. Do we need anything else?

**Comment by franciscod** [comment]
ah, for tags, missed that one! Well #759 is my work in progress for branches, I guess we could do branches first and then tags?

**Comment by extrawurst** [comment]
after https://github.com/rust-lang/git2-rs/issues/734 we can at least go ahead with the branch validity check
