### ISSUE TITLE
gitui crashes with message 'invalid git path'.

### ISSUE THREAD

**Issue by torfmaster** [extrawurst/gitui#56]
**Describe the bug**
`gitui` crashes with message 'invalid git path'.

**To Reproduce**
1. Use `cargo install` to install gitui on ubuntu 18.10
2. type `gitui` in the command line
3. Hit return
4. See 'invalid git path' and observe that the app is not started.

**Expected behavior**
The app opens

**Desktop (please complete the following information):**
 - OS: ubuntu 18.10

**Comment by extrawurst** [comment]
Hi @torfmaster thanks for reaching out.

Are you running the `gitui` inside a valid git folder?

**Comment by torfmaster** [comment]
Actually, no. Running it in a git repo actually works. Thanks for pointing that out.

**Comment by extrawurst** [comment]
took the opportunity to make the error message more elaborate:
<img width="355" alt="image" src="https://user-images.githubusercontent.com/776816/81934338-17f6e400-95ef-11ea-98ca-4680384ec7aa.png">
