### ISSUE TITLE
[Feature Request] smart config loading

### ISSUE THREAD

**Issue by dm9pZCAq** [extrawurst/gitui#570]
I'm always frustrated when i update `gitui` and new key bindings or theme properties are added and because of this **ALL** keys and themes are set to default values

i see several solutions:
1. automatically update config/theme when new setting added
2. more verbose (maybe in message box inside `gitui` or just to `stderr`) say to user that new config added or something missing (with key bindings, you can find at least some messages in logs but with themes there is no messages)
3. load settings that can be loaded and set the missing properties to defaults

**Comment by extrawurst** [comment]
So the pending PR improves diagnostics by printing messages like:
```
Theme loading error: missing field `selected_tab`
 Old file was renamed to "/Users/stephan/.config/gitui/theme.ron.old".
 Defaults loaded and saved as "/Users/stephan/.config/gitui/theme.ron"
```
or
```
KeyConfig loading error: missing field `diff_stage_lines`
 Old config was renamed to "/Users/stephan/.config/gitui/key_config.ron.old".
 Default config loaded and saved as "/Users/stephan/.config/gitui/key_config.ron"
```

into stderr. it will still boot up using the default configs when something goes wrong. but it should be easier to diagnose and fix thanks to this
