### ISSUE TITLE
Please enable Github discussion boards

### ISSUE THREAD

**Issue by shaneutt** [extrawurst/gitui#590]
:wave: thanks for creating this great tool!

Would you be open to enabling "Github Discussions" for this tool? I know there's a discord, but adding forums seems like a preferable way to communicate async _and_ search previous conversations.

Just for your considerations, thank you!

**Comment by extrawurst** [comment]
Hi @shaneutt I never checkout discussions boards yet. I also did not work with any in other open source project. can you point me at a good example? right now I fail to see the use case that is not covered by discord for realtime and the issue tracker for formal conversations.

**Comment by shaneutt** [comment]
Here's an example of another Rust project that recently started using discussions:

https://github.com/clux/kube-rs/discussions

>  right now I fail to see the use case that is not covered by discord for realtime

For realtime, discord may still be the best option.

> and the issue tracker for formal conversations.

This is where I think discussions can be useful: they can be a bit more flexible as to whether they're formal/informal (whereas issues by their nature are often formal) and operate more like forums.

I think discussions make it helpful with these mentalities:

Bug, Problem, Feature Request? -> issues

Questions, thought experiments, anecdotes? -> discussions

And then it becomes possible to easily search in github the second group, which traditionally might have been something hosted in an external forum.

**Comment by extrawurst** [comment]
for now I feel like it would be overkill and just another platform to maintain for (mostly) me. I like the formality of issues that require a little effort for people to put in and welcome everyone to join the discord server if informal exchange is required. both is actually searchable and allows pinning and linking for easier discoverability.

**Comment by extrawurst** [comment]
we can revisit this if traffic or demand justifies this in the future
