### ISSUE TITLE
Recent versions not available on Fedora repos

### ISSUE THREAD

**Issue by kaushalyap** [extrawurst/gitui#599]
**Describe the bug**
gitui is not available on Fedora repos

**To Reproduce**

❯ sudo dnf install gitui
[sudo] password for user: 
Last metadata expiration check: 0:20:26 ago on Sun 21 Mar 2021 16:56:54 +0530.
No match for argument: gitui
Error: Unable to find a match: gitui

**Expected behavior**
Installation of gitui on Fedora

**Context (please complete the following information):**
 - OS/Distro + Version: Fedora 33

**Comment by extrawurst** [comment]
Hi @kaushalyap the fedora releases are not officially maintained, I am not fedora user.
@ignatenkobrain was handling this so far (see https://github.com/extrawurst/gitui/pull/95) 
It looks like at least gitui 0.11 should be available: https://bodhi.fedoraproject.org/updates/FEDORA-2020-b942f1a64f

If there are issues I depend on fedora folks to step up🤞

**Comment by ignatenkobrain** [comment]
Sadly F33 was complicated for some reason (don't remember details)… I hope me or @decathorpe will get to update gitui and then we can build it for F33 as well.

**Comment by decathorpe** [comment]
BTW: This issue should now be resolved with Fedora 34, at least. Fedora 33 is harder to support due to uninteresting reasons.
