### ISSUE TITLE
gitui crashes while try to show branches

### ISSUE THREAD

**Issue by RookiePC** [extrawurst/gitui#602]
**Describe the bug**
just open the gitui under my repo directory, and when I try to switch to the branches view by pressing the B button on keyboard, the gitui crashes. and logs the error :

```
panic: PanicInfo { payload: Any, message: Some(assertion failed: self.is_char_boundary(new_len)), location: Location { file: "/rustc/cb75ad5db02783e8b0222fee363c5f63f7e2cf5b/library/alloc/src/string.rs", line: 1132, col: 13 } }
trace:
   0: __mh_execute_header
   1: __mh_execute_header
   2: __mh_execute_header
   3: __mh_execute_header
   4: __mh_execute_header
   5: __mh_execute_header
   6: __mh_execute_header
   7: __mh_execute_header
   8: __mh_execute_header
   9: __mh_execute_header
  10: __mh_execute_header
  11: __mh_execute_header
  12: __mh_execute_header
  13: __mh_execute_header
```

**To Reproduce**
1. open gitui under my repo directory
2. press b
3. gitui crashed, and get error 

**Expected behavior**
I don't know, maybe show the branches tree

**Screenshots**
![image](https://user-images.githubusercontent.com/25848393/112279021-64568a00-8cbe-11eb-81a7-866473ae9894.png)

**Context (please complete the following information):**
 - OS/Distro + Version: macOS 10.15.7
 - GitUI Version 0.12.0
 - Rust version: 1.50

**Comment by extrawurst** [comment]
@RookiePC thanks for reporting this. can you share your branch names so that I can reproduce this? it must be a branch with a multibyte unicode character in the name

**Comment by extrawurst** [comment]
@RookiePC I found a clear problem with unicode truncation in there. can you build from latest master and check if it is fixed?

**Comment by RookiePC** [comment]
Sorry about the late reply, I've built from the master and it works!

![image](https://user-images.githubusercontent.com/25848393/112301890-62e48c00-8cd5-11eb-9f96-242512e7c89f.png)

many thanks!
