### ISSUE TITLE
v0.13.0 reports its version as v0.12.0

### ISSUE THREAD

**Issue by savchenko** [extrawurst/gitui#616]
**Describe the bug**
Subj. In the help menu (<kbd>h</kbd>) and `--version` flag.

**Expected behavior**
v0.13.0 is being truthful about itself.

**Screenshots**
N/A, no opportunity to make a screenshot on current machine.

**Context (please complete the following information):**
 - OS/Distro + Version: Debian 11
 - GitUI Version: v0.13.0 release
 - Rust version: N/A, pre-compiled musl from GitHub

**Comment by extrawurst** [comment]
are you sure you are not looking at the rc binary?

**Comment by savchenko** [comment]
```
4e475e810a695ac8696a7cc244d294e3ebb019a3  gitui
```

Downloaded pre-built from GH.

**Comment by savchenko** [comment]
Building from `master` works as expected:

![07-Apr_11-24-04](https://user-images.githubusercontent.com/300146/113799222-d6859f00-9793-11eb-8a75-3876672e7e51.png)

**Comment by extrawurst** [comment]
I do not know what happened there but the build process is automated for git-tags and the 0.13 tag has already the correct version set in the `cargo.toml`
