### ISSUE TITLE
Show history of individual files/directories

### ISSUE THREAD

**Issue by yurivict** [extrawurst/gitui#641]
**Is your feature request related to a problem? Please describe.**
No way to easily see history of changes of changes of one sub-sirectory or one file.

**Describe the solution you'd like**
Show the list of commits that affected a specific folder or a specific file with differences or versions of files before/after commits.

**Additional context**
I work with the FreeBSD ports directory repository. Each port is like a sub-project. Sometimes I just need to focus on one such directory and see how it changed overtime.

The overall commit list doesn't help because relevant commits are a very small portion of the whole list.

**Comment by ogoes** [comment]
Hi, I'm new here and with Rust, I really liked your suggestion. I would like to write some code, can I start with this feature?

**Comment by extrawurst** [comment]
this is actually on the roadmap to release `1.0` and was tracked in #381 (before eager stale-bot closed it) this is only an implementation detail allowing folder and not just *specific file* to get the commit log of. so I will close this as a duplicate for now.
