### ISSUE TITLE
Push fails with too many redirects or authentication replays

### ISSUE THREAD

**Issue by cemremengu** [extrawurst/gitui#642]
As the title says push operation to a branch fails with:

`push failed:  git error: too many redirects or authentication replays; class=Http (34)`

**To Reproduce**
I just try to push to my branch (works fine in git bash)

**Screenshots**
![image](https://user-images.githubusercontent.com/1297759/114669174-4652d700-9d0a-11eb-8ced-13995adf1a76.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 10
 - GitUI Version: 0.14

**Comment by extrawurst** [comment]
people had that issue with `libgit2` in the past in other places: 
* https://github.com/libgit2/libgit2sharp/issues/1168
* https://stackoverflow.com/questions/26145023/libgit2sharp-fetching-fails-with-too-many-redirects-or-authentication-replays

**Comment by cemremengu** [comment]
Never encountered this before but pretty sure it is windows thing 😄 

Thanks for your work by the way. This is much faster than the current git bash etc. tools on windows which were painfully slow
