### ISSUE TITLE
Custom Pager Integration (delta, diff-so-fancy, etc)

### ISSUE THREAD

**Issue by JacobTravers** [extrawurst/gitui#650]
I think it would be really awesome if we could add an integration for custom pagers like [delta](https://github.com/dandavison/delta) or [diff-so-fancy](https://github.com/so-fancy/diff-so-fancy) in the same way [lazygit does](https://github.com/jesseduffield/lazygit/blob/master/docs/Custom_Pagers.md) with a config option.

**Comment by bhaak** [comment]
If for technical or whatever reasons you prefer an integrated Rust solution, https://github.com/mookid/diffr has a library component.

**Comment by extrawurst** [comment]
duplicate of https://github.com/extrawurst/gitui/issues/358
