### ISSUE TITLE
blame (sometimes) slow

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#673]
@cruessler I use the linux repo as a worst case git repo often to benchmark. doing a blame on `include/uapi/linux/netfilter/xt_MARK.h` takes incredibly long. we should look into this. (hope its not the underlying `libgit2` to blame):

`gitui.log`:
```
13:16:08 [TRACE] (2) scopetime: [scopetime/src/lib.rs:41] scopetime: 197212 ms [asyncgit::sync::blame::blame_file] @asyncgit/sr
c/sync/blame.rs:57
```

git cli blame:
```
time git blame include/uapi/linux/netfilter/xt_MARK.h
Blaming lines: 100% (16/16), done.

git blame include/uapi/linux/netfilter/xt_MARK.h  2.97s user 0.68s system 25% cpu 14.048 total
```

**Comment by cruessler** [comment]
I just had a look at the issue (also using the linux repo). On my machine, `repo.blame_file` seems to be responsible for the wait. As far as I could see, no other call even came close to having an influence.

**Comment by extrawurst** [comment]
Seems a known issue: https://github.com/libgit2/libgit2/issues/3027

**Comment by cruessler** [comment]
One solution I found would be to shell out to `git` and parse the output: https://github.com/Arrowbox/git-whoknows/commit/70ca833a6f957a0b7a42d6aaff4c0c9dddc3a47b. But that would mean having `git` installed as a dependency.

**Comment by extrawurst** [comment]
> One solution I found would be to shell out to `git`

that is not an option. we made it this far without that :)
I'd rather checkout optimising the blame algorithm inside `libgit2`

**Comment by muman613** [comment]
Just started using libgit2 with the hopes of using it to automate extracting blame info from git repos. Found it it takes a VERY LONG time to run a blame using libgit2 compared to running `git blame`. I was hoping to find a way to speed it up... Looks like Im not the only one.

**Comment by muman613** [comment]
For the record, I just observed a release build (from source) example `lg2 blame` take 3 minutes and 12 seconds to extract the blame report compared to the `git blame` report which is generated in .094 seconds....

Seriously that is dismal performance. Not that it is anyones fault, but I cannot use this in a real world situation with such a delay to just extract the blame information. I will be dealing with 100s of files which will need to extract blame info for lines in the source. At this rate it will take weeks to just generate the report.

Thank you. And if there is a good solution I will certain listen, and if there is a patch I can try, I'll try it.

**Comment by extrawurst** [comment]
This has to be fixed upstream in libgit2
