### ISSUE TITLE
Theme colors

### ISSUE THREAD

**Issue by pkieltyka** [extrawurst/gitui#677]
Hi there, wonderfully executed project!

One question however, I'm using "robbyrussell" zsh theme.. which looks like:

![image](https://user-images.githubusercontent.com/18831/116797506-7e9d3800-aab4-11eb-91ab-ead78a09b6c9.png)

However, the theme of gitui is very difficult to read as you can see the bottom bar:

![image](https://user-images.githubusercontent.com/18831/116797511-8f4dae00-aab4-11eb-84dc-a2567e4a4cb5.png)

in the theme, the "Blue" looks more like a cyan on my computer. And even if I try to edit the theme.ron at ~/.config/gitui/theme.ron -- I can't actually find the setting of the bottom bar, no matter which setting I try and any other color. Any help would be appreciated as its a great program, but I can't read these colours unless I change my terminal theme colours which I'd prefer to not

**Comment by extrawurst** [comment]
The bottom bar background color is using what's called `selection_bg` in the theme file. Changing that should help you

**Comment by pkieltyka** [comment]
got it, Rbg() has been helpful. 

What does "Indexed" do btw?

perhaps would be nice to update the themes doc to include the color options, and also mention any other hints, or even drop a few theme ron files
