### ISSUE TITLE
Authentication error

### ISSUE THREAD

**Issue by RexTremendae** [extrawurst/gitui#680]
**Describe the bug**
Authentication fails from gitui, but the same operation works just fine from the git CLI. In this example I tried to push a new branch to my forked gitui-repo on GitHub.

**To Reproduce**
1. Create a new branch from the branches dialog
2. From the Status tab in the main view, press [p] push the branch to remote 
3. Branch is not pushed because of authentication error

**Expected behavior**
Should be able to push branch to remote - it is my own repo, and I can do the same operation from the git CLI without any errors.

**Screenshots**
![authentication](https://user-images.githubusercontent.com/6555002/117062334-9f1ef980-ad23-11eb-8f67-3c4fd918293e.png)

**Context (please complete the following information):**
 - Windows 10 (19042.928)
 - GitUI v0.15.0
 - Git CLI v2.28.0.windows.1

**Additional context**
Authentication to GitHub is setup with an SSH key located in my user profile.

![git_origin](https://user-images.githubusercontent.com/6555002/117062803-3421f280-ad24-11eb-938a-647585a14ed3.png)

**Comment by RexTremendae** [comment]
Just found #495 which seems to be the same issue. Sorry for being too quick... But on the bright side, more user data :D

**Comment by extrawurst** [comment]
Closing in favor of #495
