### ISSUE TITLE
Create remote branch and make local branch track it on first push

### ISSUE THREAD

**Issue by Logarithmus** [extrawurst/gitui#684]
**Is your feature request related to a problem? Please describe.**
In plain `git` I can use `git push -u origin <branch_name>` to set upstream branch and push in a single command. Unfortunately, I didn't find similar functionality in `gitui`.

**Describe the solution you'd like**
I'd like `gitui` to create remote branch and make local branch track it automatically on first push to this branch.
For instance, `lazygit` does it automatically.

**Describe alternatives you've considered**
Of course, I can use `git` directly, but switching between terminals wastes a bit of time.

**Comment by extrawurst** [comment]
if you push a branch that you created locally it automatically pushes to origin/<branchname> and sets the local remote tracking branch accordingly. can you check if that does what you expect?

**Comment by Logarithmus** [comment]
> if you push a branch that you created locally it automatically pushes to `origin/<branchname>` and sets the local remote tracking branch accordingly. can you check if that does what you expect?

Sorry for bothering you, the problem was in wrong `refspec` specified in `.git/config`. I cloned that repo with `--depth` option.
