### ISSUE TITLE
Show the branching structure in the log.

### ISSUE THREAD

**Issue by oakmegaeddie** [extrawurst/gitui#685]
**Is your feature request related to a problem? Please describe.**
It can be useful seeing the branching/merging structure in the log view, in a similar way to `git log --oneline --decorate --graph`

**Describe the solution you'd like**
The graph view visible in the log window.

**Describe alternatives you've considered**
I haven't got any other alternatives other than not doing it. :-)

**Additional context**
The issue #81 has been closed and marked `wonfix` by the bot, therefore I copy the content and create a new issue here.

**Comment by extrawurst** [comment]
Let's keep track of this in the old ticket, since we link that from the roadmap in the reader already.
