### ISSUE TITLE
Is branch merging and rebasing actually supported?

### ISSUE THREAD

**Issue by Logarithmus** [extrawurst/gitui#686]
Hello again! I continue learning `gitui`, but unfortunately didn't find how to merge and/or rebase branches. I see only `checkout` option in branches popup.
Related: https://github.com/extrawurst/gitui/issues/302, https://github.com/extrawurst/gitui/issues/91

**Comment by extrawurst** [comment]
you cannot merge arbitrary branches into your current branch yet, no.

**Comment by Logarithmus** [comment]
> you cannot merge arbitrary branches into your current branch yet, no.

Is anyone working on this feature?

**Comment by extrawurst** [comment]
no because it kind of depends on #485 to first land, so that not only *super-happy-path* merges work

**Comment by extrawurst** [comment]
@Logarithmus as of 4f6aceb merging a branch is supported, but there is a bit of stuff missing: https://github.com/extrawurst/gitui/issues/485#issuecomment-835887226

**Comment by extrawurst** [comment]
Closing as duo of #32 now - merge is supported by now
