### ISSUE TITLE
Move to Stage Changes pane after adding all unstaged changes

### ISSUE THREAD

**Issue by fernandoacorreia** [extrawurst/gitui#706]
**Is your feature request related to a problem? Please describe.**
When am In in the Unstaged Changes pane, and I add all files (via "a" or by using Enter on all of them), the next step in the workflow is always to use the down arrow to move to the Stage Changes pane, where I can commit.

**Describe the solution you'd like**
After an "add" operation (a or Enter) that adds the last unstaged change, when the list of unstaged changes becomes empty, move the focus to the Stage Changes panel.

**Describe alternatives you've considered**
Enabling commit on the unstaged changes panel. This is not ideal because having focus on Staged Changes makes it more clear what will be committed, and allows the user to review the changes one last time.

**Additional context**
<img width="1440" alt="Fullscreen_5_14_21__9_22_AM" src="https://user-images.githubusercontent.com/17158/118299746-fcd6e280-b495-11eb-9d3a-329caafcc96f.png">

**Comment by extrawurst** [comment]
@fernandoacorreia good idea👍
