### ISSUE TITLE
[0.2.5] app crashes when pressing h

### ISSUE THREAD

**Issue by guss77** [extrawurst/gitui#71]
**Describe the bug**
When using the app on Ubuntu 20.04, in either view, pressing "h" for help causes the application to exit with exit code 101.

Running under strace, it doesn't look like anything bad happens - there are no signals and then something calls `exit_group(101)`.

**To Reproduce**
1. Install Ubuntu 20.04
2. Download Linux release 0.2.5 from Github
3. cd to some git working directory and run `gitui`
4. Press "h"

**Expected behavior**
Some kind of help message should appear, I guess?

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Version 0.2.5

**Comment by extrawurst** [comment]
hey @guss77 thanks for reaching out, can you check if this might be actually a dup of #63 ? If so I make sure I will do a release to offer you the fix.

**Comment by extrawurst** [comment]
@guss77 please check if release `0.2.6` fixes the issue for you: https://github.com/extrawurst/gitui/releases/tag/v0.2.6

**Comment by extrawurst** [comment]
Please let me know if you still find the issue in version >= `0.2.6`

**Comment by guss77** [comment]
This problem indeed sounds like #63 , I'll move further communications there.
