### ISSUE TITLE
Selected tab is hardcoded to white and cannot be changed via theme

### ISSUE THREAD

**Issue by Cottser** [extrawurst/gitui#719]
**Describe the bug**
The selected tab is not overrideable via the theme, and in addition it is hardcoded to white since around v0.11.0-rc1.

I recently have been trying a light theme, that's how I noticed this.

I will be submitting a PR to at least remove the hardcoding to white, and if you'd like I can also restore the previous coloring of `selected_tab` but probably needs discussion.

**To Reproduce**
1. Change your terminal emulator to a light theme
2. Launch `gitui`
3. Notice the white-on-white

**Expected behavior**
I would expect the selected tab to at least be neutral colored, or to respect the theme.ron settings.

When editing theme.ron I thought this was controlled by `selected_tab`, but I tested v0.10.1 and it seems like it's been neutral colored for quite some time (since v0.3.0 when theme overrides were added).

**Screenshots**

v0.15.0, light and dark with no theme overrides:

![0 15 0-light](https://user-images.githubusercontent.com/327943/119129525-08318d00-ba05-11eb-90ef-e67a9f0e9af3.png)

![0 15 0-dark](https://user-images.githubusercontent.com/327943/119129548-0ff13180-ba05-11eb-9892-cf9abbea6bb5.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Pop!_OS 20.10
 - GitUI Version: v0.15.0
 - Rust version: Not sure, but probably not relevant in this case. I installed gitui via nixpkgs but I can reproduce the behaviour by building gitui from source.

**Additional context**

<details>
<summary>Screenshots from v0.2.6 (before initial color theme support was added)</summary>

![0 2 6-light](https://user-images.githubusercontent.com/327943/119129724-4b8bfb80-ba05-11eb-9daa-f34c91a99020.png)

![0 2 6-dark](https://user-images.githubusercontent.com/327943/119129735-4e86ec00-ba05-11eb-94c3-66a2011e56d3.png)

</details>

<details>
<summary>Screenshots from v0.10.1 (before the selected tab was hardcoded to white)</summary>

![0 10 1-light](https://user-images.githubusercontent.com/327943/119129746-534ba000-ba05-11eb-9aea-33b27baad142.png)

![0 10 1-dark](https://user-images.githubusercontent.com/327943/119129759-58a8ea80-ba05-11eb-99c2-c5340d8c550f.png)

</details>

**Comment by extrawurst** [comment]
closed via #722
