### ISSUE TITLE
selected_tab in theme.ron might not do anything

### ISSUE THREAD

**Issue by Cottser** [extrawurst/gitui#722]
**Describe the bug**
The selected tab does not appear to be overrideable via the theme. (theme.ron has a `selected_tab` key)

**To Reproduce**
1. Edit theme.ron to change `selected_tab` to something wacky (I suggest `Red` or `Magenta` or `Cyan`)
2. Launch `gitui`
3. Open up various parts of the UI, and check for your color override (I couldn't find it anywhere)

**Expected behavior**
I would expect the selected tab (on launching `gitui` this should be "Status") to take the `selected_tab` value from the theme.ron config.

**Screenshots**

<details>
<summary>Screenshots from v0.2.6 (before initial color theme support was added)</summary>

![0 2 6-light](https://user-images.githubusercontent.com/327943/119129724-4b8bfb80-ba05-11eb-9daa-f34c91a99020.png)

![0 2 6-dark](https://user-images.githubusercontent.com/327943/119129735-4e86ec00-ba05-11eb-94c3-66a2011e56d3.png)

</details>

**Context (please complete the following information):**
 - OS/Distro + Version: Pop!_OS 20.10
 - GitUI Version: v0.15.0
 - Rust version: Not sure, but probably not relevant in this case. I installed gitui via nixpkgs but I can reproduce the behaviour by building gitui from source.

**Additional context**

<details>
<summary>Screenshots from v0.10.1 (after theme support was added, but before the selected tab was hardcoded to white)</summary>

![0 10 1-light](https://user-images.githubusercontent.com/327943/119129746-534ba000-ba05-11eb-9aea-33b27baad142.png)

![0 10 1-dark](https://user-images.githubusercontent.com/327943/119129759-58a8ea80-ba05-11eb-99c2-c5340d8c550f.png)

</details>

#719 is related.

**Comment by extrawurst** [comment]
Thanks! closed via #723
