### ISSUE TITLE
open_commit_editor missing/not working

### ISSUE THREAD

**Issue by MagicDuck** [extrawurst/gitui#728]
**Describe the bug**
can't see the open_commit_editor command in the commands section at the bottom, and can't activate it when pressing hte key bind configured in key_config.ron
```
    open_commit: (
        code: Char('m'),
        modifiers: (
            bits: 0,
        ),
    ),
    open_commit_editor: (
        code: Char('c'),
        modifiers: (
            bits: 0,
        ),
    ),

```
Pressing 'e' to edit a file in vim works...

**To Reproduce**
1. configure key_config.ron as above
2. open gitui, move to Staged Changes pane 
3. try to press 'c'

**Expected behavior**
commit message is opened in vim

**Screenshots**

**Context (please complete the following information):**
 - OS/Distro + Version: `macOS 10.14.6`
 - GitUI Version: 0.15.0
 - Rust version: n/a as installed through brew...

**Comment by extrawurst** [comment]
For obvious reasons you cannot use a key bind to open the external editor that is a valid text input character.

**Comment by extrawurst** [comment]
I will use this issue as an opportunity to extend the comment in the vi key bindings to make this more clear

**Comment by MagicDuck** [comment]
@extrawurst I am so dumb, when I wrote this I didn't realize you have to be in the commit window context in order to open in external editor. In my case, I always open in external editor because I have some vim magic that uses the part of the branch name to create a template. Would it be possible to commit with external editor from the top level without committing first?

**Comment by extrawurst** [comment]
> Would it be possible to commit with external editor from the top level without committing first?

not right now and I also do not see the huge upside of this

**Comment by MagicDuck** [comment]
pressing `c` followed by `<C-e>` each time one wants to commit is really awkward. It's too bad since all the other navigation within gitui is amazingly smooth... 😢
