### ISSUE TITLE
Open gitui in a given directory (gitui --cd=xyzdir/)

### ISSUE THREAD

**Issue by alistaircarscadden** [extrawurst/gitui#73]
**Is your feature request related to a problem? Please describe.**

I'd like to set the tool up so that when I right click on a directory (in windows) it launches gitui in the clicked directory. To do this I'd need a way to open the program in a different directory.

**Describe the solution you'd like**

`gitui.exe --cd=projectdir` to open the tool in the directory called projectdir

**Describe alternatives you've considered**

The context menu works fine from inside the directory, but with git bash I'm used to clicking on a directory to open that tool, so it would be nice if this tool mirrored that behaviour. This is a low priority thing.

**Additional context**

![image](https://user-images.githubusercontent.com/7132621/82402346-2a778000-9a2a-11ea-87d8-9bc99f86d8e8.png)

**Comment by extrawurst** [comment]
hm couldn't that be done using a `*.bat` that does the `cd $1 && gitui` ? (sorry I a, no good in windows batch)

**Comment by alistaircarscadden** [comment]
To create the 'open w/ gitui' option in the context menu in Windows you create an entry in the Registry Editor. There are different registry keys for what appears in the context menu when you click inside a folder vs. when you click on a folder.

When you click inside of a folder, the gitui can be opened with no extra options, as the directory is already correct. See:

![image](https://user-images.githubusercontent.com/7132621/82458282-7ce58a80-9a84-11ea-9e5d-933740862de8.png)

However, when you right click on a folder, the system opens the executable given from the current directory and provides the item you clicked on as `%1`. You can see how git-bash does it here:

![image](https://user-images.githubusercontent.com/7132621/82458491-b9b18180-9a84-11ea-869e-3591d1bd9e05.png)

So you gave me a good idea with the batch script. One limitation is that the value in regedit isn't run with a shell, rather just executed as a process, so putting something like `pushd %1 && gitui.exe` isn't possible. But, I created a gitui-in.bat that contains...

```
pushd %1
gitui.exe```

and by setting the registry to...

![image](https://user-images.githubusercontent.com/7132621/82458983-612eb400-9a85-11ea-92bb-beffcc87c96c.png)

I'm able to get it to work. Anyways, the --cd behaviour is supported by git bash as --cd and by PowerShell as -command Set-Location -literalPath, so I think it would feel a lot less hacky to do it with this tool as well.

**Comment by MCord** [comment]
another trick that might be useful is to run cmd directly like:

```cmd
cmd /c "cd /d %1 && gitui"
```
this way you don't need a batch file.

**Comment by alistaircarscadden** [comment]
@MCord I tried it and it works. Good idea.

**Comment by extrawurst** [comment]
wow you windows people, that is cool stuff!
@alistaircarscadden thanks for taking the time to put this together.
