### ISSUE TITLE
question: Diff pane: is there a command to jump between hunks or scroll a set number of lines?

### ISSUE THREAD

**Issue by MagicDuck** [extrawurst/gitui#731]
**Is your feature request related to a problem? Please describe.**
Was looking for a command to jump between hunks, I see page_up & page_down, but nothing more granular (except <up> and <down> arrows)

**Describe the solution you'd like**
some command to move between hunks or scroll up/down like 10 lines at a time

**Describe alternatives you've considered**
not sure there's any

**Additional context**

**Comment by extrawurst** [comment]
No we do not have such a command. We also have no way to define such combo commands necessary to do that. So far I never missed such a feature since we have up/down, paging and home/end. Might be more a habit for vim users and the fact that this is a common navigation method there.
