### ISSUE TITLE
Gitui is not compiling

### ISSUE THREAD

**Issue by KorobeinikovIgor** [extrawurst/gitui#739]
**Screenshots**
![image](https://user-images.githubusercontent.com/73735838/119660270-ba1eee00-be37-11eb-9e94-b6e41a9e1e07.png)

 - OS/Distro + Version: [e.g. `Kali Linux Raspberry Pi 4`]
 - GitUI Version [e.g. `0.5`]
 - Rust version: [e.g `1.48.0`]

**Comment by extrawurst** [comment]
min supported rust version is: `1.50`

**Comment by KorobeinikovIgor** [comment]
thanks!
