### ISSUE TITLE
Command Commit [enter] closes/crashes gitui-win

### ISSUE THREAD

**Issue by alistaircarscadden** [extrawurst/gitui#74]
**Describe the bug**
In gitui-win v0.2.6 after staging, and after writing a commit message, pressing Enter abruptly closes the gitui.exe window. Inspecting the repo after shows that the commit is not made.

**To Reproduce**
1. Create new directory and cd into it
2. Run git init
3. Add a file to be committed (file.txt)
4. Run gitui.exe
5. Press enter on the file in the unstaged menu
6. Press 2 to enter the staged menu
7. Press Commit [c]
8. Enter a message
9. Press Commit [enter]

**Expected behavior**
The commit should be made and the ui would update to reflect that without closing.

**Desktop (please complete the following information):**
gitui-win v0.2.6

**Comment by alistaircarscadden** [comment]
After some testing I discovered that the bug does not occur after I run `git config user.name myname`. So, without a username it crashes, and with a username it works just fine. With or without an email it works, as long as it has a name.

**Comment by extrawurst** [comment]
Good point! Currently it is expected to have the name set. Let me look into it

**Comment by extrawurst** [comment]
so instead of panicking it should show an expressive error now:
<img width="663" alt="Screenshot 2020-05-20 at 11 24 11" src="https://user-images.githubusercontent.com/776816/82430122-35173100-9a8d-11ea-916d-b1f4ac330c67.png">

will roll out in next release

**Comment by extrawurst** [comment]
should be fixed in `0.3.0`: https://github.com/extrawurst/gitui/releases/tag/v0.3.0

**Comment by alistaircarscadden** [comment]
I did a bit more looking around, and discovered I was wrong in my most recent comment. The git behaviour is it allows a commit to be made as long as at least a user.name or user.email is provided. The author shows up as `unknown <email@example.com>` if only an email is provided or `name <>` if only a name is provided.

When the condition is not met it shows the `*** Please tell me who you are.` message.

So, as it is right now gitui does not allow me to make a commit when git commit allows me to. Good work, by the way! :)

**Comment by extrawurst** [comment]
I am not sure I follow. Does the crash persist for you? Is there a different behavior that we need to look into?

**Comment by extrawurst** [comment]
@alistaircarscadden make sure to reopen the ticket if there is still the issue

**Comment by alistaircarscadden** [comment]
The crash is fixed, and I see the menu that you showed in your screenshot. I'm considering it may be a bug that gitui does not allow a commit in the same conditions git does allow one.

The conditions are when a user.email is present, and a user.name is not. git commit works, but committing with gitui does not.

**Comment by extrawurst** [comment]
@alistaircarscadden what error does it show when trying to commit in those conditions?

**Comment by extrawurst** [comment]
@alistaircarscadden `gitui` does not use the `git cli` and you are right, what works in regular git, should be possible in `gitui`. Please file a new ticket for this and please add the error message that `gitui` currently returns in that case.

**Comment by alistaircarscadden** [comment]
Ok! It's more complicated then I thought, I'll make an issue.
