### ISSUE TITLE
Support annotating git tags

### ISSUE THREAD

**Issue by skyfaller** [extrawurst/gitui#747]
**Is your feature request related to a problem? Please describe.**
When using git directly, I can write e.g. `git tag -a v0.0.28` to open an editor to annotate that tag. This is especially handy on platforms aside from GitHub that do not have its proprietary UI for publishing releases.

gitui does not yet support annotating tags, despite supporting creating and pushing tags, which means I have to drop back to the standard git command line to annotate tags.

**Describe the solution you'd like**
For git commit messages, gitui allows you to open your editor to leave a longer message if one line is not enough. Something similar may work well for annotating tags. Perhaps the keyboard shortcut could be "a" for annotate, to echo the git command line option.

**Additional context**
extrawurst [asked me to file this feature request](https://lobste.rs/s/l2rb4r/gitui_v0_16_supports_merging#c_lkrnlo).

**Comment by amalik18** [comment]
I can give this a shot

**Comment by extrawurst** [comment]
@amalik18 any update from your side?

**Comment by extrawurst** [comment]
![Screenflick Movie 30](https://user-images.githubusercontent.com/776816/149134740-218dea4b-a3d7-4a96-ab82-11e2bfe37bd7.gif)
