### ISSUE TITLE
Log tab shows no commits when there is 1 commit

### ISSUE THREAD

**Issue by alistaircarscadden** [extrawurst/gitui#75]
**Describe the bug**
In gitui-win v0.2.6 the Log tab shows nothing when there is exactly 1 commit. When the second commit is added, both the first and second commit will appear in the Log when you go to the tab.

Furthermore, when there are 2 commits (for example "Initial commit" and "Add readme") the text in the top left of the Log tab shows "commit 0/1" instead of 2/2.

**To Reproduce**
1. Create new directory and cd into it
2. Run git init
3. Add a file to be committed (file.txt)
4. `git add .` and `git commit -m "Initial commit"`
5. Run gitui and press Tab to enter the Log page

(for me, it will show there are no commits)

6. Create another file, stage it, commit it
7. Run gitui and press Tab to enter the Log page

(for me, it will show both commits)

**Expected behavior**
When there is exactly 1 commit the Log page would show it, as well as the top left text would read 'commit 1/1'

My impression would also be that the 'commit x/y' message would show y equals the total number of commits, and x equals the (1-indexed) number that is currently highlighted, where the very first commit is 1 and the most recent is >1.

**Desktop (please complete the following information):**
gitui-win v0.2.6

**Comment by extrawurst** [comment]
Hey @alistaircarscadden thanks for your interest in `gitui`! Indeed good catch! Should be fixed now, will roll out in the next release.

**Comment by extrawurst** [comment]
should be fixed in `0.3.0`: https://github.com/extrawurst/gitui/releases/tag/v0.3.0

**Comment by alistaircarscadden** [comment]
![image](https://user-images.githubusercontent.com/7132621/82457456-73a7ee00-9a83-11ea-9fd8-b374ed88b66f.png)

![image](https://user-images.githubusercontent.com/7132621/82457620-a3ef8c80-9a83-11ea-9a2e-fe4ee8e9599c.png)

Confirmed working. Thanks!
