### ISSUE TITLE
[Feature Request]: Integration with Delta 

### ISSUE THREAD

**Issue by samebchase** [extrawurst/gitui#754]
While using gitui to browse through some commits to understand the changes made, the lack of syntax highlighting was affecting the readability.

I was wondering whether https://github.com/dandavison/delta could be used to render the diffs. This way we can get full syntax highlighting (for all languages supported by bat) instead of the standard red/green diff highlighting.

In any case, thanks for your work on gitui. It's great! 💯🙏

**Comment by extrawurst** [comment]
dup of #358
