### ISSUE TITLE
refactor AsyncTags to use AsyncJob

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#757]
we have a lot of code duplication in the async implementations in the root of `asyncgit/src/*`. for a while we now have a unified abstraction that can be used instead: `AsyncJob` this is used already in `AsyncRemoteTagsJob` and `AsyncSyntaxJob`.

Lets one-by-one cleanup the other places starting with `AsyncTags`

**Comment by mvaneijk** [comment]
I would like to give this a try. It will be my first contribution to a rust project.

**Comment by extrawurst** [comment]
@mvaneijk may I suggest to start with `asyncgit/src/tags.rs`? It is essentially the same change but much less code, so probably a less daunting entry

**Comment by extrawurst** [comment]
@mvaneijk I added a more elaborate description above. hope that gives you a good place to start 👍

**Comment by mvaneijk** [comment]
@extrawurst Looks good, I'll give it a go.
