### ISSUE TITLE
support "undo last commit"

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#758]
I like this feature in vscode:

* it sets HEAD back to the previous commit 
* puts all changes back into the index

**Comment by franciscod** [comment]
git-cola (https://git-cola.github.io/) has this since forever, it's a nice feature :) I think it's `git reset --soft` combined with some magic to preserve the commit message

**Comment by extrawurst** [comment]
> git-cola (https://git-cola.github.io/) has this since forever, it's a nice feature :) I think it's `git reset --soft` combined with some magic to preserve the commit message

Does that mean you want to implement this? Or what’s your point? ;)

**Comment by franciscod** [comment]
maybe once i finish #759 :)

**Comment by kosayoda** [comment]
Would a more generic feature be supporting resets to any commit in the log? That would be a nice feature in my opinion.

**Comment by extrawurst** [comment]
> Would a more generic feature be supporting resets to any commit in the log? That would be a nice feature in my opinion.

Reset to a commit is different to what the proposal says. Git reset does not put all the changes that were rolled back into the index
