### ISSUE TITLE
support new windows package manager winget

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#76]
MS announced a package manager: https://devblogs.microsoft.com/commandline/windows-package-manager-preview/

would be nice to be in there!
maybe it also allows being updated as part of our `CD` pipeline.

As I am not on windows, I am going to need help here :)

**Comment by MCord** [comment]
winget is still very early stage and only open to Insider Program members. I think it's best to wait for the first version to get out. in the mean time I suggest to provide support for https://chocolatey.org/ which is the most popular package manager for windows.

**Comment by extrawurst** [comment]
Good idea. Then let's Wait for this. If you say https://chocolatey.org/ is worth doing either way let's do that in a new issue specific for that
