### ISSUE TITLE
File tree pane: folders won't collapse on Windows

### ISSUE THREAD

**Issue by enizor** [extrawurst/gitui#761]
## Description

The new file tree pane [3] has some problematic behavior on Windows.

Using Left/Right Arrow [→←] to collapse/expand folders will correctly toggle the little triangle ▾ ▸ next to the folder (and jump to parent/child on second press). However the file list is not updated so all the subfolders are still visible in the tree after a collapse. 
All subfolders are visible when opening the file tree (but marked collapsed ▸) so the result is a list of all folders and files in the repository.

Note: the bug is **not** present when using Ubuntu via WSL.

## Reproduction

Launch gitui, open File Tree pane with [3].

**Expected behavior**
Only the first-level folders and files are visible

**Actual behavior**
All folders and files are visible

In the file tree, use arrow keys to collapse and expand some folders

**Expected behavior**
Files and folders appear and disappear when their parent is collapsed / expanded

**Actual behavior**
No change in the file list, excepted for the triangles ▾ ▸ 

## Context

- OS/Distro + Version: Windows 10, reproduced on both cmd.exe and Windows Terminal
- GitUI Version 0.16.0
- Rust version: 1.52.1

## Additional Notes

It's not a big issue (for me) since the file tree pane is not the main feature I use in gitui. However I understood that the file tree component is to be reused in other places, in particular in the status view. That would really get in my way (and most Windows users too).

**Comment by extrawurst** [comment]
Does the view update correctly after a couple of seconds (it refreshes every few seconds even if no input is given)?

**Comment by enizor** [comment]
Nothing changes over time without inputs.

**Comment by extrawurst** [comment]
argh damn windows path separators. ok I found the problem

**Comment by enizor** [comment]
Seems like it, changing `/` to `\` in the input of `filetreeitems::tests::test_collapse` will break the test. If the paths are not normalized before using `FileTree::new()` this might be the cause

**Comment by extrawurst** [comment]
Will be fixed in a few

**Comment by enizor** [comment]
I can test a patch/commit on my machine should you need it

**Comment by extrawurst** [comment]
@enizor you can test the PR

**Comment by enizor** [comment]
Thanks a lot!
