### ISSUE TITLE
Basic Authentication is deprecated

### ISSUE THREAD

**Issue by iresharma** [extrawurst/gitui#763]
Recently I pushed to repository using gitui and seconds later I got the following mail

> Hi @iresharma,
>
> You recently used a password to access the repository at iresharma/realWorld.io with git using git/2.0 (libgit2 1.1.0).
>
> Basic authentication using a password to Git is deprecated and will soon no longer work. Visit https://github.blog/2020-12-15-token-authentication-requirements-for-git-operations/ for more information around suggested workarounds and removal dates.
>
> Thanks,
> The GitHub Team

### Any clues on when this can be fixed ?

**Comment by extrawurst** [comment]
this cannot happen unless you provided username/password in `gitui` or via your git config, so there is not much I can do

**Comment by iresharma** [comment]
Then can you please tell me what is correct way of doing it ?

**Comment by extrawurst** [comment]
> Then can you please tell me what is correct way of doing it ?

Use an ssh key, GitHub has documentation how to set that up. I am closing this as it is not specific to gitui but using git in general
