### ISSUE TITLE
Allow ^Z to suspend gitui

### ISSUE THREAD

**Issue by anahata0108** [extrawurst/gitui#765]
**Is your feature request related to a problem? Please describe.**
I was attempting to silence the spurious terminal activity I described in #764 by suspending gitui with ^Z, like I would with many other Unix shell applications. However, the application doesn't respond to ^Z so I cannot suspend it.

**Describe the solution you'd like**
I'd like ^Z to be able to suspend gitui, like it does for other applications.

**Describe alternatives you've considered**
There aren't really any alternatives for this besides quitting the application. This isn't ergonomic for large repositories that take a while to load.

**Comment by extrawurst** [comment]
this won't be needed once #1 landed which is the superior solution to this. therefore closing this
