### ISSUE TITLE
Allow q to quit gitui

### ISSUE THREAD

**Issue by anahata0108** [extrawurst/gitui#766]
**Is your feature request related to a problem? Please describe.**
I tried to quit gitui with `q`, but the application doesn't respond.

**Describe the solution you'd like**
I'd like `q` to quit gitui, like it does for many other Unix commandline applications--especially pagers or applications based on pagers, like less, man, mutt, slrn, and others, like ftp, telnet, dc.

In addition, ^C to quit feels oddly... forceful. ^C is used when an application isn't responding, or when there isn't some more polite way to ask the application to quit. I appreciate that this is a subtlety, and subjective, but this is the expectation I have from using Unix for 20 years.

**Describe alternatives you've considered**
There aren't really any alternatives; this is a keybinding that cannot be changed. ... actually, now that I mentinon it, rebindable keys would be lovely.

**Comment by extrawurst** [comment]
> actually, now that I mentinon it, rebindable keys would be lovely

actually this is already implemented, please see the readme: https://github.com/extrawurst/gitui#bindings

**Comment by anahata0108** [comment]
I'm sorry, guess I should read more. :)
