### ISSUE TITLE
Support Markdown emoji

### ISSUE THREAD

**Issue by Sebclem** [extrawurst/gitui#768]
**Is your feature request related to a problem? Please describe.**
I'm using a lot of markdown emoji in my commits message, but in gitui, the emoji are not parsed.

**Describe the solution you'd like**
Replace all markdown emoji by it's Unicode equivalent.

I have found this lib that can help: https://lib.rs/crates/gh-emoji 

**Describe alternatives you've considered**

**Additional context**
![image](https://user-images.githubusercontent.com/23737709/120844598-efca8200-c56f-11eb-81e4-4ced197ce1e6.png)

This should look like this:
![image](https://user-images.githubusercontent.com/23737709/120845077-96168780-c570-11eb-9ab1-4aeb5ea9edb4.png)

**Comment by extrawurst** [comment]
Hi @Sebclem I dont find that feature particularly important but I wouldn't mind it if anyone wants to pick it up👍

**Comment by andrewpollack** [comment]
This looks like a fun issue 😄 mind if I give this a go?
