### ISSUE TITLE
app error handling using anyhow

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#77]
now that we have nice error coverage in `asyncgit` we could take the next step and add error support to the main application using `anyhow` based on the great summary on error handling in rust: 

my idea would be to show an error popup similar to this one where ever possible: https://github.com/extrawurst/gitui/issues/74#issuecomment-631359272

if we come across unrecoverable errors we might need to look into a second path aswell which will close the application.

**Comment by extrawurst** [comment]
one problem is going to be external libraries that do not go full *no-unwrap* too. Currently we have one of those issue with `tui-rs`: #72

**Comment by MCord** [comment]
I am working on this.
