### ISSUE TITLE
Quit shortcut activates even in commit message

### ISSUE THREAD

**Issue by dbr** [extrawurst/gitui#770]
**Describe the bug**
If in `key_config.ron` I configure `q` (no modifiers) to be quit, it is impossible to type `q` in a input widget like the commit message

This works nicely, except, when typing in something like the commit window, I can't enter `q` without the application exiting

**To Reproduce**
1. Configure `key_config.ron`:

```
    exit: (
        code: Char('q'),
        modifiers: (
            bits: 0,
        ),
    ),
```

2. Try to write `q` in a commit message

**Expected behavior**
`q` should only quit when no input widget is active

**Screenshots**
N/a

**Context (please complete the following information):**
 - OS/Distro + Version: Consistent on macOS/iTerm, Linux + xfce-terminal
 - GitUI Version: 0.16
 - Rust version: 1.51

**Additional context**
N/a

**Comment by dbr** [comment]
Actually this is less simple than I first thought:

- It's fairly reasonable for, say, `ctrl+c` to quit even when an input is active.
- It is fairly unreasonable for `q` to quit while trying to type "Require" in an input

..so maybe "shortcuts are ignored if no modifiers are specified"

However then `Shift+q` becomes a problem (unless this is handled by the terminal as just `Q` with no modifier, in which case this is is not an issue)

**Comment by extrawurst** [comment]
let me know if #771 will solve your issue

**Comment by dbr** [comment]
Yep that sounds good to me! Thanks!
