### ISSUE TITLE
new quit key binding

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#771]
Since this comes up so often my plan is to introduce a new `quit_app` key-binding that only reacts if no popup is open.

For reference: #770 , #766 

this means:
* in popups there is still `exit_popup` (ESC) to close it which allows closing text input popups that otherwise collide with `q`-key
* we still have `exit` (CTRL+C) that exits the app no matter in what place
* the new `quit_app` (Q or ESC) will close the app only when no popup is open

I am hoping to be able to cater for all the needs that where raised so far.

**Comment by dbr** [comment]
Been using this change recently and it works really well. Thanks!

**Comment by extrawurst** [comment]
> Been using this change recently and it works really well. Thanks!

happy to hear
