### ISSUE TITLE
Log tab not updating after the first time it is opened

### ISSUE THREAD

**Issue by alistaircarscadden** [extrawurst/gitui#78]
**Describe the bug**
In gitui-win v0.3.0 the Log tab is not updating after the first time the Log tab is opened.

The Log tab does not include the most recent commit when you make the commit with gitui or when you make the commit with another tool.

Tabbing to Status and back to Log does not make it update.

**To Reproduce**
1. Create new directory and cd into it
2. Run git init
3. Add a file to be committed (file.txt)
4. Open gitui
5. Add the file to the stage with the [1] menu
6. Make a commit with the Commit [c] option
7. Open the log and see the commit is visible
8. Again do 3, 4, 5, 6 with a second new file
9. Open the log and see only one commit

**Expected behavior**
When the Log tab is opened it updates the list completely.

Perhaps, it also would update after a few seconds like the [1] menu does with new files/changes.

**Desktop (please complete the following information):**
gitui-win v0.3.0

**Comment by extrawurst** [comment]
Good point, I never tried :)
