### ISSUE TITLE
Incorrect Commit SHA length for gitlab.com commits

### ISSUE THREAD

**Issue by frixaco** [extrawurst/gitui#781]
**Describe the bug**
Commit SHA for projects in Gitlab have 8 characters, GitUI shows 7 instead

**To Reproduce**
1. Clone any repository from gitlab.com
2. Launch gitui and go to Logs tab or try to make a commit

**Expected behavior**
Full commit SHAs (8 characters) are displayed in Logs tab

**Screenshots**
SHAs from gitlab.com:
![image](https://user-images.githubusercontent.com/37442533/121331592-7399bb00-c930-11eb-80b3-0b412c71d8f8.png)

gitui:
![image](https://user-images.githubusercontent.com/37442533/121331818-ac399480-c930-11eb-8f4d-5d56ebee65dd.png)

As you can see, last characters for the first 4 commits are misssing (9, 5, c, 4)

**Context (please complete the following information):**
 - OS/Distro + Version: WSL2 (Ubuntu 20.04), Windows 10 Pro
 - GitUI Version 0.16.1
 - Rust version: 1.52.1

**Additional context**

**Comment by extrawurst** [comment]
short hashes are visualised different on different platforms (GitHub shows only 7 chars). 
press `enter` on a commit and you see the full SHA1 hash.
so this boils down to a matter of taste only actually

**Comment by frixaco** [comment]
Oh, I see. I didn't knew about short hashes. Thank you for explanation!
And for GitUI too! Been using it for a few weeks and I really like it!
