### ISSUE TITLE
Run External Command

### ISSUE THREAD

**Issue by laktak** [extrawurst/gitui#784]
**Is your feature request related to a problem? Please describe.**

I prefer to run `git pull`, `git push` and `git commit` instead of the built in commands because

- pull/push will show detailed information about the progress and changes
- commit will show me the output from my git hooks before launching vim (with the preformatted commit message) and signed commits are IMHO not supported ATM.

**Describe the solution you'd like**

I'd like to replace the commands that I do not use with an external command.

E.g. `pull` would 
- switch back to the terminal, 
- run `git pull`,
- wait for a key
- resume gitui

**Describe alternatives you've considered**
At the moment I exit gitui to run the command I need.

**Comment by extrawurst** [comment]
gitui is designed to run in tandem with the regular git cli. we do not wrap any git cli call anywhere and I am intending to keep it that way. if there are any issues making it inconvenient to switch between gitui and the cli, lets iron those out 👍

**Comment by laktak** [comment]
Well the git cli calls were just an example to run arbitrary commands that one would consider part of their commit merge flow.

Another example I often use is to parse the remote URL and open a browser window with that repo (to create a new issue, etc.)

**Comment by extrawurst** [comment]
yeah I got that

**Comment by laktak** [comment]
OK, I can give you some input on why I prefer the external commands:

- I can see more details (especially for pull).
- I can see error messages when something fails, which is not that uncommon.
- The error messages stay on the screen (in the terminal) so that I can act on them.
- The reason for commit I already noted above.

Which does not mean that I don't love gitui for all the other things it does - it's really a time saver for picking apart commits, adding, resetting and looking at logs/diffs!

**Comment by terhechte** [comment]
What about a shortcut that allows typing out a command which is then executed (much like `:!` in vim. E.g. 
- you'd type the shortcut key
- a text input would appear at the bottom
- you'd type "push --force" (or whatever)
- hit enter
- You'd see the stdout of the command as it executes
- At the end, there'd be a "press any key to return to gitui" text

**Comment by extrawurst** [comment]
I am afraid but I don’t see the advantage over leaving gitui and doing that

**Comment by laktak** [comment]
> I am afraid but I don’t see the advantage over leaving gitui and doing that

Well, combined with a predefined external command, the advantage is that you are back in gitui afterwards ;-)

Some background: I use [ranger](https://github.com/ranger/ranger/) (which I highly recommend) all the time. It is almost as extensible as vim and you can extend it with the tools you need. One of the tools is gitui.

So if I exit gitui I'm often in ranger, not the terminal. I could of course add my `git pull` etc. commands to ranger but it would be more logical to have them in gitui.

I understand though if this is outside your feature set. I just wanted to explain why it does make sense.

**Comment by GitMurf** [comment]
> What about a shortcut that allows typing out a command which is then executed (much like `:!` in vim. E.g.
> 
> * you'd type the shortcut key
> * a text input would appear at the bottom
> * you'd type "push --force" (or whatever)
> * hit enter
> * You'd see the stdout of the command as it executes
> * At the end, there'd be a "press any key to return to gitui" text

This is precisely what I am looking for! Lazygit basically does this exact workflow as you described. Did anything ever come to gitui to support custom commands like this? I am brand new to gitui coming from lazygit (which I still love) as it was getting a bit sluggish on large repos.

**Comment by alex-moiseyev-d** [comment]
> I am afraid but I don’t see the advantage over leaving gitui and doing that

The advantage would be the ability to pass the current context to the external command (currently selected commit, branch, line in code etc.). Lazygit provides a way to map an external command passing the current context to it, this allows to quickly perform a lot of [useful operations](https://github.com/jesseduffield/lazygit/wiki/Custom-Commands-Compendium).

This is not a trivial feature, as it would require designing a way to express this in the configuration, figuring out the way to pass the arguments, retrieving the arguments from the active context, and also handling the terminal state switching.
