### ISSUE TITLE
The commit function does not work when you have user.email but no user.name defined

### ISSUE THREAD

**Issue by alistaircarscadden** [extrawurst/gitui#79]
**Describe the bug**
In gitui v0.3.0 the commit function does not allow a commit to be made when the user has a user.email defined and no user.name defined.

It took me a while to discover that there is a difference between user.name being defined as empty (`git config user.name ""`) and it being undefined (as in, `git config --list` does not show the entry at all).

In the empty case, interestingly enough, git commit does not allow the commit to be made, likewise gitui does not allow it.

In the undefined case, git commit does allow the commit to be made (and I think it shows `unknown` in that field in later `git log` or `git show` calls). This is where the gitui behaviour is different, as gitui does not allow a commit to be made with this message:
```
 Status   |   Log
────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────
┌Unstaged Changes [1]──────┌Error──────────────────────────────────────────────────────────┐───────────────────────────┐
│                          │commit failed:                                                 │                           │
│                          │git error:config value 'user.name' was not found; class=Config │                           │
│                          │(7); code=NotFound (-3)                                        │                           │
│                          │                                                               │                           │
```

**Expected behavior**
gitui would allow a commit to be made and fill in `unknown` as git commit does.

**Comment by extrawurst** [comment]
followup to #74

**Comment by extrawurst** [comment]
unfortunately #155 had to be rolled back

**Comment by extrawurst** [comment]
removed `good first issue` since #155 showed that writing an appropriate unittest for this is by far more complicated than expected

**Comment by extrawurst** [comment]
still active: https://github.com/extrawurst/gitui/pull/269

**Comment by extrawurst** [comment]
@cruessler is this fixed by your PR?

**Comment by extrawurst** [comment]
@alistaircarscadden @cruessler closing this hoping that #269 actually fixed this. please reopen if this is not the case
