### ISSUE TITLE
GitUI gets distorted when using Windows Terminal

### ISSUE THREAD

**Issue by ghost** [extrawurst/gitui#790]
**Describe the bug**
When I use Windows Terminal to use GitUI, 

**To Reproduce**
`cd` into a git repo and type `gitui` and press any keys that change the screen.(e.g. arrow keys)

**Expected behavior**
The screen becomes garbled and GitUI becomes unusable.

**Screenshots**
![Animation](https://user-images.githubusercontent.com/85086136/122141938-5a8d8e80-ce89-11eb-893d-f0e9f7e365df.gif)

**Context (please complete the following information):**
 - OS/Distro + Version: Windows 10 20H2
 - GitUI Version: git-c0296687b8bf3515d1060f4911a5af4b629fda5d (built it from source)
 - Rust version: 1.52.1

**Additional context**
This problem happens with Nano on WIndows too. Maybe it could be a problem of Windows Terminal itselㄹ.

**Comment by extrawurst** [comment]
looks like a known bug in windows terminal: https://github.com/microsoft/terminal/issues/381

**Comment by 7k5x** [comment]
Then is it impossible to fix within GitUI?

**Comment by extrawurst** [comment]
> Then is it impossible to fix within GitUI?

that's right

**Comment by 7k5x** [comment]
I found a way to fix it. Adding `"experimental.rendering.forceFullRepaint": true,` to the JSON file or enabling `Redraw entire screen when display updates` fixes the frame buffer being clogged.

**Comment by extrawurst** [comment]
@7k5x interesting. wonder if that impacts the performance somehow

**Comment by 7k5x** [comment]
For me it doesn't impact the performance at all, no flickering and whatsoever but maybe that's because I have a modern GPU(GTX 1070). I guess this needs more testing for others using potato PCs.

**Comment by extrawurst** [comment]
> @extrawurst For me it doesn't impact the performance at all, no flickering or whatsoever but maybe that's because I have a modern GPU(GTX 1070). I guess this needs more testing for others using potato PCs.

great!
