### ISSUE TITLE
Doesn't even compile

### ISSUE THREAD

**Issue by isbm** [extrawurst/gitui#797]
**Describe the bug**

```
   Compiling filetreelist v0.1.2
error: `std::option::Option::<T>::as_ref` is not yet stable as a const fn
  --> /home/bo/.cargo/registry/src/github.com-1ecc6299db9ec823/filetreelist-0.1.2/src/filetree.rs:79:9
   |
79 |         self.visual_selection.as_ref()
   |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `filetreelist`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `gitui v0.16.1`, intermediate artifacts can be found at `/tmp/cargo-installSQceXJ`

Caused by:
  build failed
```

**Comment by extrawurst** [comment]
> Doesn't even compile

it takes courage to phrase an issue like this and actively ignore the template for writing proper issues which asked you what rust version you used.

the error tells me you are not using the latest rust version, although the readme tell you to do so under [build](https://github.com/extrawurst/gitui#build)

**Comment by isbm** [comment]
@extrawurst it takes courage to phrase a proper documentation how to do that. Your documentation could be a bit better, perhaps?

I use 1.55. Still doesn't compile. And not sure what it has to do with the Rust itself:
```
.cargo/registry/src/github.com-1ecc6299db9ec823/filetreelist-0.1.2/src/filetree.rs:79:9
```

But at least it is great that it works on _your_ laptop.

**Comment by extrawurst** [comment]
> But at least it is great that it works on your laptop.

and our CI running stable rust 1.53, 1.50 (minimum supported rust) and nightly

**Comment by isbm** [comment]
@extrawurst well, then maybe you could update the docs to be more detailed and do not assume everyone is Rust guru? :wink:  Because something clearly is not working and  I am not that into Rust that I would spot it right away. Currently I fail to package your stuff while similar projects in Go "just works". So I just follow a "standard" (if this is the word) procedure, then `rustup` to the latest, then getting tons of cargo updates, then it crashes. Then I google all possible combinations, it does _something_ and then crashes again. Well, OK. Now what? OS: Ubuntu 20.04 LTS, rust is installed from packages (doesn't work) and from rustup (also doesnt work). BTW, I can build other projects with Rust no problems, so I still suspect that something is not entirely right.

I would appreciate if  you could help here.

**Comment by extrawurst** [comment]
what does `cargo --version` print on your setup?

see https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1480-2020-11-19 which says that `Option::as_ref` was stabilised in rust 1.48 (> 6 months ago) the error you shared says that on your setup `Option::as_ref` is not stabilised yet. so it looks a lot like your rust is not `>=1.50`
