### ISSUE TITLE
Show full commit messages in the log

### ISSUE THREAD

**Issue by jugglerchris** [extrawurst/gitui#80]
**Is your feature request related to a problem? Please describe.**
In the Log tab, I can see only the start of the log message for each commit, but when browsing the log I am likely to want to read the full message (or indeed view the diff).

**Describe the solution you'd like**
While browing the log, pressing 'enter' when an entry is highlighted could open up a panel showing more information - principally the commit message, but the diff for that commit would also be very useful.

**Describe alternatives you've considered**
An alternative could be a view like the main Status tab, with commits instead of files on the left, and a panel with the details on the right, showing the commit highlighted.

**Additional context**

**Comment by extrawurst** [comment]
Hi @jugglerchris thanks for your interest in `gitui` - this feature is definitely on my list aswell!

**Comment by guss77** [comment]
Just wanted to pipe in with a +1 for this and the request that the info panel will also include the list of changed files.

I'm looking at gitui mainly as a replacement for [tig](https://github.com/jonas/tig)'s log view - which I find hard to use due to the non-intuitive key binding (using INS/DEL to scroll?!?). Ideally gitui would not only match tig features by showing the branches in the log (including labels) and the full commit message, file list and diff, but also feature better layout and navigation for all these things, for example:
- use different view ports for the message, file list and diff
- Allow the user to navigate the file list and choose which file to show in the diff view.

**Comment by extrawurst** [comment]
So, my current plan is to tackle this in multiple steps:

1. allow opening an info pane to the side while scrolling the log to show extended information about a commit
2. when focusing on the right side of extended information it will open this single commit up in a fullscreen fashion with the right side being used to show the file diffs exactly like in the `Status`-Tab

Step 1. will be done for this issue and look something like this:
<img width="397" alt="image" src="https://user-images.githubusercontent.com/776816/83538210-d7a3cb00-a4f5-11ea-8b97-af652a3a7e63.png">

Step2. will be a followup task

**Comment by extrawurst** [comment]
first visual prototype:
![Screenflick Movie 25](https://user-images.githubusercontent.com/776816/83617199-0a4ad380-a589-11ea-805d-9fb582f435b5.gif)

**Comment by extrawurst** [comment]
now with actual data:
![Screenflick Movie 26](https://user-images.githubusercontent.com/776816/83639123-84d81b00-a5aa-11ea-8b24-ad155553ce59.gif)

**Comment by extrawurst** [comment]
now also with file list:
<img width="1066" alt="image" src="https://user-images.githubusercontent.com/776816/83696622-3acc5500-a5fd-11ea-9fcb-bc7c3a31408e.png">

**Comment by extrawurst** [comment]
first part is merged into master. looking forward to feedback. next up is: fullscreen commit details (that's where we can diff each file in the commit)
![Screenflick Movie 27](https://user-images.githubusercontent.com/776816/83950751-63d32c80-a82d-11ea-9154-39db24867450.gif)

**Comment by extrawurst** [comment]
*next update*: now we can open the details of a single commit in a view similar to the status tab where we can diff every individual file inside a commit from the past:
![Screenflick Movie 28](https://user-images.githubusercontent.com/776816/84142336-e4c03d00-aa54-11ea-9058-29f13cf910c4.gif)

**Comment by extrawurst** [comment]
released: https://github.com/extrawurst/gitui/releases/tag/v0.6.0
