### ISSUE TITLE
Support core.hooksPath

### ISSUE THREAD

**Issue by BuzzwordChief** [extrawurst/gitui#808]
A global pre-commit hook (set with core.hooksPath) is ignored by gitui. It allows to commit the staged files even if the pre-commit hook returns with a non zero value.

**To Reproduce**
Create a pre-commit hook like this:
```
#! /bin/sh
exit 1
```

**Expected behavior**
the commit should fail, it doesn't.

**Comment by extrawurst** [comment]
That’s a known limitation: https://github.com/extrawurst/gitui#5--known-limitations-top-

**Comment by BuzzwordChief** [comment]
Sorry, overlooked this somehow!

**Comment by extrawurst** [comment]
> Sorry, overlooked this somehow!

no worries, we can keep it open in case someone is willing to pick it up. its a legit feature request

**Comment by extrawurst** [comment]
implemented in #1044

**Comment by extrawurst** [comment]
@BuzzwordChief if you feel like it please build master and try it out before this will be released soon
