### ISSUE TITLE
Option to toggle untracked files in Status [1] tab

### ISSUE THREAD

**Issue by stan-janssen** [extrawurst/gitui#809]
**Is your feature request related to a problem? Please describe.**
I'm working with a repository where I have many untracked files that I'm using locally but don't want to commit to the repository and don't want to add to the .gitignore file. This makes seeing the tracked files that are changed difficult, because I have to hunt for them between all the "new" files that I don't want to commit.

**Describe the solution you'd like**
A toggle to show/hide the untracked files in the file tree.

**Describe alternatives you've considered**
The `git status` command for example separates the untracked files from the tracked files. A GUI tool like Sublime Merge also shows them separately, and can be collapsed.

**Comment by extrawurst** [comment]
Maybe a workaround in the meantime: https://github.com/extrawurst/gitui/pull/753

**Comment by extrawurst** [comment]
I am planning to introduce a general options system which we can use to toggle stuff like this on and off cause other questions [came up before](#444) that would fit this nicely (like changing how we treat whitespaces in the diff)

**Comment by extrawurst** [comment]
The plan is to have a popup like this:

<img width="495" alt="Screenshot 2021-08-17 at 23 58 59" src="https://user-images.githubusercontent.com/776816/129806225-cea3d79e-5907-42a7-ac23-cdae34069109.png">

**Comment by extrawurst** [comment]
incoming

![ezgif com-resize](https://user-images.githubusercontent.com/776816/129987905-56a0595f-9611-4c7e-81e8-ec06376c62a1.gif)
