### ISSUE TITLE
Display the branches in the log view

### ISSUE THREAD

**Issue by GuillaumeAmat** [extrawurst/gitui#814]
**Is your feature request related to a problem? Please describe.**
Not really a problem, but I miss a nice touch from Tig: displaying the branches in the log view. Gitui already displays the tags in that view, it could be great to also display the branches, to better appreciate the state of the workspace.

**Describe the solution you'd like**
"Just" add the branches name in the log lines, as the already existing tags. 

**Additional context**

Screenshot from Tig:

![Capture d’écran de 2021-07-11 22-56-58](https://user-images.githubusercontent.com/1179174/125209826-f5686580-e29b-11eb-9711-db74c72387dd.png)

And by the way, thank you for that great project :heart:

**Comment by extrawurst** [comment]
probably a dup of #81
