### ISSUE TITLE
Stale bot misconfigured? 

### ISSUE THREAD

**Issue by sztomi** [extrawurst/gitui#815]
I searched this issue tracker for rebase support and found https://github.com/extrawurst/gitui/issues/302

It is labeled as WONTFIX, but the discussion doesn't seem to imply that it's not intended to be added (I'm also not sure if it's beneficial to close "stale" issues with substantial, forward looking discussion).

**Comment by extrawurst** [comment]
I don't think it is misconfigured. So far it does what it should: Close tickets without activity, after all closed tickets are not deleted. They are still around for reference.

What would you configure differently? 

Just an oversight in this particular example, issues we don't want to see getting closed can be marked as such.

**Comment by sztomi** [comment]
> What would you configure differently?

@extrawurst labeling the issue as WONTFIX seems to be misleading and that was done by the bot. Had I not opened the issue and read the discussion I would have gotten the impression that rebase support is out of scope for this project, but that doesn't seem to be the case. I'm not sure if all bot-closed issues get this label, but I would personally not do this (instead, maybe add a label that implies closing due to staleness, i.e. something like `closed:stale`). 

For the second part (not closing issues with substantial and forward looking discussion), labeling something uncloseable seems to be a good solution. In that case, maybe #302 is worth reopening and labeling as such.

**Comment by extrawurst** [comment]
for me the paper trail where a label comes from is well document by this:

<img width="522" alt="Screenshot 2021-07-12 at 14 18 11" src="https://user-images.githubusercontent.com/776816/125286345-ffca4400-e31b-11eb-85c0-f72a2e6d48b4.png">

if you care enough for a feature you check out the issue that was closed and marked as wont-fix and realise that it was the bot. then you can followup and bring this back into attention or even better offer help in implementing it 😁

I created a more concise followup ticket for this feature now: #816

**Comment by sztomi** [comment]
But why label with a word that means something else? There was a very real chance that I wouldn't have opened that issue since I saw the label that, to me, clearly means that the author does not want to support the feature. Not looking for the paper trail (on the off chance that WONTFIX means stale, which I never would have imagined) doesn't mean I wouldn't care about the feature. The label tells me it's out of scope and those decisions are rarely up for debate. So I had no other reason than curiosity to open the issue.

This also makes it impossible to filter for WONTFIX issues that are actually out of scope for the project. 

(don't get me wrong, I don't mean to push my views on this, I'm just very confused why it's done the way it is, with seemingly no real upside - compared to labeling stale issues with a descriptive word)

**Comment by extrawurst** [comment]
> But why label with a word that means something else? There was a very real chance that I wouldn't have opened that issue since I saw the label that, to me, clearly means that the author does not want to support the feature. Not looking for the paper trail (on the off chance that WONTFIX means stale, which I never would have imagined) doesn't mean I wouldn't care about the feature. The label tells me it's out of scope and those decisions are rarely up for debate. So I had no other reason than curiosity to read the discussion.
> 
> This also makes it impossible to filter for WONTFIX issues that are actually out of scope for the project.
> 
> (don't get me wrong, I don't mean to push my views on this, I'm just very confused why it's done the way it is, with seemingly no real upside - compared to labeling stale issues with a descriptive word)

I have nothing to add, let's discuss this further on discord if you want to
