### ISSUE TITLE
support conflict-free rebase instead of merge

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#816]
(based on #302)

now that we support merging a branch #485 we can look into rebase instead of merge.
although this gets a tad more complicated since any rebase step could fail due to conflicts and then we need to be able to proceed the rebase after conflict resolution was done.

**Comment by IndianBoy42** [comment]
Related to this: the pull branch feature will currently always merge, even though I have set to rebase by default in my `~/.gitconfig`. I hope this will be changed once rebasing is supported. 

Is the work to be done on this mostly user interface related or some technical limitations? AFAICT, If we can see/fix merge conflicts in gitui currently, rebasing should be very similar

**Comment by extrawurst** [comment]
> Is the work to be done on this mostly user interface related or some technical limitations? 

like I stated above:
> any rebase step could fail due to conflicts and then we need to be able to proceed the rebase after conflict resolution was done.
