### ISSUE TITLE
Arrow keys don't work on iTerm2

### ISSUE THREAD

**Issue by natsukagami** [extrawurst/gitui#821]
**Describe the bug**
Arrow keys do not work at all in `gitui` on iTerm2.

**To Reproduce**
1. Open `gitui` on iTerm2
2. Try to use arrow keys [nothing work]
3. All other keys work as expected

**Context (please complete the following information):**
 - OS/Distro + Version:  macOS Big Sur 11.4, Macbook Air M1
 - GitUI Version 0.16.2 from nixpkgs / 0.16.2 from `cargo install gitui`
 - Rust version: 1.53.0

**Additional context**

It works on Alacritty on the same machine.

**Comment by extrawurst** [comment]
Works for me, sure you did not change the arrow key bindings in your iterm profile?

**Comment by extrawurst** [comment]
@natsukagami I assume this means you got it to work
