### ISSUE TITLE
Delete upstream branch

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#824]
**Is your feature request related to a problem? Please describe.**

As now gitui supports creation/deletion of branches, I'm missing functionality to actually delete branches from the remote (`git push --delete <remote> <branch>`)

**Describe the solution you'd like**

In the list of remote branches, deleting should actually push deletion.

**Describe alternatives you've considered**

I did not find any.

**Additional context**

Right now deleting of the branch in "remote" tab just deletes local reference to a branch and next "fetch" will bring it back.

**Comment by extrawurst** [comment]
Duplicate of #622 right?

**Comment by ignatenkobrain** [comment]
Oh, it seems so.
