### ISSUE TITLE
Ignoring .gitignore just keeps adding .gitignore in .gitignore

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#825]
**Describe the bug**

I think subject covers it pretty well.

**To Reproduce**
1. Make sure your repository does not have any `.gitignore` in it
2. Ignore any file (so that .gitignore would be created by gitui)
3. Try to ignore .gitignore
4. The .gitignore is added to the .gitignore (and if you repeat, it is added infinitely)

**Expected behavior**

Either ignoring .gitignore would not do anything or throw an error.

**Screenshots**

![image](https://user-images.githubusercontent.com/2866862/126866672-95ac4c80-69be-466f-b928-57aeea077169.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Fedora 35
 - GitUI Version: 0.16.2
 - Rust version: 1.53

**Additional context**

None.

**Comment by extrawurst** [comment]
<img width="1421" alt="Screenshot 2021-08-03 at 23 31 13" src="https://user-images.githubusercontent.com/776816/128089030-63a142ab-1cc8-446a-be98-c0e5b0213db4.png">
