### ISSUE TITLE
panic / core dump when viewing details on shallow commits

### ISSUE THREAD

**Issue by jabra98** [extrawurst/gitui#836]
**Describe the bug**
```
panic: Any { .. }
trace:
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: start_thread
   7: __GI___clone

Aborted (core dumped)
```
**To Reproduce**
`git clone --depth 1 https://github.com/extrawurst/gitui` (note the `--depth 1` flag)
./gitui -> go to the log tab -> press enter to view details on the shallow commit

**Expected behavior**
Show details of the commit

**Context (please complete the following information):**
OS: Arch Linux
Kernel: x86_64 Linux 5.13.9-arch1-1
GitUI Version: 0.16.2
Rust version: rustc 1.54.0

**Additional context**
https://git-scm.com/docs/shallow

Useful, for example, when cloning plugins for vim (since only the last commit is fetched, it's faster that way)

**Comment by extrawurst** [comment]
the actual error:
```
[ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(failed to fetch: Git(Error { code: -3, klass: 9, message: "object not found - no match for id (d6f43f063eedf95e33d019f41265e1d377a572ec)" })), location: Location { f
ile: "asyncgit/src/commit_files.rs", line: 72, col: 18 } }
```

**Comment by jabra98** [comment]
> the actual error:
> 
> ```
> [ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(failed to fetch: Git(Error { code: -3, klass: 9, message: "object not found - no match for id (d6f43f063eedf95e33d019f41265e1d377a572ec)" })), location: Location { f
> ile: "asyncgit/src/commit_files.rs", line: 72, col: 18 } }
> ```

Is this only shown in debug builds?

**Comment by extrawurst** [comment]
> > the actual error:
> > ```
> > [ERROR] panic: PanicInfo { payload: Any { .. }, message: Some(failed to fetch: Git(Error { code: -3, klass: 9, message: "object not found - no match for id (d6f43f063eedf95e33d019f41265e1d377a572ec)" })), location: Location { f
> > ile: "asyncgit/src/commit_files.rs", line: 72, col: 18 } }
> > ```
> 
> Is this only shown in debug builds?

Nope it’s only logged if you use the respective argument
