### ISSUE TITLE
Stashing individual hunks or lines

### ISSUE THREAD

**Issue by jugglerchris** [extrawurst/gitui#85]
**Is your feature request related to a problem? Please describe.**
I sometimes want to stash only parts of files - for example some dirty debug code when mixed with "real" changes, when I might want to recover the debug code after testing the change without.

**Describe the solution you'd like**
When selecting changes to stash, allow selecting individual parts of files to stash rather than stash everything, like `git stash push --patch`.

**Describe alternatives you've considered**
Not using gitui for this.  :-)

**Comment by extrawurst** [comment]
depends on #59 (the way we decide how to do the UX of that)
depends on #106

**Comment by extrawurst** [comment]
#1116 is a continuation. Please help me get some traction on the upstream limitation that keeps us from implementing it
