### ISSUE TITLE
Files tab error when there is a empty repo

### ISSUE THREAD

**Issue by ZeemanZhang** [extrawurst/gitui#859]
**Describe the bug**
When I create a new git repo, I run gitui and switch to the Files tab, then GitUI just break.

**Screenshots**
![动画.gif](https://i.loli.net/2021/08/19/K2bj6YBOvnfsTdW.gif)

**Context (please complete the following information):**
 - System Version: Windows 10 Pro 19043.1165
 - GitUI Version: 0.16.2
 - Git Version: 2.32.0.windows.2

**Comment by extrawurst** [comment]
good catch!
