### ISSUE TITLE
UI incompletely drawn in some terminals

### ISSUE THREAD

**Issue by alerque** [extrawurst/gitui#879]
**Describe the bug**
While working on upgrading the Arch packaging to v0.17 I tested in a couple of different terminals. The UI (specifically chrome elements like frames) are not drawn properly in all terminals.

**To Reproduce**
1. Open a terminal.
1. Run `gitui` from a Git repository.
4. (Don't) see all frame borders.

**Expected behavior**
All modern terminals should render a full UI experience.

**Screenshots**

* Termite fails:
    ![image](https://user-images.githubusercontent.com/173595/130590924-9df39b4d-937b-4ab1-bb3a-b335a933ee3b.png)

* Kitty works:
    ![image](https://user-images.githubusercontent.com/173595/130591624-ace2e0c3-8115-45b0-b3cb-f4d1404113ed.png)

* Alactrity works:
    ![image](https://user-images.githubusercontent.com/173595/130591706-f3b99ff4-f182-443c-909e-d7268be52db6.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Arch Linux
 - GitUI Version: v0.17
 - Rust version: v1.54.0

**Comment by extrawurst** [comment]
Hi @alerque is that a regression or did it never work in `Termite`?

**Comment by alerque** [comment]
I am *pretty* sure this is a regression, but it might be from a few versions back. I used this quite a bit in my "quake" style dropdown terminal which has been Termite based for years, but I went for quite a spell only using it in my regular terminals (which are Alacritty) so I'm not sure when the Termite issue cropped up. I'm new to the responsibility of packaging this so I haven't intentionally tested the previous releases.

**Comment by extrawurst** [comment]
We are talking about this [Termite](https://github.com/thestinger/termite/)? Superseded by Alacritty?

I don't have an archlinux box here, so I would need some help digging into this. especially interesting would be if it ever worked there and if so which version broke it.
