### ISSUE TITLE
Add a shortcut key to run external diff tool 

### ISSUE THREAD

**Issue by exoton** [extrawurst/gitui#884]
**Is your feature request related to a problem? Please describe.**
I much prefer to use an external diff tool but I couldn't find an easy way to do that.

**Describe the solution you'd like**
I'd like to press a key and open an external diff tool that I have configured in my .gitconfig.

**Describe alternatives you've considered**
At the moment I press "e" to edit a file and I run the diff tool from my editor.

**Comment by extrawurst** [comment]
can you provide an example `.gitconfig` entry for this?

**Comment by exoton** [comment]
```
[diff]
	external = ~/bin/gitdiff
	tool = bc3
[difftool "bc3"]
	trustExitCode = true
[merge]
	tool = bc3
[mergetool "bc3"]
	trustExitCode = true
```

**Comment by pixelblender** [comment]
+1 for external diff tool

**Comment by giel** [comment]
Using [meld diff viewer](https://meldmerge.org) as an example
```
git config --global diff.tool meld
```
will result in git.config section: 
```
[diff]
  tool = meld
```

Then in a directory `git difftool` will give a overview of all changed files one at a time.
And `git difftool filename` will give a diff of only one file.

Especially the last option would be nice as an extra option under a key shortcut (`T` for diff<T>ool ?) in the Status view 'panels'.
The first option is less useful in my opinion.

**Comment by happysalada** [comment]
recently checked difftastic, and would like to be able to use a syntax aware diff tool.

**Comment by OnePieceJoker** [comment]
Is there any follow-up on this issue?

**Comment by brianmcfadden** [comment]
It would be very nice to have this available.

I currently use the edit command in gitui to simulate this behavior, keeping a GIT_EDITOR in my environment.

export GIT_EDITOR="git difftool -y" (or something like that)

This doesn't work in all contexts, but it does work for unstaged changes in the status screen, which is where i feel it's most useful.

**Comment by silicakes** [comment]
Would love difftastic support for this.

**Comment by mlabbe** [comment]
My workflow is to review each file in Beyond Compare, staging it when it passes self-review. It would be wonderful to be able to trigger a single-file difftool through gitui, enabling me to make any last minute changes before staging.  As it stands, I keep another git graphical client around for the purpose, while wholly preferring the excellent gitui for all of my other git work.  

Thanks for the generosity of your time and skills.

**Comment by therealchfkch** [comment]
Yes, difftastic alone is a reason i would want to see it. Loving the work so far, but that would be the cherry on top.

**Comment by AnhQuanTrl** [comment]
This is much needed. Right now it is really manual to have to go to another editor and open the same file to merge conflict. Would love to be able to launch that same editor within Gitui.
