### ISSUE TITLE
Highlight added/removed blank lines in the diffs

### ISSUE THREAD

**Issue by IndianBoy42** [extrawurst/gitui#887]
**Is your feature request related to a problem? Please describe.**
Right now, in the diff view, it is hard to see when a blankline has been added/removed, as there is no green/red colored characters, just a blank space

**Describe the solution you'd like**
I think that blank lines in the diff (added/removed) should be more visible, either a solid red/green line (respectively) or maybe a red/green underline

**Comment by extrawurst** [comment]
I actually plan a big change here anyway in order to integrate a outside diff lib `delta` and then this will be a part of that too (see #358)
