### ISSUE TITLE
support commit amend

### ISSUE THREAD

**Issue by extrawurst** [extrawurst/gitui#89]
new command for `git commit amend`

* opens regular commit popup but fills in last commit msg
* disable command in empty repositories
* see https://docs.rs/git2/0.13.6/git2/struct.Commit.html#method.amend

before we can do that we need to land #83

**Comment by MCord** [comment]
what about just adding a checkbox in the commit pop up to amend instead of committing ? many existing UI tools behave this way and this minimizes the number of commands and UI complexity.

**Comment by MCord** [comment]
what do you think about using function keys ? the stream is very cool indeed I am watching it right now !

**Comment by extrawurst** [comment]
I would say let's go for the commit popup like @MCord said and add an amend option that takes the previous msg and fills it in if the current msg is empty

**Comment by extrawurst** [comment]
this is what it looks now:
![Screenflick Movie 29](https://user-images.githubusercontent.com/776816/84554256-5cbd8a00-ad17-11ea-953b-4c1646e61932.gif)
