### ISSUE TITLE
Honor `commit.verbose` configuration variable

### ISSUE THREAD

**Issue by alexherbo2** [extrawurst/gitui#900]
It could be nice to have the same file content than when doing [`git commit`] to honor the settings, such as the [`commit.verbose`] configuration variable.

[`git commit`]: https://git-scm.com/docs/git-commit
[`commit.verbose`]: https://git-scm.com/docs/git-config#Documentation/git-config.txt-commitverbose

**Comment by extrawurst** [comment]
Hm I guess this only makes sense for when opening the external editor on a commit message👍

**Comment by extrawurst** [comment]
For inside gitui you have the nicer status tab to see what you are about to commit

**Comment by alexherbo2** [comment]
Yep, I want it in my editor to review changes and have word completion.

**Comment by extrawurst** [comment]
@alexherbo2 I am open to take a PR on that

**Comment by alexherbo2** [comment]
@extrawurst What do you think to provide word completion with the content of the changes?

**Comment by extrawurst** [comment]
> @extrawurst What do you think to provide word completion with the content of the changes?

I can’t follow. We open the external editor (whatever you have configured it to be) and gitui has nothing to do with word completion in there.
