### ISSUE TITLE
segfault on Gentoo

### ISSUE THREAD

**Issue by dm9pZCAq** [extrawurst/gitui#902]
**Describe the bug**
segfault when running `gitui`

**To Reproduce**
run `gitui` on eny directory

**Context (please complete the following information):**
 - OS/Distro + Version: Gentoo on musl libc
 - GitUI Version `0.17.1`
 - Rust version: `1.54.0`
 - system libgit2 version: `1.2.0` with https://github.com/libgit2/libgit2/pull/6032 applied 
 - system openssl version: `1.1.1l`
 - musl version: `1.2.2`

**Additional context**
with `gitui-0.16.2` everything works fine, but with same [ebuild](https://notabug.org/dm9pZCAq/dm9pZCAq-overlay/src/master/dev-vcs/gitui/gitui-0.16.2.ebuild) but for `0.17.1` after successful build, it's segfaults at runtime

firstly i was think this is because of `git_branch name is_valid` but my tests compiles and runs fine

<details><summary>C</summary>

```c
#include <stdio.h>
#include <git2/branch.h>

#define LEN(X) (sizeof(X) / sizeof *(X))

int
main(void)
{

	size_t	    i;
	int	    status  = -1;
	const char *tests[] = {
		"refs/heads/name",
		"master",
		"-master",
	};

	for (i = 0; i < LEN(tests); i -= (~0L), status = -1) {
		printf("git_branch_name_is_valid(%s) -> %d, ",
		       tests[i],
		       git_branch_name_is_valid(&status, tests[i]));
		printf("status %d\n", status);
	}

	return 0;
}
```
out:
```
git_branch_name_is_valid(refs/heads/name) -> -1, status 0
git_branch_name_is_valid(master) -> -1, status 0
git_branch_name_is_valid(-master) -> 0, status 0
```
`lddtree`:
```
a.out => ./a.out (interpreter => /lib/ld-musl-x86_64.so.1)
    libgit2.so.1.2 => /usr/lib/libgit2.so.1.2
        libssl.so.1.1 => /usr/lib/libssl.so.1.1
        libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1
        libpcre.so.1 => /lib/libpcre.so.1
        libhttp_parser.so.2.9 => /usr/lib/libhttp_parser.so.2.9
        libz.so.1 => /lib/libz.so.1
        libssh2.so.1 => /usr/lib/libssh2.so.1
    libc.so => /usr/lib/libc.so

```

</details>

<details><summary>rust</summary>

```rust
use git2::Branch;

type BoxedErr = Box<dyn(::std::error::Error)>;
type Result<T> = ::std::result::Result<T, BoxedErr>;

fn main() -> Result<()> {
    for name in ["refs/heads/name", "master", "-master"] {
        let valid = Branch::name_is_valid(name)?;
        println!("{:#?}", valid);
    }

    Ok(())
}
```
out:
```
true
true
false
```
`lddtree`:
```
Test => ./target/debug/Test (interpreter => /lib/ld-musl-x86_64.so.1)
    libgit2.so.1.2 => /usr/lib/libgit2.so.1.2
        libpcre.so.1 => /lib/libpcre.so.1
        libhttp_parser.so.2.9 => /usr/lib/libhttp_parser.so.2.9
        libz.so.1 => /lib/libz.so.1
        libssh2.so.1 => /usr/lib/libssh2.so.1
    libssl.so.1.1 => /usr/lib/libssl.so.1.1
    libcrypto.so.1.1 => /usr/lib/libcrypto.so.1.1
    libgcc_s.so.1 => /usr/lib/gcc/x86_64-gentoo-linux-musl/11.2.0/libgcc_s.so.1
    libc.so => /usr/lib/libc.so
```

</details>

[strace gitui](https://0x0.st/-wF1.strace)

maybe you know what it could be?

**Comment by extrawurst** [comment]
I am clearly not enough of a linux pro for this. on my ubuntu box for dummies everything seems to works.

**Comment by dm9pZCAq** [comment]
> also can you run it in a debugger so we get a useful callstack where it crashes?

can you recommend some useful tools for rust debugging?



> what added value the issue description "yet another" had?

because that's "yet another" weird segfault on Gentoo (first is here #459)

**Comment by dm9pZCAq** [comment]
ok, with best debug tool (putting `dbg!` after each line in `fn main`) i find out that segfault caused by this line
https://github.com/extrawurst/gitui/blob/7dd6b4e8d84bec4c88b5ba63c566847758f2e858/src/main.rs#L105

after i commented it out, everything works fine

**Comment by dm9pZCAq** [comment]
for me, this causes segfault too
```c
#include <stdio.h>
#include <git2/trace.h>

void
callback(git_trace_level_t level, const char *msg)
{
	puts(msg);
}

int
main(void)
{
	printf("%d\n", git_trace_set(GIT_TRACE_TRACE, callback));
	return 0;
}
```

i'll go figure it out...

**Comment by dm9pZCAq** [comment]
ok, i figured out...

the problem was that i compiled `libgit2` without tracing support (`-DENABLE_TRACE=OFF`)

`gitui` is only package on my system, that requires tracing from `libgit`

maybe it would be better to add `--feature` for `libgit` tracing, and users that don't need it, will be able to disable it?

**Comment by extrawurst** [comment]
> ok, i figured out...
> 
> the problem was that i compiled `libgit2` without tracing support (`-DENABLE_TRACE=OFF`)
> 
> `gitui` is only package on my system, that requires tracing from `libgit`
> 
> maybe it would be better to add `--feature` for `libgit` tracing, and users that don't need it, will be able to disable it?

afaik tracing is on by default. so yeah maybe a note in the readme to mention that we require this to be enabled would make sense

**Comment by dm9pZCAq** [comment]
> tracing is on by default

on most distros yes, but on Gentoo you have choice what to use and this is not enabled by default

**Comment by dm9pZCAq** [comment]
this is how i did it:
* [dependencies](https://github.com/gentoo-mirror/dm9pZCAq/blob/1487802ec85cfc9ffb83db8d8ef0e6b4c2efe310/dev-vcs/gitui/gitui-0.17.1.ebuild#L197-L198)
* [sed sources](https://github.com/gentoo-mirror/dm9pZCAq/blob/1487802ec85cfc9ffb83db8d8ef0e6b4c2efe310/dev-vcs/gitui/gitui-0.17.1.ebuild#L235-L239)

---
it can be enabled by default, but have this choice will be cool 
<details><summary>?</summary>

`asyncgit/src/lib.rs`:
```rust
///
#[cfg(feature = "trace-libgit")]
pub fn register_tracing_logging() -> bool {
    fn git_trace(level: git2::TraceLevel, msg: &str) {
        log::info!("[{:?}]: {}", level, msg);
    }
    git2::trace_set(git2::TraceLevel::Trace, git_trace)
}

///
#[cfg(not(feature = "trace-libgit"))]
pub fn register_tracing_logging() -> bool {
    true
}
```

and add feature to `Cargo.toml`

</details>

**Comment by extrawurst** [comment]
@dm9pZCAq I gladly accept a PR for this 👍
