### ISSUE TITLE
Add stage_item/unstage_item to its own key_config

### ISSUE THREAD

**Issue by merikan** [extrawurst/gitui#909]
**Is your feature request related to a problem? Please describe.**
It's not a problem but would be an improvement to avoid misunderstandings

**Describe the solution you'd like**
I wanted to remap the stage_item/unstage_item to `Spacebar` instead of `Enter`, so I changed 
```
enter: ( code: Enter, modifiers: ( bits: 0,),),    
```
to
```
enter: ( code: Char(' '), modifiers: ( bits: 0,),),
```
and it works great.

I have now changed the `Enter` key to `Space` but I do not know if it affects any other function that also uses the `Enter` keybinding.

It would be awesome if we had separate key-bindings for `stage_item` and `unstage_item` and they can of course be linked to `Enter` by default.

**Describe alternatives you've considered**
I have looked around in the code and can see that `Enter` is used in several places, so there are probably more places for improvements.

For me, `Space` is great to toggle on/off, and `Enter` is a great fit for confirming an operation, but that's just my personal preference. 😉

Thx for an awesome project 👍

**Comment by extrawurst** [comment]
That makes sense 👍

**Comment by alessandroasm** [comment]
I would like to work on that 🙂

**Comment by alessandroasm** [comment]
I've opened a PR to implement this feature. Please let me know if it needs adjustments.

**Comment by extrawurst** [comment]
@alessandroasm thanks for approaching this. now that I look into it I am wondering if we have any practical reason to separate staging/unstaging into separate keys? we only ever have one fo the two options anyway so my proposal would be to have one new `stage_unstage_item` key.  

@merikan your thoughts?

**Comment by alessandroasm** [comment]
I forgot to update the Help.
![image](https://user-images.githubusercontent.com/2970975/136112470-eb15f33c-669e-45d7-a2c8-1c136bf4f4e6.png)

I'll update the PR shortly.
