### ISSUE TITLE
Allow force push when local tries to push after undo-ing a commit locally.

### ISSUE THREAD

**Issue by a-y-u-s-h** [extrawurst/gitui#913]
**Is your feature request related to a problem? Please describe.**
Consider a scenario where after creating a local git repo, you add an empty `README.txt`, commit it and then push it. You want to pull it back and remove the commit, then force push (delete the commit, and push it back thereby deleting the commit on remote as well without adding any other extra commits). This cannot be done as of now. Gitui doesn't do anything on `Shift+p`.

**Describe the solution you'd like**
This can be done by adding the plus sign on the branch like so manually `git push --set-upstream origin +master` but gitui disables the `force push` when there's no new commit. 

**Describe alternatives you've considered**
`git push --set-upstream origin +master`

**Additional context**
None.

**Comment by extrawurst** [comment]
@a-y-u-s-h interesting corner-case, can you please run gitui with logging and share what is printed there. it should not just do nothing.

**Comment by a-y-u-s-h** [comment]
Attaching a video of what I did. Yeah, there was some error upon trying to undo first commit (in the video as well). Also, just noticed force push results in constant loading after pushing the files successfully. Have to cancel and restart to make it work.

https://user-images.githubusercontent.com/19586719/134789070-6454e7cd-ef0f-44a0-aa3b-03a2282870b4.mp4

**Comment by GitMurf** [comment]
any updates on this? just started trying gitui out after using lazygit for a long time (love it but it can get slow). love the speed of gitui but this force push without any commits is something that comes up a lot for me and lazygit does handle. curious what came about this issue as it appears it was only closed by the auto stale bot. Thanks for the great tool!

**Comment by extrawurst** [comment]
I assume it just did not come up for enough people or no one that could actually provide a PR

**Comment by GitMurf** [comment]
> I assume it just did not come up for enough people or no one that could actually provide a PR

thanks for the quick response. so i assume there is still no way to do this? and that the recommended approach is to just switch to terminal to run git commands directly when needed?
