### ISSUE TITLE
Push/pull fail when remote contains square brackets (non-standard SSH port)

### ISSUE THREAD

**Issue by Cottser** [extrawurst/gitui#916]
**Describe the bug**
When using a remote of the format `[git@host:8080]:namespace/repo.git` it's not currently possible to pull or push with gitui. With the same repo, CLI operations work OK. For context, this format seems to be what GitLab generates in its UI when configured to use a non-standard SSH port.

The error (for a fetch/pull) is:

```
fetch failed:
git error:Bad credentials.
```

Not sure if this is upstream or not (seems likely) but going to file this to at least help others with a workaround for now!

**Workaround**

Change your remote to the following format:

`ssh://git@host:8080/namespace/repo.git`

So for the example below (I know it looks a bit weird because GitHub SSH is just using the standard port):

`git remote set-url origin ssh://git@github.com:22/extrawurst/gitui.git`

**To Reproduce**
1. `git clone "[git@github.com:22]:extrawurst/gitui.git"`
2. `cd gitui`
3. `gitui`
4. Type `f` to Pull (default binding)

**Expected behavior**
Fetch (pull) operation succeeds (assuming you have a valid SSH key set up with GitHub)

**Screenshots**
n/a

**Context (please complete the following information):**
 - OS/Distro + Version: Pop!_OS 21.04 (Ubuntu-like)
 - GitUI Version 0.17.0 (but reproduced on 0.17.1 as well on macOS)
 - Rust version: (Probably not applicable)

**Additional context**

Log:

```
13:09:16 [TRACE] (1) gitui::app: [src/app.rs:352] update
13:09:16 [TRACE] (6) mio::poll: [/build/gitui-0.17-vendor.tar.gz/mio/src/poll.rs:478] registering event source with poller: token=Token(0), interests=READABLE
13:09:16 [TRACE] (6) mio::poll: [/build/gitui-0.17-vendor.tar.gz/mio/src/poll.rs:478] registering event source with poller: token=Token(1), interests=READABLE
13:09:16 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 1915316720143881540] (type: WorkingDir)
13:09:16 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 13667276242224620811] (type: Stage)
13:09:16 [TRACE] (3) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 13667276242224620811 (type: Stage)
13:09:16 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 1915316720143881540 (type: WorkingDir)
13:09:16 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:16 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:280] event: Input(Key(KeyEvent { code: Char('f'), modifiers: NONE }))
13:09:18 [TRACE] (1) asyncgit::fetch: [asyncgit/src/fetch.rs:70] request
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:352] update
13:09:18 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 10315854148163913168] (type: WorkingDir)
13:09:18 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 10786361832688014167] (type: Stage)
13:09:18 [TRACE] (4) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 10786361832688014167 (type: Stage)
13:09:18 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 10315854148163913168 (type: WorkingDir)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:18 [DEBUG] (7) asyncgit::sync::remotes::callbacks: creds: '[git@github.com:22]:extrawurst/gitui.git' Some("[git") (SSH_KEY | SSH_MEMORY | SSH_CUSTOM)
13:09:18 [DEBUG] (7) asyncgit::sync::remotes::callbacks: creds: '[git@github.com:22]:extrawurst/gitui.git' Some("[git") (SSH_KEY | SSH_MEMORY | SSH_CUSTOM)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Fetch)
13:09:18 [ERROR] fetch error: git error:Bad credentials.
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:352] update
13:09:18 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 16497959313889857639] (type: WorkingDir)
13:09:18 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 10760547439531155206] (type: Stage)
13:09:18 [TRACE] (3) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 10760547439531155206 (type: Stage)
13:09:18 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 16497959313889857639 (type: WorkingDir)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Fetch)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:18 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:19 [TRACE] (1) gitui::app: [src/app.rs:280] event: Input(Key(KeyEvent { code: Enter, modifiers: NONE }))
13:09:21 [TRACE] (1) gitui::app: [src/app.rs:352] update
13:09:21 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 3058622914774764491] (type: WorkingDir)
13:09:21 [TRACE] (1) asyncgit::status: [asyncgit/src/status.rs:95] request: [hash: 165825549770520795] (type: Stage)
13:09:21 [TRACE] (3) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 165825549770520795 (type: Stage)
13:09:21 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:21 [TRACE] (2) asyncgit::status: [asyncgit/src/status.rs:151] status fetched: 3058622914774764491 (type: WorkingDir)
13:09:21 [TRACE] (1) gitui::app: [src/app.rs:371] update_async: Git(Status)
13:09:22 [TRACE] (1) gitui::app: [src/app.rs:280] event: Input(Key(KeyEvent { code: Char('q'), modifiers: NONE }))
```

**Comment by extrawurst** [comment]
ok I tested that and our core library `libgit2` does not support this bracket-style format. it is an upstream issue - please report it over at [libgit2](https://github.com/libgit2/libgit2) that the [git_remote_callbacks](https://libgit2.org/libgit2/#HEAD/type/git_remote_callbacks) field `credentials` will pass a malformed url when using this bracket style-format. you can see this in the log in this line:

```
13:09:18 [DEBUG] (7) asyncgit::sync::remotes::callbacks: creds: '[git@github.com:22]:extrawurst/gitui.git' Some("[git") (SSH_KEY | SSH_MEMORY | SSH_CUSTOM)
```

where the `Some("[git")` is maleformed - but it is what libgit2 passes to us in this callback.

**Comment by Cottser** [comment]
@extrawurst I took some time this morning to start writing up a bug report but I'm not really sure what to specify for reproduction steps. Should I look at https://github.com/rust-lang/git2-rs to provide the best context for upstream?

**Comment by extrawurst** [comment]
> @extrawurst I took some time this morning to start writing up a bug report but I'm not really sure what to specify for reproduction steps. Should I look at https://github.com/rust-lang/git2-rs to provide the best context for upstream?

just startout writing it in prose, pointing here, my write-up above should be pretty clear without any git2-rs knowledge to the libgit2 guys

**Comment by extrawurst** [comment]
@Cottser you made libgit2 move! There is a PR to add that now 🥳

**Comment by Flo-Slv** [comment]
Hi there,

I am a bit confused. I am using SSH as remote url and I can not pull or push.

Git error: Bad credentials.

```sh
[remote "origin"]
        url = [git@github.com:22]:extrawurst/gitui.git
        fetch = +refs/heads/*:refs/remotes/origin/*  
```

```sh
[remote "origin"]
        url = git@github.com:extrawurst/gitui.git
        fetch = +refs/heads/*:refs/remotes/origin/*  
```

I tried with this 2 syntaxes for url.

Do I miss something ? Do we have to wait a PR ?

Thanks for help

Flo

**Comment by extrawurst** [comment]
Feel free to try to build from master, the fix in upstream is not in the last gitui release

**Comment by marcoziti** [comment]
Run ``eval "$(ssh-agent)"`` before ``ssh-add ~/.ssh/id_rsa`` resolve this issue for me.
