### ISSUE TITLE
Improve contrast for selected branch in branch popup for light themes

### ISSUE THREAD

**Issue by Cottser** [extrawurst/gitui#922]
**Describe the bug**
The contrast for the branch name for the selected branch could be improved for light themes (see screenshots below).

**To Reproduce**
1. Open the branch modal
2. Look at the selected branch

**Expected behavior**
I expected this to have better contrast

**Screenshots**

![before-light](https://user-images.githubusercontent.com/327943/135285349-3ba1ead7-d490-437f-b806-be95e576289d.png)
![before-dark](https://user-images.githubusercontent.com/327943/135285359-b214f952-8bf8-4fe7-a5cf-7159002b9102.png)

**Context (please complete the following information):**
 - OS/Distro + Version: Pop!_OS 21.04 (Ubuntu-like)
 - GitUI Version 0.17.1
 - Rust version: 1.55.0

**Additional context**
The contrast is even worse (invisible, black-on-black) with my own terminal/gitui theme.

**Comment by extrawurst** [comment]
Did you try to change that color using a local custom gitui theme?

**Comment by Cottser** [comment]
Hi! I don't think it can be changed through the gitui theme, I believe it's just the default terminal foreground color being used here.

I just posted the PR: #923

**Comment by extrawurst** [comment]
@Cottser thanks! can you post a comparison screenshot with your change?

**Comment by extrawurst** [comment]
> @extrawurst definitely, I forgot to post those. Do you want those in here, in the PR, or both?

here is fine

**Comment by Cottser** [comment]
Dark theme, before and after:
![before-dark](https://user-images.githubusercontent.com/327943/135289804-55b1c9b7-f911-436f-bf9a-f40523fec9e2.png)
![after-dark](https://user-images.githubusercontent.com/327943/135289841-657dec41-e0f1-44c4-817b-d678859c9a7b.png)


Light theme, before and after:
![before-light](https://user-images.githubusercontent.com/327943/135289854-47501665-28bc-4057-baf4-11776c3761bb.png)

![after-light](https://user-images.githubusercontent.com/327943/135289859-cb5b00c6-65c0-48d9-8802-f4bf33c93669.png)

**Comment by Cottser** [comment]
Looks like this may actually improve contrast in some dark themes as well.

**Comment by Cottser** [comment]
Solarized dark, before/after:
![before-solarized-dark](https://user-images.githubusercontent.com/327943/135290637-33ffb241-6366-4199-88eb-bea72dbca54d.png)
![after-solarized-dark](https://user-images.githubusercontent.com/327943/135290647-7e43541a-c3f4-4580-a342-0f31fbc73054.png)

Thanks @extrawurst!
