### ISSUE TITLE
Add an equivalent to `git add -u`

### ISSUE THREAD

**Issue by tmke8** [extrawurst/gitui#933]
**Is your feature request related to a problem? Please describe.**
I often want to stage and commit all changes to files that are already tracked by git, but not add new files. With `git`, this can be done with `git add -u` or `git commit -a`. (I might be the only one who does that though, in which case feel free to ignore this.)

**Describe the solution you'd like**
There is already `status_stage_all`, so what I would like to have is `status_stage_update` (or something like that) which I can map, for example, to `u`.

**Describe alternatives you've considered**
The alternative is going through all files in the status view and either press `down` or `enter`; or first staging everything and then removing some changes.

**Comment by extrawurst** [comment]
the options dialog should solve this. in the options you can hide the untracked files and it will effectively also only stage files visible then
