### ISSUE TITLE
Showing unstaged JSON causes: out of range integral type conversion attempted

### ISSUE THREAD

**Issue by ignatenkobrain** [extrawurst/gitui#96]
**Describe the bug**
```
Error: out of range integral type conversion attempted
```

**To Reproduce**
1. Open gitui with unstaged json (possibly big enough, I have https://src.fedoraproject.org/extras/pagure_owner_alias.json)
2. Click on "→" arrow

**Expected behavior**
gitui should not exit with an error, the json should be shown :)

**Desktop (please complete the following information):**
 - OS: Fedora
 - Version: 33

**Comment by ignatenkobrain** [comment]
Just realized that you don't have to open a diff, once you go through unstaged files and hit this json, gitui closes with an error.

**Comment by extrawurst** [comment]
@ignatenkobrain thanks for the report. I fixed the error first but I am still not happy since performance suffers when diffing giant files

**Comment by extrawurst** [comment]
Now that should do. will release a patch version later today
