### ISSUE TITLE
Hotkey for starting an interactive rebase from the commit list / log

### ISSUE THREAD

**Issue by athre0z** [extrawurst/gitui#966]
**Is your feature request related to a problem? Please describe.**
I tend to do a lot of interactive rebasing, typically at least 3-5 times per day. My workflow for that is invoking `git log`, locating the commit that I want to start cleaning up at, copying the SHA, typing `git rebase -i <hash>`. In some cases, I'll also specify `--onto`, to rebase on a different branch. 

**Describe the solution you'd like**
It would be rather convenient to be able to run `gitui`, switch to the `Log [2]` tab, select the right commit via cursor keys and then just have a keybind, e.g. <kbd>^I</kbd>, for doing that. I'd imagine that it would then pop a modal where I can select a branch to rebase onto, with the default being the current branch. Upon confirming with enter, it would exit gitui and let me perform my typical interactive rebase workflow.

**Describe alternatives you've considered**
It would be even better to have the whole interactive rebase support with a nice UI within `gitui`, like suggested in #32. However, since this is a very significant amount of work, my proposed version seems like a decent stop-gap for me.

**Comment by extrawurst** [comment]
closing in favour of #32
