### ISSUE TITLE
Any  config to set  the diff changes view with ++/-- back

### ISSUE THREAD

**Issue by butterl** [extrawurst/gitui#978]
**Is your feature request related to a problem? Please describe.**
1. Any  config to set  the diff changes view with ++/-- back? since the only green/red changes lines not that friendly to color blind people
2.  the log view may add back the numstat to show the change size , also the diff may have line number option
3. the blame view  Inspect [→] is the enter way to get detail log of change lines, maybe the close key is just close the blame view

**Describe the solution you'd like**
1. give some config or hotkey to make ++/-- style change
2. give option to show the change size( hot key or config file) and line number
3. the blame view  Inspect [→] is the enter way to get detail log of change lines, maybe the close key is just back to blame not to close it, also maybe there is way to show blame line left and inspect in the left to fast change blame frequent changed blocks（with many commits in small block of code） 

**Describe alternatives you've considered**

**Additional context**

**Comment by arilou** [comment]
I would also love if there was a way to make a diff config file to re-enable the view with +/- with the color like in git gui.
And make a permanent config for the diff view (context lines etc.)
