### ISSUE TITLE
Suggest moving theme.ron from XDG_CACHE_HOME to XDG_CONFIG_HOME

### ISSUE THREAD

**Issue by wezm** [extrawurst/gitui#98]
Related to #27

[The spec](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html) notes:

> $XDG_CACHE_HOME defines the base directory relative to which user specific non-essential data files should be stored.

The non-essential bit there means this data can be purged at any point without impacting the user. `theme.ron` being user data probably should be preserved, which suggests it should be in `"$XDG_CONFIG_HOME/gitui/theme.ron"`

**Comment by extrawurst** [comment]
good point sounds reasonable!
