### ISSUE TITLE
[Feature] Allow checking out specific commits in log view

### ISSUE THREAD

**Issue by Omnikar** [extrawurst/gitui#983]
Hi! I just found this project and think it's pretty cool!

Anyway, I think it would be nice if the log view had an option to enter detached HEAD state and checkout the selected commit.

**Comment by extrawurst** [comment]
should be fairly easy to implement actually. all the tools are there. someone willing to take it?

**Comment by Omnikar** [comment]
@extrawurst I could try to implement it, what keybind should it have?

**Comment by extrawurst** [comment]
@Omnikar still interested in tackling this?

**Comment by Omnikar** [comment]
Yeah sorry, I've been busy. I should have time now.

**Comment by Omnikar** [comment]
@extrawurst What is `scope_time!`?

**Comment by extrawurst** [comment]
@Omnikar see https://github.com/extrawurst/gitui/tree/master/scopetime

**Comment by Omnikar** [comment]
OK
