### ISSUE TITLE
Font Color in changes macOS

### ISSUE THREAD

**Issue by areyouready** [extrawurst/gitui#988]
Is there a way to change the font color in changes? The background color is so bright and the font so light that there is not much contrast and it is hard to read with my terminal settings
![image](https://user-images.githubusercontent.com/376879/141944763-a94fa27e-38ca-4c5a-84f8-94c66274447c.png)

**Comment by extrawurst** [comment]
Please have a look at https://github.com/extrawurst/gitui/discussions/942

**Comment by areyouready** [comment]
Yeah I saw that but hoped there would be a better answer as nobody answered the original question and changing the color scheme seems to be no good option to me.

Thx. for the answer anyway

**Comment by extrawurst** [comment]
@areyouready I added a little clarification 9eb30ec and in the discussion thread: https://github.com/extrawurst/gitui/discussions/942#discussioncomment-1782002
