### ISSUE TITLE
Missing some options to work on files/directories (create, delete, modify, rename, etc.)

### ISSUE THREAD

**Issue by chlopes** [extrawurst/gitui#989]
Hi!

I've just found the project so maybe I'm missing something but I didn't find a way to invoke the editor ("Edit [e]" option) from the *Files [3]* tab to start modifying files. Also, I've not found the options to create, delete and rename files/directories through it.

Maybe these options are out of the scope of the project, I don't know, but I think it'd be nice to have them for small and quick changes, thus avoiding context switches.

Thanks for the outstanding job! Just keep it up!

**Comment by extrawurst** [comment]
>  I didn't find a way to invoke the editor ("Edit [e]" option) from the Files [3] tab

thats not implemented yet, but that makes sense actually!

> I've not found the options to create, delete and rename files/directories through it.

I am not sure I want to go down that path, I also do not see parallels in the git GUI apps that inspired gitui (looking at Fork)

**Comment by chlopes** [comment]
> thats not implemented yet, but that makes sense actually!

Good to know :)

> I am not sure I want to go down that path, I also do not see parallels in the git GUI apps that inspired gitui (looking at Fork)

I understand your concerns but I do hope you consider adding it because it complements the feature above, fulfilling the need of managing project files directly through the tool.

**Comment by extrawurst** [comment]
> I understand your concerns but I do hope you consider adding it because it complements the feature above, fulfilling the need of managing project files directly through the tool.

still this should be a separate issue so we can prioritise it differently. the `edit [e]` part is a low hanging fruit, the other part not as much. can you split these two things?

**Comment by chlopes** [comment]
> can you split these two things?

Absolutely!

Shall we keep this issue for the `edit [e]` part and just open a new one for the other part or do you prefer to close this one and open another two separately?

**Comment by extrawurst** [comment]
Let’s keep this one for the edit cmd

**Comment by extrawurst** [comment]
implemented with one oddity: since the file tree reflects a revision of the tree changing a file that we see there will not be reflected afterwards in the tree view. therefore I switch to the status tab when editing a file

**Comment by mark2185** [comment]
> since the file tree reflects a revision of the tree changing a file that we see there will not be reflected afterwards in the tree view

Why is that? I found it odd changing a file and seeing the view of the file in the `Files` tab to remain unchanged. And yet, editing said file shows the _actual_ state of it.
