### ISSUE TITLE
Limit shown/loaded history

### ISSUE THREAD

**Issue by aik** [extrawurst/gitui#992]
Nice tool but not usable for the kernel as every modern branch is a million commits long. For this matter `tig` allows `set main-options = -n 15000` in `~/.tigrc`, would be nice to have a similar thing in `gitui`

**Comment by extrawurst** [comment]
that limits the list of commits it loads to 15000?

why is it unusable with a million commits? last time I checked it took only 20s to parse the entirety of the log and just a blink of an eye to parse the first 10k commits, should not be unusable while still parsing the rest.
