### ISSUE TITLE
Open remote repository in the current branch

### ISSUE THREAD

**Issue by nucliweb** [extrawurst/gitui#995]
**Is your feature request related to a problem? Please describe.**

For years I'm using the npm package [git-open](https://github.com/paulirish/git-open) to open the remote repository in the current branch in the browser. This is very useful to create PR.

I think that will be a great and useful feature to have in gitui

**Comment by extrawurst** [comment]
I did not look into *git-open* but if it can be done cross-platform, I have no objections to receiving a PR
