### ISSUE TITLE
remove stale bot

### ISSUE THREAD

**Issue by skyfaller** [extrawurst/gitui#996]
Please disable stale bot on GitHub. It makes the open or closed status of an issue meaningless, and increases GitHub notification noise.

My understanding is that if an issue is closed, it means:

- the problem has been fixed, or
- the problem cannot be fixed (e.g. upstream bug), or
- the maintainer does not want it to be fixed

If stale bot runs around closing bugs willy nilly, now the closed state doesn't mean much of anything. The difference between a closed bug and an open bug can just be happenstance, or the confluence of tangential factors such as:

- Was the nature of the bug obvious? How much discussion was required before everyone understood it? Longer discussions mean more time before stale bot triggers. I think obvious bugs may sometimes be higher priority to fix.
- How many annoying users who like to complain did this issue affect? This gives incentives to users who care about the bug to be whiny, rather than wait patiently. It also fills my GitHub notifications with stale bot and people defending against stale bot, which now that I think about it may be the core of my grudge against stale bot. I certainly comment on any stale botted issue I follow, purely because I hate stale bot, but this is a little like emailing a large email thread asking to be removed because you're getting too many email notifications. Now we all must suffer.
- Did the person with the time and energy to fix it show up in 3 months or 6 months? This is an arbitrary matter of timing, and says nothing about the bug itself.

In my last confrontation with stale bot, me and the other user who cared about the bug eventually found someone to work on fixing it... But the bug is still closed! https://github.com/yuin/goldmark/issues/180 "Closed" doesn't even mean that the bug is inactive, that nobody is working on it, because stale bot sucks meaning out of the universe!

From now on I will link to this issue in issues that stale bot marks as stale, rather than repeating myself.

**Comment by extrawurst** [comment]
I responded to this here already: https://github.com/extrawurst/gitui/issues/865#issuecomment-974557426
